### ISSUE TITLE
Neovide freezes on launch after update

### ISSUE THREAD

**Issue by HTofi** [neovide/neovide#2245] opened 2024-01-07 13:47 UTC
**Describe the bug**
Yesterday my system updated to neovim v0.9.5 and neovide v0.12.0. Now neovide freezes at launch and can only be closed by killing the process in the system monitor. 

**To Reproduce**
1. Launch neovide
4. It freezes

**Expected behavior**
No freeze

**Desktop:**
 - OS: Manjaro Linux
 - Neovide Version 0.12.0
 - Neovim Version 0.9.5

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/13853646/neovide_rCURRENT.log)

**Comment by fredizzimo** [comment] 2024-01-08 02:34
I nelieve this is an (almost) duplicate of, but here an warning is displayed instead of error
* https://github.com/neovide/neovide/issues/2233

This should already be fixed on main if you build from source and included with the next release.

**Comment by fredizzimo** [comment] 2024-01-08 02:36
We should do a new release very soon, since the warnings might not be something you can work around

**Comment by HTofi** [comment] 2024-01-08 19:11
You're right ! Updating my plugins removed the warning and now Neovide works. Thanks !

**Closed** 2024-01-08 23:16 UTC
Labels: bug
