### ISSUE TITLE
Support for dynamic padding/

### ISSUE THREAD

**Issue by Rid1-fz-06** [neovide/neovide#2381] opened 2024-02-24 03:52 UTC
**Is your feature request related to a problem? Please describe.**
Some fonts don't fill the full width of the screen. So it left some padding on the right and the bottom in some cases.

**Describe the solution you'd like**
Just spread the padding to all the sides instead of the right and the bottom.

**Additional context**
This feature is similar to the dynamic padding of the Alacritty terminal.

**Comment by fredizzimo** [comment] 2024-02-24 13:17
Closing as a duplicate of:
* https://github.com/neovide/neovide/issues/1738

**Closed by fredizzimo** 2024-02-24 13:17 UTC
Labels: enhancement
