### ISSUE TITLE
Command-line/MsgArea renders with a black background when transparency is enabled and the value is set to none

### ISSUE THREAD

**Issue by GNRSN** [neovide/neovide#1819] opened 2023-03-26 15:06 UTC
**Describe the bug**
Unable to make command-line/MsgArea transparent when using Neovide with transparency, 

**To Reproduce**
1. Launch with transparency
2. Attempt to remove the background, screenshot features a minimal init.lua to reproduce

**Expected behavior**
For there to be some way to have no background for the the MsgArea, setting the background to nil/none allows for this in Nvim but in Neovide it renders with a black background when set to a none-value. The fg value is respected though so this seems like a bug to me, or is there something I'm missing? 

**Screenshots**
<img width="721" alt="image" src="https://user-images.githubusercontent.com/9020004/227783644-f52bbab2-efcc-450e-8b45-61442465a5d9.png">

**Desktop (please complete the following information):**
 - OS: 
 macOS Ventura 13.2.1
 - Neovide Version
neovide 0.10.3
 - Neovim Version
NVIM v0.8.3

**Comment by falcucci** [comment] 2023-04-18 23:39
It only occurs when --multigrid is enabled.

I am debugging but this is probably related to the grip `paint` 🙃

@Kethku as multigrid is now enabled by default due to a stable version, seems like we found a bug?

**Comment by fredizzimo** [comment] 2023-07-31 11:36
Duplicate of https://github.com/neovide/neovide/issues/1508

**Closed by fredizzimo** 2023-07-31 11:36 UTC
Labels: bug
