### ISSUE TITLE
Detach from terminal

### ISSUE THREAD

**Issue by marcinjahn** [neovide/neovide#2726] opened 2024-07-23 05:48 UTC
**Is your feature request related to a problem? Please describe.**
When I run `neovide .`, I want it to behave like `code .`.
Instead, it "blocks" the terminal.

**Describe the solution you'd like**
 The command should exit and let me type another command afterwards.

**Describe alternatives you've considered**

**Additional context**

**Comment by fredizzimo** [comment] 2024-07-23 06:18
Duplicate of
* https://github.com/neovide/neovide/issues/2147
* https://github.com/neovide/neovide/issues/2579
* https://github.com/neovide/neovide/issues/2579

**Closed by fredizzimo** 2024-07-23 06:18 UTC
Labels: enhancement
