### ISSUE TITLE
Nvim detection fails on WSL with nushell (might also affect other shells)

### ISSUE THREAD

**Issue by Belgabor** [neovide/neovide#1900] opened 2023-06-17 22:24 UTC
**Describe the bug**
If you use nushell as your login shell in WSL neovide fails to detect nvim inside WSL.

**To Reproduce**
1. Use nushell as your login shell in WSL
2. Try to use neovide
3. Neovide closes because it thinks nvim isn't available

**Expected behavior**
Neovide should be able to detect nvim

**Desktop (please complete the following information):**
 - OS: Windows/WSL
 - Neovide Version: 0.10.4
 - Neovim Version: 0.9.1

**Additional context**
The issue can be fixed rather easily. Currently neovide uses '$SHELL' to call commands inside WSL through the shell binary stored in the environment. I can submit a PR that implements an option to override the shell binary neovide uses to make calls. This, in my tests, fixes the issue.
While it doesn't make it work out-of-the-box, this allows the user to make neovide work with more exotic shell choices without having to cater for each individually.

Example:
```powershell
neovide --wsl --wsl-shell=/usr/bin/bash
```

**Comment by fredizzimo** [comment] 2023-06-17 23:18
I made another fix for this a while ago, but have never submitted a PR, since I never tested it completely. 

https://github.com/neovide/neovide/compare/main...fredizzimo:neovide:fsundvik/fix-nvim-detection

The idea is to call `nvim -v`,  which is a quite standard way to detect if a program is available. That way it's shell independent, and furthermore it's possible to verify that the version is supported and that it at least claims to be Neovim.

Using a different shell could be problematic, since the paths could be configured differently. But that said, perhaps it would be a good option to allow the user to select the shell.

**Comment by fredizzimo** [comment] 2023-07-26 11:07
Duplicate of #1812

**Closed by fredizzimo** 2023-07-26 11:07 UTC
Labels: bug
