### ISSUE TITLE
Neovide 0.13.0 panics on Windows 11

### ISSUE THREAD

**Issue by myth0genesis** [neovide/neovide#2556] opened 2024-05-17 18:30 UTC
**Describe the bug**
After installing 0.13.0 with both the .msi installer and building from source, Neovide panics as soon as I attempt to run the executable

**To Reproduce**
Via installer:
1. Download Neovide 0.13.0 installer for Windows from neovide.dev
2. Run Neovide installer
3. Run Neovide executable

Via building from source:
1. Updated Rust via `rustup update`
  (CMake version: 3.29.1 already installed)
  (LLVM version: 18.1.4 already installed)
2. Ran command
  ```cargo install --git https://github.com/neovide/neovide.git```
3. Run Neovide executable

**Expected behavior**
Neovide executable runs.

**Desktop:**
 - OS: Windows 11 Home Version 10.0.22631 Build 22631
 - Neovide Version 0.13.0
 - Neovim Version 0.10.0
 - NVidia RTX 3070ti GPU
 - NVidia Game Ready drivers are latest version (552.44)

Contents of log:
2024-05-17 18:05:11 - Neovide panicked with the message 'Failed to create DXGI factory: Error { code: HRESULT(0x887A0001), message: "The application made a call that is invalid. Either the parameters of the call or the state of some object was incorrect.\r\nEnable the D3D debug layer in order to see details via debug messages." }'. (File: src\renderer\d3d.rs; Line: 112, Column: 59)
   0: \<unknown\>
   1: \<unknown\>
   2: \<unknown\>
   3: \<unknown\>
   4: \<unknown\>
   5: \<unknown\>
   6: \<unknown\>
   7: \<unknown\>
   8: \<unknown\>
   9: \<unknown\>
  10: \<unknown\>
  11: \<unknown\>
  12: \<unknown\>
  13: BaseThreadInitThunk
  14: RtlUserThreadStart

**Additional context**
I'm wary of updating CMake and LLVM frequently because the build ecosystem for my job breaks pretty much every time I do it, so that's why CMake and LLVM on my system aren't the absolute newest versions available (probably a skill issue on my part, but I just do what works for me).
Neovim 0.10.0 currently runs as expected on my system. I'm also using LazyVim, so the expected behavior in my specific case is that the dashboard comes up when I run Neovide.
It should also be noted that not a single error came up when building with Rust.

**Comment by fredizzimo** [comment] 2024-05-17 18:42
If you are already building from source, can you run
`cargo run --features d3d_debug` if that does not work,

Then it looks like this line is wrong
https://github.com/neovide/neovide/blob/818ff73f410dd6a1170c8a6414e8b9f33d46d50b/src/renderer/d3d.rs#L112

And it should be changed to `CreateDXGIFactory2(0).expect("Failed to create DXGI factory") `

Well, actually it should be selected to be either 0 or `DXGI_CREATE_FACTORY_DEBUG` depending on if `d3d_debug` is enabled or not.  But I missed that when I made the previous fix in this PR:
* https://github.com/neovide/neovide/pull/2529

**Comment by myth0genesis** [comment] 2024-05-17 18:50
You're going to have to give me more details on how to do that. The only way I know how to use `cargo run` is when I'm in the folder for a Rust project I've created myself, not one that's been already built into an executable.

**Comment by myth0genesis** [comment] 2024-05-17 18:55
Never mind. I found the git checkout folder with the source did `cargo run` from there. Here's the output with `3d3_debug`:
```
Neovide panicked with the message 'Failed to create Direct3D debug controller: Error { code: HRESULT(0x887A002D), message: "The application requested an operation that depends on an SDK component that is missing or mismatched." }'. (File: src\renderer\d3d.rs; Line: 104, Column: 18)
This is a bug and we would love for it to be reported to https://github.com/neovide/neovide/issues
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Backtrace saved to neovide_backtraces.log!
error: process didn't exit successfully: `target\debug\neovide.exe` (exit code: 101)
```

**Comment by fredizzimo** [comment] 2024-05-17 18:56
Thanks, yes, then it's likely what I expected.

Can you try changing line 112 in d3d.rs to `CreateDXGIFactory2(0).expect("Failed to create DXGI factory") `, `0` instead of `DXGI_CREATE_FACTORY_DEBUG`?

**Comment by myth0genesis** [comment] 2024-05-17 19:04
Got the exact same error, in addition to the warning for the unused import, of course.

**Comment by fredizzimo** [comment] 2024-05-17 19:09
Hm, I'm not sure what the problem could be. 

You could try `CreateDXGIFactory1` (you need to import it first) without any parameters. But I don't think it will help.

Starting neovide using `neovide --opengl` probably works though as a workaround until the problem is found.

**Comment by myth0genesis** [comment] 2024-05-17 19:26
Yeah, running Neovide with the OpenGL renderer still works.
I went ahead and imported CreateDXGIFactory1 and replaced
```Rust
CreateDXGIFactory2(0).expect("Failed to create DXGI factory")
```
with
```Rust
CreateDXGIFactory1().expect("Failed to create DXGI factory")
```
but still got the exact same error.

Might I suggest WebGPU at some point in the future? It handles switching platform-specific renderers pretty much automatically (DX, Vulkan, and Metal). I use it for a personal project I'm working on and also the C++ lib for work and it's worked on every platform I've tested it on (except MacOS; that's pending, but soon) without any hassle, with the exception of having to handle WASM builds a bit differently for the web; something I suspect isn't a high priority for this project. What's nice about it is you only have to set up one pipeline and wgpu does the rest, as far as translating to platform-specific API calls.

**Comment by fredizzimo** [comment] 2024-05-17 20:01
I think `IDXGIFactory4` can be changed to `IDXGIFactory2`, or maybe `IDXGIFactory3` but I don't think it will help. All internet searches seem to indicate corrupted directx installs (when searching for errors with `CreateDXGIFactory1` or `CreateDXGIFactory2`).   It seems unlikely that it's a code problem, I don't see anything different in these examples https://github.com/microsoft/DirectX-Graphics-Samples/blob/51d0c1c5e225186a279bcdf15b7dbf68745301db/Samples/UWP/D3D12HelloWorld/src/HelloTriangle/D3D12HelloTriangle.cpp#L50

Yes, we are actually in progress of moving to wgpu, but there will be much work to do, since the Skia library we are using right now takes care of all the 2d and text drawing stuff. So, we are building a library that Neovide can use https://github.com/neovide/vide

**Comment by myth0genesis** [comment] 2024-05-17 21:43
I'm somewhat doubtful it's a DX issue on my end, as I'm working from a less-than-month-old fresh (from scratch) Windows 11 install and I've not had any DX-related crashes elsewhere since doing the reinstall. I also just ran dxdiag and no issues came up there. Looking at what it would take to reinstall DX, well, it seems the only method that works on Windows 11 is to reinstall Windows, which I just did not too long ago and definitely have no desire to do again anytime soon.

I'm excited about the switch to wgpu, though, and am looking forward to it!
I was about to say something about how it appears Zed wrote their own text UI renderer, too, but looking at the link to your lib, it looks like you guys are already aware of that 😅Exciting stuff! I'm going to be writing my own GPU debugging UI for my wgpu renderers within the next couple of days, but only for monospace bitmap fonts where the distances, antialiasing masks, and normals are baked into them (roughtly following Octavio Good's methods). Nothing so fancy as TT fonts like y'all are probably doing.

I'm gonna leave this issue open for now, if that's all right, to see if any other Windows 11 users end up with the same problem.

**Comment by myth0genesis** [comment] 2024-05-17 22:15
Woo-hoo! I decided to replace all occurrences of `IDXGIFactory4` with `IDXGIFactory2` and it worked! But I also had to keep the flag for `CreateDXGIFactory2()` at line 112 at `0` like you suggested earlier.
```Rust
CreateDXGIFactory2(0).expect("Failed to create DXGI factory")
```
I don't use git for remote stuff other than `clone` and `push`, and even locally I only use it for a sort of macro undo system with a single branch so I can revert whenever I need to, so I don't know how to check out a branch here and merge with whatever you have.

Another note: You can't do
```
cargo run --features d3d_debug
```
with these changes.
I even tried putting the `DXGI_CREATE_FACTORY_DEBUG` flag back into the `CreateDXGIFactory2()` function, but then it just panics with the same errors as before, regardless of whether you're running a debug or release build.

**Comment by pedrohgmacedo** [comment] 2024-05-17 22:18
> I think `IDXGIFactory4` can be changed to `IDXGIFactory2`, or maybe `IDXGIFactory3` but I don't think it will help. All internet searches seem to indicate corrupted directx installs (when searching for errors with `CreateDXGIFactory1` or `CreateDXGIFactory2`). It seems unlikely that it's a code problem, I don't see anything different in these examples https://github.com/microsoft/DirectX-Graphics-Samples/blob/51d0c1c5e225186a279bcdf15b7dbf68745301db/Samples/UWP/D3D12HelloWorld/src/HelloTriangle/D3D12HelloTriangle.cpp#L50
> 
> Yes, we are actually in progress of moving to wgpu, but there will be much work to do, since the Skia library we are using right now takes care of all the 2d and text drawing stuff. So, we are building a library that Neovide can use https://github.com/neovide/vide

I have this issue as well, and I don’t think it’s anything to do with DX corrupted installs, as I literally switched computers like 2 weeks ago.

**Comment by Perry3D** [comment] 2024-05-17 22:26
I get the exact same error message on a windows 10 machine with an AMD card.

**Comment by pedrohgmacedo** [comment] 2024-05-17 22:32
> I get the exact same error message on a windows 10 machine with an AMD card.

Mine is Intel + nvidia. Windows 11.

**Comment by InfyniteHeap** [comment] 2024-05-18 02:40
This bug seems randomly occured because neovide 0.13.0 works as expected on my Windows 11 computer. (I built it from source)

**Comment by InfyniteHeap** [comment] 2024-05-18 03:19
> Never mind. I found the git checkout folder with the source did `cargo run` from there. Here's the output with `d3d_debug`:
> 
> ```
> Neovide panicked with the message 'Failed to create Direct3D debug controller: Error { code: HRESULT(0x887A002D), message: "The application requested an operation that depends on an SDK component that is missing or mismatched." }'. (File: src\renderer\d3d.rs; Line: 104, Column: 18)
> This is a bug and we would love for it to be reported to https://github.com/neovide/neovide/issues
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> Backtrace saved to neovide_backtraces.log!
> error: process didn't exit successfully: `target\debug\neovide.exe` (exit code: 101)
> ```

I searched on the Internet and according to `HRESULT(0x887A002D)` error code in your provided debug log, it might because you haven't enabled "Graphics Tools" feature on your Windows 11 OS.

I hope this link can help you: https://learn.microsoft.com/en-us/previous-versions/windows/apps/dn914047(v=win.10)!

**Comment by ThaiDuy12345** [comment] 2024-05-18 08:29
```
2024-05-18 08:27:30 - Neovide panicked with the message 'Failed to create DXGI factory: Error { code: HRESULT(0x887A0001), message: "The application made a call that is invalid. Either the parameters of the call or the state of some object was incorrect.\r\nEnable the D3D debug layer in order to see details via debug messages." }'. (File: src\renderer\d3d.rs; Line: 112, Column: 59)
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: BaseThreadInitThunk
  15: RtlUserThreadStart
```
I got this after install 0.13 ver..any solutions?

**Comment by fredizzimo** [comment] 2024-05-18 08:31
I will release a fix soon, but for now you can run `neovide --opengl`

**Comment by ThaiDuy12345** [comment] 2024-05-18 08:35
> I will release a fix soon, but for now you can run `neovide --opengl`

Thanks 😊

**Comment by pedrohgmacedo** [comment] 2024-05-18 10:00
> I will release a fix soon, but for now you can run `neovide --opengl`

If there’s any information that could help debug… —opengl is working.

**Comment by fredizzimo** [comment] 2024-05-18 10:20
I just created a PR that works around the issue by crating dxgi 1.2 interfaces instead of 1.4. I'm not very happy to leave it there though, since dxgi 1.4 should be available starting from the very first Windows 10 release.

The first step of debugging is probably a dxdiag log, to see what's actually supported on your systems.

The next step is to test the Microsoft provided examples
* https://github.com/microsoft/windows-rs/tree/master/crates/samples/windows/direct2d
* https://github.com/microsoft/windows-rs/tree/master/crates/samples/windows/direct3d12 (you might have to run this with `--release`, if it's only the debug interface that's causes the problem)

If those does not work, then we should probably report the problem on that repository. My suspicion is that it somehow loads the wrong dll here
https://github.com/microsoft/windows-rs/blob/78a40347f66440daeec326da9cc9fabfbe74bd04/crates/libs/windows/src/Windows/Win32/Graphics/Dxgi/mod.rs#L22-L29

And if it does, I guess we just have to try to find out the differences between our code and theirs.

That could also be verified by https://learn.microsoft.com/en-us/sysinternals/downloads/procmon, but the detailed instructions are too complicated to write down here.

**Comment by rainzee** [comment] 2024-05-18 11:28
Ran into the same problem on Windows 10

```
2024-05-18 10:11:43 - Neovide panicked with the message 'Failed to create DXGI factory: Error { code: HRESULT(0x887A0001), message: "应用程序进行了无效的调用。调用的参数或某对象的状态不正确。\r\n启用 D3D 调试层以便通过调试消息查看详细信息。" }'. (File: src\renderer\d3d.rs; Line: 112, Column: 59)
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: BaseThreadInitThunk
  14: RtlUserThreadStart

2024-05-18 10:11:55 - Neovide panicked with the message 'Failed to create DXGI factory: Error { code: HRESULT(0x887A0001), message: "应用程序进行了无效的调用。调用的参数或某对象的状态不正确。\r\n启用 D3D 调试层以便通过调试消息查看详细信息。" }'. (File: src\renderer\d3d.rs; Line: 112, Column: 59)
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: BaseThreadInitThunk
  14: RtlUserThreadStart

2024-05-18 10:12:07 - Neovide panicked with the message 'Failed to create DXGI factory: Error { code: HRESULT(0x887A0001), message: "应用程序进行了无效的调用。调用的参数或某对象的状态不正确。\r\n启用 D3D 调试层以便通过调试消息查看详细信息。" }'. (File: src\renderer\d3d.rs; Line: 112, Column: 59)
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: BaseThreadInitThunk
  14: RtlUserThreadStart

2024-05-18 10:12:21 - Neovide panicked with the message 'Failed to create DXGI factory: Error { code: HRESULT(0x887A0001), message: "应用程序进行了无效的调用。调用的参数或某对象的状态不正确。\r\n启用 D3D 调试层以便通过调试消息查看详细信息。" }'. (File: src\renderer\d3d.rs; Line: 112, Column: 59)
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: BaseThreadInitThunk
  14: RtlUserThreadStart


```

**Comment by asavartsov** [comment] 2024-05-18 11:36
Not sure if helpful or not but installing Graphics Tools from Optional Features indeed helped me. I am running Windows 11 LTSC (that leaked build) on a laptop with Intel graphics.

```
Processor	13th Gen Intel(R) Core(TM) i7-1355U   1.70 GHz
Installed RAM	32,0 GB (31,6 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
```

```
Edition	Windows 11 IoT Enterprise LTSC
Version	24H2
Installed on	‎08/‎04/‎2024
OS build	26100.560
Experience	Windows Feature Experience Pack 1000.26100.1.0
```

But `neovide --help` or `neovide --version` don't work though. Probably it's a different issue because error message has nothing DX realated

```
2024-05-18 11:12:30 - Neovide panicked with the message 'Trying to retrieve a settings object that doesn't exist: {:?}'. (File: src\settings\mod.rs; Line: 98, Column: 14)
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: BaseThreadInitThunk
  17: RtlUserThreadStart
```

**Comment by fredizzimo** [comment] 2024-05-18 11:42
@asavartsov, yes installing the Graphics tool will allow it to run the debug functionality. But it seems like something else than just the debug features are missing since @myth0genesis, tried to disable them and it still fails to create the interface.

For anyone trying to help debugging the issue *don't* instal the Graphics Tools, since after that it's not possible to reproduce.

@asavartsov, for the second issue, can you create a new issue with a log file from `neovide --log` attached?

**Comment by myth0genesis** [comment] 2024-05-18 23:39
What exactly are you looking for in the dxdiag logs? I don't really feel comfortable posting the whole thing, plus it's like 1800 lines long.

**Comment by yashamon** [comment] 2024-05-18 23:45
I have the same issue on Win 11, intel chipset gpu

**Comment by fredizzimo** [comment] 2024-05-19 09:14
@myth0genesis, 
For the dxdiag, mostly the first sections (but they contain less useful information than I remembered)
* System Information
* DxDiag Notes
* DirectX Debug Levels
* Display Devices

You can censor out things like computer name and paths if you want.

**Comment by fredizzimo** [comment] 2024-05-19 11:07
We will release a hotfix soon, but so far no-one has confirmed that the PR actually fixes the issue https://github.com/neovide/neovide/pull/2559. None of the maintainers can confirm since it works without that on all the windows machines that we own.

And it's not totally unusable since you can launch with `--opengl`.

Personally, I also don't like to release a fix without understanding the root cause. Only a subset of the Windows installations are affected, so we don't know what the common denominator is.  We know that the lack of the "Debug tools" feature is one of them, but that's not everything, since completely disabling the debug features from the code does not fix it. 

If someone for example https://github.com/microsoft/windows-rs/tree/master/crates/samples/windows/direct3d12, works without issues, then it's possible that we can make a much better fix.

**Comment by myth0genesis** [comment] 2024-05-19 22:24
I just don't know enough about remote git repos to be able to clone and build any branch that's not the main one 😅 I try to keep the cognitive load for any tools I use as minimal as possible, so I try to keep my usage to as basic a level as I can. If the proposed fix gets merged with the main branch, I'll clone and build and let you know how it goes, though.

**Comment by fredizzimo** [comment] 2024-05-19 22:32
If you have the github cli (https://cli.github.com/) installed you can test it with `gh pr checkout 2559`

And if you don't want to build from souce, then you can download the artifacts from here https://github.com/neovide/neovide/pull/2559/checks

**Comment by myth0genesis** [comment] 2024-05-19 22:39
Just downloaded the pre-built .exe and it works for me.

**Comment by myth0genesis** [comment] 2024-05-19 22:41
And here's my dxdiag.
[DxDiag.txt](https://github.com/neovide/neovide/files/15371028/DxDiag.txt)

**Comment by fredizzimo** [comment] 2024-05-19 23:49
Thanks, I will create a release tomorrow with the fixes.

But there are no hints in the dxdiag log why it wouldn't work with IDXGIFactory4, and why we need to go back all the way to`IDXGIFactory2`, which was available already in Windows 7 with the platform update. In fact you should have the newest one, IDXGIFactory7, which become available in Windows 10 1809.

So there must be something else on the non-working systems. Or something wrong with the Microsoft provided bindings, in which case https://github.com/microsoft/windows-rs/tree/master/crates/samples/windows/direct3d12 should fail as well. Testing that is pretty simple, just clone the repository and run `cargo run --release -p sample_direct3d12`. Could you try that?

**Comment by pedrohgmacedo** [comment] 2024-05-20 02:12
> If someone for example https://github.com/microsoft/windows-rs/tree/master/crates/samples/windows/direct3d12, works without issues, then it's possible that we can make a much better fix.

I compiled that example and ran it. Was it supposed to do anything? Seems like it panicked just like neovide.

**Comment by pedrohgmacedo** [comment] 2024-05-20 02:14
> So there must be something else on the non-working systems. Or something wrong with the Microsoft provided bindings, in which case https://github.com/microsoft/windows-rs/tree/master/crates/samples/windows/direct3d12 should fail as well. Testing that is pretty simple, just clone the repository and run `cargo run --release -p sample_direct3d12`. Could you try that?

This is what I get:
![image](https://github.com/neovide/neovide/assets/118010672/69ea5e52-b0cf-4f76-8c31-0d7f37df5bf4)

**Comment by pedrohgmacedo** [comment] 2024-05-20 02:43
> @asavartsov, yes installing the Graphics tool will allow it to run the debug functionality. But it seems like something else than just the debug features are missing since @myth0genesis, tried to disable them and it still fails to create the interface.

I installed the Graphics Tools and neovide is working now.

**Comment by pedrohgmacedo** [comment] 2024-05-20 03:01
> @myth0genesis, For the dxdiag, mostly the first sections (but they contain less useful information than I remembered)
If it helps, here:
[DxDiag.txt](https://github.com/neovide/neovide/files/15372156/DxDiag.txt)

**Comment by pedrohgmacedo** [comment] 2024-05-20 03:08
> If you have the github cli (https://cli.github.com/) installed you can test it with `gh pr checkout 2559`
> 
> And if you don't want to build from souce, then you can download the artifacts from here https://github.com/neovide/neovide/pull/2559/checks

PR 2559 works in my machine 🕺🏻. 
1. I removed graphics tools
2. Confirmed I could still repro with neovide 0.13
3. Downloaded the artifact and run

**Comment by fredizzimo** [comment] 2024-05-20 05:04
I'm re-opening this until the release, so that people can see it more easily.

**Comment by fredizzimo** [comment] 2024-05-20 05:29
@pedrohgmacedo
> I compiled that example (cargo build on the directory) and ran it. Was it supposed to do anything? Seems like it panicked just like neovide.

The release mode is supposed to work without the graphics tools, but the debug mode will crash without it. And yes, a tringle is shown when running it.

Can you confirm that both release and debug crashes without the graphics tools installed? Or is it only the debug mode? I need enough information to report a bug to the windows-rs repository. 

Ideally, we should also confirm that this one works https://github.com/microsoft/DirectX-Graphics-Samples/tree/master/Samples/Desktop/D3D12HelloWorld/src. But that requires compiling from source and Visual Studio, so it might be too complex for you to test.

I might have to try to install a virtual machine and see if I can reproduce the problem there myself.

**Comment by pedrohgmacedo** [comment] 2024-05-20 05:59
> Can you confirm that both release and debug crashes without the graphics tools installed? Or is it only the debug mode? I need enough information to report a bug to the windows-rs repository.

Only the debug mode crashes. 
> Ideally, we should also confirm that this one works https://github.com/microsoft/DirectX-Graphics-Samples/tree/master/Samples/Desktop/D3D12HelloWorld/src. But that requires compiling from source and Visual Studio, so it might be too complex for you to test.

I don't have visual studio installed, only the build tools. If it's possible to compile from the command line without installing visual studio, I'd be down to test it.

**Comment by fredizzimo** [comment] 2024-05-20 06:10
It might be possible to compile with the command line, but I don't have any instructions for it. So, the best option is Visual Studio https://visualstudio.microsoft.com/downloads/ (note not Visual Studio Code), with the Desktop Development with C++ workload (asked during the installation).

**Comment by pedrohgmacedo** [comment] 2024-05-20 06:13
> It might be possible to compile with the command line, but I don't have any instructions for it. So, the best option is Visual Studio https://visualstudio.microsoft.com/downloads/ (note not Visual Studio Code), with the Desktop Development with C++ workload (asked during the installation).

Yeah, I think I'll pass this one 😁

**Comment by fredizzimo** [comment] 2024-05-20 16:14
I was partially able to verify these issues using the official Windows 11 test image https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/, and gpu passthrough.

Just like reported here, it fails to launch in both debug and release without the "Graphics Tools" installed. Installing it fixes the problem. 

But I was unable to reproduce the crashing reported here https://github.com/neovide/neovide/issues/2556#issuecomment-2118218322. when setting `CreateDXGIFactory2(0).expect("Failed to create DXGI factory")`.  For me that change alone fixes the issue and does not require the graphics tools to be installed. Logically that also makes sense, because `DXGI_CREATE_FACTORY_DEBUG`  is not meant to be used without the tools It's the fact that we needed to change to `IDXGIFactory4` to `IDXGIFactory2` that threw me off. I can only conclude that there was something wrong with the testing process, maybe not launching the executable that was actually built or something.

The Windows-rs d3d12 example, crashes in debug mode and runs in release mode without any changes. But it doesn't display a triangle. Installing the graphics tools makes the triangle show up in Debug mode, but the release mode is still white. My conclusion is that the example is somehow broken, at least partially.

The native D3D tests have a similar behaviour, but the release mode displays a triangle both with the tools installed and not.

This means that I'm quite confident in releasing the fix, and that it's not some kind of bad workaround. The change to `IDXGIFactory2` is probably not needed, unless we want to support Windows 7, but it shouldn't do any harm either.

**Comment by VladimirMarkelov** [comment] 2024-05-24 22:14
Thank you for the update! Version `0.13.1` fixes the panic at start, but I have a new trouble with `0.13.1` on Windows 10 (neovim `0.10.0`). After start neovide does not show anything inside its windows The windows is filled with colorscheme background color - neither text nor cursor nor statusline is visible. On the other hand, neovide responds to key presses: I am able to type blindly `:q<Return>` and neovide closes after that correctly.

**Comment by fredizzimo** [comment] 2024-05-24 22:26
@VladimirMarkelov, can you post a logfile with `neovide --log`

**Comment by fredizzimo** [comment] 2024-05-24 22:31
And can you put it in #2592

I'm closing this one

**Closed by fredizzimo** 2024-05-24 22:31 UTC
Labels: bug
