### ISSUE TITLE
Font size incorrect when display density changes

### ISSUE THREAD

**Issue by dhleong** [neovide/neovide#2542] opened 2024-05-13 16:32 UTC
**Describe the bug**

When the display density goes from a high value to low, the font size is stuck at the higher density size.

**To Reproduce**
1. Open neovide on a retina MacBook Pro (for example).
2. Open some files
3. Plug the laptop into an external monitor with a lower pixel density
4. See error (screenshot below)

**Expected behavior**

I would expect the font size to adjust to the display density.

**Screenshots**

![Screenshot 2024-05-13 at 12 24 59 PM](https://github.com/neovide/neovide/assets/816150/7997fd21-4913-4a5f-a88b-a30002099252)

**Desktop (please complete the following information):**
 - OS: macOS 14.4.1; also experienced before upgrading to Sonoma
- Neovide Version: 0.12.2
 - Neovim Version: 0.9.4

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

Pastebin [here](https://pastebin.com/GCfwjAaJ) (it was too long to paste inline)

**Additional context**
- Moving the mouse over the affected lines causes *only those lines* to be re-rendered. 
- Lines in other tabs do not get fixed when the same visual line is fixed in another tab; the issue persists across tab switches
- `:redraw[!]` does not fix the issue

**Comment by fredizzimo** [comment] 2024-05-13 17:25
This is a duplicate of
* https://github.com/neovide/neovide/issues/2479

I will check if I can repeat it later today, it used to work before.

**Closed by fredizzimo** 2024-05-13 17:25 UTC
Labels: bug
