### ISSUE TITLE
Differences between Kitty and Neovide

### ISSUE THREAD

**Issue by ddevaal** [neovide/neovide#2375] opened 2024-02-22 07:58 UTC
I want Neovide to look the same as vim running under Kitty. But I have no idea how to fix the issues below:

On the left you see Kitty with Lazyvim (nevermind the blur). On the right Neovide. Somehow there are horizontal lines in the LazyVim logo?

Also the 'lightning' icon seems to have a different color but this might be a LazyVim issue.

![LAZYVIM kopie](https://github.com/neovide/neovide/assets/74067645/a6f4ea30-c25a-4432-92d2-fba09b6b8a0d)

I'm using the JetBrainsMono Nerd Font. I have configured this font in `~/.config/neovide/config.toml`:

```
frame = "transparent"

[font]
normal = ["JetBrainsMono Nerd Font"]
size = 13
```

Popup windows are not fully transparent. How can I remove the black background? Kitty/Vim popup windows are fully transparent so I'm not sure if this is a Telescope problem. Also what is going on with the statusbar? 
 
![Neovide](https://github.com/neovide/neovide/assets/74067645/77c59e8b-9fa4-4115-b62c-958714e7365c)

These are the only settings I have configured in LazyVim:

```
vim.g.guifont = "JetBrainsMono Nerd Font:h13"
vim.g.neovide_transparency = 0.5
return {
  "tokyonight.nvim",
  opts = {
    transparent = true,
    styles = {
      sidebars = "transparent",
      floats = "transparent",
    },
  },
}
```

I'm running Neovide 0.12.2 (macOS 14.3.1).

Thanks for any support. Neovide is amazing! ❤️

**Comment by emonadeo** [comment] 2024-02-24 00:16
The popups not being fully transparent is because of how neovide renders [multigrid](https://neovide.dev/command-line-reference.html?highlight=multigrid#multigrid) I think.
Run Neovide with `--no-multigrid`, or put `no-multigrid = true` into your ~/.config/neovide/config.toml to turn it off.
Afaik the floating window transparency is tied to your `neovide_transparency`, so I don't think you can have it look like kitty without disabling multigrid. (Correct me if I am wrong)

**Comment by xzbdmw** [comment] 2024-02-25 06:41
If I set telescope winblend to 100, the font below floating window will not shadow, which is totally invisible if mutigrid is disabled, it is the biggest difference of neovidetransparency and winblend.

**Comment by ddevaal** [comment] 2024-02-26 13:40
> The popups not being fully transparent is because of how neovide renders [multigrid](https://neovide.dev/command-line-reference.html?highlight=multigrid#multigrid).
> 
> To fix this see https://neovide.dev/faq.html#how-to-enable-floating-and-popupmenu-transparency or disable multigrid entirely.
> 
> Afaik the floating window transparency is tied to your `neovide_transparency`, so I don't think you can have it look like kitty without disabling multigrid. (Correct me if I am wrong)
> 
> Maybe we should add a `neovide_floating_transparency` option to decouple them?

Thanks! Disabling multigrid works but it also disables smooth scrolling. One of the reasons I want to use Neovide. I've tried messing around winblend, pumblend options but I can't get it to look right like Kitty/Alacritty (left). 

<img width="1352" alt="Scherm­afbeelding 2024-02-26 om 14 39 22" src="https://github.com/neovide/neovide/assets/74067645/b0827eb9-5d01-45ff-a07a-9d6df1b53b8b">

**Comment by fredizzimo** [comment] 2024-02-26 23:27
There are many things here.

1. The horizontal lines. I'm not fully sure if it's a font problem or if we/skia is rendering Jetbrains Mono wrong, almost all our font problems seem to be caused by that font. It could also be fixed by by drawing the the `box drawing` characters manually. The main issue for this problem is:
  * https://github.com/neovide/neovide/issues/1197
2. The lighting icon, that's the high voltage emoji ⚡ (https://emojipedia.org/high-voltage#technical). Neovim is supposed to render emojis in color,  but the problem is that Nerd fonts also includes it in a non-color form https://www.nerdfonts.com/cheat-sheet (`nf-oct-zap`). And because the nerd fonts have higher priority in your font config, that's used first. I consider this a Nerd Fonts issue, it should not overwrite standard Unicode emoji ranges. I'm not sure what Neovide can do here, and why kitty manages to render it properly. but maybe it always tries system fonts first for emojis or something. A quick fix that you could do is to specify fallbacks fonts like, `["JetBrainsMono", "The System Emoiji Font", "JetBrainsMono Nerd Font"]` So first the regular font, then the emoji and then finally the nerd font one. Alternatively, you could also use the symbols only nerd font. 
3. For the transparency. Neovide renders the transparency like glass, if you put two pieces of darkened glass on top of each other the end result is darker. This is simulated by the standard `over` alpha blending operator as described here for example https://developer.nvidia.com/content/transparency-or-translucency-rendering, and is also what Neovide uses when rendering multigrd.

   So, if you don't want the telescope window to become darker, you have to set it fully transparent, this can be done with 

    ```lua
    telescope.setup({
        defaults = {
            winblend = 100,
        },
    })
    ````
   as documented here https://github.com/nvim-telescope/telescope.nvim/blob/2e1e382df42467029b493c143c2e727028140214/doc/telescope.txt#L215

   And the end result is something like this:
   ![image](https://github.com/neovide/neovide/assets/9946255/9843aaff-bbd0-48b3-a785-d71f79d82d8c)

**Comment by emonadeo** [comment] 2024-02-28 15:24
> Can I set a Zindex to let MutiGrid ignore this floating window, so some plugin using floating window will not have shadows which is a little embarrasing such as this
> 
> <img width="1004" alt="截屏2024-02-28 23 11 20" src="https://github.com/neovide/neovide/assets/97848247/2d634d7d-c95f-4d37-bb8d-8617db7d2584">

You can set `neovide_floating_shadow` to false to disable shadows globally, but I don't think it's possible to set it per plugin/floating window.

You could also try writing a script that enables/disables shadows depending on what floating windows are currently active.

**Comment by ddevaal** [comment] 2024-03-01 07:59
> There are many things here.
> 
> 1. The horizontal lines. I'm not fully sure if it's a font problem or if we/skia is rendering Jetbrains Mono wrong, almost all our font problems seem to be caused by that font. It could also be fixed by by drawing the the `box drawing` characters manually. The main issue for this problem is:
...
> 

I don't have much to say at the moment. But thank you for your extensive answer!

**Comment by fredizzimo** [comment] 2024-04-06 12:38
I created a proposal for dealing with global transparency
* #2471

**Comment by fredizzimo** [comment] 2024-05-17 11:16
I think everything has been answered here now, and covered in different issues, so closing this one.

**Closed by fredizzimo** 2024-05-17 11:16 UTC
Labels: bug
