### ISSUE TITLE
Mouse pointer may be drifted while click and drag selection.

### ISSUE THREAD

**Issue by qianwch** [neovide/neovide#1368] opened 2022-06-24 13:23 UTC
**Describe the bug**
When click and drag mouse to select texts, the line next to the selected line is selected, so the texts from the mouse-clicked position to the next line are selected. 

**To Reproduce**
1. Open any file
2. Click in any line
3. Drag mouse left or right wisely.
4. See the scope of texts selected.

**Expected behavior**
Select only the line where I expected.

**Screenshots**
![截屏2022-06-24 21 12 33](https://user-images.githubusercontent.com/45196316/175543887-62e7b0f9-08b8-48c7-b91d-8cff9764621c.png)
As the upper picture, it is clear I clicked in line 8 and wanted to select texts in line 8, but the actual selected texts are unexpected.

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 12.4]
 - Neovide Version [0.8.0]
 - Neovim Version [0.7.0 / 0.8.0-dev]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
TRACE [neovide] Neovide version: 0.8.0
https://gist.github.com/qianweichun/d05876cf4e2a5daa128375321d16a677
**Additional context**

**Comment by LeeBuckle** [comment] 2022-07-02 23:58
I'm also experiencing this with Neovide 0.9.0, Nvim 0.7.2, on MacOS 12.

![CleanShot 2022-07-03 at 00 56 57](https://user-images.githubusercontent.com/80564456/177019397-c0c35a17-207d-4e6a-b9fd-af9d85d56a44.gif)
3

**Comment by dineshKumar777** [comment] 2022-07-06 23:10
@qianwch @LeeBuckle I dont understand this issue. As long as your mouse cursor selecting in the same line it will work perfectly. When holding and you move mouse to next line, obviously it will select first line complete and move to next line till cursor position.
I tried the same with nvim terminal, vscode too. all behaves the same. 

@qianwch can you attach a video for clear understanding

**Comment by mfichman** [comment] 2022-07-11 20:34
I have this issue too. If multiple window splits are open, then the drag offset is not correct. The initial click position is correct, and accounts for splits to the top & left of the split you clicked in. However, when you start to drag, the dragging seems to use the mouse's absolute position rather than the local position within the current split. Hope that helps.

**Comment by qianwch** [comment] 2022-07-13 15:06
> @qianwch @LeeBuckle I dont understand this issue. As long as your mouse cursor selecting in the same line it will work perfectly. When holding and you move mouse to next line, obviously it will select first line complete and move to next line till cursor position. I tried the same with nvim terminal, vscode too. all behaves the same.
> 
> @qianwch can you attach a video for clear understanding
Here is the video, it is clear that I did not intend to select multiple lines:
https://user-images.githubusercontent.com/45196316/178767011-6d4ba8a3-05e0-4dc8-acd5-c6c4de051d91.mov

**Comment by dineshKumar777** [comment] 2022-07-14 01:20
@qianwch  thanks for sharing. Now i can see the issue.
@j-xella  nice catch. thanks to you finally i can reproduce this issue in my machine.

ref: attached recording
1. first split = can able to select characters, which is the expected behaviour
2. second right split = unable to select characters, instead its selecting the whole line
3. third bottom split = unable to select characters, instead its selecting the whole block
https://user-images.githubusercontent.com/21097695/178865899-10a37049-5797-4950-9f2c-188c42027c8f.mov

**Comment by MultisampledNight** [comment] 2022-08-06 13:07
Haven't seen it mentioned here yet: This is only reproducable with multigrid _not_ set.

**Comment by cobbm** [comment] 2022-08-29 21:49
I'm also experiencing this issue on MacOS 12.4. I'm also using nvim-tree and when the tree is open on the left-hand side, when trying to drag and select text, the selection starts on the correct character, but then dragging the mouse around to select causes the selection cursor to be shifted over to the right by the same width as the tree. If I close the tree, selection is still bugged but is no longer shifted to the right.

My hunch is that neovide is not taking into account things that shift the position of text around (I'm using bufferline too, so the top line of nvim is taken up by bufferline which i think causes the selection to be shifted down by one line)

**Comment by mfichman** [comment] 2022-08-29 22:27
Just wanted to note that turning on multi grid (—multigrid option) fixed
the problem for me.

**Comment by Taverius** [comment] 2022-10-12 18:54
Getting this too, and multigrid causes more issues that it solves with nvim 0.8

**Comment by b4skyx** [comment] 2023-04-04 17:21
This bug has been bothering me as well.
Setting the multigrid option breaks mouse scrolling for me. [1746](https://github.com/neovide/neovide/issues/1746)

A workaround is to set multigrid and neovide_scroll_animation_length to 0.
That virtually disables the smooth scrolling so the mouse scroll isn't broken anymore.

**Comment by sphynx79** [comment] 2023-04-13 22:03
Same problem in windows 10, Neovim 0.9

Same problem, enabling multigrid makes the issue disappear, but the scrolling problem remains.

**Comment by gabe-lee** [comment] 2023-05-17 20:13
I can confirm this is still an issue, MacOS 12.2, neovim 0.9, neovide 0.10.4

I'm using the LunarVim config which comes with a number of plugins pre-installed

When any splits/plugins/settings cause extra rows of information above my buffer window to exist (bufferline, breadcrumbs, etc.) my selection starts at the correct place but when dragging it is offset by EXACTLY the number of rows taken up above the buffer.

Same with anything to the left of the buffer window (NvimTree, etc.), the selection starts at the correct place but when dragging it is immediately offset by the column width of the windows to the left.

**Comment by 9mm** [comment] 2023-08-20 19:32
I'm having this same issue, but in a slightly different way, using different permutations of various settings:

```
no multigrid, buttonless frame, tabs visible, bug = present
no multigrid, buttonless frame, tabs hidden, bug = absent
multigrid, buttonless frame, tabs visible, bug = absent
```

Up above, it looks like they're NOT using buttonless, and tabs are hidden...

So maybe their button frame + no tabs is the same as my frameless + tabs?

So far by switching to multigrid I have no more issues. I havent tested if multigrid + no tabs also has the bug or not, but i can if someone needs me to test more

**Comment by Kethku** [comment] 2023-11-08 23:44
Closing this as multigrid is now the default and any remaining issues with it should be considered high priority bugs

**Closed by Kethku** 2023-11-08 23:44 UTC
Labels: bug
