### ISSUE TITLE
[Linux] Keyboard input requires mouse click, even if window is actively focused

### ISSUE THREAD

**Issue by mmstick** [neovide/neovide#960] opened 2021-09-16 16:48 UTC
**Describe the bug**

On Linux, when Neovide's window is given focus by the window manager, keyboard inputs aren't handled until after clicking the window.

**To Reproduce**

1. Using a tiling window manager, Super + Arrow to move focus between Neovide windows
2. Even if a Neovide window is focused, keyboard input doesn't function until clicking the window with a mouse pointer
3. And after clicking, you may now type and run commands

**Desktop (please complete the following information):**
 - OS: Pop!_OS 21.10
 - Neovide: 839f293

**Comment by Kethku** [comment] 2021-09-18 18:43
I think this is an upstream winit issue. Can you try using some of the winit examples? Unfortunately I don't have a linux box to repro this myself.

**Comment by rti** [comment] 2021-09-20 17:41
This behavior sounds familiar to me. A similar issue was reported in #942.

There is an experimental fix. If you want to give it a try, you can build my branch `fix-gnome-x11-meta-mod-focus` from https://github.com/rti/neovide.

**Comment by rti** [comment] 2021-09-20 18:25
This _should_ be fixed in https://github.com/Kethku/winit/pull/1

**Comment by Kethku** [comment] 2021-09-20 19:33
I plan on reworking the combined keyboard branch soon TM.

there have been more upstream changes that need integrated on top of this PR so its a little more work than just merging :)

**Comment by jonvaldes** [comment] 2021-11-02 20:29
I'm also hitting this issue in my Linux box.

Given the current state of things, is there anything we can do to help out here, @Kethku?

**Comment by Kethku** [comment] 2022-01-10 21:02
@jonvaldes do you still encounter this? I think its possible this is fixed.

**Comment by jonvaldes** [comment] 2022-01-15 16:05
Issue seems to be gone indeed. 👍🏻 

A bit of a weird thing, though. When hitting Alt+Tab while in insert mode, it switches to normal mode. This doesn't happen in nvim on the terminal. Is this a known thing?

**Comment by Kethku** [comment] 2022-01-15 19:22
I'm not aware of that bug off the top of my head, but it may be captured somewhere. It'd be helpful to open an issue and we can dedup later if necessary

**Comment by jonvaldes** [comment] 2022-01-18 21:59
Ok, just ran some tests and confirmed it. I'll create an issue for it

**Comment by jonvaldes** [comment] 2022-01-20 19:27
Closing this as I can't repro it anymore.

**Closed by jonvaldes** 2022-01-20 19:27 UTC
Labels: bug, upstream, Keyboard Input

**Comment by mihneaCR** [comment] 2022-05-06 15:37
Also present for me, when building from source.
Using Arch with Kernel 5.17.5,

**Comment by almcr** [comment] 2022-07-31 08:22
Same here as described by @Enayaaa. builded from source, and running on `Pop-os 22.04`,

**Comment by pspiagicw** [comment] 2022-08-07 12:03
Same here , PopOS 22.04 and latest Neovide from release.

**Comment by Alex-vZyl** [comment] 2022-09-04 08:21
Also having this issue with i3.

**Comment by hn275** [comment] 2022-09-14 07:17
I have the same issue! running it on Arch 5.19, built from source and AUR.

**Comment by correabuscar** [comment] 2022-09-26 07:45
I hit the same issue but it doesn't work if I just click it, clicking within it makes the cursor move there, even though the keyboard doesn't work still. I have to alt-tab away then alt-tab back (just like [this comment](https://github.com/neovide/neovide/issues/960#issuecomment-1119748904)) for it to see the `FocusGained` event for the first time (it actually sees it right before `FocusLost` when I alt-tab away) and only then it allows keyboard inputs to work.

[This workaround](https://github.com/neovide/neovide/compare/main...rti:neovide:fix-gnome-de-function-focus-loss-handling#diff-7cce2ffa667db375a182b9eaf6280c9cac6a224d2e8d0afbcc3840b4d3468672L42-R43) from [the above comment](https://github.com/neovide/neovide/issues/960#issuecomment-923139093) doesn't seem to work for me, in fact the following doesn't affect my issue at all:
```patch
diff --git a/src/window/keyboard_manager.rs b/src/window/keyboard_manager.rs
index 2807dbf..0222198 100644
--- a/src/window/keyboard_manager.rs
+++ b/src/window/keyboard_manager.rs
@@ -20,7 +20,7 @@ pub struct KeyboardManager {
     alt: bool,
     prev_dead_key: Option<char>,
     logo: bool,
-    ignore_input_this_frame: bool,
+    //ignore_input_this_frame: bool,
     queued_input_events: Vec<InputEvent>,
 }
 
@@ -32,7 +32,7 @@ impl KeyboardManager {
             alt: false,
             prev_dead_key: None,
             logo: false,
-            ignore_input_this_frame: false,
+            //ignore_input_this_frame: false,
             queued_input_events: Vec::new(),
         }
     }
@@ -45,7 +45,7 @@ impl KeyboardManager {
             } => {
                 // When window is just focused or lost it's focus, ignore keyboard events
                 // that were submitted this frame
-                self.ignore_input_this_frame = true;
+                //self.ignore_input_this_frame = true;
             }
             Event::WindowEvent {
                 event:
@@ -79,7 +79,7 @@ impl KeyboardManager {
             }
             Event::MainEventsCleared => {
                 // If the window wasn't just focused.
-                if !self.should_ignore_input() {
+                //if !self.should_ignore_input() {
                     // And we have a keyboard event this frame
                     for input_event in self.queued_input_events.iter() {
                         let mut next_dead_key = self.prev_dead_key;
@@ -111,11 +111,11 @@ impl KeyboardManager {
                         }
                         self.prev_dead_key = next_dead_key;
                     }
-                }
+                //}
 
                 // Regardless of whether this was a valid keyboard input or not, rest ignoring and
                 // whatever event was queued.
-                self.ignore_input_this_frame = false;
+                //self.ignore_input_this_frame = false;
                 self.queued_input_events.clear();
             }
             _ => {}
@@ -123,8 +123,9 @@ impl KeyboardManager {
     }
 
     fn should_ignore_input(&self) -> bool {
-        let settings = SETTINGS.get::<KeyboardSettings>();
-        self.ignore_input_this_frame || (self.logo && !settings.use_logo)
+        //let settings = SETTINGS.get::<KeyboardSettings>();
+        //self.ignore_input_this_frame || (self.logo && !settings.use_logo)
+        false
     }
 
     fn maybe_get_keybinding(&self, key_event: &KeyEvent) -> Option<String> {
```
