### ISSUE TITLE
os.execute() of lua will crash

### ISSUE THREAD

**Issue by MontiL** [neovide/neovide#1376] opened 2022-06-30 03:06 UTC
**Describe the bug**
in command mode:
: lua os.execute("ls") <-- will crash while executing any command

**To Reproduce**
1. Go to 'command mode'
2. : lua os.execute("ls") or any os commands
3. crash

**Expected behavior**
execute without crash

**Desktop (please complete the following information):**
 - OS: macOS 12.4 M1
 - Neovide Version: 0.8.0
 - Neovim Version: : 0.7.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:
[neovide_r2022-06-30_10-57-11.log](https://github.com/neovide/neovide/files/9016097/neovide_r2022-06-30_10-57-11.log)
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/9016098/neovide_rCURRENT.log)

**Comment by MultisampledNight** [comment] 2022-06-30 06:55
Can reproduce. Shuffling a bit around in `rr` I found this hidden error:

```rs
nvim_rs::error::DecodeError::InvalidMessage(nvim_rs::error::InvalidMessage::NotAnArray(rmpv::Value::Integer(rmpv::Integer {
          n: rmpv::IntPriv::PosInt(97)
        })))
```

The question is... why would Neovide expect an array...

**Comment by MultisampledNight** [comment] 2022-06-30 07:08
https://docs.rs/nvim-rs/0.4.0/nvim_rs/error/enum.InvalidMessage.html

> This should be very basically non-existent, since it would indicate a bug in neovim.

Hm. Wondering whether we should report this upstream.

**Comment by starptr** [comment] 2023-01-04 07:39
Took me a bit to figure out why neovide was crashing; maybe this bug should be documented in the [Troubleshooting page](https://neovide.dev/troubleshooting.html) :)

**Comment by shaunsingh** [comment] 2023-01-27 17:03
I think we should report this upstream rather than asking users to work around it. If its deemed a bug with nvim-rs/neovide instead of neovim itself we can certainly add it to the documentation and work on fixing it here

**Comment by starptr** [comment] 2023-02-01 23:39
I agree, but for the time being I think as a user of neovide it would have been nice to know about this behavior instead of having to bisect it again. I also don't know enough about neovim to confirm that the bug is upstream; I'm quoting here (it looks like there is a possibility that this is an nvim_rs issue instead? I am not sure).

So maybe the correct order of actions is
1. File a bug in neovim
2. Document this behavior in the neovide docs, and **link to the ticket** in the documentation

I will try to file the bug in neovim in a few weeks if no one else has filed it by then

**Comment by MultisampledNight** [comment] 2023-02-04 11:44
For what it's worth, I can't reproduce this on Neovim Nightly with neovim/neovim@90333b24c3 anymore. @starptr can you check whether or not that's the case on your side?

**Comment by MultisampledNight** [comment] 2023-02-04 15:04
Oh, maybe it's also been fixed by #1697. Either way, a reconfirmation would be useful!

**Comment by MontiL** [comment] 2023-02-06 04:35
Update original bug:

Describe the bug
in command mode:
: lua os.execute("ls") <-- will crash while executing any command

To Reproduce
Steps to reproduce the behavior:

1. Go to 'command mode'
2. : lua os.execute("ls") or any os commands
3.  doesn't get info from ls command
Expected behavior
execute and get ls info

Desktop (please complete the following information):

OS: macOS 13.1 M1
Neovide Version: 0.10.3
Neovim Version: : v0.9.0-dev-867+gf9826e1df-dirty
**Please run neovide --log and paste the contents of the .log file created in the current directory here:
[neovide_r2023-02-06_12-30-35.log](https://github.com/neovide/neovide/files/10659742/neovide_r2023-02-06_12-30-35.log)
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/10659743/neovide_rCURRENT.log)

**Comment by MultisampledNight** [comment] 2023-02-07 11:04
Hm, I'm not exactly sure anymore if this is something upstream can even _do_ anything about. Since Neovide runs Neovim with `--embed`, Neovim communicates to Neovide through stdout — but the same stdout seems also to be used by lua's `os.execute`. This can be confirmed by comparing `echo` and `echo -n`: The first one prints a newline and crashes Neovide, the second one prints not even a newline and does not crash Neovide.

But on the other hand I'm not sure where the stdout of `os.execute` is supposed to go either. TUI nvim cries with having an invalid file handle on `:lua os.execute("ls")`.

**Comment by MultisampledNight** [comment] 2023-02-07 11:27
Hm, I'll just go ahead and open an issue on the Neovim repo. Even if they don't see a way to fix it, they'll likely have an idea on how to work around it.

**Comment by MultisampledNight** [comment] 2023-02-07 11:47
Wait a moment. This somehow doesn't seem to happen with neovim-qt.

**Comment by last-partizan** [comment] 2023-06-11 07:19
I think this can be closed.

I cannot reproduce this, and https://github.com/epwalsh/obsidian.nvim/issues/65#issuecomment-1556556923 this issue is closed also.

**Closed by last-partizan** 2023-06-11 07:19 UTC
Labels: bug
