### ISSUE TITLE
Multigrid: Resizing pane crashes neovide

### ISSUE THREAD

**Issue by bmulholland** [neovide/neovide#1503] opened 2022-08-24 11:41 UTC
**Describe the bug**
Resizing panes in multigrid crashes neovide.

**To Reproduce**
1. `neovide --multigrid`
2. Resize a pane with `Ctrl-W |` or `Ctrl-W _`
3. Crash

**Desktop (please complete the following information):**
 - OS: macOS 12.5.1 (21G83)
 - Neovide Version: Neovide 0.10.1
 - Neovim Version: v0.7.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
This seems to produce two log files: https://gist.github.com/bmulholland/10c697f770e5c51a1ee294d61f1ff51e

**Comment by Kethku** [comment] 2023-04-08 00:33
@bmulholland does this crash with a more modern version of neovim?

**Comment by bmulholland** [comment] 2023-07-10 17:19
I just reproduced this again. Is there a crash log that I can get if I don't start neovide with logs enabled?

**Comment by bmulholland** [comment] 2023-07-21 10:09
Okay here's the logs: https://gist.github.com/bmulholland/fdc532f589203e13e3ad7b285d10713a

NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

neovide 0.10.4

**Comment by fredizzimo** [comment] 2023-07-23 18:10
I'm quite sure, but not completely, that this is a Neovim bug.

If you open a Neovim instance in the terminal (not through Neovide), then inside that open a terminal buffer, and start resizing the teriminal window rapidly, it soon crashes.

I found this out a few days ago, but I have not reported a Neovim bug yet.

**Comment by bmulholland** [comment] 2023-07-24 17:28
Ahh -- and multigrid implements resize through a rapid series of resizes?

**Comment by fredizzimo** [comment] 2023-07-24 18:02
Not necessarily rapidly, but it's the resizing of the terminal that's crashing it. Doing it rapidly just makes it easier to repeat.

BTW, I just tried the terminal mode Neovim,  opened a built in terminal with a vsplit, grabbed the split with the mouse and rapidly moved it back and forth, and was able to make it crash that way as well. So that makes me even more certain that that it's a Neovim bug, and not a Neovide one.

**Comment by fredizzimo** [comment] 2023-07-24 19:43
I reported this here https://github.com/neovim/neovim/issues/24471

**Comment by fredizzimo** [comment] 2023-07-24 21:26
@bmulholland, your issue is probably different after all, since the terminal resizing bug seems to an issue only with Neovim nightly.

**Comment by fredizzimo** [comment] 2023-07-24 21:44
@bmulholland. I took a closer look at the logs, and it appears like there are two issues. You have many crashes related to dragging something with the mouse. Is that something you have reported in another issue?

For the new one "Could not create surface.", that one should be fixed in #1790, and therefore also #1870, which is based on that. I'm not sure what's the cause could have been, but it could be either an invalid size, or out of GPU memory. #1790 don't create any additional surfaces during runtime, so therefore I think it will be fixed by that.

**Comment by bmulholland** [comment] 2023-07-25 12:56
I don't recall ever seeing a crash caused by dragging the mouse. I pretty much never use my mouse with neovide. I'm happy to test this again once those PRs are released :)

**Closed** 2023-11-01 18:54 UTC
Labels: bug, crash

**Comment by bmulholland** [comment] 2023-11-02 12:17
Looking forward to testing this fix in the next release :)
