### ISSUE TITLE
Window show up at the bottom on macOS

### ISSUE THREAD

**Issue by stevalkr** [neovide/neovide#2767] opened 2024-08-17 14:24 UTC
**Describe the bug**

When I start `neovide` from terminal (Kitty.app), I'm still at kitty and neovide always shows up in the background, meaning I have to "Cmd-Shift-Tab" to open the window.

**To Reproduce**
1. Open Kitty.app
2. run `neovide`

**Expected behavior**

Like any other apps, it should show up at the top

**Screenshots**

https://github.com/user-attachments/assets/79ef76ab-d0b6-4df6-a32d-dad325d9a03b

**Desktop (please complete the following information):**
 - OS: macOS 15.1 beta
 - Neovide Version 0.13.3
 - Neovim Version 0.10.1

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

[neovide_rCURRENT.log](https://github.com/user-attachments/files/16645253/neovide_rCURRENT.log)

**Comment by fredizzimo** [comment] 2024-08-22 23:32
I'm closing this as a duplicate of
* https://github.com/neovide/neovide/issues/2330

**Closed by fredizzimo** 2024-08-22 23:32 UTC
Labels: bug
