### ISSUE TITLE
Slow downs and keys getting shuffled

### ISSUE THREAD

**Issue by Diegovsky** [neovide/neovide#802] opened 2021-07-07 05:26 UTC
**Describe the bug**
Slow initialisation, occasional slowdowns, stuttering and keys being shuffled if pressed too fast.

**To Reproduce**
1. Be on `main`, compiled using AUR's `neovide-git`.
2. Open neovide

**Video**
Here's a video comparison with neovide from `main` and alacritty:
https://www.dropbox.com/s/7xz565u63v3h0ol/2021-07-07%2001-58-02.mp4?dl=0

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Neovide Version: `main` 80c57bb (shown in video) and 07c0349  
 - Neovim Version: 0.5 `master`

**Additional context**
I'm not sure what caused this on `main` but Neovide 0.7 is really smooth and fast. About the video: I did type incorrectly in alacritty once, but the rest was clean :)

**Comment by Kethku** [comment] 2021-07-07 06:08
Ok yes. That issue is similar to what I'm encountering on my first gen surface book. Hopefully whatever fix I come up with there will fix here. Stay tuned

**Comment by Diegovsky** [comment] 2021-07-07 16:45
Alrighty :)

Here's my specs if that helps profile what is be going on:
CPU: Ryzen 5 3600
GPU: AMD Rx 580
Root drive: nvme
Ram: 16Gb ddr4
Display server: Sway (wayland)
Drivers: amdgpu, amdvlk
Mesa version: 21.1.4

Also: I'm using two monitors of different resolution, 1080p and 1360p

**Comment by Diegovsky** [comment] 2021-07-10 20:10
Just reporting in here to say that as of 07c0349 I don't feel any noticeable slowdowns :)

 I haven't tested any commit before btw

**Comment by bltavares** [comment] 2021-08-11 01:05
I'm also facing a similar situation on a5d1af226f376e4e34d20f4298e1b4fe25653745

I noticed that if I change the window size, `neovide` goes from 32mb-56mb in memory to 238mb-242mb and becomes very laggy, starting to scramble input if I type fast.

I'm not setting any `guifont` on my config. Runnig `neovim --maximized` attempts to maximize the screen, but Mac resizes it to a smaller size after it starts. Calling it with a preset geometry (eg: `neovide --geometry 400x400`) also causes the laggy behaviour.

```
Processor            •  Intel® Core™ i7-4770HQ CPU @ 2.20GHz (8)
Memory               •  16.8 GB    
Operating System     •  macOS 10.15.7 Catalina 
```

**Comment by bltavares** [comment] 2021-08-12 22:43
I dunno what happened, but I've tried to `git bisect` the commit which caused it and I cannot reproduce it anymore - confused.

I did not clear the cache between builds - maybe something was cached and linked on the final binary that improved - but I dunno what it would be.

**Comment by Kethku** [comment] 2022-01-20 02:38
This is fixed in main. Please reopen if the problem persists.

Note: there is a cursor fps issue being tracked elsewhere. Closing this as key shuffling is fixed

**Closed by Kethku** 2022-01-20 02:38 UTC
Labels: bug

**Comment by letavocado** [comment] 2023-04-04 21:57
Running `neovim --maximized` becomes very laggy, without `--maximized` works fine. 

```
Neovide: 0.10.3 (latest release) on Nov 7, 2022 ·06986a8

Nvim: v0.8.3 (latest stable release)
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by builduser

OS: Arch Linux x86_64
HOST: XPS 17 9700
Kernel: 6.2.8-arch1-1
DE: GNOME 43.4
Resolution: 3840x2400
WM: Mutter (Wayland)
CPU: Intel i9-10885H (16) @ 5.300GHz
GPU: NVIDIA GeForce RTX 2060 Max-Q

```
