### ISSUE TITLE
Text Rending issue

### ISSUE THREAD

**Issue by xyven1** [neovide/neovide#2282] opened 2024-01-18 02:20 UTC
**Describe the bug**
Text is rendering incorrectly when searching files with fzf-lua in neovim.

**To Reproduce**
1. With fzf-lua installed run: `:FzfLua files`
2. Type something in

**Expected behavior**
Text should render clearly (see screenshots)

**Screenshots**
This is the issue in neovide:
![image](https://github.com/neovide/neovide/assets/35360746/ea2c2262-f52b-49c7-a72d-260097f5ed30)
And here it is rending fine in wezterm:
![image](https://github.com/neovide/neovide/assets/35360746/920358e2-ed9e-4f91-812a-798eedb6fdb8)

If the first letter in the fuzzy match is present it works?
![image](https://github.com/neovide/neovide/assets/35360746/6392b3df-e45c-4416-b401-4bf1c56a6ca8)

**Desktop (please complete the following information):**
 - OS: NixOS (23.11)
 - Neovide Version: 0.12.1
 - Neovim Version: v0.10.0-dev-28c183b

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
This is a 1.6MB file for me?

**Additional context**
If you want to better understand the environment that neovide is running in, you can check my nixos config at https://github.com/xyven1/nixos-configuration. The gist of it is: gnome, wayland, paperwm

**Comment by xyven1** [comment] 2024-01-18 02:21
My guess is its an issue with the terminal escape sequences being used?

**Comment by fredizzimo** [comment] 2024-01-18 02:30
This is duplicate of
* https://github.com/neovide/neovide/issues/2211

There is a workaround in the thread, but I'm not sure what the proper fix would be, it most likely need either a patch to fzf lua or Neovim

**Closed by fredizzimo** 2024-01-18 02:30 UTC
Labels: bug
