### ISSUE TITLE
Neovide panics when displays are added or removed

### ISSUE THREAD

**Issue by aryanjassal** [neovide/neovide#2795] opened 2024-09-17 04:36 UTC
**Describe the bug**
I am using Hyprland on NixOS. When I connect my external displays, I disable my laptop screen using `hyprctl`. When I either disable or enable the screen, Neovide panics with the following output:

```console
[aryanj@laptop:~]$ neovide
ERROR [neovide::settings::config] Could not watch config file, chances are it just doesn't exist: No such file or directory (os error 2) about ["/home/aryanj/.config/neovide"]
Neovide panicked with the message 'Received event for dead output'. (File: /build/neovide-0.13.3-vendor.tar.gz/smithay-client-toolkit/src/output.rs; Line: 425, Column: 14)
This is a bug and we would love for it to be reported to https://github.com/neovide/neovide/issues
```

**To Reproduce**
1. Use Hyprland
2. Launch Neovide
3. Modify monitor configuration using `hyprctl`
4. profit

**Expected behavior**
It should keep running

**Screenshots**
N.A.

**Desktop:**
 - OS: Linux (6.6.31), NixOS (24.05)
 - Neovide Version: 0.13.3
 - Neovim Version: 0.10.1

#### `neovide_backtraces.log`:
```
2024-09-17 03:51:14 - Neovide panicked with the message 'Received event for dead output'. (File: /build/neovide-0.13.3-vendor.tar.gz/smithay-client-toolkit/src/output.rs; Line: 425, Column: 14)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::panicking::panic_display
   7: core::option::expect_failed
   8: wayland_client::event_queue::queue_callback
   9: wayland_client::event_queue::EventQueue<State>::dispatching_impl
  10: <core::cell::RefCell<calloop::sources::DispatcherInner<S,F>> as calloop::sources::EventDispatcher<Data>>::process_events
  11: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::loop_dispatch
  12: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::pump_events
  13: neovide::main
  14: std::sys_common::backtrace::__rust_begin_short_backtrace
  15: main
  16: __libc_start_call_main
  17: __libc_start_main@@GLIBC_2.34
  18: _start
```

**Additional context**

**Comment by fredizzimo** [comment] 2024-09-17 05:01
It looks like the root cause is a bug in hyprland. However, winit and `smithay-toolkit` has a patch available, so we need to update to that.

* https://github.com/rust-windowing/winit/pull/3774
* https://github.com/Smithay/client-toolkit/pull/461
* https://github.com/Smithay/client-toolkit/issues/468
* https://github.com/alacritty/alacritty/issues/8065

We need to update to at least winit 0.30.4 (On Wayland, avoid crashing when compositor is misbehaving) https://github.com/rust-windowing/winit/releases/tag/v0.30.4

**Comment by Kethku** [comment] 2024-09-22 22:38
Merged. Should be fixed now. @aryanjassal can you try from main?

**Closed** 2024-09-22 22:38 UTC
Labels: bug, Windowing, Wayland
