### ISSUE TITLE
I can't use the cmd+v to paste text on my mac; 

### ISSUE THREAD

**Issue by CG-man** [neovide/neovide#1263] opened 2022-04-07 06:27 UTC
**Describe the bug**
I can't use the cmd+v to paste text on my mac; 

**To Reproduce**
1. use cmd+c to copy something
2. switch to neovide
3. cmd+v to paste the text 

**Expected behavior**
paste the text to buffer/other

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 12.3
 - Neovide Version 0.8.0
 - Neovim Version 0.7.0

**Please run `neovide --log` and paste the contents of the `.log` file here:**

**Additional context**

**Comment by MultisampledNight** [comment] 2022-04-07 09:42
Neovide just forwards all key commands to NeoVim, which indeed does not have <kbd>Cmd</kbd> + <kbd>V</kbd> (or `<M-v>` in Vim) bound to anything. You can use the `clipboard` option and set it to `unnamedplus` if you want to use <kbd>p</kbd> and <kbd>y</kbd> as replacements for it. Or rebind `<M-v>` to `"+p` and `<M-c>` to `"+y`.

Either way, closing as that's not an issue with Neovide itself.

**Comment by terhechte** [comment] 2022-04-11 07:05
@CG-man 
Actually, using `<D-v>` or `<D-c>` does nothing on macOS because [this PR](https://github.com/neovide/neovide/pull/857) disables the command key. Took me way too long to figure this out as it isn't really documented.

To enable Cmd + V / Cmd + P on macOS, I have these bindings:

```
" Allow copy paste in neovim
let g:neovide_input_use_logo = 1
map <D-v> "+p<CR>
map! <D-v> <C-R>+
tmap <D-v> <C-R>+
vmap <D-c> "+y<CR> 
```

**Comment by terhechte** [comment] 2022-04-11 07:06
@MultisampledNight So it is a bit of a Neovim issue because Neovim introduces a non-standard setting that disables the command key by default. Personally, I think this setting should be default-enabled on macOS. Would be willing to crate a PR for that.

**Comment by MultisampledNight** [comment] 2022-04-11 10:26
@terhechte (you probably meant this is a Neovide issue) That's valid, feel free to try it out! I think it should be as simple as manually implementing the `Default` trait for `KeyboardSettings`.

**Comment by amitkot** [comment] 2022-04-17 14:59
Based on @terhechte , I used this in `init.lua`:

```lua
-- Allow clipboard copy paste in neovim
vim.g.neovide_input_use_logo = 1
vim.api.nvim_set_keymap('', '<D-v>', '+p<CR>', { noremap = true, silent = true})
vim.api.nvim_set_keymap('!', '<D-v>', '<C-R>+', { noremap = true, silent = true})
vim.api.nvim_set_keymap('t', '<D-v>', '<C-R>+', { noremap = true, silent = true})
vim.api.nvim_set_keymap('v', '<D-v>', '<C-R>+', { noremap = true, silent = true})
```

**Comment by metalelf0** [comment] 2022-05-25 07:39
I think having something that works out of the box (without the need to search the project issue tracking, copying mappings and so on) would be much better. `cmd-v` is the standard paste command on macOS. A GUI user shouldn't care about keycodes, mappings and this kind of stuff unless doing something custom. Pasting should "just work" like in the rest of the OS.

**Comment by MultisampledNight** [comment] 2022-05-25 09:19
Unfortunately fronts are hitting against each other in this case. Some users might have <kbd>Cmd</kbd> + <kbd>V</kbd> mapped to something else, as it is the same combination as <kbd>Meta</kbd> + <kbd>V</kbd> in other cases.

**Comment by benwaffle** [comment] 2022-06-10 14:04
Agreed with @metalelf0, as neovide is a GUI, I expect <kbd>⌘</kbd>+<kbd>v</kbd> to work. <kbd>⌘</kbd>+<kbd>v</kbd> already works in iTerm2 with neovim.

If a user has <kbd>⌘</kbd>+<kbd>v</kbd> mapped to something else, does that still work in iTerm/neovim?

**Comment by rmagatti** [comment] 2022-07-26 03:02
Just wanted to give my 2 cents here. I agree with @MultisampledNight on this. Imo it's better to have the flexibility as the GUI implementation and just document things really well with a section in the readme for MacOS users than to just make it the default. MacOS isn't the only OS out there, people might be porting their configs, it's likely inadvisable for Neovide to assume a particular use case.

**Comment by jonasdiemer** [comment] 2022-08-05 11:05
I agree with @metalelf0 for out-of-the box behavior on MacOS - took me a while to realize why pasting wouldn't work (with an otherwise well-working vimrc).

But I can also see as @rmagatti  pointed out that other platforms may expect different defaults. Hence I've created a [PR](https://github.com/neovide/neovide/pull/1455) to change the default only for MacOS builds.

**Closed** 2022-08-13 19:10 UTC
Labels: bug

**Comment by shepherdjerred** [comment] 2022-10-08 22:33
> Based on @terhechte , I used this in `init.lua`:
> 
> ```lua
> -- Allow clipboard copy paste in neovim
> vim.g.neovide_input_use_logo = 1
> vim.api.nvim_set_keymap('', '<D-v>', '+p<CR>', { noremap = true, silent = true})
> vim.api.nvim_set_keymap('!', '<D-v>', '<C-R>+', { noremap = true, silent = true})
> vim.api.nvim_set_keymap('t', '<D-v>', '<C-R>+', { noremap = true, silent = true})
> vim.api.nvim_set_keymap('v', '<D-v>', '<C-R>+', { noremap = true, silent = true})
> ```

This worked perfectly! Thank you.

**Comment by suyby** [comment] 2022-10-27 00:17
> 
In addition, the value should be assigned like this.
```
vim.g.neovide_input_use_logo=v:true
```

**Comment by i-am-the-slime** [comment] 2022-11-07 20:11
@suyby 
It just doesn't work:
NVIM v0.8.0
macOS 13

**Comment by shepherdjerred** [comment] 2022-11-07 20:17
> @suyby It just doesn't work: NVIM v0.8.0 macOS 13

What isn't working? What happens when you use `cmd + v`? Can you paste your configuration?

**Comment by suyby** [comment] 2022-11-08 07:14
@shepherdjerred @i-am-the-slime My configuration is 
```
if exists("g:neovide")
  let g:neovide_transparency=0.9
  let g:neovide_no_idle=v:false
  let g:neovide_fullscreen=v:false
  let g:neovide_remember_window_size=v:true
  let g:neovide_cursor_animation_length=0.1
  let g:neovide_cursor_antialiasing=v:false
  let g:neovide_cursor_vfx_mode = "torpedo"

  " mapping macOS short keys
  let g:neovide_input_use_logo=v:true
  map <D-v> "+p<CR>
  map! <D-v> <C-R>+
  tmap <D-v> <C-R>+
  vmap <D-c> "+y<CR>
endif
```

**Comment by bassamsdata** [comment] 2022-12-15 20:02
II tried all of these key mapping and nothing worked on neovide.

All usual copy and paste via the command key In neovim on alacritty and kitty are working perfectly. (either in vanilla neovim or configured neovim)

the behavior of neovide is weird, in insert mode, when I press <D-v> the output is `^` when I press BS to erase the output transfer to `<BS>` .

In normal mode the `<D-v>` it turns block mode on.

I tried all the configs in this issue, **yet** the problem not solved.

BTW, the command key working perfectly with macvim .

**Comment by falcucci** [comment] 2023-03-20 10:44
@amitkot works like a charm. thank you!

**Comment by hjwp** [comment] 2024-02-15 14:25
I've used the `.nvim_set_keymap()` solution outlined above. all works pretty well (and thanks to everyone who contributed it)...

 except in `command mode`, ie pasting into the `:` menu, `Cmd+V` seems to do nothing until I press another key (eg spacebar).  manually doing `Ctrl-R`, `+` works fine, ie pastes immediately.

any ideas?

**Comment by dexat0r** [comment] 2024-02-21 12:35
Checkout terminal paste
```
  vim.keymap.set('t', '<D-v>', '<C-\\><C-n>"+Pi') -- Paste terminal mode
```

**Comment by jaekyeom** [comment] 2024-02-29 21:43
The suggestions above are helpful, but don't work in some situations (e.g., with [fzf-lua](https://github.com/ibhagwan/fzf-lua), which was bothering me).

The most reliable (and correct imo) solution I've found is using `vim.api.nvim_paste`:
```
vim.keymap.set(
    {'n', 'v', 's', 'x', 'o', 'i', 'l', 'c', 't'},
    '<D-v>',
    function() vim.api.nvim_paste(vim.fn.getreg('+'), true, -1) end,
    opts
)
```

@MultisampledNight It would be nice if you would consider updating the documentation with something like this using `vim.api.nvim_paste`.

**Comment by fredizzimo** [comment] 2024-02-29 21:49
We do have a PR open for updating the docs, but the problem is that it's macOS specific
* https://github.com/neovide/neovide/pull/2101

**Comment by hjwp** [comment] 2024-03-01 11:29
nice one @jaekyeom !  this solves my problem with needing an extra keystroke after pasting in command mode.  i'll adopt it.

i did notice a slight difference in the way pasting multiline strings behaves in command mode.  before, it pasted them as a single line with `^M` chars in.  with  your version it just pastes the first line (only in command mode. in normal/insert it's fine).  i'm pretty happy that's still better so i'm keeping it, but i'm curious if you know why?

**Comment by jaekyeom** [comment] 2024-03-01 20:49
Hi @hjwp ,
I believe it should be the same behavior as the original Neovim's pasting behavior (which can be modified by setting the `vim.paste` handler according to the [documentation](https://neovim.io/doc/user/api.html#nvim_paste()), though).
Another way to modify the behavior, without touching the `vim.paste` handler, might be just manipulating the string obtained with `vim.fn.getreg('+')` before passing it to `vim.api.nvim_paste `, e.g., replacing newline characters with whitespace characters.

**Comment by youssef-lr** [comment] 2024-09-25 19:50
The terminal mapping in this issue did not work for in insert mode in the terminal, so I went with this instead:

```
-- Function to paste from the system clipboard
local function pasteFromClipboard()
    -- Get the contents of the clipboard using Neovim's API
    local clipboard_content = vim.fn.getreg('+') -- '+' is the system clipboard register

    -- Insert clipboard content at the current cursor position
    vim.api.nvim_put({ clipboard_content }, 'l', true, true)
end
vim.keymap.set('t', '<D-v>', pasteFromClipboard, { silent = true, noremap = true })
```
