### ISSUE TITLE
Neovide does not change keyboard layout when the system keyboard layout gets changed, while neovide is open

### ISSUE THREAD

**Issue by tecbeast42** [neovide/neovide#1084] opened 2021-12-10 09:35 UTC
**Describe the bug**
Open Neovide with e.g. the us keyboard layout. Change the keyboard layout to e.g. de. Neovide still behaves as if the keyboard is set to us. 

**To Reproduce**
use `setxkbmap us` to set to us layout
Open Neovide type 'y'
use `setxkbmap de` to set to de layout
type 'y' it will output 'z'

**Expected behavior**
Keyboard layout changes should apply to neovide.

**Desktop (please complete the following information):**
 - OS: Archlinux with X Server
 - 0.7.0.r227.g4131c50-1

**Please run `neovide --log` and paste the contents of the `.log` file here:**
No output from log

**Comment by Kethku** [comment] 2021-12-10 19:12
Which version of neovide are you running? Is it from main?

**Comment by tecbeast42** [comment] 2021-12-14 09:40
yes but i moved on

i have the same problem with

```
neovide -V
Neovide 0.8.0
```

**Comment by last-partizan** [comment] 2021-12-19 11:35
What desktop environment are you using? Does it work for other apps, besides neovide?

I'm using Gnome, and it has option for per-window input switching.

**Comment by Shatur** [comment] 2021-12-21 14:08
I have the same issue on KDE. I also use per-window input switching, but when switching to another app and switching the layout from US to, say, RU, after returning to Neovide, my system reports that I am using US (this is correct!), but Neovide has Russian input.

**Comment by tecbeast42** [comment] 2022-01-04 09:52
I use bspwm on arch.

Neovide is the only app that has this problem on my system.

**Comment by Kethku** [comment] 2022-01-04 22:17
This is likely a winit issue. I'm curious if its been fixed upstream

**Comment by Kethku** [comment] 2022-01-04 22:21
A quick search doesn't show up anything...

**Comment by tecbeast42** [comment] 2022-05-02 14:11
FYI this issue still persist. Should I open an Issue on winit? 

@Kethku not sure how certain you are that it is related to winit.

**Comment by MultisampledNight** [comment] 2022-05-02 14:43
No, we use a fork of winit which is way behind upstream. You can try reproducing it with winits examples, however.

**Comment by Sinono3** [comment] 2022-05-09 22:13
This happens to me as well on bspwm on Void Linux.

**Comment by coordinatio** [comment] 2022-05-15 10:38
I also observe the same issue on Arch Linux with KDE and the recent neovide from git.

**Comment by Strongleong** [comment] 2022-06-09 00:54
Arch linux with qtile. 
Nvim version: 0.7.0
Neovide version: 0.9.0
Same behavior.

Also I have plugin lyokha/vim-xkbswitch installed

**Comment by IWYpPtD49k1OHyy3AqwT9vOBJEaZ4S** [comment] 2022-08-17 10:40
Same happens on NixOS Unstable with nvim 0.7.2 and neovide 0.9.0.

**Comment by TomLebeda** [comment] 2022-08-30 14:25
Same behavior on Manjaro XFCE with nvim 0.7.2 and neovide 0.9.0-3

**Comment by Strongleong** [comment] 2022-09-07 00:01
Any update on this? I am still have this error

**Comment by evenbrenden** [comment] 2023-05-10 08:03
Same behavior using `setxkbmap` with `NVIM v0.8.1`, `neovide 0.10.3` and `X.Org version: 1.20.14`.

**Comment by fredizzimo** [comment] 2023-06-14 21:56
We likely need to wait for https://github.com/rust-windowing/winit/issues/2678

**Comment by fredizzimo** [comment] 2024-01-13 13:02
I don't think this is an issue on either Wayland and X11 anymore. At leas I have been able to toggle layouts correctly. But it would be good to a confirmation from others before closing.

**Comment by MultisampledNight** [comment] 2024-01-13 15:07
Unable to reproduce it anymore either.

**Comment by tecbeast42** [comment] 2024-01-14 14:03
I am not able to reproduce it anymore either :+1:

**Closed** 2024-01-14 14:03 UTC
Labels: bug, Windowing, status:needs-response
