### ISSUE TITLE
Ability to use multple cursor particles animations at the same time

### ISSUE THREAD

**Issue by LordRishav** [neovide/neovide#1128] opened 2022-01-05 18:20 UTC
**Is your feature request related to a problem? Please describe.**
Is it possible to use mutliple Cursor Particles animations at the same time, like using both [Torpedo](https://github.com/neovide/neovide/wiki/Configuration#torpedo) and [Sonic Boom](https://github.com/neovide/neovide/wiki/Configuration#sonic-boom)? This may be useful because Torpedo is related to the movement of the cursor and Sonic Boom is related to changing of modes and editions.

Digging into it I saw that both the animations use the same variable `g:neovide_cursor_vfx_mode`, which make it impossible (?) to use both at the same time.

**Describe the solution you'd like**
Allow using multiple cursor particle animations at the same time and, if necessary, use different variables for different types of animations.

**Describe alternatives you've considered**
N/A

**Comment by jonvaldes** [comment] 2022-01-26 07:17
Closing this, as it's a duplicate of
https://github.com/neovide/neovide/issues/978

**Closed by jonvaldes** 2022-01-26 07:17 UTC
Labels: enhancement
