### ISSUE TITLE
Neovide won't run when directly clicked.

### ISSUE THREAD

**Issue by Shadoware** [neovide/neovide#1820] opened 2023-03-26 19:04 UTC
**Describe the bug**
Neovide.exe wont run when I directly click over it with mouse but it runs if create a shortcut and paste it on windows taskbar or desktop.

**To Reproduce**
Just left click the mouse over neovide.exe in windows explorer

**Expected behavior**
 Neovide run.

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit, 22H2, OS compilation: 19045.2788. Windows Feature Experience Pack 120.2212.4190.0
 - Neovide Version 0.10.3
 - Neovim Version 0.8.3

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
Cant put log here because its too big. I'll past just a fragment of it:

TRACE [neovide] Neovide version: 0.10.3
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "nvim.exe" "--embed" "-p", kill_on_drop: false }
DEBUG [neovide::settings::window_geometry] Loaded window settings: Windowed { position: PhysicalPosition { x: 690, y: 35 }, size: Dimensions { width: 140, height: 43 } }
INFO [neovide::bridge::setup] Neovide registered to nvim with channel id 1
INFO [neovide::bridge] Neovim process attached
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: ArabicShape(true) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: AmbiWidth("single") })
TRACE [neovide::editor] Option set ArabicShape(true)
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: Emoji(true) })
TRACE [neovide::editor] Option set AmbiWidth("single")
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: GuiFont("") })
TRACE [neovide::editor] Option set Emoji(true)
TRACE [neovide::editor] Option set GuiFont("")
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: GuiFontWide("") })
TRACE [neovide::editor] Option set GuiFontWide("")
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: LineSpace(0) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: Unknown("mousefocus", Boolean(false)) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: Unknown("mousemoveevent", Boolean(false)) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: Pumblend(0) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: ShowTabLine(1) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: TermGuiColors(true) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: Unknown("ttimeout", Boolean(true)) })
TRACE [neovide::editor] Option set LineSpace(0)
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: Unknown("ttimeoutlen", Integer(PosInt(50))) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: Unknown("ext_linegrid", Boolean(true)) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: Unknown("ext_multigrid", Boolean(false)) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: Unknown("ext_hlstate", Boolean(false)) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: Unknown("ext_termcolors", Boolean(false)) })
TRACE [neovide::editor] Option set Unknown("mousefocus", Boolean(false))
TRACE [neovide::editor] Option set Unknown("mousemoveevent", Boolean(false))

**Comment by Shadoware** [comment] 2023-03-26 19:08
It also wont run if I right click over a file and choose: "Open with" dialog.
When I click over a Neovide shortcut it runs as mentioned though.

**Comment by alewkinr** [comment] 2023-03-29 22:57
The same problem, MacOS 12.4, 21F79
neovide 0.10.3

**Comment by caerphoto** [comment] 2023-04-20 09:46
Having a similar problem after updating from 0.10.0 to 0.10.4 on MacOS Monterey (12.6.3). Running `open ~/Applications/Neovide.app` from a command prompt works fine, but when double-clicking the icon in Finder (or clicking on Dock icon), it looks like Neovide crashes immediately.

Maybe something $PATH related?

**Comment by alewkinr** [comment] 2023-04-22 08:50
> Having a similar problem after updating from 0.10.0 to 0.10.4 on MacOS Monterey (12.6.3). Running `open ~/Applications/Neovide.app` from a command prompt works fine, but when double-clicking the icon in Finder (or clicking on Dock icon), it looks like Neovide crashes immediately.
> 
> Maybe something $PATH related?

I discovered that the problem is in Homebrew changes. Almost fixed the problem, following instructions given here — https://neovide.dev/troubleshooting.html

**Comment by fredizzimo** [comment] 2024-01-13 11:24
This contains multiple issues, on various platforms, without proper log files, and is quite old so I'm closing this

**Closed by fredizzimo** 2024-01-13 11:24 UTC
Labels: bug
