### ISSUE TITLE
Files with % (percent) are opened incorrectly.

### ISSUE THREAD

**Issue by williamspatrick** [neovide/neovide#1659] opened 2022-12-01 17:18 UTC
**Describe the bug**

If I try to open a file a percent in the file name, extra quotation marks are passed to nvim and the wrong file is open.

**To Reproduce**
1. Run neovide with a file with a percent: `neovide asdf%.md`.
2. Change file and save.
3. See file created as `"asdf%md"`.

**Expected behavior**

**Screenshots**
![20221201_11h15m22s_grim](https://user-images.githubusercontent.com/105009/205117347-9a85f82e-1cc3-4b4b-b20c-5ec2aa48b037.png)

**Desktop (please complete the following information):**
 - OS: Gentoo Linux
 - Neovide Version 0.10.3

**Please run `neovide --log` and paste the `contents` of the `.log` file created in the current directory here:**
```
TRACE [neovide] Neovide version: 0.10.3
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "/usr/bin/nvim" "--embed" "-p" "\"asdf%.md\"", kill_on_drop: false }
INFO [neovide::bridge::setup] Neovide registered to nvim with channel id 1
INFO [neovide::bridge] Neovim process attached
```
(I can upload full files to gist if useful).

**Additional context**
None.

**Comment by MultisampledNight** [comment] 2022-12-01 22:25
Thanks for reporting! Likely related to #1652.

**Comment by williamspatrick** [comment] 2022-12-01 22:43
> Thanks for reporting! Likely related to #1652.

This seems to be an issue related to scrolling speed. Did you reference the wrong issue?

**Comment by MultisampledNight** [comment] 2022-12-02 06:23
...I'm unable to read. I meant #1651, sorry.

**Comment by Kethku** [comment] 2023-11-09 00:20
I think if I'm reading this correctly this has been fixed via an already merged PR. I can't reproduce it, so please reopen if this problem persists.

**Closed by Kethku** 2023-11-09 00:20 UTC
Labels: bug
