### ISSUE TITLE
`which_key` overlays under `telescope`, but should be over, only on Neovide

### ISSUE THREAD

**Issue by so-rose** [neovide/neovide#2425] opened 2024-03-17 12:57 UTC
Heyo, I may have found a bug. Hope it can help!

**Describe the bug**
In Neovide, but not in a terminal, `which_key` overlays are under `telescope`. See <https://github.com/nvim-telescope/telescope.nvim/issues/2976>.

As I can only reproduce it in Neovide, I figured it was appropriate to report it here.

**To Reproduce**
1. Configure the Issue's referenced minimal config, which mainly includes `telescope` and `which_key`.
2. Open any telescope picker, and go to normal mode.
3. Open `which_key` help with `?`. It should render under the telescope picker, when it should render over.

**Expected behavior**
The `which_key` popover should be layered over `telescope`.

**Screenshots**
See the images in the original issue; I have nothing productive to add.

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Neovide Version 0.12.2
 - Neovim Version v0.9.5 (Release)

**Comment by fredizzimo** [comment] 2024-03-23 14:41
This is a duplicate of
* https://github.com/neovide/neovide/issues/1676

**Closed** 2024-03-23 14:47 UTC
Labels: bug
