### ISSUE TITLE
How to get neovim's default buffer?

### ISSUE THREAD

**Issue by bonecountysheriff** [neovide/neovide#620] opened 2021-05-03 08:04 UTC
Neovide seems to open a scratch file by default instead of the help screen in vim/neovim. How do you change this?

**Comment by Kethku** [comment] 2021-05-03 21:22
Thats a good question. I suspect this is a bug in the init logic.

**Comment by Kethku** [comment] 2021-05-03 21:22
Shouldn't be hard to fix. THe relevant code is in the bridge mod.rs file

**Comment by ErikMayrhofer** [comment] 2021-05-23 18:53
I would like to offer my help with this issue.

At first glance, the issue seems to be that the screen is redrawn before anything is input by the user (e.g because of a resize or something).
nvim's `:h :into` tells us that:
```
When Vim starts without a file name, an introductory message is displayed (for
those who don't know what Vim is).  It is removed as soon as the display is
redrawn in any way.  To see the message again, use the ":intro" command (if
there is not enough room, you will see only part of it).
```

I will now investigate if my suspicion is correct and if startup-redraws can be avoided.

**Comment by Kethku** [comment] 2021-05-24 00:11
Wow thanks so much for the in depth investigation. This is super useful. As a side note: did you find logging the rpc calls to slow down the system? I wonder if we should change the --log function to do this all the time. For bonus points we could also have it log every command between the different neovide threads. That would turn it into a truly useful log rather than the hit or miss experience it is today.

As for the issue at hand, I suspect that the two resizes happen because we resize the screen when we get the font from neovim. I don't remember for sure, but I think its possible that the window tries to preserve the current size as close as possible when the font changes. So we start with the default font at a given size, and then on receiving the configured font, resize again to match the new font dimensions.

**Comment by ErikMayrhofer** [comment] 2021-05-24 08:31
I did not notice any slowdowns while logging. However this isn't pretty representative, because first I didn't do much more than starting it up, look if the intro is shown and then `:q`uitting instantly and second I just used a `println!` for the sake of brevity and third my system's pretty beefy. 

I simply inserted a `println!("Method CALL: {} {:?}", method, args);` as the first line in [`nvim-rs/src/neovim.rs:Neovim.call`](https://github.com/Kethku/nvim-rs/blob/109feea9e345fcbb2674384b0d6914ba4b8fc61e/src/neovim.rs#L125).

I did however notice that there weren't that many RPC calls at all so maybe a simple `trace!` call wouldn't be a problem. Maybe that call would even get removed in release builds. I can draft up a PR to your `nvim-rs` repo if you deem it useful.

---

The resize after font change sounds like a bit of a problem for our issue here, as that one probably depends on nvim up and running and we probably cannot delay starting nvim to after we know the font. Maybe we can delay the call to [`nvim.ui_attach`](https://github.com/Kethku/neovide/blob/0b976c3d28bbd24e6c83a2efc077aa96dde1e9eb/src/bridge/mod.rs#L276) to after the font is known. I will take a look at that.

**Comment by Kethku** [comment] 2021-05-27 17:29
I am still thinking about this. I think it makes sense to me to delay creation of the window until we get an official font from the vim config. That way we can set the font size correct rather than resizing a couple times. But I don't know exactly yet what the best way is to go about that. If you have ideas, I'm all ears.

As a side note, I added hooks to the message channels between the neovim threads so that when in logging mode, every message is logged out to file. I also took the opportunity to clean up some pretty useless traces we had lying around. Overall I think the log feature is way better for diagnostic purposes now. Thanks for the idea!

**Comment by ErikMayrhofer** [comment] 2021-05-27 18:38
I think solving this issue beautifully is not as trivial as it may initially seem. I'll get a bit more comfortable with the OpenGL branch for now and maybe inspiration strikes me. We probably just need one good idea and then everything falls into place XD

**Comment by rosingrind** [comment] 2023-08-08 19:22
FYI: nothing actually changed on macOS, the startup screen is still a blank file

**Comment by fredizzimo** [comment] 2023-08-09 10:31
I'm re-opening this, something that we did after the fix has broken it again. 

And I think we should prioritize getting this fixed, we shouldn't hide `:help iccf` and `:help sponsor`, especially after Bram passed away, but that does not mean that it wasn't equally important before.

We do have other bugs related to resizing at the startup too, so we should try to tackle everything once and for all.

**Comment by fredizzimo** [comment] 2023-08-13 17:58
This seems pretty much impossible to implement as designed, unless we revert back to saving the window size in columns and rows, instead of pixels and also drop the padding support for example.

We have to call `nvim_ui_attach` with the correct amount of columns and rows before Neovim continues to even start parsing `init.vim/lua`. Any changes we make to the size after that will close the `intro` screen. 

There's one possible workaround. we cold add an autocommand on `VimEnter`, that checks if there's only one buffer and that it's empty. If that's the case call `:intro`:

I tested the following locally
```vim
augroup showintro
    autocmd!
     autocmd vimenter * intro
augroup END
```

But unfortunately it's rendered behind the default buffer with `--multigrid`  and only "press ENTER or type command to continue" is visible. Without multigrid it works fine, and I think that's a Neovim bug. The same thing happens when you enter the command `:intro` manually. 

I will open a bug report on the Neovim repository.

**Comment by rosingrind** [comment] 2023-08-13 19:03
> unless we revert back to saving the window size in columns and rows, instead of pixels and also drop the padding support for example

Does it makes any sense to store cols/rows (then you can easier implement #1956) and store padding (require user to manually set it's color) as an addition? I think then you probably can:

- request correct buffer size on init from headless nvim
- sum it up with required padding
- open a winit window with calculated dimensions
- fill the window up with padding's color
- make a surface for drawing out nvim's buffer on desired coordinates

About storing cols/rows instead of pixel w/h: from my perspective, it feels more native to control window size as a text grid instead of traditional pixel grid. It's not really obvious how will opened editor look if I set all paddings of `300px` and main size of `400px`; there's also no `autopadding` options so they're not really that handy to set up for me on a retina display.

I think if nvim does support grabbing window dimensions on a startup (seen a [nvim_ui_attach](https://neovim.io/doc/user/api.html#nvim_ui_attach()), probably it's there), this may be a solution. I didn't dig neovide's sources yet, so I may state obviously implemented things already.

<img width="1382" alt="Screenshot 2023-08-13 at 9 53 45 PM" src="https://github.com/neovide/neovide/assets/108860307/2ae60dc7-2c7f-4f7b-b7e9-eeb5cdabf03a">

**Comment by 9mm** [comment] 2023-08-13 19:45
I don't know about you guys, or if I'm reading this wrong, but one of the things I hated most about macvim was its extremely inflexible window sizing. It would only resize according to rows and columns and it wreaked havoc on window managers. That was one of the most exciting things about coming to Neovide was... the window actually behaves like its supposed to like the rest of Mac OSX, in a pixel perfect way. I also think padding is a really nice feature as I have adjusted it perfectly. It would be very unfortunate if that goes away, but of course I'm just on the outside commenting from the peanut gallery...

**Comment by fredizzimo** [comment] 2023-08-13 19:52
The problem with storing rows and columns, is that we then also need to store the font and the padding in the settings files, and don't allow any changes to those at runtime. Otherwise there's no guarantee that we open it up with the same size the next time you start Neovim. 

For example, some people like to change the font size, depending on what you are doing, and you don't want the window layout to be screwed up just because you had the wrong size the last time you exited.

We also need to solve this in another way https://github.com/neovide/neovide/issues/1636, which was the main issue fixed by storing the window size as pixels.

Furthermore, we have a lot of other bugs too right now, due setting the window size at least twice during startup. Now when we we store the pixel size we could create it with the correct size immediately and get a whole bunch of issues solved. So instead of resizing the OS window twice, we resize the internal Neovide columns and rows instead, which all happens before anything is rendered.

**Comment by fredizzimo** [comment] 2023-08-13 20:02
The Neovim issue is here https://github.com/neovim/neovim/issues/24705

**Comment by fredizzimo** [comment] 2023-08-15 20:44
I have now implemented this in https://github.com/neovide/neovide/pull/1980

**Closed** 2023-08-18 09:44 UTC
Labels: bug

**Comment by 9mm** [comment] 2023-08-18 12:46
The first piece of lua code in neovide 🥸

**Comment by MultisampledNight** [comment] 2023-08-18 12:58
Actually some of the clipboard handling used Lua inb4.
