### ISSUE TITLE
neovide hangs on close

### ISSUE THREAD

**Issue by adriancostin6** [neovide/neovide#1761] opened 2023-02-06 12:09 UTC
**Describe the bug**
Trying to close Neovide whilst in fullscreen mode freezes the application, prompting the user to having to use the task manager to kill the process. This happens randomly, from my experience so far.

**To Reproduce**
1. Toggle fullscreen mode in Neovide: `:lua vim.g.neovide_fullscreen=1`
2. Use as normal
3. Try to exit the application with :q
4. Trigger freeze (sometimes)

**Expected behavior**
Closing the application to work as normal, not trigger a not-responding type of situation.

**Screenshots**
Not applicable, don't think a frozen empty buffer provides much context here.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Neovide Version 0.10.3
 - Neovim Version 0.8.1

**Logs**
Don't provide much context in this situation, also exceed character limit, so did not paste them here.

**Additional context**
None, yet

**Comment by isovector** [comment] 2023-06-20 21:50
I've noticed this too in 0.10.4-1; downgrading to 0.10.3-1 seems to have fixed the problem.

**Comment by HansVanpee** [comment] 2024-01-08 07:05
Same problem here: since +/- a week neovide hangs on close.

I am using:
Arch Linux with kernel 6.6.10.
Neovide 0.12.1.
Nvim 0.9.5 (release).
Window manager: LeftWM.
Windowing system: X11.

**Comment by fredizzimo** [comment] 2024-01-08 07:08
@HansVanpee, you are mos likely encountering this
* https://github.com/neovide/neovide/issues/2003

And yes, that's a recent Neovim regression

**Comment by HansVanpee** [comment] 2024-01-08 07:13
@fredizzimo Indeed, it doesn't happen when I close immediately after opening neovide (without yanking).

**Comment by fredizzimo** [comment] 2024-01-08 07:16
Hm, that appears to be different then. But we do have a similar issue on Windows, without the clipboard involved.

* https://github.com/neovide/neovide/issues/2182

Do you have a logfile?

**Comment by HansVanpee** [comment] 2024-01-08 07:24
@fredizzimo Here is the log file:
[neovide_r2024-01-08_07-21-07.log](https://github.com/neovide/neovide/files/13857253/neovide_r2024-01-08_07-21-07.log)

**Comment by fredizzimo** [comment] 2024-01-08 07:45
I see what's wrong, since we handle neovide ui draw commands and other messages separately, we can receice a draw command after the quit confirmation.

This changed the events to be sent using the winit event loop
https://github.com/neovide/neovide/pull/2167

But it fails/hangs due to the event loop already being destroyed. I'm not sure if it's a winit bug or if it can be fixed. It needs further debugging, which I will be unable to do for a couple of weeks more.

Most likely, this never returns https://github.com/neovide/neovide/blob/b4b804095e2c75cf5a806b9b74a8ae7d9e3b53f7/src/editor/draw_command_batcher.rs#L23. 

It's supposed to give an error, but maybe it doesn't.

**Comment by fredizzimo** [comment] 2024-01-08 07:53
Actually, it could also be the same issue as on windows, that the neovim handler never quits.

**Comment by HansVanpee** [comment] 2024-01-08 07:56
@fredizzimo Thanks for your reply. For the time being I `kill` neovide after use. This bug is not preventing me from using neovide, it is just an inconvenience.

**Comment by fredizzimo** [comment] 2024-06-19 02:39
I'm closing this in favor ofhttps://github.com/neovide/neovide/issues/2182, which have more information.

If you still have problems with the latest 0.13.1 release on Windows, please reply there along with your system specs.

**Closed by fredizzimo** 2024-06-19 02:39 UTC
Labels: bug, windows
