### ISSUE TITLE
Cursor vfx not working

### ISSUE THREAD

**Issue by crides** [neovide/neovide#162] opened 2020-03-02 03:25 UTC
First, this project looks really amazing! I tried it out as soon as I saw the reddit thread about it. But it seems like some of the cursor effects are not working, specifically the ones related to the mode changes (I assume that's how it works?; the sonicboom, ripple and wireframe modes). The cursor move animations work as expected.

System info:
* OS: Ubuntu 19.10
* Neovim: 0.4.2
* `rustc`: 1.41.1

**Comment by crides** [comment] 2020-03-02 03:38
When I set the mode to "sonicboom", it seems like the cursor will start in the top left corner, plays the sonic boom animation, and then move to whatever the first position should be, but there's no more sonic boom animations after that.

**Comment by Kethku** [comment] 2020-03-02 05:05
@jonvaldes

**Comment by jonvaldes** [comment] 2020-03-02 06:56
Hummm I just tried it, and I can't seem to reproduce this issue. Could you either record a short video, or write step-by-step instructions to reproduce this? Thanks!

**Comment by Kethku** [comment] 2020-03-02 07:08
I think the confusion comes from the fact that it only makes the effect when changing modes and not when changing between command mode and normal mode. Is that correct?

**Comment by Kethku** [comment] 2020-03-02 18:57
@crides does my description match your experience or is there something deeper going on?

**Comment by crides** [comment] 2020-03-02 19:41
Not really. From the animations in the README, it seems like the effect shows when the switches between insert and normal modes, which is what I tried. 

 [This](https://imgur.com/a/9nE0BDd) is a recording of a test session. I first opened a file, and you can see the sonicboom effect showing up in the top left corner. Then I just tapped <kbd>i</kbd> and <kbd>Esc</kbd> to switch between normal and insert mode, but nothing showed up around the cursor.

**Comment by Kethku** [comment] 2020-03-02 19:48
Yup that looks like a bug! Thanks for the report. I will look into this. Given that its not experience breaking it may be a bit tho

**Comment by crides** [comment] 2020-03-02 19:55
Just FYI, the commit I built on is 8aff807

**Comment by jonvaldes** [comment] 2020-03-02 20:16
Huh, that's very strange. Haven't seen that before.
Some random questions, trying to narrow the issue down:
- Do you have a non-standard hidpi configuration on your monitor?
- Does neovide continue using a bunch of cpu even if you're doing nothing?

**Comment by crides** [comment] 2020-03-02 20:24
I don't know anything about hidpi settings. I'm using a 1080p 15" laptop, connected using HDMI to another monitor also at 1080p.

If I just open a file and let it stay there, it uses close to 0 CPU time, like less than 1 sec in the ~1:30 duration I opened it.

**Comment by Kethku** [comment] 2020-03-02 20:48
side note about zero cpu while idle: that makes me very happy. Lots of work went into that :P

**Comment by Kethku** [comment] 2021-04-19 22:11
@crides the app has changed significantly since. Do you still encounter the same issue?

**Comment by crides** [comment] 2021-04-20 19:42
So I'm trying to install `neovide` again, but the 0.7.0 release binary doesn't work. It panicked at `'Could not create surface', src/renderer/rendered_window.rs:40:6`. Trying build from `main` also isn't working. Here's the cargo error:

```
error: failed to compile `neovide v0.7.0 (https://github.com/Kethku/neovide?branch=main#d8d6f4ea)`, intermediate artifacts can be found at `/tmp/cargo-installE5sjKc`

Caused by:
  failed to select a version for `skulpin`.
      ... required by package `neovide v0.7.0 (/home/steven/.cargo/git/checkouts/neovide-35332cc81b2f0340/d8d6f4e)`
  versions that meet the requirements `*` are: 0.13.0

  the package `neovide` depends on `skulpin`, with features: `skulpin_sdl2` but `skulpin` does not have these features.


  failed to select a version for `skulpin` which could resolve this conflict
```

**Comment by Kethku** [comment] 2021-04-22 21:41
could you try to build from the opengl branch instead?

**Comment by crides** [comment] 2021-04-23 02:04
So the build works, but it segfaults:

```
Thread 1 "neovide" received signal SIGSEGV, Segmentation fault.
0x0000555555cb52e3 in GrGLExtensions::init(GrGLStandard, GrGLFunction<unsigned char const* (unsigned int)>, GrGLFunction<unsigned char const* (unsigned int, unsigned int)>, GrGLFunction<void (unsigned int, int*)>, GrGLFunction<char const* (void*, int)>, void*) ()
```

I can do a debug build later and help figure out the issue

**Comment by crides** [comment] 2021-05-23 17:56
Okay I can build from the `opengl` branch now, and the binary works. However the issue is still there, i.e. it plays the animation on the top left corner when `neovide` starts, moves to whatever the first cursor position should be, and no animation after that.

Here's a recording of the issue (also note that it renders the normal font in bold for some reason, and most shifted symbols don't work; surprisingly `:` does):

https://user-images.githubusercontent.com/15631555/119271141-e0d5ee00-bbc5-11eb-8130-4b532a1f17db.mp4

**Comment by Kethku** [comment] 2021-05-26 00:49
That is very strange. I'm guessing that somewhere in the system the vfx notification for when the cursor moves has broken. I will come back to this

**Comment by thistlillo** [comment] 2023-02-01 12:27
I can confirm some visual effects do not work on Windows 11 with neovide `0.10.3` on top of neovim `0.8.2`, specifically "Ripple", "Wireframe". All the others run fine.

I have a 4K high DPI screen .

**Comment by fredizzimo** [comment] 2024-01-13 09:05
I don't think that this is an issue anymore, and if it is, then it's caused by bad graphics card drivers/skia bugs like this
* https://github.com/neovide/neovide/issues/843

And will most likely be fixed with the better supported d3d
* https://github.com/neovide/neovide/pull/2215

**Closed by fredizzimo** 2024-01-13 09:05 UTC
Labels: bug
