### ISSUE TITLE
Neovide 0.12.1 frozen and unresponsive immediately upon startup

### ISSUE THREAD

**Issue by gwerbin** [neovide/neovide#2271] opened 2024-01-14 02:45 UTC
**Describe the bug**

When I start Neovide either from the KDE Applications Menu or from the shell, the window is immediately frozen and unresponsive upon opening. It can be resized and minimized, but the "exit" button has no effect, and the process needs to be terminated manually. The `neovide` process does respond to SIGTERM and exits.

**To Reproduce**

```bash
pacman -Syu neovide
rehash
neovide
```

**Expected behavior**

I expected Neovide to respond to keyboard input and update the UI as normal.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: EndeavourOS (Arch-based, rolling), KDE X11
 - Neovide version: 0.12.1
 - Neovim version: v0.10.0-dev-1698+g640680

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

Here is the log including my attempts to get the application to respond: https://gist.github.com/gwerbin/0bde5854c23804e1e9c0c8b8df69bf81

**Additional context**

This problem started recently, but I'm not sure if it coincided with a version update.

**Comment by gwerbin** [comment] 2024-01-14 02:46
Quick update: I tried `neovide -- -u NONE` and it actually worked fine. So the problem might be related to my config, although I'm surprised that a problem with my config would cause Neovide to become nonresponsive.

**Comment by fredizzimo** [comment] 2024-01-14 02:49
The issue is fixed on main if you build from source. Basically any errors at startup will cause Neovide to freeze. In this case nvim-dap is not configured. We will hopefully be able to do a release soon.

**Comment by gwerbin** [comment] 2024-01-14 04:00
You're talking about this message?

> nvim-dap is not installed. Cannot configure.

That's just a `:message` emitted by Lua `print()` in my plugin script `plugin/plugin-config/nvim-dap.lua`:

```lua
local ok, dap = pcall(require, "dap")
if not ok then
  print("nvim-dap is not installed. Cannot configure.")
  return
end
```

Is it the act of `print()`-ing something that causes the error?

**Comment by fredizzimo** [comment] 2024-01-14 04:01
Yes, any message that requires you to press enter during the startup will cause it to hang.

**Comment by fredizzimo** [comment] 2024-01-19 02:35
I'm going to close this as duplicates of 
* https://github.com/neovide/neovide/issues/2233
* #2277
* https://github.com/neovide/neovide/issues/2261
* https://github.com/neovide/neovide/issues/2245
* https://github.com/neovide/neovide/issues/2286

It's fixed on main if you build from source with 
* https://github.com/neovide/neovide/pull/2241

**Closed by fredizzimo** 2024-01-19 02:35 UTC
Labels: bug
