### ISSUE TITLE
neovide_confirm_quit option not working when pressing command+q on macos

### ISSUE THREAD

**Issue by dineshKumar777** [neovide/neovide#1279] opened 2022-04-20 00:52 UTC
**Describe the bug**
https://github.com/neovide/neovide/pull/1247
Option does not seem to work on MacOS 12.3, neither via command-q or via clicking the menu option.

**To Reproduce**
1. enable option let g:neovide_confirm_quit=1 and g:neovide_confirm_quit=v:true
2. make changes in buffer
3. click command-q or via clicking the menu option
4. neovide closes without save prompt

**Expected behavior**
show save prompt when quit
Note: In windows, alt+f4 shows save prompt.
More info on https://github.com/rust-windowing/winit/issues/41

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 12.3]
 - Neovide Version [e.g. 0.8.0]
 - Neovim Version [e.g. 0.7.0]

**Comment by MultisampledNight** [comment] 2022-04-20 07:54
Do we even want to explicitly handle that or just let the user configure it?

**Comment by dineshKumar777** [comment] 2022-04-20 10:09
@MultisampledNight nvim-qt prompts on cmd-q, so I thought this is the default behavior. since this mac specific I am not sure about this one. As per winit#41 discussion, application authors has to handle this behavior.

[Alacritty implementation](https://github.com/alacritty/alacritty/blob/9bbb296d1dc4f72e845695f22e903bcc1d66d5a3/alacritty/src/config/bindings.rs#L720)

**Comment by Liverm0r** [comment] 2022-04-22 07:46
I remapped cmd+q (and lots of other cmd hotkeys, like cmd+v/c/w/s for paste/copy/close/save respectively) for neovide to be alt+q, and mapped alt+q to exit in vim.

[karabiner settings](https://github.com/Liverm0r/dotfiles/blob/master/.config/karabiner/assets/complex_modifications/1234504.json)

I gues you know how to remap vim keys yourself :)

**Comment by 9mm** [comment] 2023-06-28 05:42
I still have this issue, was there something that i need to do to get this to work? id love to adjust both the window position as well as the side to always be on right half of screen

**Comment by 9mm** [comment] 2023-06-28 05:44
@D00mch did you find a way to remap command+Q/W/T in neovide? i was trying to add tabs back and windows like macvim

**Comment by fredizzimo** [comment] 2023-06-28 07:14
I think this might be fixed in Neovide main. We recently updated to latest winit there.

And https://github.com/rust-windowing/winit/issues/41 was marked as fixed by https://github.com/rust-windowing/winit/pull/1583. I don't know if we need to do anything special to enable the menu though.

**Comment by 9mm** [comment] 2023-07-29 23:56
@fredizzimo im using --HEAD homebrew and when I press command+Q it immediately exits losing any changes

**Comment by fredizzimo** [comment] 2023-07-30 11:09
Does the menu introduced by https://github.com/rust-windowing/winit/pull/1583 show up? I think it should do that by default, otherwise it probably needs to be enabled with https://github.com/rust-windowing/winit/blob/2b2dd6b65dcb20f59219f963a9e90f15d1ad8e9a/src/platform/macos.rs#L342.

**Comment by 9mm** [comment] 2023-07-30 15:33
@fredizzimo hmm I don't see it, sorry, so how do I enable it?

I added this:

```
vim.g.neovide_with_default_window = true
```

but it still doesnt show any menu, not sure if that's the wrong way though.

<img width="273" alt="image" src="https://github.com/neovide/neovide/assets/1386207/ab35a72b-c09c-480c-b36b-4ebded0c3ee2">

**Comment by fredizzimo** [comment] 2023-07-30 15:54
Yes, it needs changes to the code, the `EventLoop::new()` should be replaced with `EventLoopBuilder` and then setting `EventLoopBuilderExtMacOS::with_default_menu` to true. That should be easy for someone with a mac to do.

**Comment by 9mm** [comment] 2023-09-23 21:35
@fredizzimo im assuming this issue changes after all your winit stuff? I was going to attempt this issue and I noticed a lot of the event loop code is already switched to the Builder way.

**Comment by fredizzimo** [comment] 2023-09-23 21:47
@9m, Yes, I changed it in the render loop branch to use the builder

https://github.com/neovide/neovide/blob/d322a50cb3fd2cb88ad20c67da5271e3c37421d6/src/window/mod.rs#L77-L79

The easiest way is probably if you create a PR that targets that branch.

**Comment by 9mm** [comment] 2023-09-23 23:05
Sorry if this is dumb, but I still don't see a menu. Does something about this look wrong? It compiles fine

```rust
#[cfg(target_os = "macos")]
use winit::platform::macos::EventLoopBuilderExtMacOS;

...

pub fn create_event_loop() -> EventLoop<UserEvent> {
    let mut builder = EventLoopBuilder::<UserEvent>::with_user_event();

    #[cfg(target_os = "macos")]
    builder.with_default_menu(true);

    builder.build()
}
```

https://docs.rs/winit/latest/x86_64-apple-darwin/winit/platform/macos/trait.EventLoopBuilderExtMacOS.html#tymethod.with_default_menu

Ultimately I guess I am confused how a menu bar affects command+Q to quit. I'll look more into it later today or tomorrow as I only gave it a cursory glance. Tomorrow Ill just read through the entire issue.

**Comment by fredizzimo** [comment] 2023-09-23 23:37
It looks correct.

I have no idea either, but in winit there's this code
https://github.com/rust-windowing/winit/blob/8c8fb39fcd147fc86e722374cbd0632888299947/src/platform_impl/macos/app_state.rs#L468-L471

And the menu adds a quit option
https://github.com/rust-windowing/winit/blob/master/src/platform_impl/macos/menu.rs

And if I understand correctly, that should then deal with the keyboard shortcut and send an `Event::LoopDestroyed` event, which can be handled on our side. Although there seem to be no possibility to confirm, so it does not actually solve the issue 😢 . But it should be possible to save the window size at least.
* https://github.com/rust-windowing/winit/issues/1998
* https://docs.rs/winit/latest/winit/event/enum.Event.html#variant.LoopDestroyed

**Comment by fredizzimo** [comment] 2023-09-23 23:45
Maybe the trick is to not add the menu, and deal with the shortcut manually?

**Comment by 9mm** [comment] 2023-09-24 14:45
So.. is it this?

<img width="222" alt="image" src="https://github.com/neovide/neovide/assets/1386207/d36f346d-f536-4f6f-912f-962b57480e36">

Because I saw that, but I didn't even think that was it because neovide installed from homebrew already has that.

If thats the menu, it still appears not to trigger the "confirm" part.

**Comment by 9mm** [comment] 2023-09-24 15:08
It is a bit wild to me that a library with the purpose of window management doesnt appropriately handle (or seem to care) about windows on Mac, given that they chose to support it. I suppose they just consider Mac second class, which is also weird that they focus on windows so much when all developers I know use linux or macos. I suppose Im just surprised Mac proper usability gets such low support...

Ive seen a few issues over there while reading it going ... errr, this is a huge fundamental part of mac. One is that windows are able to close while the program process is running. I cant remember where but I feel like he was like "nah dont need that", and also quit functionality triggering 'save' in each window is also fundamental to the way apps work and they seem to be like "meh".

These are not really minor things, they're paramount to the entire way the mac UI is designed

Not to say I'm ungrateful or anything .. I suppse just more surprised that it's basically getting shoehorned into the way windows or linux works (or at least, thats what it looks like, could be missing some finer nuance)

**Comment by fredizzimo** [comment] 2023-09-24 15:16
I think the issue is that it's hard to find developers on macOS. We have the same issue with Neovide features as well. 

Anyway, I think you can fix the issue. By *disabling* the menu, then hopefully the key is not captured. Which in turn means that you should be able to `map <D-q> <cmd>quit<cr>`. 

If that works, we can then add a default mapping here:
https://github.com/neovide/neovide/blob/6694b0f8935f4118e8cdcbe22b657810f88c8b17/src/bridge/setup.rs#L56-L150

The other option would be to customize the menu, but I don't see a way to do that.

**Comment by 9mm** [comment] 2023-09-24 15:17
@fredizzimo Ill have a look. What OS do most of your developers use, linux?

**Comment by fredizzimo** [comment] 2023-09-24 15:20
I think both windows and Linux have a fair share of developers, mabye a bit more on Linux due to how specialized Neovide is.

And the mapping should be map `<D-q> <cmd>confirm q<cr>` for a confirmation.

**Comment by MultisampledNight** [comment] 2023-09-24 15:23
To add to the macOS experience, personally speaking: It's impossible for me to develop for macOS without 1. buying a costly device and 2. locking me into a platform that may do anything to my setup at any time. And since the macOS EULA disallows installing macOS on non-Apple-manufactured devices, it's impossible for me to at least run it in a VM or the like, either.

As a result, for anything I develop I have to rely on other people's feedback who are fine with those two things, and am unable to provide anything platform-specific without long feedback cycles.

**Comment by 9mm** [comment] 2023-09-24 15:27
@MultisampledNight definitely no complaint on the Neovide side :) Or really any complaint anywhere. More just an observation that a library devoted to windows management seems to not actually support... managing windows in an expected way.

**Comment by 9mm** [comment] 2023-09-24 15:47
@fredizzimo so I could make a PR for this, because what we talked about here works (`<D-q>` can now be mapped), but by hiding the menu, "hide" `<D-h>` also stops working which is way more important than quit IMO. Is there a way to trigger that functionality within winit from a keymap, and then I could just edit the docs potentially for a section similar to "How do I get copy/paste" to work?

The other option I was thinking is the menu would need to be built from scratch with about/hide/quit, except with custom quit functionality.

**Comment by fredizzimo** [comment] 2023-09-24 16:03
@9mm , we do have this
* https://github.com/neovide/neovide/pull/1971

Which would let you map `:suspend`. Is minimize the correct thing to do on macOS, or should it be hide there?

**Comment by fredizzimo** [comment] 2023-09-24 16:14
Customization might be possible:

https://github.com/rust-windowing/winit/pull/1583#issuecomment-786424072
> I think this PR should be merged as-is. Allowing for custom menus can be done later but this is something that is needed now.

https://github.com/rust-windowing/winit/pull/1583#pullrequestreview-599615654
> However, I'm working on a library myself for supporting this, and for that it would be really nice this was an optional feature (either compilation or a setting on the event loop), so winit and my custom library don't both try to set the main menu!

And that library is this:
https://github.com/madsmtm/menubar
https://docs.rs/menubar/latest/x86_64-apple-darwin/menubar/macos/index.html

**Comment by 9mm** [comment] 2023-09-24 16:15
Looking at the issue it fixes, I don't know what "minimize on Ctrl-Z" means. That's always meant "undo" to me on windows, which equates to command+Z on Mac. I've never heard of any combination with z minimizing something.

While I read about what suspend means, I made a short loom to help just visually show the behavior

https://www.loom.com/share/c01bf85275954028bfe555ba4672eae8

**Comment by fredizzimo** [comment] 2023-09-24 16:22
`CTRL-Z` is used on Linux to suspend a process, usually in the terminal. That returns the control back to the terminal. So many people using Vim has traditionally used to go back to the terminal and run terminal commands, and then return back. 

So, minimize tries to emulate that in a GUI context. 

Winit also supports hide, so I think the implementation could be changed to that on macOS. On Windows that would not work, since the UI does not have a way to bring the window back. Applications typically do that to minimize to the system tray, and hide it from the regular task bar.

**Comment by 9mm** [comment] 2023-09-24 16:28
Ah, that makes sense. In this sense. In this case, Hide is more appropriate (on mac, anyway) because Hide will hide the entire _application_ and then give focus to the previously used application, whereas Minimize simply (and painfully) animates the closing of a single window, but the same application still has focus.

**Comment by 9mm** [comment] 2023-09-25 15:02
@fredizzimo do you want me to write a note in the PR for him to make it where it's Hide on macos only? I see its already approved so I don't want to add noise if thats not the route to go

**Comment by fredizzimo** [comment] 2023-09-25 15:03
@9mm, perhaps we should try the custom menu approach using https://github.com/madsmtm/menubar?

**Comment by fredizzimo** [comment] 2023-09-25 15:16
@9mm. There are some examples in that repository, and you can also check out the code introduced in https://github.com/rust-windowing/winit/pull/1583

**Comment by 9mm** [comment] 2023-09-26 18:04
Damn!!

It took me all morning but I got this far!

<img width="724" alt="image" src="https://github.com/neovide/neovide/assets/1386207/1ac99789-2700-42e2-bba7-b9ea05e38ba7">

This is me using rust

![image](https://github.com/neovide/neovide/assets/1386207/dc04039c-5576-44a9-9b24-7c733a133e0d)

Im afraid to put my code, but im going to work on it a lot more before I make a PR, and then from there you can tell me where all the code is supposed to go.

from the looks of it, window/main.rs but im going to continue to just keep reading

**Comment by fredizzimo** [comment] 2023-09-26 23:40
@9mm, nice! That's great progress already. I felt pretty lost with rust when I started as well. Even after reading [The Book](https://doc.rust-lang.org/stable/book/), and over 20 years of professional C++ experience.

I think you can create a new function `create_menu` and call it from `create_window`.

**Comment by halostatue** [comment] 2024-02-08 06:43
> @9mm , we do have this
> 
> * [feat: minimize window on suspend #1971](https://github.com/neovide/neovide/pull/1971)
> 
> Which would let you map `:suspend`. Is minimize the correct thing to do on macOS, or should it be hide there?

Neither.

MacVim.app should be the guide for what is "correct" vim-ish on MacOS behaviour, and in GUI mode, MacVim.app *ignores* `:suspend`.

I believe that gvim on Windows minimizes, but that was a really weird behaviour that I was happy to see that MacVim ignored. There's no really meaningful "suspend" for a forked GUI application.

On macOS, `⌘-M` should minimize the current window and `⌘-H` should hide the current application.

**Closed** 2024-02-29 17:47 UTC
Labels: bug, macos
