### ISSUE TITLE
Cannot launch neovide on my MacBook Pro M1

### ISSUE THREAD

**Issue by vkaushal288-alivecor** [neovide/neovide#1998] opened 2023-08-30 04:15 UTC
**Describe the bug**
Unable to open the app on MacBook M1 Pro (Ventura - 13.4)

**To Reproduce**
1. Download the macOS zip file from GitHub releases. 
2. Unzip to get the DMG file. 
3. Mount DMG. 
4. Try to launch the app in the DMG (or drag to /Applications and then try to launch it)

**Expected behavior**
App should launch. 

**Screenshots**
Trying to launch the DMG first says this:

<img width="372" alt="Screenshot 2023-08-30 at 9 34 13 AM" src="https://github.com/neovide/neovide/assets/71737424/1ba93f42-064f-4f80-a239-1d64a5ffb155">

Then I go to System Settings (System Preferences of macOS Ventura) -> Privacy Settings and click on the _Open Anyway_ Button. 

<img width="827" alt="Screenshot 2023-08-30 at 9 37 59 AM" src="https://github.com/neovide/neovide/assets/71737424/15daa570-5961-4b47-ab38-7bffb2a220b2">

Then it gives another popup: 

<img width="372" alt="Screenshot 2023-08-30 at 9 37 54 AM" src="https://github.com/neovide/neovide/assets/71737424/58b1eac2-2b9f-4aa0-933d-a86dc0f50a94">

I click on "Open" but it does not work.

**Desktop (please complete the following information):**
 - OS: macOS 13.4
 - Neovide Version: 0.11.1
 - Neovim Version: 0.9.1
 
```
% nvim -v
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.1/share/nvim"

Run :checkhealth for more info
```

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
_Since I cannot launch the app, I can't provide the log. Please tell me how else can I help provide more data._ 

**Additional context**
I am on a company managed laptop and I cannot change certain settings (like disabling system protection and all) but I have admin privileges otherwise (I can `sudo`) and am able to install and use most other stuff.

**Comment by orlandosh** [comment] 2023-08-30 18:58
not a maintainer, but this is likely not a bug, it's because neovide isn't notarized. you can try installing the brew formula and opening it from the terminal, which "bypasses" notarization check. 
In the manual .dmg installation, if you try to open Applications -> Neovide.app (right click) -> open it should work. If it doesn't it most likely is a limitation from the mdm/profile in the company's laptop.
the easiest way to fix it would be just notarizing neovide, but it requires an apple developer license which costs 99 usd a year.

**Comment by fredizzimo** [comment] 2023-08-30 19:32
I was going to close this issue as a duplicate, since we already have two issues open, but I forgot, but I'm doing it now. 
 https://github.com/neovide/neovide/issues/1479 and https://github.com/neovide/neovide/issues/1373.

It's also listed on our prioritized issues list https://github.com/neovide/neovide/issues/1463. 

Since Neovide is open source and developed by an organization, the issue is mostly about who will own the developer license and pay for it. Technically there seem to be good enough solutions to integrate the signing to our CI process, when we have that.

**Closed** 2023-08-30 19:32 UTC
Labels: bug
