### ISSUE TITLE
I am facing a problem in opening neovide

### ISSUE THREAD

**Issue by harish2222** [neovide/neovide#717] opened 2021-06-13 14:00 UTC
I have downloaded windows binary from neovide release but it is not even opening

**Comment by PyGamer0** [comment] 2021-06-13 14:54
can you try running it from the command line;
if that also doesnt work try running it with `--log` as an argument

**Comment by harish2222** [comment] 2021-06-13 15:38
Yes, I done it and got the log file  uploaded it 
[neovide_rCURRENT.log](https://github.com/Kethku/neovide/files/6644185/neovide_rCURRENT.log)
![Screenshot 2021-06-13 210404](https://user-images.githubusercontent.com/42508156/121813756-2187cb00-cc8b-11eb-8599-1c2d992617cb.png)

but I haven't builder it using rust
it have installed the binary from neovide releases version 0.7

**Comment by Kethku** [comment] 2021-06-13 17:32
What version of neovim do you have installed? Is it on the path? Do you set guifont in your config?

**Comment by harish2222** [comment] 2021-06-13 17:53
I am using neovim NVIM v0.5.0-dev+1385-g93f15db5d

**Comment by harish2222** [comment] 2021-06-13 17:54
can you tell me how to use neovide if I had installed the binary from github release

**Comment by Kethku** [comment] 2021-06-13 17:59
I'm guessing that the issue is due to guifont settings in your vim config. The release version of neovide fails if the guifont is set to a name which the font system can't find. I'd try running with `neovide --clean` to see if it runs that way. If it does, then that indicates that the problem is with the guifont setting

**Comment by harish2222** [comment] 2021-06-13 18:01
So should I clear my nvim folder and do it

**Comment by Kethku** [comment] 2021-06-13 18:02
--clean should run without your config. No need to clear your nvim folder

**Comment by harish2222** [comment] 2021-06-13 18:17
I am not able to understand how to use neovide could you please explain how to link it with my neovim

**Comment by harish2222** [comment] 2021-06-13 18:20
When I am trying to build neovide I am getting this error
LINK : fatal error LNK1181: cannot open input file 'SDL2.lib'

**Comment by j4qfrost** [comment] 2021-06-13 18:56
@harish2222 It seems like you might have downloaded an older binary. We have builds that use opengl now, here is the latest one https://github.com/Kethku/neovide/actions/runs/933593677

This removes SDL as a dependency.

**Comment by harish2222** [comment] 2021-06-13 19:09
I have downloaded it and runned it but no getting this error
Check the log file
[neovide_rCURRENT.log](https://github.com/Kethku/neovide/files/6644463/neovide_rCURRENT.log)

**Comment by j4qfrost** [comment] 2021-06-13 19:33
That isn't really an error. Is neovide just not starting up now? What is the behavior?

**Comment by harish2222** [comment] 2021-06-13 19:58
it is starting the neovide window and then collasping without showing any output

**Comment by harish2222** [comment] 2021-06-16 19:04
And when I built the vulken based neovide I get an error.
Saying neovide is not a command

**Comment by jackysee** [comment] 2021-06-18 08:17
I cannot open it in windows too. When I run `neovide --version` with `RUST_BACKTRACE=full`, it gives:
```
Neovide version: 0.7.0
dpi fix applied
thread 'main' panicked at 'Failed to create window: SdlError("Failed loading vulkan-1.dll: The specified module could not be found.\r\n")', src\window\sdl2\mod.rs:442:10
stack backtrace:
   0:     0x7ff79ca0a898 - <unknown>
   1:     0x7ff79c8fb8cb - <unknown>
   2:     0x7ff79ca097c8 - <unknown>
   3:     0x7ff79ca08d4c - <unknown>
   4:     0x7ff79ca07eb2 - <unknown>
   5:     0x7ff79ca115a5 - <unknown>
   6:     0x7ff79ca114ff - <unknown>
   7:     0x7ff79ca1149f - <unknown>
   8:     0x7ff79c8f9d50 - <unknown>
   9:     0x7ff79c8fff33 - <unknown>
  10:     0x7ff79c875174 - <unknown>
  11:     0x7ff79c8089ac - <unknown>
  12:     0x7ff79c859a66 - <unknown>
  13:     0x7ff79c8058c9 - <unknown>
  14:     0x7ff79cf68bc0 - SDL_wcsstr
  15:     0x7fff72d97034 - BaseThreadInitThunk
  16:     0x7fff74682651 - RtlUserThreadStart
```

**Comment by PyGamer0** [comment] 2021-06-18 14:35
@jackysee try running an executable from here https://github.com/Kethku/neovide/actions/runs/947940077

**Comment by jackysee** [comment] 2021-06-19 02:49
@PyGamer0  this build can be opened OK on my windows!

**Comment by Kethku** [comment] 2021-06-19 20:04
> 
> 
> And when I built the vulken based neovide I get an error.
> Saying neovide is not a command

@harish2222 can you paste exactly what command you run? Neovide is not a command means that you don't have neovide on your path. Closing immediately after running is usually due to either an invalid font setting in your vim config or not finding the neovim executable on your path.

**Comment by harish2222** [comment] 2021-06-21 13:13
I have used all the commands to run neovide 
used remote TCP
used ssh
nothing worked.
also removed the nvim config folder and make a new one with the same name and insert an init.vim file having just one setting that is  
`set number `
`set relativenumber` 
After adding these to my new neovim config I used the same commands again but nothing showed up rather a new console opened up with plain black screen

**Comment by Kethku** [comment] 2021-06-21 20:49
Neovide when run on windows trys to run an executable called neovim on startup. If it can't find it, it will likely just close out. If you are running neovide with the wsl command, it will try to locate a neovim executable inside your wsl install and run that. I'm guessing the problem you are encountering is that Neovide can't find the neovim executable.

@harish2222 its almost certainly something weird about your configuration or path. Neovim must be on your path to run. Also "neovide is not a command" means that neovide itself isn't on your path. I'm not sure we can help you unless you can verify that both of those things are true.

With respect to which version of neovide to use, I recommend using one from the github actions page rather than the releases. The current release on the releases page requires both sdl2 and vulkan to work properly which may be confusing things.

Could you also give some details about what kind of windows machine are your running?

**Comment by harish2222** [comment] 2021-06-22 10:08
My neovim is set to system variable in environment variables. And I am using windows 21H1 build version 

1. With that I am using spacevim for instance and wanted to try neovide, now spacevim config is controlling neovim so is it necessary to remove it.
2. even used `--wsl` it looks for neovim but doesn't show any output only neovide window is opened and crashes.

**Comment by harish2222** [comment] 2021-06-22 10:13
Check out the log file output that I am getting 
[neovide_rCURRENT.log](https://github.com/Kethku/neovide/files/6693295/neovide_rCURRENT.log)

**Comment by xianzheTM** [comment] 2021-06-23 04:37
I installed neovide (0.5.0) with scoop and had the same problem.
[neovide_rCURRENT.log](https://github.com/Kethku/neovide/files/6698913/neovide_rCURRENT.log)

**Comment by harish2222** [comment] 2021-06-23 05:24
@xianzheTM  Is your window collapsing after you run neovide. If so you are facing the same problem that I am facing

**Comment by xianzheTM** [comment] 2021-06-23 06:30
@harish2222 yes,Open it, the shape of the window appears, and then it crashes.

**Comment by harish2222** [comment] 2021-06-23 11:49
@xianzheTM Was neovide working for you before if so 

Can it be the neovim version that can be trouble or any other for neovide's crashing

**Comment by xianzheTM** [comment] 2021-06-23 13:53
@harish2222 I am using neovide for the first time ...😢

**Comment by PyGamer0** [comment] 2021-06-30 10:08
@xianzheTM try an executable from [here](https://github.com/Kethku/neovide/actions/runs/984701889)

**Comment by harish2222** [comment] 2021-06-30 17:50
I am getting the same error again this time I am have used both versions of neovim version = 0.4.4 and version = 0.5
nothing worked gave the same error as pervious

**Comment by xianzheTM** [comment] 2021-07-01 01:59
> 
> 
> @xianzheTM try an executable from [here](https://github.com/Kethku/neovide/actions/runs/984701889)

It's worked for me!

**Comment by harish2222** [comment] 2021-08-12 16:37
@Kethku Bro I had to work on the problem and at last, found that it's not the executable that was not working it was my old laptop which had Intel HD 4000 which supports OpenGL (4.0) and doesn't support Vulkan. All the latest animations need at least OpenGL 4.1 (if older animation) and OpenGL 4.4 for most of the later powerful animation. 
Neovide isn't working is because of my old laptop chip running i5 3360m (mobile chip with Intel HD 4000 graphics having OpenGL 4.0.
SO the problem was hardware

**Comment by Kethku** [comment] 2021-08-28 03:14
Ok so I think I'm going to close this. Feel free to reopen if there is still an issue.

**Closed by Kethku** 2021-08-28 03:14 UTC
Labels: bug
