### ISSUE TITLE
Cursor in the CLI gets locked after lunching Neovide

### ISSUE THREAD

**Issue by alexventuraio** [neovide/neovide#2597] opened 2024-05-26 16:34 UTC
**Describe the bug**
After upgrading to Neovim v0.10.0 and Neovide 0.13.1, I stared to get a really nasty behavior:
- Every time I open a project or a file from the CLI I get the CLI prompt kind of locked so that I can not execute any other commands in it until I close the corresponding Neovide window.
- Also, if I press <kbd>Ctrl</kbd>+<kbd>c</kbd> in the CLI, the Neovide window gets closed.

**To Reproduce**
1. From your terminal `cd` into any folder you have.
2. Open Neovide with `neovide .`
3. The Neovide window gets opened.
4. Go back to your terminal and try to execute any other command.

**Expected behavior**
It should allow me to keep typing and executing commands in my terminal and keep the Neovide window as a separate process.

**Screenshots**
<img width="1518" alt="image" src="https://github.com/neovide/neovide/assets/13169164/d7ee84c1-32dd-44c3-9956-e12afdf40830">

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.5 (23F79)
 - Neovide Version 0.13.1
 - Neovim Version 0.10.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/15449533/neovide_rCURRENT.log)

**Additional context**

**Comment by LavaCxx** [comment] 2024-05-30 05:31
I have the same issue here, and the terminal displays `neovide[27893:14313744] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES`.

**Comment by alexventuraio** [comment] 2024-05-30 17:59
I had to downgrade to version `0.12.2` as a solution because these last two releases are too buggy!

**Comment by DanWiseProgramming** [comment] 2024-06-04 06:24
I'm think that this is not a bug, but expected behaviour given that the new default for Neovide 0.13+ is to not fork the process upon launch (mainly due to macOS behaviour).

See here:
https://github.com/neovide/neovide/releases/tag/0.13.0

> The --fork option has been reversed, and --no-fork is now the default. If the old behaviour is desired, you can set the environment variable NEOVIDE_FORK=1

I think that this issue can be closed.

**Comment by alexventuraio** [comment] 2024-06-04 17:24
@DanWiseProgramming thanks for pointing that out, so where should I put that ENV variable? In my `.zshrc` file?

**Comment by DanWiseProgramming** [comment] 2024-06-06 08:45
@alexventuraio As far as I know, `.zshrc` is not sourced by Neovide, but `.zprofile` is, so you could set it in there like so:
```bash
export NEOVIDE_FORK=1
```

**Comment by alexventuraio** [comment] 2024-07-13 22:08
I can can confirm that this has been fixed in the new [`0.13.2` version](https://github.com/neovide/neovide/releases/tag/0.13.2)

**Comment by alexventuraio** [comment] 2024-07-15 21:28
I'm sorry for the confusion here, but I didn't realize about the `export NEOVIDE_FORK=1` env variable I had in my `.zprofile` file and after commenting that out I found that it does not work, the terminal still locked until I close Neovide or press <kbd>Ctrl</kbd>+<kbd>c</kbd> in the terminal 😞

**Comment by fredizzimo** [comment] 2024-07-15 22:08
This is by design and documented as a breaking change in [0.13.0](https://github.com/neovide/neovide/releases/tag/0.13.0), so I'm closing this.

The decision was based on the discussions here https://github.com/neovide/neovide/issues/2147, and the PR was also left open for over a week for comments https://github.com/neovide/neovide/pull/2512. One user disagreed, and another long after it was merged.

Neovide, now behaves like most other applications when launched from the terminal. emacs, kate, libre office, google chrome and so on, just to mention a few, stay attached to the terminal by default. There are two exceptions I know of, Visual Studio Code, and gvim. And then some other Neovim guis (including previous versions of Neovide) that followed the gvim standard. 

If you prefer the old behaviour you can either set the `NEOVIDE_FORK=1` environment variable, set `fork=false` in `config.toml` or start `neovide --fork`.

**Closed by fredizzimo** 2024-07-15 22:08 UTC
Labels: bug

**Comment by fredizzimo** [comment] 2024-07-15 22:41
BTW, this debate is 21 years old https://vim-use.narkive.com/PCeauHU9/rant-gvim-f-on-linux

**Comment by bmulholland** [comment] 2024-07-16 09:11
I don't know about others, but for me I launch neovide from terminal only because that's seemingly the only way I can get all the environmental things working. In fact, I just tried to open neovide on its own, and it crashes, unable to find nvim (?!... it works fine when opened from the editor, and nvim is installed fine). Even if I got past that, what about asdf settings, ruby bundler, etc...

I'd like to accept the approach taken here, without forking workarounds! (Which is to say, I agree with Bram :) ) I assume others monitoring this thread would, too. Are there instructions or other info to help us figure out how to get all the environment settings, paths, version managers, etc working correctly when launching neovide as a macOS application directly? Where's the best place to discuss this?

I found https://neovide.dev/faq.html#neovide-is-not-picking-up-some-shell-configured-information which has some helpful suggestions. I've moved things to zprofile, which is a good step, but I'd still need to initialize asdf and get it to choose the configured each version of the project I cd to, I think? As it is, I get `node: No such file or directory`. Since this is neovide-specific, some docs to help with the intended approach for this would be nice. I'm happy to help contribute -- this comment is me starting them :)

I've hit my time limit for fiddling with environment things for today. If someone can help me make more progress, I'll write it all up. Hopefully, with some work, we can get to a place where no one wants neovide to be forking in the first place :)
