### ISSUE TITLE
Unable to use neovide if theres some missing features on neovim

### ISSUE THREAD

**Issue by sjakk** [neovide/neovide#2249] opened 2024-01-08 13:05 UTC
**Describe the bug**
Unable to close neovide(freeze state) unless that be by the task manager 

**To Reproduce**

https://github.com/neovide/neovide/assets/87045222/ec722c0a-52ff-4c73-83c5-781739eff713

**Expected behavior**
able to open neovim anyways and able to shutdown the window without being by task manager or add an error handling like when you open neovide and theres no nvim installed

**Comment by fredizzimo** [comment] 2024-01-08 13:10
This is a duplicate of
* https://github.com/neovide/neovide/issues/2233

And is fixed on main if you build from source by
* https://github.com/neovide/neovide/pull/2241

**Closed by fredizzimo** 2024-01-08 13:10 UTC
Labels: bug
