### ISSUE TITLE
Failed launching neovide on macOS from brew

### ISSUE THREAD

**Issue by denis631** [neovide/neovide#1373] opened 2022-06-27 16:54 UTC
**Describe the bug**
Installed the neovim through brew. Tried to run it without success. 

**To Reproduce**
1. Try to open neovide

**Expected behavior**
Being able to open neovide

**Desktop (please complete the following information):**
 - OS: macOS 12.4
 - Neovide Version 0.8.0
 - Neovim Version 0.7.0
 
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/8994156/neovide_rCURRENT.log)

**Comment by dineshKumar777** [comment] 2022-07-01 22:46
@denis631 I am not able to reproduce this in my macos(12.4)
had 'Apple can’t check app for malicious software' error. once i allowed, neovide is working fine.

brew install --cask --debug --verbose neovide => this is the command i used. added debug, verbose flag because installation took longer than usual

**Comment by dialtone** [comment] 2022-07-06 23:22
I also have this issue but not just from brew, even when I build from source. And what is more strange is that if I run `open Neovide` from command line it will open it, but double clicking on the App bundle will not result in the app to open. This is both with the downloaded release as with the source built version.

Malicious software shouldn't be the reason as it doesn't show up in the "Security & Privacy" preference pane, and as mentioned calling `open` manually works.

**Comment by dineshKumar777** [comment] 2022-07-06 23:32
@dialtone  for me when i first installed from brew, i got an popup for malicious or security popup warning. then after googling and enabled neovide (i am new to mac). After that I am not facing any issues so far.

Will try to build from source too.

**Comment by dialtone** [comment] 2022-07-06 23:36
![Console logs](https://user-images.githubusercontent.com/23195/177660008-8f7072e4-b99c-4115-a355-4314c79f75f6.png)

It could very well be a security approval thing, but I've already approved neovide security before, and apparently the TCCD daemon is killing neovide due to some security policy violation which I don't know about since I think it's approved and I receive no pop-ups on it.

**Comment by dialtone** [comment] 2022-07-06 23:57
Even adding neovide to the "development tools" security policy in macOS, explicitly adding it to "Full Access" for disk, and a few more groups, I get rid of the errors above in the screenshot, but neovide still crashes on start.

**Comment by dineshKumar777** [comment] 2022-07-07 00:01
@dialtone  thanks for the info. I posted this issue in neovide dev discord group. Hopefully someone will look into it.

**Comment by polachok** [comment] 2022-07-08 18:42
>And what is more strange is that if I run open Neovide from command line it will open it, but double clicking on the App bundle will not result in the app to open. 

Neovide launches nvim using login shell, so check that you have nvim binary in $PATH for login non-interactive shell, which basically means $PATH should be set in ~/.zprofile or ~/.zlogin (~/.zshrc is **not** read). Hope that helps.

**Comment by dialtone** [comment] 2022-07-08 23:43
that was it, solved it, thanks!

**Comment by dineshKumar777** [comment] 2022-07-09 00:11
@denis631 can you try this from your end?

**Comment by totoroot** [comment] 2022-07-11 07:58
Can confirm that @polachok's suggestion solves the issue at hand.
I observed the same issues that @denis631 raised and it was due to `nvim` not being found, as it still had to be added to my $PATH variable.

**Comment by iurev** [comment] 2022-07-11 14:46
MacOS: 11.6.7
NVIM v0.7.2
neovide 0.9.0

Neovide started successfully from the console

**Comment by shaunsingh** [comment] 2022-07-13 04:17
This thread can largely be split into two separate issues 
1. "Apple can’t check app for malicious software" 
2.  automatically killing neovide unless opened from terminal 

Sadly the "Apple can’t check app for malicious software" error/warning cannot be fixed without notarizing and properly code signing the app. Afaik that would require someone with an apple developer account, a cost of about 99$ a year. Im sure the org could afford it but considering the workaround is simple enough (iirc just ctrl+click -> open and allowing the app) I don't think is a good investment. 

As for the second, there isn't a workaround as neovide expects an "nvim" executable in your path, as it goes through the shell. I suppose you could bundle neovim within neovide, but this opens other issues (see: the vimr gui client. You wouldn't be able to customize neovim version (some people use nightly and some use stable), as well as architecture issues (m1 vs x86))

**Comment by ychin** [comment] 2022-07-28 03:44
> Sadly the "Apple can’t check app for malicious software" error/warning cannot be fixed without notarizing and properly code signing the app. Afaik that would require someone with an apple developer account, a cost of about 99$ a year. Im sure the org could afford it but considering the workaround is simple enough (iirc just ctrl+click -> open and allowing the app) I don't think is a good investment.

(Disclaimer: MacVim developer here) I think if you are serious about shipping a binary release on macOS, you are eventually going to want to get a signed / notarized app working in your workflow. It's not really good practice to train people to ignore security warnings, and in fact, Apple has been making it more and more annoying to ignore the warning, so it's just going to increase friction for people who want to use this, and it really limits the audience (most people just don't want to have to deal with this while they just want an editor that "just works"). It does cost $99 / year though, and signing / notarization requires additional work (it's not easy to automate), so I sympathize with the overhead especially if macOS isn't the primary target platform. Cool project btw!

**Comment by shaunsingh** [comment] 2022-07-28 06:57
I think in the future once Keith frees up we'll look more into notarizing and signing the app. As neovide becomes more popular, you're definitely right that it's not a good idea to make them ignore security warnings. The actual work of the notarization process shouldn't be much of an issue, since we don't release too often. Right now it isn't too high of a priority since unlike macvim, neovide does ship windows/linux builds as well (and I believe most of the team uses windows and linux). But yeah, looking forward to signing the builds in the future

> Cool project btw!

I and a few others here probably wouldn't be using vim without macvim either (my first introduction to vim was on macvim), so thanks for the cool project too!

**Comment by chipbuster** [comment] 2022-08-15 20:20
Over on starship, we had [a report from a user](https://github.com/starship/starship/issues/1774#issuecomment-1025184712) that their company was requiring *all* programs used on MacOS systems to be signed + notarized. While it doesn't seem common at the moment, it does mean that there are some situations where users are no longer able to override the security warnings.

**Comment by MultisampledNight** [comment] 2022-08-15 20:38
Woah, thank you for the link! Having a Rust project already gone through that and automated the process could greatly help future attempts in that direction.

Though for some part, my free software spirit kicks in. But I think there's not much of a choice here from a user's perspective.

**Comment by ychin** [comment] 2022-08-15 22:13
FWIW this is where MacVim does it: 1) [sign MacVim.app](https://github.com/macvim-dev/macvim/blob/668a73972a32be57f27dfa7f0ea0766eafd5e44e/src/Makefile#L3674-L3675) and 2) [sign MacVim.dmg, then notarize/staple MacVim.dmg](https://github.com/macvim-dev/macvim/blob/668a73972a32be57f27dfa7f0ea0766eafd5e44e/src/Makefile#L3698-L3702)

For starship's scripts above, it seems to say you need to notarize twice, and I'm not sure why. I'm guessing it's probably because of the way it's packaged? Since Neovide is just distributed as a .dmg file with neovide.app inside, you should just be able to notarize/staple the neovide.dmg file, and that will make the neovide.app file inside it notarized as well. You *do* need to sign both the neovide.app and neovide.dmg files though.

Also, there are two ways to store your notarization credentials, either using app-specific passwords, or using an App Store Connect API key (https://appstoreconnect.apple.com/access/api). I remember I eventually settled on using an API key which is just a secret token that you can store on the keychain (using `xcrun notarytool store-credentials --key $my_secret_key_file`) or provide as a file during the notarization submission process (`xcrun notarytool --key` or `xcrun notarytool --key-id`) as it seemed cleaner than having a team / username / app-specific password combo, but I don't remember what else was better since I haven't had to revisit it. I think the API key is also what you would use if you use the new webhook API (basically submitting for notarization via a REST API).

> Though for some part, my free software spirit kicks in

To be fair Apple has not indicated they will remove the escape hatch of running unsigned apps any time soon. They just make it annoying. Also, anyone can build Neovide locally without a developer account and it will run (Xcode will automatically sign it with a local certificate that only runs on the local machine). This just applied to pre-compiled binaries that you download off the web, built by someone else.

**Comment by chipbuster** [comment] 2022-08-15 22:30
> For starship's scripts above, it seems to say you need to notarize twice, and I'm not sure why. I'm guessing it's probably because of the way it's packaged?

Yes, we distribute a binary executable separately from the .pkg file, so we need to notarize them both. I think we would only need to notarize once if we only provided one form or the other.

Also, thanks for the tip on the Connect API! I somehow didn't see anything about it while I was researching the notarization process. I might take a look at that later and see if it makes the CI workflows simpler.

**Comment by owittek** [comment] 2022-12-16 14:36
> > And what is more strange is that if I run open Neovide from command line it will open it, but double clicking on the App bundle will not result in the app to open.
> 
> Neovide launches nvim using login shell, so check that you have nvim binary in $PATH for login non-interactive shell, which basically means $PATH should be set in `~/.zprofile` or `~/.zlogin` (`~/.zshrc` is **not** read). Hope that helps.

Had the same issue and this worked but since I'm on a M1 Mac homebrew installs universal apps into /opt so I simply symlinked nvim to my local bin folder ( ln -s /opt/homebrew/bin/nvim /usr/local/bin/nvim ).

**Comment by asins** [comment] 2023-01-04 08:41
I am also using Mac M1, the local command works fine, but NeoVide is not in the list of applications, I solved the problem by using the ln command. However, there will still be problems with future version updates.


```bash
ln -sfv /opt/homebrew/Cellar/neovide/0.10.3/Neovide.app ~/Applications/Neovide.app
```

**Comment by dongnqda** [comment] 2023-04-02 17:17
I have tried enable terminal inside Developer Tools, and it worked. I don't know if it's safe to do that.
<img width="570" alt="image" src="https://user-images.githubusercontent.com/113326771/229368448-17b7d5f3-bb62-4ce3-a0f9-6d005a8145e0.png">

**Comment by t1gu1** [comment] 2023-08-25 07:47
I found a nice work around to open it with an icon after installing it with brew to be able to open it with a shortcut in /Application.

https://github.com/t1gu1/Neovide-Mac-shortcut/tree/main

This is simply a file that I create with Automator.
Don't know if by sharing it, it cause the same problem.

**Comment by MultisampledNight** [comment] 2023-08-25 09:58
Fwiw I'd not advise downloading a random binary without checking if it can be reproduced locally.

**Closed** 2024-07-10 15:46 UTC
Labels: bug, macos, shell
