### ISSUE TITLE
Keyboard mapping is broken when multiple keyboards are plugged in on Linux/X11

### ISSUE THREAD

**Issue by johnmeacham** [neovide/neovide#1416] opened 2022-07-22 07:48 UTC
**Describe the bug**
When you plug in multiple keyboards that have different mappings (or plug an
external keyboard into a laptop) then neovide will choose the scancode
mapping of whatever keyboard happened to have a button pressed last and the
other keyboard will produce gibberish.

This is extremely likely to be fixed by calling XRefreshKeyboardMapping
whenever you get a MappingNotify event. The bug is conistent with not
handling that event.

**To Reproduce**
Plug another keyboard into your laptop

set the mappings for the keyboards:

```
setxkbmap -device $(xinput --list --id-only "OLKB Preonic" ) us
setxkbmap -device $(xinput --list --id-only "AT Translated Set 2 keyboard" ) dvorak
```

(use xinput to see a list of names for your keyboards)

**Expected behavior**
Both keyboads should work and not produce gibberish

**Desktop (please complete the following information):**
 - OS: Linux/X11
 - Neovide Version [e.g. 0.9.0]
 - Neovim Version [e.g. 0.6.1]

**Additional context**
One possibility is that neovide is not handling the X MappingNotify events
that
are used to change the keyboard mapping for a running app.

To fix this call XRefreshKeyboardMapping and return when you get a
MappingNotify event. nothing else needs to be done.

You can see the mapping events being generated by running the 'xev' program
and watching events as you switch between typing on different devices.

**Comment by MultisampledNight** [comment] 2022-07-22 07:57
Thanks for reporting! I can imagine that this is yet another issue possibly fixed by upstream winit, could you try if the [winit examples](https://github.com/rust-windowing/winit/tree/master/examples) can reproduce this issue? (I don't have another keyboard around at the moment, else I'd do it myself.)

**Comment by MultisampledNight** [comment] 2022-07-22 08:19
Doing some digging myself, [Neovide does this handle already](https://github.com/neovide/winit/blob/019ce9862f1745281048a5e85a957992b4a9c195/src/platform_impl/linux/x11/event_processor.rs#L165), but only if the mapping request is `MappingModifier` or `MappingKeyboard`. Upstream isn't different here. I don't know anything about X11 though, so I can't really tell what effect this has.

(for an explanation about this upstream thing: we use a forked version of winit for a better keyboard API which I just linked, but we're often outdated and missing hot upstream patches)

**Comment by fredizzimo** [comment] 2023-06-14 22:34
We have merged a new winit version with the new keyboard api in https://github.com/neovide/neovide/pull/1789. Could you try again with Neovide master?

**Comment by fredizzimo** [comment] 2024-01-13 11:05
Is this still an issue?

**Comment by fredizzimo** [comment] 2024-05-17 13:01
Closing due to no response, it was most likely fixed by the winit update.

**Closed by fredizzimo** 2024-05-17 13:01 UTC
Labels: bug, Windowing, status:needs-response
