### ISSUE TITLE
Opening Homebrew-installed Neovide on Mac gives warnings

### ISSUE THREAD

**Issue by lemorage** [neovide/neovide#2804] opened 2024-09-22 08:52 UTC
**Describe the bug**
Opening Neovide app on Mac, will provide me with the following warning msg: "Apple could not verify 'neovide.app' is free of malware that... ".
Btw, I could go to the "Privacy & Security" tab under the system settings on mac, and click the "run it anyway" to open this app, but I just wonder if it's possible to clear away this warning the first time opening this app.

**To Reproduce**
1. Download through `brew install --cask neovide`
2. Open downloaded `neovide.app` directly
3. See error

**Screenshots**
<img width="372" alt="warning-msg-on-mac" src="https://github.com/user-attachments/assets/45abe4de-a439-432a-a3d3-a4661b1e2dec">

**Desktop (please complete the following information):**
 - OS: macOS Sequoia 15.0
 - Neovide Version: 0.13.3
 - Neovim Version: 0.10.1

**Comment by AyaanAhmed25** [comment] 2024-10-05 21:01
its a mac os sequoia thing. Go to settings > Privacy and security > scroll all the way down and then allow neovide.

**Comment by lucax88x** [comment] 2024-10-25 13:34
even if this is a duplicate of #1373, looks like we cannot "skip" the verification by opening neovide from the /Applications folder as you could do before.

and sadly, if you have a managed laptop you cannot. 'run it anyway' in the "Privace & Security" tab, meaning we cannot run Neovide at all :(

**Comment by falcucci** [comment] 2024-10-25 22:12
fix is coming soon at https://github.com/neovide/neovide/pull/2814

**Comment by lucax88x** [comment] 2024-10-26 15:15
for anyone stuck in the meantime

```shell
xattr -d com.apple.quarantine /Applications/Neovide.app
```

**Closed** 2024-11-06 01:39 UTC
Labels: bug
