### ISSUE TITLE
Color mismatch between terminal and neovide

### ISSUE THREAD

**Issue by lucax88x** [neovide/neovide#2447] opened 2024-03-28 07:51 UTC
**Describe the bug**
Neovide, somehow not using the full 256 colors

**To Reproduce**
1. Open Neovide
2. Confront to any terminal color

**Expected behavior**
I would expect to see same color palette between neovide and terminal nvim

**Screenshots**
<img width="1656" alt="Screenshot 2024-03-28 at 08 40 55" src="https://github.com/neovide/neovide/assets/6294464/8461b1e0-36f1-4d60-9e39-9964762ccc0f">
<img width="1656" alt="Screenshot 2024-03-28 at 08 41 29" src="https://github.com/neovide/neovide/assets/6294464/0d49a9b8-2f55-45e1-9032-54544e23f22c">

**Desktop (please complete the following information):**
 - macos 14.4.1
 - Neovide Version 0.12.2
 - Neovim Version v0.10.0-dev-2723+g981301d11

**Additional context**
It's ofc possible I'm missing something, and in this case, I would likely accept any guidance on where to check.

**Comment by xzbdmw** [comment] 2024-03-28 11:44
Kitty by default using srgb colorspace, you can try set `macos_colorspace displayp3` in kitty.conf to see the difference

**Comment by lucax88x** [comment] 2024-03-28 13:22
but my problem is on neovide, on kitty everything is fine?

Now that you mentioned the colorspace, could this be the issue? https://github.com/neovide/neovide/issues/2044

**Comment by xzbdmw** [comment] 2024-03-28 13:38
Hmm, that setting in kitty gives me the same color in mac builtin display(more vivid), you can change system color space to srgb in system settings maybe.

**Comment by fredizzimo** [comment] 2024-03-28 13:42
Yres, this is a duplicate of
* https://github.com/neovide/neovide/issues/2044
Which is a continuation of this
* https://github.com/neovide/neovide/issues/1102#issuecomment-1726394535

**Closed by fredizzimo** 2024-03-28 13:42 UTC
Labels: bug
