### ISSUE TITLE
The keyboard repeat rate is sometimes low

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [neovide/neovide#1336] opened 2022-05-26 13:36 UTC
I often navigate around by arrow keys or hjkl and the key repeat rate is very low.

**Describe the solution you'd like**
At best I wish there was a way it would match my environment (GNOME 3 on Wayland) but being able to configure how fast keys repeat would be great. Also, just increasing the default rate. I used some random snapshot of neovide and it was faster, so I am not entirely sure what changed in which way but it is noticeably slower now.

**Describe alternatives you've considered**
Don't use cursor movement keys :(

**Comment by jeremycostanzo** [comment] 2022-05-29 13:32
I am not a neovide expert, but I think that this is handled in linux itself: https://askubuntu.com/questions/846030/how-to-set-keyboard-repeat-delay-and-speed-in-ubuntu-gnome-16-10

But maybe it is a problem of performance with neovide?

**Comment by Leonidas-from-XIV** [comment] 2022-06-09 08:23
I wish it was matching (and agree that that's the best source of that config) but it is significantly slower than key repeat in other applications.

But yes, might be a performance problem indeed (`nvim` on the console is fast though so it would have to be neovide). I haven't thought of that, good point!

**Comment by Leonidas-from-XIV** [comment] 2022-06-14 12:11
I investigated it a bit and the slow key-repeat seems to be dependent on the window size: the bigger the window the slower the cursor moves. In the default small window it is fast, but when I full screen it gets significantly slower.

I checked the current `master` version and it is the same as on 0.8.

**Comment by ZerdoX-x** [comment] 2023-08-24 02:19
Experiencing the same issue, you are not alone :)

I am on Gentoo Wayland Apple M1 (asahi) machine

**Comment by ZerdoX-x** [comment] 2023-09-01 15:42
>  investigated it a bit and the slow key-repeat seems to be dependent on the window size

This is definitely a duplicate of https://github.com/neovide/neovide/issues/1312

**Comment by fredizzimo** [comment] 2023-09-01 15:51
The slow rendering should be fixed in https://github.com/neovide/neovide/pull/1977.

But the key repeat rate is similarly slow when running over a slow TCP connection for example. It's also slow if Neovim slows down for some reason. The issue is that we send the key presses using serial messages, therefore we block the next command until we have got a response back from Neovim. That should not be necessary, we should be able to send it asynchronously and don't care about the response.

**Comment by ZerdoX-x** [comment] 2023-09-01 18:27
> But that does not fix the entire issue.
> key repeat rate is similarly slow when running over a slow TCP connection for example

I mean OP mentioned that making window smaller fixes the issue, so I think this is render loop issue. Thank you so much for linking PR, I'll try to compile this branch.

**Comment by fredizzimo** [comment] 2024-01-13 07:21
Closing this as fixed

**Closed by fredizzimo** 2024-01-13 07:21 UTC
Labels: enhancement
