### ISSUE TITLE
Problems with window size due to font selection/definition

### ISSUE THREAD

**Issue by yngwi** [neovide/neovide#1400] opened 2022-07-14 07:04 UTC
**Describe the bug**
When `let g:neovide_remember_window_size = v:true` in init.vim, Neovide remembers the window width by writing it into `neovide-settings.json`. As far as I can tell this works well on my system (Windows 11). However, I have problems when selecting specific fonts *or* defining the font heights with `guifont`.

On my system this works fine:
`set guifont=Cascadia\ Code`

This doesn't work, each successive re-opening of the gui, the size gets bigger:
`set guifont=Cascadia\ Code:h12`

Initial settings (set manually): `{"window":{"Windowed":{"position":{"x":613,"y":149},"size":{"width":120,"height":30}}}}`

* after first open/close of gui: `{"window":{"Windowed":{"position":{"x":494,"y":121},"size":{"width":146,"height":36}}}}`
* after second open/close of gui: `{"window":{"Windowed":{"position":{"x":494,"y":121},"size":{"width":178,"height":44}}}}`
* after third open/close of gui: `{"window":{"Windowed":{"position":{"x":494,"y":121},"size":{"width":217,"height":53}}}}`
* ... and so on

The same happens when setting a different font, even without specifying the height directly:
`set guifont=Iosevka`

The difference here is that while the window width keeps increasing, the window height keeps decreasing, after several re-openings, the settings are `{"window":{"Windowed":{"position":{"x":126,"y":168},"size":{"width":265,"height":22}}}}`

**To Reproduce**
Repeat the process outlined in the problem description

**Expected behavior**
The window stays the same size after multiple open/closes without changing the size be resizing the gui window.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11
 - Neovide 0.9.0
 - Neovim v0.8.0-dev+608-g778541067

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

Log after manually setting the window dimensions in the settings to 120x30: [GitHub Gist](https://gist.github.com/yngwi/a369b0744800fbaa548015347f9ce913)

**Additional context**

**Comment by tonystr** [comment] 2022-11-05 18:20
I experience the same issue with Fira\ Code:h12, though it works fine with h13 or h11. Would be great if someone could look at this issue

**Comment by fredizzimo** [comment] 2023-08-07 16:07
The problem is fixed in Neovide 0.11.0, the window size is saved as pixels instead of columns and rows.

**Closed by fredizzimo** 2023-08-07 16:07 UTC
Labels: bug
