### ISSUE TITLE
Run with --server args will lost some config

### ISSUE THREAD

**Issue by baizeyv** [neovide/neovide#2791] opened 2024-09-13 13:13 UTC
**Describe the bug**

Run with `--server foobar` will lost my options.lua configuration.

**To Reproduce**
1. in the first terminal , run :  nvim --headless --listen 127.0.0.1:7373
2. in the second terminal, run : neovide --server 127.0.0.1:7373
3. normal startup, but lost something

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 PRO
 - Neovide Version: 0.13.3
 - Neovim Version: 0.10.1

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

**Additional context**

My neovim options configuration:
```lua
vim.o.guifont = "FantasqueSansM Nerd Font Mono,Symbols Nerd Font Mono:h14"
if vim.g.neovide then
  vim.g.neovide_transparency = 0.85
  vim.g.neovide_hide_mouse_when_typing = true
  vim.g.neovide_fullscreen = true
  vim.g.neovide_remember_window_size = true
  vim.g.neovide_profiler = false
  vim.g.neovide_cursor_vfx_mode = "wireframe"
end
```
run with --server 127.0.0.1:7373, these options will not effective.

Please.

Direct startup is like this:
![image](https://github.com/user-attachments/assets/1d3bda35-3875-4e2a-8e5e-cca90d5e96a9)

but add some args will like this:
![image](https://github.com/user-attachments/assets/8d387e52-74d6-468b-b666-75f7a01ed9c0)

**Comment by fredizzimo** [comment] 2024-09-17 05:49
I'm closing this as a duplicate of
* https://github.com/neovide/neovide/issues/1868

We need Neovim support for this
* https://github.com/neovim/neovim/issues/29634

I think you might be able to work around it, by moving part of your configuration to https://neovim.io/doc/user/autocmd.html#UIEnter, or simply by removing the if `vim.g.neovide then` check.

**Closed by fredizzimo** 2024-09-17 05:49 UTC
Labels: bug
