### ISSUE TITLE
Can't start Neovide when using nushell because of "which" command

### ISSUE THREAD

**Issue by DannyJJK** [neovide/neovide#1498] opened 2022-08-20 22:54 UTC
**Describe the bug**
Trying to run Neovide when using shell Nushell fails because of "which" command.

**To Reproduce**
1. Use Nushell (I am using 0.67.0 installed via cargo) https://www.nushell.sh
2. Open Neovide from Terminal
3. See error in log file

**Expected behavior**
Neovide finds nvim executable via a method which works across different shells/operating systems, and runs successfully.

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.5.1 (21G83)
 - Neovide Version: 0.10.1
 - Neovim Version: v0.7.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

TRACE [neovide] Neovide version: 0.10.1
DEBUG [neovide::bridge::command] Running which command: "/Users/dannykirkham/.cargo/bin/nu" "-lc" "which nvim"
ERROR [neovide::bridge::command] nvim not found!

**Comment by chipbuster** [comment] 2022-08-25 00:55
If you're willing to add a dependency, [which](https://lib.rs/crates/which) might be useful for this. It does rely on PATH being exported from the parent shell though.

**Comment by fredizzimo** [comment] 2023-07-26 11:07
Duplicate of #1812

**Closed** 2023-07-26 11:08 UTC
Labels: bug, shell
