### ISSUE TITLE
Unwanted key grabbing

### ISSUE THREAD

**Issue by phi-mah** [neovide/neovide#958] opened 2021-09-15 13:21 UTC
Hi, 

On a KDE Plasma desktop, I am bothered by an issue where neovide grabs key strokes that should be handled solely by plasma itself: 

In the following screencast neovide runs on *desktop 2* and --after typing *"hello"*, I want to switch to *virtual desktop 1* (via `Ctrl + F1`). The switching occurs, but the `F1` keystroke seems still to be caught by neovide. This can be seen when switching back (this time via a mouse click on the desktop pager). Neovide is now presenting the help page (triggered by the `F1` key).

![Peek 2021-09-15 14-41](https://user-images.githubusercontent.com/14107889/133436720-33f3a29a-1afa-4783-8c15-435b3d8d2b32.gif)

From time to time I am expiring a similar issue when text fragments ~~from the clipboard are unintentionally~~ *typed into other applications are also ending up in the neovide/vim buffer.* ~~I assume that I copied/pasted them when working on a different virtual desktop, with neovide being around on its own virtual desktop in "standby mode"~~  Unfortunately, I do not have a reproducer for this behavior, but it feels kind of similar to the issue I described above.

NB: As it can also be seen in the screencast, the neovide screen area only gets updated when the mouse pointer touches its active area. When starting the screencast the neovide window still renderes the countdown animation. When switching back from *desktop 1* to *desktop 2*, only the window decoration is shown (but not neovide itself). In both cases, only after moving the mouse pointer into the screen area covered by the neovide window, it finally gets drawn.

Again, I do not know if this is really a "bug" or an unavoidable feature, I also can live with that, just want to mention it.

---
I compiled neovide myself, the commit i used is 839f2938a1c446c089ca795712dcb9aee22121de (head of the main branch). The DE is quite old, it is KDE Plasma 5.8.6 (as shipped by debian stretch)

**Comment by rti** [comment] 2021-09-20 17:46
I can confirm that neovide reacts on key presses handled by the desktop environment on X11. I experienced a similar issue on Gnome 40.4.0. For example switching away from neovide to another window using ALT-Tab triggers tab related actions in neovide.

**Comment by LoipesMas** [comment] 2021-10-20 10:55
I've tried to replicate that on my setup (dwm), but couldn't get it to happen.
Could this be that your window managers don't send focus change?
Can of you run `neovide --log`, reproduce this bug, attach the log here and also describe exactly what you did (what you pressed, in what order, when did the workspace change etc.)?

**Comment by LoipesMas** [comment] 2021-10-20 14:05
In both logs it seems as if neovide doesn't unfocus correctly. But this might as well be a bug in `winit` (because I think neovide gets focus commands from `winit`) or some weird interaction with your window managers. 
Either way, it's sadly probably out of my reach.

**Comment by acheronfail** [comment] 2022-01-09 23:40
FWIW I'm encountering this issue as well from `i3`.

In `i3`, I have it set to open a specific window of another application when F1 is pressed. When I press F1, it's ignored in all other apps, and my desired application activates.

In `neovide` however, it also detects this F1 keypress and then opens the help menu (default F1 behaviour), which is really frustrating!

**Comment by last-partizan** [comment] 2022-01-26 17:41
I've applied that patch to `fix-stuck-shift` branch of our `winit` and update neovide branch `fix-stuck-shift`, please check if it fixes issue.

**Comment by phi-mah** [comment] 2022-01-26 18:03
Thank's a lot!
I am happy to report that the `fix-stuck-shift` branch seems to fix the bug. On first sight it looks good, I will do some further testing

**Comment by last-partizan** [comment] 2022-01-26 20:45
I've merget that one small patch https://github.com/neovide/winit/commit/59eb01c19f78a8f81232448c2792dae39fd13efc into our winit, and updated neovide main dependencies.

Please now test it with main.

**Comment by phi-mah** [comment] 2022-01-28 14:21
Sorry for the late reply, but also the master branch looks good. Thank you for taking over this issue, i think we can close it.

Out of curiosity: Why are you guys maintaining your own winit fork? What has been added that is not their in the `winit:new-keyboard` branch?

**Comment by last-partizan** [comment] 2022-01-29 13:47
I think we're waiting for this PR https://github.com/rust-windowing/winit/pull/1932

And we're merged it and fixed some other bugs as well.

**Closed by last-partizan** 2022-01-29 13:48 UTC
Labels: bug, Keyboard Input
