### ISSUE TITLE
Typing after entering command mode : too quickly loses the cursor

### ISSUE THREAD

**Issue by yashamon** [neovide/neovide#1297] opened 2022-05-01 13:30 UTC
**Describe the bug**
If you type right after entering command mode : the cursor disappears from command line
**To Reproduce**
1.  first map
nmap t :blah
2. now in normal mode press t
no cursor in command line. It appears to be desync of some kind. 

**Expected behavior**
This does not happen in normal nvim. (Or goneovim)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 11.4] Linux Debian sid
 - Neovide Version [e.g. 0.6.0] .8 but this bug has been present in earlier versions
 - Neovim Version [e.g. 0.5.0] .8

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

**Additional context**

**Comment by yashamon** [comment] 2022-05-06 03:08
I have also tried this in windows. The bug is not present, but if you pass --wsl it reappears. 
goneovim --wsl does not have this issue.

**Comment by yashamon** [comment] 2022-07-01 17:19
Oh I can confirm the same bug as eprst on windows when --multigrid option is passed. Also the original bug on windows requires --multigrid.

**Comment by MultisampledNight** [comment] 2022-07-08 14:34
Duplicate of #1207, closing in favor of that issue. Thank you anyways!

**Closed by MultisampledNight** 2022-07-08 14:34 UTC
Labels: bug
