### ISSUE TITLE
<C-6> cannot be detected

### ISSUE THREAD

**Issue by kalokng** [neovide/neovide#991] opened 2021-10-01 12:26 UTC
**Describe the bug**
<C-6> should be able to be detected, and treated as <C-^>, which similar to `:e #`

**To Reproduce**
1. Open fileA
2. Open fileB
3. Press `<C-6>`
4. Press `<C-^>`

**Expected behavior**
In step 3 and 4, the buffer should be swapped. (e.g. fileA -> fileB)
But only step 4 swapped buffer.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10, 20H2, build 19042.1237
 - Neovide Version latest main branch, commit fb9c1de
 - Neovim Version v0.5.0-dev+1357-g192f89ea1

**Please run `neovide --log` and paste the contents of the `.log` file here:**

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/7267056/neovide_rCURRENT.log)

**Additional context**
From the log, only <C-^> is received:
`TRACE [neovide::channel_utils] ui_command Keyboard("<C-^>")`

**Comment by fredizzimo** [comment] 2023-06-14 22:44
I'm closing this as a duplicate of https://github.com/neovide/neovide/issues/1646. But we have to remember that some users want to manually map `<C-6>` to something, while it should also work like standard terminal Neovim in other cases.

**Closed by fredizzimo** 2023-06-14 22:44 UTC
Labels: bug, Keyboard Input
