### ISSUE TITLE
rendering of lines/blocks/braille characters for gapless alignment, "refrence: st boxdraw patch"

### ISSUE THREAD

**Issue by motaz-shokry** [neovide/neovide#2676] opened 2024-06-29 11:12 UTC
rendering of lines/blocks/braille characters for gapless alignment

**Comment by fredizzimo** [comment] 2024-06-29 11:20
I'm closing this as a duplicate of
* https://github.com/neovide/neovide/issues/2491

**Closed by fredizzimo** 2024-06-29 11:20 UTC
Labels: enhancement
