### ISSUE TITLE
Font style config for normal style doesn't work in 0.13.2(was working in 0.13.1)

### ISSUE THREAD

**Issue by Syndim** [neovide/neovide#2707] opened 2024-07-14 08:53 UTC
**Describe the bug**
Font style config for normal font in the `config.toml` file doesn't work in 0.13.2. My config file looks like this:

```
fork = true

[font]
size = 16
hinting = "full"
edging = "antialias"

[[font.normal]]
family = "FiraCode Nerd Font Mono"
style = "Medium"
```

But in Neovide the normal text's font weight is always `Normal`, changing the style config to other values(like `Bold`) also won't work.

**To Reproduce**
1. Set normal font's style to a value other than `Normal`
2. Open neovide

**Expected behavior**
Normal text in Neovide should apply font style defined in the config file

**Screenshots**
Below is a comparasion of what it looks like in 0.13.1(left) and 0.13.2(right):
![](https://github.com/user-attachments/assets/278e207c-9d7c-4a63-ac95-e99642df545f)

**Desktop (please complete the following information):**
 - OS: WIndows 11
 - Neovide Version: 0.13.2
 - Neovim Version: 0.10.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

[neovide_r2024-07-14_15-56-32.log](https://github.com/user-attachments/files/16216179/neovide_r2024-07-14_15-56-32.log)

**Additional context**
It looks like the issue is related to [this line](https://github.com/neovide/neovide/blob/f56145238570e9e3134a8d7d43144690661f62d0/src/renderer/fonts/font_options.rs#L220C1-L220C57). If no other styles are applied, the style is set to `None` istead of the one defined by the normal font style.

**Comment by fredizzimo** [comment] 2024-07-14 09:22
This was probably a regression caused by https://github.com/neovide/neovide/pull/2639

I think I was either unclear with my comment here https://github.com/neovide/neovide/pull/2639#discussion_r1629843138, or it was merged too early without being properly fixed.

My intent was that missing fallbacks reverts to the default style for that weight. So, if Neovide tries to render a bold font, and a bold fallback is missing, then it uses the font name and other properties from the normal font but overrides the style to bold.

@xzbdmw, do you want to fix it or should I do it? I think we should create a new release soon that fixes this, so that we can move on to bigger upgrades in the 0.14.x version of Neovide.

**Comment by xzbdmw** [comment] 2024-07-14 09:26
I’ll update a fix today

**Comment by fredizzimo** [comment] 2024-07-14 09:27
Thank you!

**Closed** 2024-07-16 08:30 UTC
Labels: bug, font rendering
