### ISSUE TITLE
Many things are broken with Neovim 0.8 and multigrid enabled

### ISSUE THREAD

**Issue by xbladesub** [neovide/neovide#1584] opened 2022-10-04 08:25 UTC
I noticed that floating windows transparency doesn't work with multigrid enabled (always have background color no matter what). 
Also which-key UI is broken - doesn't draw it properly anymore with Neovim update to 0.8. Aswell as toggleterm - floating terminals completely freeze entire Neovide instance, so only cmd+q helps. 

Is there any plans to fix multigrid? I used Neovide because of animations and smooth scroll, but considering to switch to helix right now as it not really useful anymore.

(macOS 12.6, m1 pro)

**Comment by fredizzimo** [comment] 2022-10-04 18:01
I don't immediately see any [changes](https://github.com/neovim/neovim/releases/tag/v0.8.0) that could have caused this, and I haven't tried to debug it yet. But obviously this is something we have to sort out really soon, since more people are using it all the time, sometimes almost without a choice, if you are running Arch Linux for example.

I won't have time do do it myself, since I'm concentrating on the performance improvements. But it would be good if someone could look into this. The problem is probably quite easy to fix, once we figure out what exactly causes it.

**Comment by avalonv** [comment] 2022-10-04 23:07
@xbladesub did you test if which-key fails ONLY with --multigrid enabled?

Asking because there are issues with highlighting entries which seem to be related to Neovim 0.8 which occur even without multigrid enabled:

(Neovide -u NORC)
![image](https://user-images.githubusercontent.com/29720696/193946595-8d3c04f3-6e96-4fc9-9dd0-50607dcc3812.png)
(nvim on kitty)
![image](https://user-images.githubusercontent.com/29720696/193946603-c5f12d29-7197-4996-b94f-3ee5807811bb.png)

**Comment by xbladesub** [comment] 2022-10-05 01:22
> @xbladesub did you test if which-key is broken ONLY with --multigrid enabled?
> 
> Asking because there are issues with highlighting entries which seem to be related to Neovim 0.8 which occur even without multigrid enabled:
> 
> (Neovide -u NORC) ![image](https://user-images.githubusercontent.com/29720696/193946595-8d3c04f3-6e96-4fc9-9dd0-50607dcc3812.png) (nvim on kitty) ![image](https://user-images.githubusercontent.com/29720696/193946603-c5f12d29-7197-4996-b94f-3ee5807811bb.png)

yes, which-key is broken only with multigrid enabled (as other things also). I would try to dive to this issue by myself, but I'm still new in rust

**Comment by AbbasSrour** [comment] 2022-10-09 14:26
> @xbladesub did you test if which-key is broken ONLY with --multigrid enabled?
> 
> Asking because there are issues with highlighting entries which seem to be related to Neovim 0.8 which occur even without multigrid enabled:
> 
> (Neovide -u NORC) ![image](https://user-images.githubusercontent.com/29720696/193946595-8d3c04f3-6e96-4fc9-9dd0-50607dcc3812.png) (nvim on kitty) ![image](https://user-images.githubusercontent.com/29720696/193946603-c5f12d29-7197-4996-b94f-3ee5807811bb.png)

I can also confirm whichkey is only broken in multigrid mode, the normal mode is fine, also I can also confirm multigrid mode is causing laggy animation (especially with winbar) and stutters.

**Comment by stefanwatt** [comment] 2022-10-12 19:32
For me using multigrid completely freezes up neovide on startup. Makes it completely unusable.
Works fine with 0.72 release of neovim.

**Comment by Isti115** [comment] 2022-10-13 19:41
Opening certain "popup" windows under neovim 0.8 with multigrid enabled completely locks up my entire system, not just neovide. (It starts quickly filling up memory, rendering my OS unusable after eating 32GB of RAM and an additional 32GB of swap.)

**Comment by xbladesub** [comment] 2023-01-08 03:48
Any updates on this? I'd like to know where to find the issue so I'd try to fix it by myself

**Comment by MultisampledNight** [comment] 2023-02-12 15:26
@xbladesub Hi! I haven't looked into this (and probably won't due to a lack of time), but these things might be interesting for you:

- `src/main.rs` contains a rough architecture overview.
- I'm not sure what _exactly_ is broken so far, but likely
  - the same events from Neovim might mean different things now (especially scrolling). In that case `src/bridge` could be a good starting point.
  - overlaid windows are thought different now, and Neovide draws them exactly as not expected by Neovim. One thing I noticed here is the `:LspInfo` window from nvim-lspconfig, which on `<Tab>` opens a window displaying server information — but that's sometimes hidden behind the main `:LspInfo` window, whereas it perfectly overlays in TUI Neovim.
- We have a Discord server for more synchronous communication, check the badges at the top of the readme.

**Comment by xbladesub** [comment] 2023-02-18 08:56
> 

Thanks for reply, I'll do best what I can

**Comment by fredizzimo** [comment] 2023-03-04 23:16
https://github.com/neovide/neovide/pull/1786, should fix the issue with floating windows being positioned wrong. 

If you still have issues other than windows being positioned in the wrong place, please open new issues with clear instructions on how to reproduce the bug. I have not personally not seen any of the other problems mentioned here.

**Comment by A-Lamia** [comment] 2023-03-05 08:31
I still seem to be having the issue with the missing transparency on windows.

**Comment by MultisampledNight** [comment] 2023-03-05 09:20
@A-Lamia Did you build from main or did you try out the PR by fredizzimo? It's not quite clear.

**Comment by A-Lamia** [comment] 2023-03-05 09:25
@MultisampledNight i did both, sorry for i was confusing.

**Comment by fredizzimo** [comment] 2023-03-05 11:00
The transparency issues are unrelated to Neovim 0.8, I believe. I think it has always been broken in a way or another.

I do have some fixes for that too, but I did not want to make the same fix multiple ways depending on the base way of rendering everything, so I haven't made an independent fix for it.

I think I will be able to include it in a pull request I probably will put up later today though. That will be a huge pull request in terms of changes and completely changes the way we do smooth scrolling, but it will fix a lot of things, like disappearing lines and not working together with folds and so on. It gets rid of the scrolling snapshots, so the memory requirements will also lower. 

Ideally the transparency fixes would not be included in that, since it can be separated out, but depending on it. But I will include it at least as a draft initially, since it will probably take a long time for it to be reviewed and merged.

**Comment by xbladesub** [comment] 2023-03-05 12:08
> The transparency issues are unrelated to Neovim 0.8, I believe. I think it has always been broken in a way or another.
> 
> I do have some fixes for that too, but I did not want to make the same fix multiple ways depending on the base way of rendering everything, so I haven't made an independent fix for it.
> 
> I think I will be able to include it in a pull request I probably will put up later today though. That will be a huge pull request in terms of changes and completely changes the way we do smooth scrolling, but it will fix a lot of things, like disappearing lines and not working together with folds and so on. It gets rid of the scrolling snapshots, so the memory requirements will also lower.
> 
> Ideally the transparency fixes would not be included in that, since it can be separated out, but depending on it. But I will include it at least as a draft initially, since it will probably take a long time for it to be reviewed and merged.

Could you please share your MR branch?

**Comment by fredizzimo** [comment] 2023-03-05 12:25
I don't have that exact branch ready yet, but I do have one that includes even more stuff https://github.com/fredizzimo/neovide/commits/fsundvik/directx, that one currently needs to be run with the `--noidle` option, and it assumes a fixed vsync of 60fps with opengl

Some of that branch does in addition to the multigrid stuff is:
* Completely changes the rendering to make it much smoother, including a new rendering thread, the default winit one only reacts to "WM_PAINT" on Windows, and can't therefore be made smooth. On other platforms, I haven't checked how winit works, but the rendering thread version mostly works
* Enables Direct3D on Windows (that currently works better than the opengl version of other platforms)

Some of the known problems with that branch are:
* There's also still some minor issues with the transparency, especially how it relates to the global `g:neovide_transparency` option .
* There are still some other problems in that too, for example the DPI scaling notifications, probably don't work as they should.
* The `--noidle` requirement

**Comment by A-Lamia** [comment] 2023-03-05 13:04
@fredizzimo not sure if this will effect other people but just testing your branch out it seems some people might run in to this issue, https://github.com/rust-skia/rust-skia/issues/314

**Comment by fredizzimo** [comment] 2023-03-05 13:12
I might have forgot some setting that makes Skia build from source in the branch. It should be fine as long as the binary is used, and I will make sure that happens when finalize the branch.

I was using this https://crates.io/crates/cargo-local-registry, when I was testing locally on Windows.

**Closed** 2023-03-05 21:27 UTC
Labels: bug, multigrid

**Comment by fredizzimo** [comment] 2023-03-05 22:13
@A-Lamia, @xbladesub, the other pull request is now up (the one that should fix the transparency, and a lot of other multigrid issues). https://github.com/neovide/neovide/pull/1790

**Comment by A-Lamia** [comment] 2023-03-06 03:39
@fredizzimo ill compile it now thanks :D
