### ISSUE TITLE
Stuck and unresponsive when quitting

### ISSUE THREAD

**Issue by rainzee** [neovide/neovide#2207] opened 2023-12-26 08:51 UTC
**Describe the bug**
Stuck and unresponsive when quitting on windows

**To Reproduce**
1. :q!
2. See error

**Screenshots**
![image](https://github.com/neovide/neovide/assets/4585440/04e0d6b4-f5a7-4b2c-8e6e-5fcd1039bd41)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Neovide Version [e.g. 0.12.0]
 - Neovim Version [e.g. 0.9.4]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

**Additional context**

**Comment by fredizzimo** [comment] 2023-12-26 15:28
Closing this as a duplicate of https://github.com/neovide/neovide/issues/2182

**Closed by fredizzimo** 2023-12-26 15:28 UTC
Labels: bug
