### ISSUE TITLE
Neovide not opening (wayland-client error)

### ISSUE THREAD

**Issue by MC2BP** [neovide/neovide#1727] opened 2023-01-06 18:30 UTC
**Describe the bug**
Neovide no longer starts properly on sway version 1.18.

**To Reproduce**
start neovide 

**Expected behavior**
Neovide window opening

**Desktop (please complete the following information):**
 - OS: Void Linux (Kernel: 6.0.15_1)
 - Neovide Version 0.11.0 and 0.9.0
 - Neovim Version 0.8.2
 - Wayland Compositor: Sway 1.8

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/10362265/neovide_rCURRENT.log)

**Additional context**
I've investigated the issue a bit and seems like somethings wrong with wayland. 
Running the debugbuild gave me this result:
```
[wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting.
zsh: IOT instruction  cargo run
```
Here are also the logs with `WAYLAND_DEBUG=1`:
```
[ 949089.648]  -> wl_display@1.get_registry(new id wl_registry@2)
[ 949089.662]  -> wl_display@1.sync(new id wl_callback@3)
[ 949089.706] wl_display@1.delete_id(3)
[ 949089.710] wl_registry@2.global(1, "wl_shm", 1)
[ 949089.730]  -> wl_registry@2.bind(1, "wl_shm", 1, new id [unknown]@4)
[ 949089.742] wl_registry@2.global(2, "wl_drm", 2)
[ 949089.745] wl_registry@2.global(3, "zwp_linux_dmabuf_v1", 4)
[ 949089.748] wl_registry@2.global(4, "wl_compositor", 5)
[ 949089.755]  -> wl_registry@2.bind(4, "wl_compositor", 5, new id [unknown]@5)
[ 949089.760] wl_registry@2.global(5, "wl_subcompositor", 1)
[ 949089.765]  -> wl_registry@2.bind(5, "wl_subcompositor", 1, new id [unknown]@6)
[ 949089.769] wl_registry@2.global(6, "wl_data_device_manager", 3)
[ 949089.772] wl_registry@2.global(7, "zwlr_gamma_control_manager_v1", 1)
[ 949089.774] wl_registry@2.global(8, "zxdg_output_manager_v1", 3)
[ 949089.777] wl_registry@2.global(9, "org_kde_kwin_idle", 1)
[ 949089.779] wl_registry@2.global(10, "ext_idle_notifier_v1", 1)
[ 949089.782] wl_registry@2.global(11, "zwp_idle_inhibit_manager_v1", 1)
[ 949089.784] wl_registry@2.global(12, "zwlr_layer_shell_v1", 4)
[ 949089.787] wl_registry@2.global(13, "xdg_wm_base", 2)
[ 949089.791] wl_registry@2.global(14, "zwp_tablet_manager_v2", 1)
[ 949089.793] wl_registry@2.global(15, "org_kde_kwin_server_decoration_manager", 1)
[ 949089.796] wl_registry@2.global(16, "zxdg_decoration_manager_v1", 1)
[ 949089.802]  -> wl_registry@2.bind(16, "zxdg_decoration_manager_v1", 1, new id [unknown]@7)
[ 949089.806] wl_registry@2.global(17, "zwp_relative_pointer_manager_v1", 1)
[ 949089.810]  -> wl_registry@2.bind(17, "zwp_relative_pointer_manager_v1", 1, new id [unknown]@8)
[ 949089.814] wl_registry@2.global(18, "zwp_pointer_constraints_v1", 1)
[ 949089.819]  -> wl_registry@2.bind(18, "zwp_pointer_constraints_v1", 1, new id [unknown]@9)
[ 949089.823] wl_registry@2.global(19, "wp_presentation", 1)
[ 949089.825] wl_registry@2.global(20, "zwlr_output_manager_v1", 4)
[ 949089.828] wl_registry@2.global(21, "zwlr_output_power_manager_v1", 1)
[ 949089.831] wl_registry@2.global(22, "zwp_input_method_manager_v2", 1)
[ 949089.833] wl_registry@2.global(23, "zwp_text_input_manager_v3", 1)
[ 949089.837]  -> wl_registry@2.bind(23, "zwp_text_input_manager_v3", 1, new id [unknown]@10)
[ 949089.840] wl_registry@2.global(24, "zwlr_foreign_toplevel_manager_v1", 3)
[ 949089.843] wl_registry@2.global(25, "ext_session_lock_manager_v1", 1)
[ 949089.846] wl_registry@2.global(26, "wp_drm_lease_device_v1", 1)
[ 949089.848] wl_registry@2.global(27, "zwlr_export_dmabuf_manager_v1", 1)
[ 949089.851] wl_registry@2.global(28, "zwlr_screencopy_manager_v1", 3)
[ 949089.853] wl_registry@2.global(29, "zwlr_data_control_manager_v1", 2)
[ 949089.856] wl_registry@2.global(30, "zwp_primary_selection_device_manager_v1", 1)
[ 949089.858] wl_registry@2.global(31, "wp_viewporter", 1)
[ 949089.861] wl_registry@2.global(32, "wp_single_pixel_buffer_manager_v1", 1)
[ 949089.864] wl_registry@2.global(33, "zxdg_exporter_v1", 1)
[ 949089.867] wl_registry@2.global(34, "zxdg_importer_v1", 1)
[ 949089.869] wl_registry@2.global(35, "zxdg_exporter_v2", 1)
[ 949089.872] wl_registry@2.global(36, "zxdg_importer_v2", 1)
[ 949089.874] wl_registry@2.global(37, "xdg_activation_v1", 1)
[ 949089.877] wl_registry@2.global(38, "zwp_virtual_keyboard_manager_v1", 1)
[ 949089.879] wl_registry@2.global(39, "zwlr_virtual_pointer_manager_v1", 2)
[ 949089.882] wl_registry@2.global(40, "zwlr_input_inhibit_manager_v1", 1)
[ 949089.885] wl_registry@2.global(41, "zwp_keyboard_shortcuts_inhibit_manager_v1", 1)
[ 949089.887] wl_registry@2.global(42, "wl_seat", 8)
[ 949089.891]  -> wl_registry@2.bind(42, "wl_seat", 6, new id [unknown]@11)
[ 949089.901] wl_registry@2.global(43, "zwp_pointer_gestures_v1", 3)
[ 949089.903] wl_registry@2.global(44, "wl_output", 4)
[ 949089.907]  -> wl_registry@2.bind(44, "wl_output", 3, new id [unknown]@12)
[ 949089.914] wl_registry@2.global(45, "wl_output", 4)
[ 949089.917]  -> wl_registry@2.bind(45, "wl_output", 3, new id [unknown]@13)
[ 949089.921] wl_callback@3.done(14673)
[ 949089.924]  -> wl_display@1.sync(new id wl_callback@3)
[ 949089.961] wl_display@1.delete_id(3)
[ 949089.963] wl_shm@4.format(0)
[ 949089.970] wl_shm@4.format(1)
[ 949089.972] wl_shm@4.format(875709016)
[ 949089.974] wl_shm@4.format(875708993)
[ 949089.976] wl_shm@4.format(875710274)
[ 949089.978] wl_shm@4.format(842094674)
[ 949089.980] wl_shm@4.format(842088786)
[ 949089.982] wl_shm@4.format(892426322)
[ 949089.984] wl_shm@4.format(892420434)
[ 949089.986] wl_shm@4.format(909199186)
[ 949089.988] wl_shm@4.format(808665688)
[ 949089.990] wl_shm@4.format(808665665)
[ 949089.991] wl_shm@4.format(1211384408)
[ 949089.993] wl_shm@4.format(1211384385)
[ 949089.995] wl_shm@4.format(942948952)
[wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting.
zsh: IOT instruction  RUST_BACKTRACE=1 WAYLAND_DEBUG=1 cargo run
```

**Comment by MultisampledNight** [comment] 2023-01-07 09:06
Thanks for reporting! This is a duplicate of #1356, so I'll close this to keep discussion at one place.

**Closed by MultisampledNight** 2023-01-07 09:06 UTC
Labels: bug
