### ISSUE TITLE
[macOS] neovide command-line opens each file in duplicated tabs. 

### ISSUE THREAD

**Issue by s-daveb** [neovide/neovide#2652] opened 2024-06-12 15:05 UTC
**Describe the bug**
Using the default configuration (no `config.toml`), when I open multiple files on the command-line, I get two tabs for each file.

**To Reproduce**
1. Install neovide `brew install --cask neovide``
2. Don't create a config.toml
3. In Terminal, go to a folder and run `neovide --fork include/*.h` or some other command that opens multiple files.

**Expected behavior**
Each file is opened in as ingle tab

**Screenshots**
![image](https://github.com/neovide/neovide/assets/2100425/34b95b44-7a4b-4563-bb53-b5607d9b2506)

**Desktop (please complete the following information):**
 - OS: macOS 13.6.7
 - Neovide: v0.3.1
 - Neovim: 
   - NVIM v0.10.0
   - Build type: Release
   - LuaJIT 2.1.1716656478

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

[neovide_rCURRENT.log](https://github.com/user-attachments/files/15807096/neovide_rCURRENT.log)

**Additional context**
I've tried to run the application with `-- --clean` at the end, and I get the same behavior.

**Comment by fredizzimo** [comment] 2024-06-12 15:08
I'm closing this as a duplicate of
* https://github.com/neovide/neovide/issues/2609

**Closed by fredizzimo** 2024-06-12 15:08 UTC
Labels: bug
