### ISSUE TITLE
can not open in terminal

### ISSUE THREAD

**Issue by ystyle** [neovide/neovide#1938] opened 2023-07-18 03:47 UTC
**Describe the bug**
can not open in terminal

**To Reproduce**
1. Go to a terminal
2. exec `neovide .`

**Expected behavior**

**Screenshots**
![image](https://github.com/neovide/neovide/assets/4478635/a8ae72dc-a54d-4c11-a7ea-32df559b2a13)

**Desktop (please complete the following information):**
 - OS: archlinux
 - Neovide Version 0.10.4
 - Neovim Version 0.9.1

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/12075692/neovide_rCURRENT.log)

**Additional context**

**Comment by fredizzimo** [comment] 2023-07-18 06:50
I think the issue is the same as reported here https://github.com/neovide/neovide/pull/1870#discussion_r1258416860. But unfortunately I don't know the root cause for it and a better fix than to disable the transparency completely.

Could you also provide the output from `glxinfo`?

**Comment by ystyle** [comment] 2023-07-18 07:29
> I think the issue is the same as reported here [#1870 (comment)](https://github.com/neovide/neovide/pull/1870#discussion_r1258416860). But unfortunately I don't know the root cause for it and a better fix than to disable the transparency completely.我认为这个问题与此处报告的问题相同#1870（评论）。但不幸的是，我不知道其根本原因，也不知道比完全禁用透明度更好的解决方法。
> 
> Could you also provide the output from `glxinfo`?您还可以提供 `glxinfo` 的输出吗？

```shell
 ystyle@Archlinux  ~  glxinfo
name of display: :0
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: undefined symbol: _ZTIN4llvm19RTDyldMemoryManagerE, version LLVM_15 (search paths /usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: undefined symbol: _ZTIN4llvm19RTDyldMemoryManagerE, version LLVM_15 (search paths /usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: undefined symbol: _ZTIN4llvm19RTDyldMemoryManagerE, version LLVM_15 (search paths /usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  152 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  40
  Current serial number in output stream:  41
```

**Comment by fredizzimo** [comment] 2023-07-18 07:50
It looks like you don’t have `mesa` installed correctly. https://wiki.archlinux.org/title/OpenGL

**Comment by ystyle** [comment] 2023-07-18 07:54
> It looks like you don’t have `mesa` installed correctly. https://wiki.archlinux.org/title/OpenGL您似乎没有正确安装 `mesa` 。 https://wiki.archlinux.org/title/OpenGL

I just found the actual problem. I have a software that must configure LD_LIBRARY_PATH to specify its own lib directory. There are llvm-related libraries in it. My operating system is archlinux. Its library conflicts with the llvm version of the archlinux library, resulting in this question.

**Comment by MultisampledNight** [comment] 2023-07-18 21:25
Modifying `LD_LIBRARY_PATH` can yield pretty much any behavior that's not really in control of the application ran, and if it's set globally (which is what it looks like in your case), that also means that _any_ program run on your PC is subject to that modified library path, possibly resulting in potentially unwanted or even adversary behavior if the replacement libraries are not further audited. Without info on the exact environment, I don't think there's much that can be done on Neovide's side.

**Comment by fredizzimo** [comment] 2023-07-31 08:37
Closing this, as it's not a Neovide bug.

The correct way to fix this is to run `make install` or similar to a custom directoy, which typically ensures that the libraries will be read from there, rather than the system.

If that's not possible, the second best option to set rpath as an option to the linker linker  `-Wl,-rpath,./path/to/lvm`. And if that's not possible you can use patchelf https://man.archlinux.org/man/extra/patchelf/patchelf.1.en, and call `--add-rpath`, or `-set-rpath` if you need a specific order.

**Closed by fredizzimo** 2023-07-31 08:37 UTC
Labels: bug
