### ISSUE TITLE
Multigrid floating windows misplaced

### ISSUE THREAD

**Issue by anson-val** [neovide/neovide#1186] opened 2022-01-28 10:07 UTC
**Describe the bug**
When multigrid is enabled, some floating windows would be badly positioned. This would not occur when multigrid is off. The suggestion list from CoC is overlapped with another window showing the details of each suggestion.
**To Reproduce**
1. Have CoC installed
2. call the suggestion list
3. The details floating window and the suggestion list are overlapped.

**Expected behavior**
Multigrid off:
![image](https://user-images.githubusercontent.com/54179931/151526698-7df36131-3071-401c-8834-dbddb31e7fdb.png)

**Screenshots**
Multigrid on:
![image](https://user-images.githubusercontent.com/54179931/151526474-5331b691-ace2-4176-942c-c6a8d8329f91.png)
**Desktop (please complete the following information):**

 - OS: Windows 11
 - Neovide Version 0.8.0 
 - Neovim Version 0.7.0 nightly

**Please run `neovide --log` and paste the contents of the `.log` file here:**
(Tried to run `neovide --log`, no log file was generated.)

**Comment by fredizzimo** [comment] 2022-02-05 12:54
https://github.com/neovide/neovide/issues/1198 and https://github.com/neovide/neovide/issues/1197 also seem to be caused by misplaced and wrongly sized floating windows. But there it's nowhere as bad as this.

**Comment by zirco740** [comment] 2022-02-05 14:01
> #1198 and #1197 also seem to be caused by misplaced and wrongly sized floating windows. But there it's nowhere as bad as this.

So currently there is no fix for that?

**Comment by fredizzimo** [comment] 2022-02-05 14:04
Don't worry, this will be fixed. But no one has had time to properly look at the code yet, to determine exactly what goes wrong.

**Comment by zirco740** [comment] 2022-02-05 14:47
> Don't worry, this will be fixed. But no one has had time to properly look at the code yet, to determine exactly what goes wrong.

Okay, I will keep my neovide updated.

**Comment by fredizzimo** [comment] 2022-02-05 14:52
Let’s keep this open until it’s fixed

**Comment by fredizzimo** [comment] 2023-03-05 22:04
I think this fixes it https://github.com/neovide/neovide/pull/1786

**Comment by Kethku** [comment] 2023-04-09 07:22
Closed as I think this is fixed because #1786 merged

**Closed by Kethku** 2023-04-09 07:22 UTC
Labels: bug
