### ISSUE TITLE
Could not parse event from neovim: invalid string format []

### ISSUE THREAD

**Issue by JMarkin** [neovide/neovide#1809] opened 2023-03-20 07:59 UTC
**Describe the bug**
I use https://github.com/klen/nvim-config-local for local config.
After changed config and trusted it neovide crashed.

**To Reproduce**
1. Install plugin https://github.com/klen/nvim-config-local and setup like readme
2. Create .vimrc.lua
3. Add line like `local a = 1`
4. Trust it

**Expected behavior**
Local config changes without crash

**Screenshots**
I recorded screen for explain
https://disk.yandex.ru/i/SzeA10pisat4UQ

**Desktop (please complete the following information):**
 - OS: macOS 13.2.1, m1 pro
 - Neovide Version: current main branch
 - Neovim Version: v0.9.0-dev-1252+g5726f33e8

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
Log file: https://disk.yandex.ru/d/zUlxFqb3deRtpg

**Additional context**

**Comment by 54corbin** [comment] 2023-04-06 02:09
+1
Whenever I press 3yy the neovide gonna crash with the same error message：
`neovide --nofork
2023-04-06 10:04:35.292 neovide[24380:100970] TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit
ERROR [neovide::error_handling] Could not parse event from neovim: invalid string format []
thread 'tokio-runtime-worker' panicked at 'Could not parse event from neovim: invalid string format []', src/error_handling.rs:5:5
stack backtrace:
   0:        0x102222b10 - __mh_execute_header
   1:        0x102182ca8 - __mh_execute_header
   2:        0x10220bbf8 - __mh_execute_header
   3:        0x102217984 - __mh_execute_header
   4:        0x102217658 - __mh_execute_header
   5:        0x102218248 - __mh_execute_header
   6:        0x102223144 - __mh_execute_header
   7:        0x1022230bc - __mh_execute_header
   8:        0x102217e1c - __mh_execute_header
   9:        0x102602228 - __mh_execute_header
  10:        0x10212dc58 - __mh_execute_header
  11:        0x10212dbfc - __mh_execute_header
  12:        0x1020f0e18 - __mh_execute_header
  13:        0x1020e2510 - __mh_execute_header
  14:        0x1021dedc0 - __mh_execute_header
  15:        0x1020e9964 - __mh_execute_header
  16:        0x1022547ec - __mh_execute_header
  17:        0x102259168 - __mh_execute_header
  18:        0x10224899c - __mh_execute_header
  19:        0x10224aeb8 - __mh_execute_header
  20:        0x10221b27c - __mh_execute_header
  21:        0x192c1026c - __pthread_deallocate
ERROR [neovide::bridge] Error joining IO loop: 'task 11 panicked'`

**Comment by chaozwn** [comment] 2023-05-03 13:45
me,too . when i use `d2j`
2023-05-03 13:43:38 - Neovide panicked with the message 'Could not parse event from neovim: invalid string format 79'. (File: src/error_handling.rs; Line: 5, Column: 5)
   0: __mh_execute_header
   1: __mh_execute_header
   2: __mh_execute_header
   3: __mh_execute_header
   4: __mh_execute_header
   5: __mh_execute_header
   6: __mh_execute_header
   7: __mh_execute_header
   8: __mh_execute_header
   9: __mh_execute_header
  10: __mh_execute_header
  11: __mh_execute_header
  12: __mh_execute_header
  13: __mh_execute_header
  14: __mh_execute_header
  15: __mh_execute_header
  16: __mh_execute_header
  17: __pthread_start

**Comment by Tanish2002** [comment] 2023-06-13 15:53
+1
I was just trying to do `ci"` inside this file: http://0x0.st/Hc0P.html and neovide crashed with this output:
```
ERROR [neovide::error_handling] Could not parse event from neovim: invalid string format []
Neovide panicked with the message 'Could not parse event from neovim: invalid string format []'. (File: s
This is a bug and we would love for it to be reported to https://github.com/neovide/neovide/issues

Backtrace saved to neovide_backtraces.log!
ERROR [neovide::bridge] Error joining IO loop: 'task 13 panicked'
```
here is the backtraces log generated: http://0x0.st/Hc0Z.txt

**Comment by fredizzimo** [comment] 2023-06-14 21:49
This looks like a duplicate of https://github.com/neovide/neovide/issues/1871. Can you run again with Neovide master, it should have better error reporting to figure out what's wrong.

**Closed by fredizzimo** 2023-06-14 21:49 UTC
Labels: bug
