### ISSUE TITLE
Neovide crashes on delete lines with [ d-[ ]

### ISSUE THREAD

**Issue by krapjost** [neovide/neovide#1737] opened 2023-01-13 05:47 UTC
**Describe the bug**

**To Reproduce**
1. Go to any files
2. Delete multiple lines by pressing "d [ "
3. Crash

**Expected behavior**
Should not be crashed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Arch x86_64]
 - Neovide Version [0.10.3]
 - Neovim Version [0.9.0]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

> TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(WindowViewport { grid: 2, top_line: 0.0, bottom_line: 48.0, current_line: 13.0, current_column: 0.0, line_count: Some(811.0) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(Flush)
TRACE [neovide::editor] viewport event received before window initialized
TRACE [neovide::editor] Image flushed
TRACE [neovide::channel_utils] alloc::vec::Vec<neovide::renderer::DrawCommand> [UpdateCursor(Cursor { grid_position: (3, 19), parent_window_id: 1, shape: Horizontal, cell_percentage: Some(0.2), blinkwait: Some(0), blinkon: Some(0), blinkoff: Some(0), style: Some(Style { colors: Colors { foreground: None, background: Some(Color4f { r: 1.0, g: 0.49411765, b: 0.7137255, a: 1.0 }), special: None }, reverse: false, italic: false, bold: false, strikethrough: false, blend: 0, underline: None }), enabled: true, double_width: false, grid_cell: (" ", None) })]
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
ERROR [neovide::error_handling] Could not parse event from neovim: invalid string format []
ERROR [neovide::bridge] Error joining IO loop: 'task 13 panicked'
INFO [neovide::running_tracker] Quit neovim processed failed
DEBUG [neovide::settings::window_geometry] Saved Window Settings: {"window":{"Windowed":{"position":{"x":0,"y":0},"size":{"width":86,"height":48}}}}

**Additional context**

**Comment by MultisampledNight** [comment] 2023-02-05 13:32
Thanks for the report! I can't seem to reproduce this though, Neovim just expects more input after `d[` for me. Could you share your full configuration (likely `init.vim`) and how you mapped `[`?

**Comment by infinite-ops** [comment] 2023-02-05 22:43
I have a similar issue, except it is related to having noice.nvim installed/enabled. dG triggers the crash too.

Disabling/removing noice.nvim for me stops it crashing for both.

**Comment by ryo33** [comment] 2023-02-18 13:36
https://github.com/neovide/neovide/issues/1751#issuecomment-1435670801 This may help to investigate this issue.

**Comment by xbladesub** [comment] 2023-02-26 12:51
yes, it's `Noice` issue. Sad, it's really nice plugin...

**Comment by atriw** [comment] 2023-03-12 01:56
FYI, there is no need to remove noice.nvim entirely to stop this crash.
```lua
require('noice.nvim').setup({
  messages = {
    view = false,
  },
})
```
This workaround stops the crash, at least for me. But the downside is some messages like "2 more lines" will not be displayed.

**Comment by luisiacc** [comment] 2023-04-23 22:37
> Thanks for the report! I can't seem to reproduce this though, Neovim just expects more input after `d[` for me. Could you share your full configuration (likely `init.vim`) and how you mapped `[`?

@MultisampledNight I filed a buf report with a sample init.lua file and reproduction steps, I believe it's the same problem as this, so you can close mine and keep it as reference.

https://github.com/neovide/neovide/issues/1847

**Comment by fredizzimo** [comment] 2023-06-22 08:45
Closing this, since we already have #1751, which in turn is a bug in Noice, but Neovim does not offer an alternative at the moment  see https://github.com/neovim/neovim/issues/22344  

Setting `messages { enabled = false }` or disabling noice is the correct way to fix this at the moment.

**Closed by fredizzimo** 2023-06-22 08:45 UTC
Labels: bug
