### ISSUE TITLE
Splits as sepreate windows

### ISSUE THREAD

**Issue by Suyashtnt** [neovide/neovide#1349] opened 2022-06-12 16:35 UTC
**Is your feature request related to a problem? Please describe. **
Whenever I want to add apps whenever I'm working with neovim, it's always a pain to get my splits working with the app layouts

**Describe the solution you'd like**
the ability to use a flag or a config variable to allow splits as entirely separate windows

**Describe alternatives you've considered**
There are no real alternatives to add windows into splits

**Additional context**
I first saw this idea at https://github.com/glacambre/nwin

**Comment by MultisampledNight** [comment] 2022-06-12 18:50
This would yet another time require an IPC structure, which Neovide doesn't have (yet, don't know if anyone wants to do that).

But there are other programs kind of providing that: Specifically, [nvr](https://github.com/mhinz/neovim-remote). You could launch a Neovim instance through nvr, and make every Neovide instance you open connect to it. Afterwards, you could open each buffer you'd like to have in a separate window in that separate window. That should be pretty automatizable with the `WinEnter`/`BufWinEnter` autocmd.

**Comment by fredizzimo** [comment] 2024-01-13 07:20
Closing as a duplicate of 
* https://github.com/neovide/neovide/issues/1332

Specifically see this comment https://github.com/neovide/neovide/issues/1332#issuecomment-1802965871

**Closed by fredizzimo** 2024-01-13 07:20 UTC
Labels: enhancement

**Comment by axelkar** [comment] 2025-08-04 19:41
So this could be implemented by overriding the split and vsplit commands and keybinds (how about Lua APIs?) and using IPC with your window manager and Neovide?

Context: I use a scrollable-tiling Wayland compositor named [Niri](https://github.com/YaLTeR/niri) and open too many splits on a laptop screen. Scrollable-tiling works perfectly until it meets Neovim!
