### ISSUE TITLE
Nerd font characters cannot be displayed in Windows

### ISSUE THREAD

**Issue by weilin-ge** [neovide/neovide#1881] opened 2023-06-01 14:52 UTC
**Describe the bug**
When I open Neovide on the Windows platform, some nerd font characters cannot be displayed. I have installed `Hack Nerd Font` and configured `guifont=Hack\ Nerd\ Font:h11` in init.lua file. These characters can be displayed correctly in the Windows Terminal.

**To Reproduce**
1. Open neovide
2. Wait nvim-cmp and lsp loaded
3. Input some characters

**Expected behavior**
Display these characters correctly.

**Screenshots**
![In Windows Termial](https://github.com/neovide/neovide/assets/53041709/a8cc4413-1a2a-4a33-ae41-bccdd4a69b2e)
![In Neovide](https://github.com/neovide/neovide/assets/53041709/1cfae807-aa90-4d9f-89b3-8eceda2001f3)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Neovide Version release 0.10.4
 - Neovim Version 0.9.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/11626524/neovide_rCURRENT.log)

**Additional context**
When I launch Neovide with the `--wsl` option, it can display these characters correctly.
![Working in WSL](https://github.com/neovide/neovide/assets/53041709/5330b85d-8830-4beb-b41f-2b3f45627fe2)
I'm not sure whether it's a bug.
Please help me analyze it, thank you！

**Comment by theangryangel** [comment] 2023-06-13 12:54
Nerdfonts 3.0.0 introduced some major breaking changes regarding the Material Design Icons codepoints. Might be worth checking that first if you haven't.

**Comment by fredizzimo** [comment] 2023-07-30 12:09
I did not see this issue until now. But it’s a duplicate of the newer https://github.com/neovide/neovide/issues/1944, which has more disussion. So closing this as a duplicate.

**Closed** 2023-07-30 12:11 UTC
Labels: bug
