### ISSUE TITLE
OpenGL context creation failure

### ISSUE THREAD

**Issue by alexmozaidze** [neovide/neovide#2283] opened 2024-01-18 05:49 UTC
# Bug description

Neovide fails to create OpenGL context and, thus, the window. After the thread handling graphics panics, Neovide hangs in the background, requiring manual termination.

## Reproduction steps

1. Run Neovide
2. No window :(

## Expected behavior

Creates OpenGL context and the window normally, but if it fails, terminates the entire program instead of hanging in the background.

## Desktop

 - OS: Void Linux
 - CPU: Pentium(R) Dual-Core
 - Neovide 0.12.1
 - Neovim v0.10.0-dev-2074+g786089013 (though, I don't think it matters)

## Logs

> [!NOTE]\
> All the output was from the dev build of Neovide (without `--release`) in order to get maximum info.

<details>
<summary>Backtrace</summary>

```rust
2024-01-18 05:24:08 - Neovide panicked with the message 'Failed to create OpenGL context: Error { raw_code: Some(170), raw_os_message: Some("GLXBadFBConfig"), kind: BadConfig }'. (File: src/renderer/opengl.rs; Line: 119, Column: 10)
   0: neovide::main::{{closure}}
             at src/main.rs:78:25
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/alloc/src/boxed.rs:1999:9
      std::panicking::rust_panic_with_hook
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:709:13
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:597:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/sys_common/backtrace.rs:151:18
   4: rust_begin_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:593:5
   5: core::panicking::panic_fmt
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/panicking.rs:67:14
   6: core::result::unwrap_failed
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/result.rs:1651:5
   7: core::result::Result<T,E>::expect
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/result.rs:1033:23
   8: neovide::renderer::opengl::build_context
             at src/renderer/opengl.rs:118:19
   9: neovide::window::window_wrapper::WinitWindowWrapper::new
             at src/window/window_wrapper.rs:86:32
  10: neovide::window::main_loop
             at src/window/mod.rs:335:30
  11: neovide::main
             at src/main.rs:98:13
  12: core::ops::function::FnOnce::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:250:5
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/sys_common/backtrace.rs:135:18
  14: std::rt::lang_start::{{closure}}
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/rt.rs:166:18
  15: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/core/src/ops/function.rs:284:13
      std::panicking::try::do_call
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:500:40
      std::panicking::try
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:464:19
      std::panic::catch_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:500:40
      std::panicking::try
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panicking.rs:464:19
      std::panic::catch_unwind
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/panic.rs:142:14
      std::rt::lang_start_internal
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/rt.rs:148:20
  16: std::rt::lang_start
             at /rustc/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/library/std/src/rt.rs:165:17
  17: main
  18: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  19: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:360:3
  20: _start
             at /builddir/glibc-2.38/csu/../sysdeps/x86_64/start.S:115
```

</details>

<details>
<summary>OpenGL info</summary>

```sh
$ glxinfo | grep "OpenGL"
OpenGL vendor string: Mesa Project
OpenGL renderer string: i915 (chipset: G33)
OpenGL version string: 2.1 Mesa 23.3.1
OpenGL shading language version string: 1.20
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 23.3.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:
```

</details>

**Comment by fredizzimo** [comment] 2024-01-18 09:37
This is a duplicate of
* https://github.com/neovide/neovide/issues/2068

We officially don't support older opengl versions than 3.3(released in 2010). But, you can try the workaround in this message https://github.com/neovide/neovide/issues/2068#issuecomment-1754110369

**Closed by fredizzimo** 2024-01-18 09:37 UTC
Labels: bug

**Comment by danielmain** [comment] 2024-09-20 08:19
Hi unfortunately with higher OpenGL version I still face the issue 'Failed to create Window: Error { raw_code: None, raw_os_message: None, kind: NotSupported("provided display handle is not supported") }'. (File: src/renderer/opengl.rs; Line: 254, Column: 10)

I have:
- Asahi Linux (Fedora) `6.10.9-401.asahi.fc40.aarch64+16k`
- OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.2.0-asahi20240727

my neovide_backtraces.log looks like this:

```
2024-09-20 08:07:46 - Neovide panicked with the message 'Failed to create Window: Error { raw_code: None, raw_os_message: None, kind: NotSupported("provided display handle is not supported") }'. (File: src/renderer/opengl.rs; Line: 254, Column: 10)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: neovide::renderer::opengl::build_window
   8: neovide::window::window_wrapper::WinitWindowWrapper::try_create_window
   9: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::pump_events
  10: neovide::main
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: main
  13: __libc_start_call_main
  14: __libc_start_main@@GLIBC_2.34
  15: _start

2024-09-20 08:08:48 - Neovide panicked with the message 'Failed to create Window: Error { raw_code: None, raw_os_message: None, kind: NotSupported("provided display handle is not supported") }'. (File: src/renderer/opengl.rs; Line: 254, Column: 10)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: neovide::renderer::opengl::build_window
   8: neovide::window::window_wrapper::WinitWindowWrapper::try_create_window
   9: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::pump_events
  10: neovide::main
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: main
  13: __libc_start_call_main
  14: __libc_start_main@@GLIBC_2.34
  15: _start

2024-09-20 08:09:40 - Neovide panicked with the message 'Failed to create Window: Error { raw_code: None, raw_os_message: None, kind: NotSupported("provided display handle is not supported") }'. (File: src/renderer/opengl.rs; Line: 254, Column: 10)
   0: neovide::main::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys_common::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::result::unwrap_failed
   7: neovide::renderer::opengl::build_window
   8: neovide::window::window_wrapper::WinitWindowWrapper::try_create_window
   9: winit::platform_impl::platform::wayland::event_loop::EventLoop<T>::pump_events
  10: neovide::main
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: main
  13: __libc_start_call_main
  14: __libc_start_main@@GLIBC_2.34
  15: _start
```

I appreciate your help :)
