### ISSUE TITLE
Neovide crash when scrolling through large amount of files

### ISSUE THREAD

**Issue by kishikaisei** [neovide/neovide#1353] opened 2022-06-15 20:46 UTC
**Describe the bug**
When scrolling through a large amount of files, neovide crashes, tried in a terminal (wezterm) and a gui neovim (Nvy) and could not reproduce.

**To Reproduce**
1. Open neovide, and using telescope run through a large amount of files
2. keep running for a while
3. Neovide Crashes to desktop

**Expected behavior**
Neovide could stutter, or lag, but not crash

**Screenshots**

https://user-images.githubusercontent.com/1894123/173922882-bb6e98ea-e096-462b-9901-dee8057c5047.mp4

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Neovide Version 0.9.0
 - Neovim Version 0.8.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

https://gist.github.com/kishikaisei/51584ef64105c414aeac167076e4c9a2

**Additional context**

**Comment by MultisampledNight** [comment] 2022-06-15 21:04
Can't reproduce with

```vim
call plug#begin("~/.local/share/nvim/vim-plug")

Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'

call plug#end()
```

being my config and using vim-plug, so either that's a platform issue (I'm on Linux) or a specific configuration scenario which causes that. Could you share your relevant/reproducable configuration?

**Comment by Kethku** [comment] 2023-04-09 07:30
CLosing for lack of reproduction

**Closed by Kethku** 2023-04-09 07:30 UTC
Labels: bug
