### ISSUE TITLE
Option to specify ligature set

### ISSUE THREAD

**Issue by feature-not-a-bug** [neovide/neovide#1360] opened 2022-06-19 20:45 UTC
**Describe the solution you'd like**
It would be nice to be able to specify the ligature set that's being used within a config.

VSCode supports this through an ` "editor.fontLigatures"` setting. What I can do is set this as `true` or add a specific ligation set like `'dlig'`

Specifically, what I'm looking for is the ability to change ligations based on the language by specifying it an ftplugin file so that the ligations are contextually loaded, say for Haskell using the Iosevka font https://github.com/be5invis/Iosevka/blob/master/doc/language-specific-ligation-sets.md

**Additional context**
Swash seems to support this through their feature tags. I'm not sure if this would allow language specific sets like in the link above, but having the option to choose between `dlig` and `calt` would be a big help.

https://github.com/dfrg/swash/blob/master/src/feature/util.rs

**Comment by feature-not-a-bug** [comment] 2022-06-20 17:10
Another example for how I have Haskell ligatures set up in VSCode: `"editor.fontLigatures": "'calt' off, 'HSKL' on"`.

**Comment by fredizzimo** [comment] 2023-08-07 16:18
There's a PR open for this https://github.com/neovide/neovide/pull/1920

**Comment by fredizzimo** [comment] 2023-08-07 16:31
Duplicate of https://github.com/neovide/neovide/issues/1249

**Closed by fredizzimo** 2023-08-07 16:31 UTC
Labels: enhancement
