### ISSUE TITLE
Crash when pasting yank buffer into command mode when running /w --multigrid on MacOS

### ISSUE THREAD

**Issue by DominicAnelloSonos** [neovide/neovide#1871] opened 2023-05-19 14:24 UTC
**Describe the bug**
When attempting to paste into the command buffer via `C-r` Neovide crashes.

**To Reproduce**
1. Open a file with Neovide
2. Yank some text with `yw`
3. Press `:`
4. Start a command, e.g. `%s/`
5. Press `C-r`
6. Press `"`
7. Crash

Also tried to use the "replace word" idiom with `:%s/<C-r><C-w>` and it also resulted in a crash.  This works with command-line `nvim`

**Expected behavior**
Yanked text is pasted into the command line.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 13.3.1
 - Neovide Version 0.10.4
 - Neovim Version 0.8.3, also tried upgrading to 0.9.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
```
2023-05-19 14:21:01 - Neovide panicked with the message 'Could not parse event from neovim: invalid u64 format -1'. (File: src/error_handling.rs; Line: 5, Column: 5)
   0: __mh_execute_header
   1: __mh_execute_header
   2: __mh_execute_header
   3: __mh_execute_header
   4: __mh_execute_header
   5: __mh_execute_header
   6: __mh_execute_header
   7: __mh_execute_header
   8: __mh_execute_header
   9: __mh_execute_header
  10: __mh_execute_header
  11: __mh_execute_header
  12: __mh_execute_header
  13: __mh_execute_header
  14: __mh_execute_header
  15: __mh_execute_header
  16: __mh_execute_header
  17: __pthread_joiner_wake
```

```
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(WindowViewport { grid: 2, top_line: 1.0, bottom_line: 32.0, current_line: 24.0, current_column: 26.0, line_count: Some(31.0), scroll_delta: Some(0.0) })
ERROR [neovide::error_handling] Could not parse event from neovim: invalid u64 format -1
ERROR [neovide::bridge] Error joining IO loop: 'task 13 panicked'
INFO [neovide::running_tracker] Quit neovim processed failed
DEBUG [neovide::settings::window_geometry] Saved Window Settings: {"window":{"Windowed":{"position":{"x":563,"y":25},"size":{"width":156,"height"
```

**Additional context**

**Comment by fredizzimo** [comment] 2023-05-19 14:58
The error you are seeing here is consistent with running Neovide < 0.10.4 combined with Neovim 0.9.0, but that does not match the versions in your description.

There might still be a crash, but a different one than the logs you pasted.

Could you try to reproduce it using Neovide 10.0.4 and Neovim 0.9.0?

**Comment by DominicAnelloSonos** [comment] 2023-05-22 16:24
Ahh, looking at my aliases, looks like I am running with `--multigrid`, so looks like that is the culprit.  Removing that flag fixes the issue.

In case it is helpful, here is the repro with `--multigrid`:

```
$ nvim --version
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3

$ /Applications/Neovide.app/Contents/MacOS/neovide --version
neovide 0.10.4

$ echo foo > test.txt

$ /Applications/Neovide.app/Contents/MacOS/neovide test.txt --multigrid --log
```

Crash induced with command `:%s/<C-rw>`

**neovide_backtraces.log**
```
2023-05-22 16:13:33 - Neovide panicked with the message 'Could not parse event from neovim: invalid u64 format -1'. (File: src/error_handling.rs; Line: 5, Column: 5)
   0: __mh_execute_header
   1: __mh_execute_header
   2: __mh_execute_header
   3: __mh_execute_header
   4: __mh_execute_header
   5: __mh_execute_header
   6: __mh_execute_header
   7: __mh_execute_header
   8: __mh_execute_header
   9: __mh_execute_header
  10: __mh_execute_header
  11: __mh_execute_header
  12: __mh_execute_header
  13: __mh_execute_header
  14: __mh_execute_header
  15: __mh_execute_header
  16: __mh_execute_header
  17: __pthread_joiner_wake
```

**neovide_rCURRENT.log**
```
TRACE [neovide] Neovide version: 0.10.4
DEBUG [neovide::bridge::command] Running which command: "/opt/homebrew/bin/bash" "-c" "which nvim"
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "/opt/homebrew/bin/bash" "-c" "/opt/homebrew/bin/nvim --embed -p test.txt", kill_on_drop: false }
INFO [neovide::bridge::setup] Neovide registered to nvim with channel id 1
INFO [neovide::bridge] Neovim process attached
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: ArabicShape(true) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: AmbiWidth("single") })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: Emoji(true) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: GuiFont("") })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: GuiFontWide("") })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: LineSpace(0) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: Unknown("mousefocus", Boolean(false)) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: Unknown("mousemoveevent", Boolean(false)) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: Pumblend(0) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: ShowTabLine(1) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: TermGuiColors(true) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: Unknown("ttimeout", Boolean(true)) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: Unknown("ttimeoutlen", Integer(PosInt(50))) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: Unknown("verbose", Integer(PosInt(0))) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: Unknown("ext_linegrid", Boolean(true)) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: Unknown("ext_multigrid", Boolean(true)) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: Unknown("ext_hlstate", Boolean(false)) })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(OptionSet { gui_option: Unknown("ext_termcolors", Boolean(false)) })
TRACE [neovide::editor] Option set ArabicShape(true)
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(DefaultColorsSet { colors: Colors { foreground: Some(Color4f { r: 1.0, g: 1.0, b: 1.0, a: 1.0 }), background: Some(Color4f { r: 0.0, g: 0.0, b: 0.0, a: 1.0 }), special: Some(Color4f { r: 1.0, g: 0.0, b: 0.0, a: 1.0 }) } })
TRACE [neovide::editor] Option set AmbiWidth("single")
TRACE [neovide::editor] Option set Emoji(true)
TRACE [neovide::editor] Option set GuiFont("")
TRACE [neovide::editor] Option set GuiFontWide("")
TRACE [neovide::editor] Option set LineSpace(0)
TRACE [neovide::editor] Option set Unknown("mousefocus", Boolean(false))
TRACE [neovide::editor] Option set Unknown("mousemoveevent", Boolean(false))
TRACE [neovide::editor] Option set Pumblend(0)
TRACE [neovide::editor] Option set ShowTabLine(1)
TRACE [neovide::editor] Option set TermGuiColors(true)
TRACE [neovide::editor] Option set Unknown("ttimeout", Boolean(true))
TRACE [neovide::editor] Option set Unknown("ttimeoutlen", Integer(PosInt(50)))
TRACE [neovide::editor] Option set Unknown("verbose", Integer(PosInt(0)))
TRACE [neovide::editor] Option set Unknown("ext_linegrid", Boolean(true))
TRACE [neovide::editor] Option set Unknown("ext_multigrid", Boolean(true))
TRACE [neovide::editor] Option set Unknown("ext_hlstate", Boolean(false))
TRACE [neovide::editor] Option set Unknown("ext_termcolors", Boolean(false))
...
TRACE [neovide::editor] Image flushed
TRACE [neovide::channel_utils] alloc::vec::Vec<neovide::renderer::DrawCommand> [UpdateCursor(Cursor { grid_position: (4, 40), parent_window_id: 1, shape: Block, cell_percentage: Some(0.0), blinkwait: Some(0), blinkon: Some(0), blinkoff: Some(0), style: None, enabled: false, double_width: false, grid_cell: ("\u{f0219}", Some(Style { colors: Colors { foreground: Some(Color4f { r: 0.5372549, g: 0.8784314, b: 0.31764707, a: 1.0 }), background: Some(Color4f { r: 0.17254902, g: 0.19607843, b: 0.23529412, a: 1.0 }), special: None }, reverse: false, italic: false, bold: false, strikethrough: false, blend: 0, underline: None })) })]
TRACE [neovide::redraw_scheduler] Next frame queued
TRACE [neovide::window] Settings geometry PhysicalSize { width: 156, height: 41 }
TRACE [neovide::window] Inner size: PhysicalSize { width: 1560, height: 820 }
TRACE [neovide::bridge::handler] Neovim notification: "redraw"
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(BusyStop)
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(GridLine { grid: 3, row: 0, column_start: 0, cells: [GridLineCell { text: " ", highlight_id: Some(1), repeat: Some(4) }] })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(WindowClose { grid: 5 })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(Destroy { grid: 5 })
TRACE [neovide::editor] Cursor on
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(GridLine { grid: 3, row: 0, column_start: 4, cells: [GridLineCell { text: "\"", highlight_id: Some(1), repeat: None }] })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(GridLine { grid: 3, row: 0, column_start: 4, cells: [GridLineCell { text: " ", highlight_id: Some(1), repeat: Some(1) }] })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(GridLine { grid: 3, row: 0, column_start: 0, cells: [GridLineCell { text: ":", highlight_id: Some(1), repeat: None }] })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(GridLine { grid: 3, row: 0, column_start: 1, cells: [GridLineCell { text: "%", highlight_id: Some(1), repeat: None }, GridLineCell { text: "s", highlight_id: None, repeat: None }, GridLineCell { text: "/", highlight_id: None, repeat: None }] })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(GridLine { grid: 3, row: 0, column_start: 4, cells: [GridLineCell { text: "f", highlight_id: Some(1), repeat: None }] })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(MessageSetPosition { grid: 3, row: 41, scrolled: false, separator_character: " " })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(WindowPosition { grid: 2, start_row: 1, start_column: 0, width: 156, height: 39 })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(GridLine { grid: 2, row: 1, column_start: 1, cells: [GridLineCell { text: " ", highlight_id: Some(76), repeat: Some(2) }, GridLineCell { text: "1", highlight_id: None, repeat: None }, GridLineCell { text: " ", highlight_id: None, repeat: None }, GridLineCell { text: "f", highlight_id: Some(145), repeat: None }, GridLineCell { text: "o", highlight_id: Some(145), repeat: Some(2) }, GridLineCell { text: " ", highlight_id: Some(145), repeat: Some(148) }] })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(GridLine { grid: 3, row: 0, column_start: 0, cells: [GridLineCell { text: " ", highlight_id: Some(1), repeat: Some(156) }] })
TRACE [neovide::channel_utils] neovide::editor::EditorCommand NeovimRedrawEvent(WindowViewport { grid: 2, top_line: 0.0, bottom_line: 2.0, current_line: 0.0, current_column: 0.0, line_count: Some(1.0), scroll_delta: Some(0.0) })
ERROR [neovide::error_handling] Could not parse event from neovim: invalid u64 format -1
ERROR [neovide::bridge] Error joining IO loop: 'task 13 panicked'
INFO [neovide::running_tracker] Quit neovim processed failed
DEBUG [neovide::settings::window_geometry] Saved Window Settings: {"window":{"Windowed":{"position":{"x":563,"y":25},"size":{"width":156,"height":41}}}}
```

**Comment by fredizzimo** [comment] 2023-05-26 18:13
I see now, there's some event that we are assuming to have an unsigned parameter, but Neovim sends `-1` for some reason. 

It's one of these https://github.com/neovide/neovide/blob/4b3c234a49d7db3edbc6ba821964805525f7a02a/src/bridge/events.rs#L138-L278 It's most likely one of the `CommandLine` ones. Unfortunately, our error reporting is not very good, but I have a PR for improving that https://github.com/neovide/neovide/pull/1876. Would it be possible for you to try again with that for better logs?

**Comment by fredizzimo** [comment] 2023-06-06 11:46
@DominicAnelloSonos,

The improved error reporting has now been merged into master, so if you can, it would be good to get a new log from that version.

**Comment by fredizzimo** [comment] 2023-07-31 08:42
This was almost certainly caused by `nvim.noice`, which is now fixed if you update that. https://github.com/neovide/neovide/issues/1751

**Closed by fredizzimo** 2023-07-31 08:42 UTC
Labels: bug
