### ISSUE TITLE
Conflict with init.vim

### ISSUE THREAD

**Issue by homie-desktop** [neovide/neovide#1189] opened 2022-01-30 01:04 UTC
**Describe the bug**
Hi, I just installed neovide from source as per the instruction for Linux. I'm using Pop!_OS 21.10, and the issue is neovide won't recognize my `~/.vimrc` file, but when I paste my `.vimrc` contents to `~/.config/nvim/init.vim` it works as intended. However, I am used to using `~/.vimrc` instead of `~/.config/nvim/init.vim`. Is there any way to make neovide read my `~/.vimrc` file instead of the `~/.config/nvim/init.vim` because that's also my setup in my Windows PC, that's why I would like to maintain my current setup so both my systems (linux and windows) has the same setup at file structure. 

Here's my `init.vim` contents (i'm sourcing the `~/.vimrc` so all my configs are stored there)

```
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
source ~/.vimrc
```

**To Reproduce**
1. create `init.vim` file and paste the following contents 

```
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
source ~/.vimrc
```

2. now, create `~/.vimrc` file (all my configs are stored here)
3. `neovide configs` aren't being recognize when it is stored in the `~/.vimrc` file instead. 

**Expected behavior**
Neovide should be able to read my `~/.vimrc` file

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Pop!_OS 21.10
 - Neovide Version [0.8.0]
 - Neovim Version [e.g. 0.4.4]

**Please run `neovide --log` and paste the contents of the `.log` file here:**

**Additional context**

**Comment by MultisampledNight** [comment] 2022-01-31 19:52
Hm, I'm unable to reproduce. This is in my `init.vim`, behavior does not change if I remove the first two lines:

```vim
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
source ~/.vimrc
```

With this being `~/.vimrc` (used the `morning` colorscheme to detect whether configs were applied):

```
colo morning
```

I'm not sure if I understand you to 100%, but you don't delete `~/.config/nvim/init.vim` , right? Theoretically Neovide just calls NeoVim in headless mode and takes over rendering and input, so config behavior should not be different from normal NeoVim.

**Comment by Kethku** [comment] 2022-02-03 04:48
Modern neovim doesn't read init.vim from your home directory anymore. This issue isn't specific to neovide. So I'm closing this as unrelated. Please address the issue upstream if its a problem (but I'm pretty sure modern neovim doesn't do this by design)

**Comment by homie-desktop** [comment] 2022-02-03 07:15
@MultisampledNight Hi, thanks for the response and your time. I've tried doing the same installation process from my laptop to a VM with the same OS, Neovim, and neovide versions and it worked in the VM, but not on my laptop. The VM reads/recognized my `~/.vimrc`  configs from the home directory. But on my laptop, it reads the `~/.config/nvim/init.vim` instead. 

I used and followed the same exact Installation process and configs from my laptop to the VM.

**Comment by Kethku** [comment] 2022-02-03 07:38
Are both of those installs the same version of neovim?

**Comment by homie-desktop** [comment] 2022-02-03 10:48
@Kethku yes, same version for both laptop and VM. And on my laptop and VM when I use Neovim in terminal it works as intended (reads my `~/.vimrc` and `~/.config/nvim/init.vim` files).

**Comment by fredizzimo** [comment] 2022-02-04 20:17
The only thing I can think of, is that there could be some plugin or something that fails to load, and causes the rest of the config not to be loaded. Try with something very minimal, and rename your plugin directories to make sure that they are not autloaded.

**Comment by homie-desktop** [comment] 2022-02-05 12:00
@fredizzimo, I've tried your suggestion, by adding/removing my configs one by one, to get a vanilla config of neovim and neovide, but the issue still persists, also another weird thing is when I press my **left** ctrl-key (which I am using for my mappings) it has to be press twice in order to execute my mapping (e.g `map <c-z> :Files<CR>` for FZF) but when I try to use my  **right** ctrl-key, it works as intended (single press to execute my mapping). 

Maybe it's my laptop that has issue, thanks for you time, feel free to close this issue. I'll just wait for neovide to be included in the official APT repository, the snap package doesn't work well in my laptop too. Thanks again.

**Comment by MultisampledNight** [comment] 2022-02-05 13:17
In case it's snaps fault, you could try installing neovide through `cargo install --git https://github.com/neovide/neovide` (after installing Rust), which would put a binary called `neovide` in `$HOME/.cargo/bin`.

**Comment by homie-desktop** [comment] 2022-02-10 00:20
@MultisampledNight just tried your suggestion and run the binary inside `.cargo/bin/neovide` but the same issue persist. Like I have to press left-ctrl key twice to activate my mappings like `<C-z>` for `FZF plugin`.

**Comment by fredizzimo** [comment] 2024-05-17 14:15
This has to be some problem with the user configuration.

**Closed by fredizzimo** 2024-05-17 14:15 UTC
Labels: bug
