### ISSUE TITLE
Neovide unresponsive after opening

### ISSUE THREAD

**Issue by Lolobstant** [neovide/neovide#2277] opened 2024-01-17 08:13 UTC
**Describe the bug**
after neovide launch, it ask to press any key but stay unresponsive

**To Reproduce**
launch neovide 

**Expected behavior**
neovide should start normally

**Desktop (please complete the following information):**
 - OS: macOS 14.2.1 
 - Neovide Version 0.12.1 installed through homebrew
 - Neovim Version 0.9.5

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_r2024-01-17_08-09-14.log](https://github.com/neovide/neovide/files/13960356/neovide_r2024-01-17_08-09-14.log)

**Additional context**
running `neovide -- -v` crashes has shown in the screenshot
 
<img width="430" alt="Capture d’écran 2024-01-17 à 09 10 48" src="https://github.com/neovide/neovide/assets/1752512/af241d36-a5af-4f45-a358-cae3ec0ead29">

running `neovide -- -u NONE`  launch a responsive neovide so it could be a configuration issue, but it hasn't change recently

**Comment by fredizzimo** [comment] 2024-01-18 02:19
This is fixed on main if you compile from source. There was a regression in 0.12.0 and 0.12.2 that causes hangs when a  message is shown during startup that requires the user to press enter. So you can also fix the problem by running normal terminal nvim first, and fix your config to ensure that there's no output during startup.

The second crash happens because neovim will exit immediately instead of running the UI protocol when passing `--version`. We should probably add special case handling for that.

**Comment by fredizzimo** [comment] 2024-01-19 02:34
I'm going to close this as duplicates of 
* https://github.com/neovide/neovide/issues/2233
* https://github.com/neovide/neovide/issues/2271
* https://github.com/neovide/neovide/issues/2261
* https://github.com/neovide/neovide/issues/2245
* https://github.com/neovide/neovide/issues/2286

It's fixed on main if you build from source with 
* https://github.com/neovide/neovide/pull/2241

**Closed by fredizzimo** 2024-01-19 02:34 UTC
Labels: bug
