### ISSUE TITLE
`--remote` support like original `gvim`

### ISSUE THREAD

**Issue by wzhliang** [neovide/neovide#1863] opened 2023-05-13 05:29 UTC
Original gvim has an option `--remote` to send a file into an already opened GUI. It'd be nice to have this in neovide

See documentation here: https://vimdoc.sourceforge.net/htmldoc/remote.html

**Comment by wzhliang** [comment] 2023-05-13 07:17
`brew install neovide` solved it

**Comment by fredizzimo** [comment] 2023-07-31 09:00
This is a duplicate of https://github.com/neovide/neovide/issues/1293. `nvr` is a good workaround for now.

**Closed by fredizzimo** 2023-07-31 09:00 UTC
Labels: enhancement
