### ISSUE TITLE
Add blacklisting of commandline/statusline/etc for cursor animations

### ISSUE THREAD

**Issue by keevan** [neovide/neovide#158] opened 2020-02-28 13:26 UTC
Below is an example I've been able to produce (Windows build) by toggling between normal mode and insert mode. 

Had issues recording a gif so I uploaded an mp4 instead
https://streamable.com/s/4kpe4/utgzux

I believe the cursor should stay at it's current location when changing modes, and only jump down for things like command mode

**Comment by Kethku** [comment] 2020-02-28 19:08
This is an upstream issue. The cursor jumps to locations where text changes.

This particular problem can be improved by adding `set noshowmode` to your config.
Further this problem is made worse by setting `set lazyredraw` which makes the cursor position issue worse.

**Comment by tssm** [comment] 2020-02-29 08:49
[It is not considered a bug, but a feature](https://vim.fandom.com/wiki/Prevent_escape_from_moving_the_cursor_one_character_to_the_left), although it is quite confusing. I doubt the Neovim team will change it.

@keevan in the link there's a suggested configuration that you can add to your `init.vim` file as a workaround

**Comment by Kethku** [comment] 2020-02-29 23:39
Well the escape issue is by design and won't be fixed. I think the main problem is the jumping to the commandline when switching modes

**Comment by keevan** [comment] 2020-03-01 01:47
> Well the escape issue is by design and won't be fixed. I think the main problem is the jumping to the commandline when switching modes

Yeah this is what I meant. I can see how it might have been misinterpreted

**Comment by Kethku** [comment] 2020-03-01 02:44
Did my suggestion fix it for you?

**Comment by keevan** [comment] 2020-03-01 03:52
> Did my suggestion fix it for you?

I haven't tried yet but I believe it would. I'm going to go on a hunch and say it would affect any message that shows at the bottom, which shouldn't actually come up as often in day to day use.

As a side note, if anyone uses this fix/workaround but still wants to see the current mode, they can use a plugin like vim-airline where the current mode is displayed. But those wanting to use base vim will probably have to wait for an upstream fix.

**Comment by Kethku** [comment] 2020-03-01 16:23
I haven't done the searching yet to find if there is an upstream issue. One thing that may obviate the need for upstream work is settings which determine where the cursor is allowed to animate to. There has been discussion in the past about adding configuration which sets whether jumping to the command line is a valid operation. In general it probably never makes sense to jump to the window status line

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by keevan** [comment] 2020-03-01 16:46
@Kethku I think it should be a default, as you mentioned, it doesn't make sense for it to go to the window status line. 

As far as my usage goes, the only time it probably makes sense to go down there, is when in command mode

**Comment by Kethku** [comment] 2020-03-01 20:26
Unfortunately blacklisting cursor moves to the statusline probably has to wait until the multigrid extension is implemented.

**Comment by Nemo157** [comment] 2020-03-03 09:21
> it would affect any message that shows at the bottom, which shouldn't actually come up as often in day to day use.

Depends what plugins you use, with ALE showing warnings for the current line in the status line I notice this happening a lot (when moving line-by-line over some warnings it appears to happen on ~every 5th to 10th line I cross).

**Comment by fredizzimo** [comment] 2024-01-13 09:07
We have been blacklisting some windows for a while now in multigrid, which is now the default.

**Closed by fredizzimo** 2024-01-13 09:07 UTC
Labels: enhancement
