### ISSUE TITLE
Chinese Input Method Pinyin Not Displayed in Real-Time

### ISSUE THREAD

**Issue by Flower101010** [neovide/neovide#2335] opened 2024-02-03 01:05 UTC
The current issue revolves around the real-time display of Pinyin while using a Chinese input method. Presently, the Pinyin input is only visible after completion, causing inconvenience during the input process.

I would like the neovide to support real-time rendering of Pinyin during the input process with a Chinese input method. This improvement would enhance the user experience and streamline the workflow when inputting Chinese characters.

- Neovim Default Client with Real-Time Display:
![image](https://github.com/neovide/neovide/assets/36117512/7c987542-7e7e-4375-853f-9d0a7c5d8f60)
- Neovide without Real-Time Display:
![image](https://github.com/neovide/neovide/assets/36117512/33582041-0f78-4e98-b6fa-4e8e104af749)

**Additional context**
OS: Windows 10
Neovim Version: 0.9.5
Neovide Version: 0.12.2
Input Method: Microsoft Pinyin

**Comment by fredizzimo** [comment] 2024-02-03 05:38
This is a duplicate of
* https://github.com/neovide/neovide/issues/1931

And there's a partial fix here 
* https://github.com/neovide/neovide/pull/2198

You might also be able to configure your IME to display the typed characters using its own ui as a temorary workaround.

**Closed by fredizzimo** 2024-02-03 05:38 UTC
Labels: enhancement
