### ISSUE TITLE
add neovide's tabs (like wezterm)

### ISSUE THREAD

**Issue by erlangparasu** [neovide/neovide#2688] opened 2024-07-09 03:52 UTC
**Is your feature request related to a problem? Please describe.**
add neovide's tabs (like wezterm)

**Describe the solution you'd like**
add neovide's tabs (like wezterm)

**Describe alternatives you've considered**
.

**Additional context**
.

**Comment by erlangparasu** [comment] 2024-07-09 04:04
in wezterm, there is option to render Tabs as text

https://wezfurlong.org/wezterm/config/lua/config/use_fancy_tab_bar.html
set it to `false`

**Comment by erlangparasu** [comment] 2024-07-09 04:04
https://github.com/neovide/neovide/issues/1623

**Comment by fredizzimo** [comment] 2024-07-09 08:54
Yes, I'm closing this as a duplicate of:
* #1623

**Closed by fredizzimo** 2024-07-09 08:54 UTC
Labels: enhancement
