### ISSUE TITLE
Issue with firefox when running using WINIT_UNIX_BACKEND=x11 

### ISSUE THREAD

**Issue by Mofiqul** [neovide/neovide#1278] opened 2022-04-19 10:00 UTC
**Describe the bug**
I have a problem with neovide a firefox on Gnome 42. If I focus on firefox and comeback to neovide, the keybord input behaves strange. going to command mode will put in insert mode, typing something in insert mode put to normal mode. Focusing on any other app and come back fix the problem

**To Reproduce**
1. Go to neovide
2. Type something
3. Go to firefox 
4. Come back to nevide 
5. Try to change mode

**Expected behavior**
Changing mode behave correctly

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora 36 beta
 - Neovide Version: 0.9.0
 - Neovim Version: v0.6.1

**Please run `neovide --log` and paste the contents of the `.log` file here:**

[neovide log](https://pastebin.com/N5Ku26m6)

**Additional context**
I run nevide using `WINIT_UNIX_BACKEND=x11`

**Comment by MultisampledNight** [comment] 2022-04-19 10:44
Just to make sure:

- Do you run GNOME shell in Wayland or X11 mode?
- What keyboard layout are you using? I noticed XWayland having some problems with mapping keycode -> actual key meaning.

**Comment by Mofiqul** [comment] 2022-04-19 10:47
Yes I run Gnome shell in Wayland and Keyboard layout is English US

**Comment by MultisampledNight** [comment] 2022-04-19 11:03
Okay, thank you. Do you have the environment variable `MOZ_ENABLE_WAYLAND` set? (If not, Firefox is running in XWayland and not in Wayland.)

**Comment by Mofiqul** [comment] 2022-04-19 13:09
`MOZ_ENABLE_WAYLAND` is  not set but can't they both run on XWayland together?

**Comment by MultisampledNight** [comment] 2022-04-19 13:33
They should be able to. But I have no idea at all how to debug this, I can't reproduce it with Xwayland on sway either.

Related, why do you force Xwayland at all? Due to the window decorations?

**Comment by Mofiqul** [comment] 2022-04-19 16:14
Yes window decoration is the reason I forced to Xwayland. For now `MOZ_ENABLE_WAYLAND` I set this. Is there a way to get gnome window decoration on wayland?

**Comment by MultisampledNight** [comment] 2022-04-19 16:23
Unfortunately not, without having us in a major dependency hell. I'm thinking about adding custom decorations for Neovide though. For context, the server (GNOME) providing window decorations is quite usual, but GNOME only does that in X11 mode or with Xwayland clients. So everything has to draw its decoration by itself.

**Comment by rhoot** [comment] 2022-04-20 02:06
Seeing as you're on the Fedora 36 Beta, you may be hitting [this gnome-shell bug in Fedora 36](https://bugzilla.redhat.com/show_bug.cgi?id=2076390).

**Comment by rhoot** [comment] 2022-04-22 00:47
If you update mutter in the Fedora beta as of today it should bring you up to `mutter-42.0-5`. That has the fix for that bug. Then you can reboot (or restart your session probably) to see if that fixes this.

**Comment by Mofiqul** [comment] 2022-04-22 08:24
Unfortunately, it did not fix my issue

**Comment by ErikReider** [comment] 2022-07-22 15:23
I also seem to have this issue but only when focusing a different window on another monitor. I'm running the latest sway-git on Arch

**Comment by fredizzimo** [comment] 2023-06-14 22:33
I think this might be fixed by the new winit version merged here https://github.com/neovide/neovide/pull/1789. Could you try again with the latest master?

**Comment by fredizzimo** [comment] 2024-01-13 08:03
Closing, this is either an upstream or winit bug that should be fixed by now.

If not, please re-open

**Closed by fredizzimo** 2024-01-13 08:03 UTC
Labels: bug
