### ISSUE TITLE
unable to iinstall on macos sonoma v 14.3.1

### ISSUE THREAD

**Issue by ghost** [neovide/neovide#2371] opened 2024-02-19 22:22 UTC
**Describe the bug**
Apple refu8sed to0 open the dmg file. Apple claimed the dmg was insecure and contact the developer

**To Reproduce**
1. Go to 'neovide down load and click on the mac download button.
2. go to the download directory and click on the zip file tio extract the *;.dmg file.
3. click on the dmg file. After a period of time macos will pop a dialog saying the dmg cannot be read because it doesn't meet Apples
4. security criterion.
5. Click on '....'
6. Scroll down to '....'
7. See error

**Expected behavior**
neiovide to install

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 11.4]
 - macos sonoma v 14.3.1
 - Neovide Version [e.g. 0.6.0]
 - unknown the website did not really say and the install did not get far enough to get an "about" file
 - Neovim Version [e.g. 0.5.0]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
neovide did not install so there is no log. I do not know if there is a macos log, and Apple suport cannot/will not tell me.
macos sonoma v 14.3.1
**Additional context**

**Comment by fredizzimo** [comment] 2024-02-20 19:18
I believe this is a duplicate of these issues:
* https://github.com/neovide/neovide/issues/1479
* https://github.com/neovide/neovide/issues/1373
* https://github.com/neovide/neovide/issues/1998

Although the error message might be different. But I leave this open until confirmed.

Long story short, we need to pay Apple yearly to be able to sign every release, and most likely a single person needs to own that license and do the signing. So, until someone wants to take the responsibility and pay/accept donations for it unfortunately has to stay this way.

**Closed** 2024-11-06 01:53 UTC
Labels: bug, macos
