### ISSUE TITLE
no-fork exits with SIGSEGV

### ISSUE THREAD

**Issue by entailz** [neovide/neovide#2504] opened 2024-04-25 03:37 UTC
**Describe the bug**
`neovide --no-fork` or `NEOVIDE_FORK=0 neovide`
leads to segfault on exit.
`Job 1, 'NEOVIDE_FORK=0 neovide' terminated by signal SIGSEGV (Address boundary error)`

**To Reproduce**
Using a wayland compositor, attempt to use no-fork to block from terminal.

**Expected behavior**
Expected to exit cleanly

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux 
 - Neovide Version: neovide 0.12.2
 - Neovim Version: NVIM v0.9.5
                                  Build type: Release
                                  LuaJIT 2.1.1713773202

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

[neovide_r2024-04-24_20-27-57.log](https://github.com/neovide/neovide/files/15103723/neovide_r2024-04-24_20-27-57.log)

**Additional context**

**Comment by fredizzimo** [comment] 2024-04-25 09:05
This is a duplicate of:
* https://github.com/neovide/neovide/issues/2223

And will be fixed by:
* https://github.com/neovide/neovide/pull/2463

But since that PR is stalled due do issues on some Windows system, I might extract it into it's own PR.

**Closed** 2024-04-25 09:05 UTC
Labels: bug
