### ISSUE TITLE
[BUG]: Window Flickering and incorrect Color Mapping on MacOS Broken

### ISSUE THREAD

**Issue by NyanHelsing** [neovide/neovide#2448] opened 2024-03-28 14:58 UTC
**Describe the bug**

Neovide doesn’t display the correct colors. It seems to for a little bit; flickering in and out when the app is first opened but before the app may have become fullscreen

After becoming fullscreen, the colors become stable, but only display the incorrect “lighter” colors.

This is with the rose-pine theme but it doesn’t seme to matter what the theme is, the colors are wrong period.

[Video of the behaviour](http://storage.infinite.jetzt/firefish/f2804a13-0aac-43c3-a47a-3b7486689e41.mov) Neovide's entire window flickers like a strobe and the colors neovide displays are not correct.

**To Reproduce**
Launch neovim
when windowed next to another app like terminal, the colors should match and not flicker.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 11.4]
 - Neovide Version [e.g. 0.6.0]
 - Neovim Version [e.g. 0.5.0]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

**Additional context**

**Comment by fredizzimo** [comment] 2024-05-17 14:41
I think the flickering should be gone, or at least improved now, when we switched to `--no-fork` as the default.

The colors is a duplicate of this:
* https://github.com/neovide/neovide/issues/2044

**Closed by fredizzimo** 2024-05-17 14:41 UTC
Labels: bug, macos
