### ISSUE TITLE
slow performance on windows 10

### ISSUE THREAD

**Issue by adriancostin6** [neovide/neovide#1299] opened 2022-05-02 01:52 UTC
**Is your feature request related to a problem? Please describe.**
Is anyone else experiencing lackluster performance and laggy animations on Windows 10? What is the cause of this and how can it be fixed, to bring it in line with nvim-qt which is blazing fast. Possible to be related to my system only, but unsure.

**Describe the solution you'd like**
Better performance, or fix for laggy animations.

**Describe alternatives you've considered**
Using nvim-qt, as that runs 10x faster, at least on my machine.

**Additional context**
Context: neovide installed with scoop package manager, as building from source generated linker error when trying to build neovide binary with MSVC.

**Comment by MultisampledNight** [comment] 2022-05-02 05:25
First: You can try setting [`g:neovide_no_idle` to `v:true`](https://github.com/neovide/neovide/wiki/Configuration#no-idle) to force Neovide to redraw without looking if anything changed. You can also use [`g:neovide_refresh_rate`] to control the actual framerate.

Then: What specs are you running on (specifically GPU and CPU, maybe driver version)? And what version?

**Comment by adriancostin6** [comment] 2022-05-03 20:28
Setting no-idle to true didn't seem to do anything, as I arready did that. I will try also setting the refresh rate to see if that helps.

I am also going to give an update on the hardware when I get home, as I don't know it off the top of my head, but I'm gonna say this, I first came across Neovide a couple of days ago and set it up on an old Thinkpad T520, with an i7 and integrated graphics running Linux.

The setup was blazing fast, and I quickly came to love the animations so I was like: "Let me also set this up on my work laptop". 

The device is much much newer and is a Dell Precision 5530 (more detail on the specs in a later edit), so naturally I had a surprise when Neovide was laggy 😀 Granted, the Os difference, but still, wouldn't expect it to lag as hard as it did.

**Comment by adriancostin6** [comment] 2022-05-03 22:54
Specs

- CPU: i7-8850H @2.6GHz
- GPU
    - Nvidia Quadro P1000 with driver version 472.39
    - Intel UHD 630

**Comment by dineshKumar777** [comment] 2022-05-03 23:02
This never happened to me. I use neovide in both personal and work machine. 

Can you try downloading neovide exe from GitHub actions and try !

https://github.com/neovide/neovide/actions/runs/2250294042

If issue persists try launching with clean config to rule out any configuration issue.
"neovide --  --clean

**Comment by adriancostin6** [comment] 2022-05-05 15:23
![image](https://user-images.githubusercontent.com/32834752/166956983-e8a264ec-25ba-4ca2-ac61-a90195ab9b3e.png)

Yup, tried to get it from the latest actions that had an artifact in them. Running it defaults to a black screen and nothing else. I think my computer just dislikes Neovide 😆 I'm not meant for them pretty animations. Only version I can get to work is the one I got from 'scoop' package manager (0.8.0), but that one lags like crazy. My config is not that extensive (20-25 plugins).

**Comment by tan-wei** [comment] 2022-05-12 05:50
Met the same issue on My Windows 10. But on MacOS, it is quite fast.

**Comment by adriancostin6** [comment] 2022-05-12 06:55
> By the way, are you sure Neovide is using your dGPU (the Quadro one)?

Yes, I checked :)

**Comment by adriancostin6** [comment] 2022-05-12 06:56
> Met the same issue on My Windows 10. But on MacOS, it is quite fast.

Can agree with this, as I said, on my 2008 Thinkpad T520 running Arch it's blazing fast.

**Comment by akim-13** [comment] 2022-05-14 16:20
Are you using it with a 4k monitor? Can you try making the window half the size of the screen and then check the performance? I also encountered an Issue related to performance (#1312) and it is directly linked to window size (larger window - slower performance).

**Comment by adriancostin6** [comment] 2022-05-16 12:20
> Are you using it with a 4k monitor? Can you try making the window half the size of the screen and then check the performance? I also encountered an Issue related to performance (#1312) and it is directly linked to window size (larger window - slower performance).

This is GENIUS. I shrinked the window down and it indeed is running 100 times faster it seems. Forgot I had a 4k monitor on the laptop 😂

This is extremely weird tho, I'll look into the issue to get some insight into the situation.

**Comment by akim-13** [comment] 2022-05-16 12:43
> Later edit: Just looked at the other issue. Any insight into how this might be fixed? 

I tried to combat this issue several times during the past few months by tweaking Arch stuff, but apparently it's a bug, so can't do much about this. There is a workaround — you can make the window spawn smaller, but in my experience it's just not worth it.

With that said, I'm extremely excited about Neovide because everything is so much smoother and fancier with it. So I hope that this bug, which prevents me from using the program, will get fixed ASAP :)

**Comment by tan-wei** [comment] 2022-05-16 14:45
> Are you using it with a 4k monitor? Can you try making the window half the size of the screen and then check the performance? I also encountered an Issue related to performance (#1312) and it is directly linked to window size (larger window - slower performance).

Yes for my Windows laptop. It's a surface Pro whose screen is 4K (maybe, it's high resolution).

**Comment by tan-wei** [comment] 2022-05-23 02:09
I think the issue is related to #1312. I try to use 2 screens on my laptop. One is 2K, the other is 4K. It's just OK on 2K, however, extremely slow on 4K.

**Comment by cravussin** [comment] 2022-07-01 22:40
Same here, big lag on macbook pro 2020 on dual 4K screens when the window is bigger than a quarter of the screen. Maybe a VRAM management issue?

**Comment by adriancostin6** [comment] 2022-07-06 09:47
Neovide doesn't seem to br the only frontend that has this problem. I just tried nvui, which is written in c++ and it also seems to lag like crazy on a 4k display. The only fronted that is blazing fast for me at the moment is nvim-qt.

**Comment by VladimirMarkelov** [comment] 2022-07-07 04:01
It seems `let g:neovide_no_idle=v:true` helps on Windows 10 in this case: after restoring neovide from minimized state, often for some time it displays only window border and title - the text area is like 100% transparent. Sometimes it takes up to 20 seconds until neovide paints the text area. I set `let g:neovide_no_idle=v:true` to check if it helps. I have not tested it thoroughly but for the last hour it seems working.

**Comment by Verf** [comment] 2022-08-08 00:36
> Neovide doesn't seem to be the only frontend that has this problem. I just tried nvui (https://github.com/rohit-px2/nvui), which is written in c++ and it also seems to lag like crazy on a 4k display. The only fronted that is blazing fast for me at the moment is nvim-qt.

I tried [Nvy](https://github.com/RMichelsen/Nvy) also have this problem.  The only frontend that works perfectly at 4k is neovim-qt.

**Comment by adriancostin6** [comment] 2023-01-31 11:32
Happy to report that this problem gas been fixed, at least for me. Just pulled latest neovide on windows with scoop amd no more lag.

**Comment by adriancostin6** [comment] 2023-02-13 21:37
Broken again

**Comment by domsch1988** [comment] 2023-05-17 06:02
Just wanted to add that this isn't limited to 4k.
Im having the same Issue on 1440p. Resizing the window does indeed make this better.

**Comment by fredizzimo** [comment] 2023-07-31 11:06
This will be fixed by https://github.com/neovide/neovide/pull/1870

**Closed** 2023-11-01 18:54 UTC
Labels: enhancement
