### ISSUE TITLE
Crash regression on sway: Buffer size is not divisible by scale

### ISSUE THREAD

**Issue by REmerald** [neovide/neovide#2200] opened 2023-12-24 18:58 UTC
**Describe the bug**
Black window opens for a millisecond, then disappears (crashes).

**To Reproduce**
1. Launch the program through the terminal or a sway keybind.
2. See *Describe the bug*.

**Expected behavior**
No crash.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Arch Linux, Sway `1:1.8.1-4`, wlroots `0.17.0-1`
 - Neovide Version `git-0.11.2.r57.gb496ab23-1`, `git-0.12.0.r0.gaf9869bd-1`
 - Neovim Version `v0.10.0-dev-1938+g242261d4e`

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
```
[remorin@chuwawa:0 ~]$ lazyvide --no-fork
wl_surface@32: error 2: Buffer size (710x909) is not divisible by scale (2)
Protocol error 2 on object wl_surface@32: 
Protocol error 2 on object wl_surface@32: 
Protocol error 2 on object wl_surface@32: 
/home/remorin/.local/bin/lazyvide: line 3:  8593 Segmentation fault      (core dumped) neovide --neovim-bin "$HOME/.local/bin/lazyvim" "$@"
[ble: exit 139]
[remorin@chuwawa:0 ~]$ lazyvide --log --no-fork
wl_surface@32: error 2: Buffer size (710x909) is not divisible by scale (2)
Protocol error 2 on object wl_surface@32: 
Protocol error 2 on object wl_surface@32: 
Protocol error 2 on object wl_surface@32: 
warning: queue 0x7f3d40000d00 destroyed while proxies still attached:
  zwp_primary_selection_device_v1@26 still attached
  zwp_primary_selection_device_manager_v1@22 still attached
  wl_data_device@25 still attached
  wl_seat@24 still attached
  wl_data_device_manager@23 still attached
  wl_registry@21 still attached
^C
[ble: exit 130]
```
[neovide_r2023-12-24_21-02-08.log](https://github.com/neovide/neovide/files/13762613/neovide_r2023-12-24_21-02-08.log)

**Additional context**
This is a regression, the commits on Dec 23 broke it, since after downgrading to `neovide-git-0.11.2.r52.gce0174a1-1` everything works fine.
```
[remorin@chuwawa:0 ~]$ lazyvide --log --no-fork
[remorin@chuwawa:0 ~]$
```
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/13762621/neovide_rCURRENT.log)

**Comment by fredizzimo** [comment] 2023-12-25 12:07
I can repeat this in sway when using a scale factor of two. But it's not reproducible in gnome for example.

But I need to research a bit how to fix this properly, it's not clear to me at the moment if this refers to the opengl surface or the window itself. And also how we should round this number, when using fractional scaling, and the scale might not divisible by an integer.

We did have a similar issue before, but in that case it was because of a race condition, when we were running the renderar in a separate thread from the winit event loop.

@kchibisov, do you know what's the right way to solve this?

**Comment by kchibisov** [comment] 2023-12-25 12:49
Could you post `WAYLAYND_DEBUG=1` log? Also, when fractional scaling is in use you can't crash due to that because of the viewporter protocol.

**Comment by fredizzimo** [comment] 2023-12-25 12:56
@kchibisov, for some reason I can't repeat it any more. So, it might have something to do with the initial size of the window, which is saved. I will try to figure out what triggers it and give a log soon.

**Comment by fredizzimo** [comment] 2023-12-25 13:02
Yes, it has something to do with that, I started Neovide with `WAYLAND_DEBUG=1 neovide --size 301x301 2>&1 >wayland.txt` and here is the output

[wayland.txt](https://github.com/neovide/neovide/files/13766110/wayland.txt)

**Comment by fredizzimo** [comment] 2023-12-25 13:11
Here's a better one, I think, the previous one did not seem to include the error 
[wayland.txt](https://github.com/neovide/neovide/files/13766131/wayland.txt)

**Comment by fredizzimo** [comment] 2023-12-25 13:27
Hm.. I think it might be a Neovide bug and that we apply the scale factor in the wrong direction somewhere, because if I specify a size of 302x302, then it complains that 151x151 is not divisible by 2.

**Comment by kchibisov** [comment] 2023-12-25 13:31
Hm, fractional scale is not in use.

Make sure to resize EGL context **before** making it current if you deactivate it, and when you create window you create gl surface after window creation with the `inner_size`.

Also, if you support more than one window you make sure to deactivate all contexts before starting creating it.

**Comment by fredizzimo** [comment] 2023-12-25 13:34
@kchibisov 

It looks like it's this code that fails already
https://github.com/neovide/neovide/blob/af9869bd6d8d3434b187e29f85032ee74e40b536/src/window/mod.rs#L142-L150

If the requested inner size is not divisible by the scale factor of the system. But I will run a few more tests to be absolutely sure that is the case.

**Comment by kchibisov** [comment] 2023-12-25 13:55
it doesn't matter because the initial size is `1` and the actual size is on the `Surface` from the glutin, winit just has hints, nothing more.

**Comment by fredizzimo** [comment] 2023-12-25 14:11
I forgot to change the resize function for the glutin surface. But once I did that, it's enough to make sure that the glutin surface is divisible by the scale factor.  This is easy enough to do when the scale factor is an integer, but what should we do when it isn't?

**Comment by kchibisov** [comment] 2023-12-25 14:19
>This is easy enough to do when the scale factor is an integer, but what should we do when it isn't

It doesn't matter, winit gives you integers for the sizes, it can't give you floats, just use the sizes it tells you.

**Comment by fredizzimo** [comment] 2023-12-25 14:30
Currently I'm using a clamped `get_inner_size`, which does not work.

https://github.com/neovide/neovide/blob/af9869bd6d8d3434b187e29f85032ee74e40b536/src/renderer/opengl.rs#L65-L66

And this is the fix for a scale factor of 2, but not generic for any scale factor, which is a f64, and I have no idea how I should round that.
```diff
diff --git a/src/renderer/opengl.rs b/src/renderer/opengl.rs
index b0a8fde..c257031 100644
--- a/src/renderer/opengl.rs
+++ b/src/renderer/opengl.rs
@@ -47,7 +47,11 @@ impl Context {
     }
 
     pub fn resize(&self, width: NonZeroU32, height: NonZeroU32) {
-        GlSurface::resize(&self.surface, &self.context, width, height)
+        let width = u32::from(width);
+        let height = u32::from(height);
+        let width = 2 * ((width + 1) / 2);
+        let height = 2 * ((height + 1) / 2);
+        GlSurface::resize(&self.surface, &self.context, NonZeroU32::new(width).unwrap(), NonZeroU32::new(height).unwr
ap());
     }
 
     pub fn swap_buffers(&self) -> glutin::error::Result<()> {
```

**Comment by kchibisov** [comment] 2023-12-25 14:46
You probably don't understand the issue. Winit always gives you the sizes which are correct according and won't make you get the behavior or error you see.

Fractional scaling is always of buffer scale 1, it can't have this issue on any level.

The first frame on wayland until `wl_compositor v6` always uses the scale 1, so the 301x301 is correct until you draw and present the window, only after that it'll get the scale factor.

With the modern protocol you can get the scale 2 very early (wl_compositor v6), thus you must to query `inner_size` right after you create a window to account for that or maximize state.

In general, I'd suggest to look into alacritty's code wrt resizing and window creation.

glutin also has documented behavior (as I said before as well) when it comes to buffer latching in EGL, which is likely what is going on here, and that's why I explicitly told the order you should be using.

**Comment by fredizzimo** [comment] 2023-12-25 16:18
I found the issue. The glutin buffers were not always resized properly before trying to render. This was caused by an assumption that no longer holds after we moved to use the winit wayland callbacks.

**Comment by REmerald** [comment] 2023-12-27 12:47
@kchibisov @fredizzimo I don't fully understand the things you are taking about here, but I'm gonna say just in case that I had (and still have) the scaling of 1.5. `output eDP-1 scale 1.5`

**Comment by fredizzimo** [comment] 2023-12-27 12:52
@REmerald, in that case it probably renders with a scale of 2 and then the compositor scales it down to 1.5. I think that I have read that at least some compositors do that.

In any case my fix should deal with fractional scales as well, since it was just a problem of not reacting fast enough to the scale and size changes.

**Comment by REmerald** [comment] 2023-12-27 13:03
Hmm, also, I launched just `neovide` instead of `~/.local/bin/lazyvide` (`neovide --neovim-bin "$HOME/.local/bin/lazyvim" "$@"`) in half-screen (the other half was taken by my terminal) and it launched! but `lazyvim` didn't in the same conditions.
But then I did something and `neovide` stopped launching as well.
I think the cause was that I mapped `neovide` to a sway mapping and tried to launch it "fullscreen", then it crashed.

**Comment by fredizzimo** [comment] 2023-12-27 13:07
Note that the fix is not yet merged, so you will need to compile it by hand, or use the binaries from here https://github.com/fredizzimo/neovide/actions/runs/7322966077, if you want to test it.

And yes, in some cases it did launch without the fix, when I tested it as well. I think it's related to the initial window size, which is saved in a settings file.

**Comment by REmerald** [comment] 2023-12-27 13:16
@fredizzimo hmm but why did it work on the old commit `ce0174a1`? Just wondering

**Comment by fredizzimo** [comment] 2023-12-27 13:17
Like, I said, sometimes it worked, sometimes not, and it probably depends on the saved window size.

**Comment by REmerald** [comment] 2023-12-27 13:30
> Note that the fix is not yet merged, so you will need to compile it by hand, or use the binaries from here https://github.com/fredizzimo/neovide/actions/runs/7322966077, if you want to test it.
Downloaded the AppImage, and it worked. No crash in "fullscreen" and "half-screen". Thanks!

Also tested the AppImage from the `0.12.0` Assets, crashes the same as the git version. Will definitely need to release `0.12.1` after the fix is merged.

**Closed** 2024-01-04 20:32 UTC
Labels: bug
