### ISSUE TITLE
Macos open with doesnt work

### ISSUE THREAD

**Issue by ta3pks** [neovide/neovide#1682] opened 2022-12-19 13:26 UTC
**Describe the bug**
trying to open a file with neovide using open with opens an empty neovide instance on mac

**To Reproduce**
1. right click a text file in finder
2. hover "open with"
3. select neovide to open with
4. an empty neovide opens instead of the selected file

**Expected behavior**
selected file to open in neovide

**Desktop (please complete the following information):**
 - OS: macOS 13.1 ventura
 - Neovide Version 0.10.3
 - Neovim Version 0.8.1

**Comment by owittek** [comment] 2022-12-20 17:13
Does opening via Spotlight work? Might be related to my issue (https://github.com/neovide/neovide/issues/1679#issue-1500989320)

**Comment by girishji** [comment] 2022-12-21 21:12
Same issue here. 
1) You can right click on a file in Finder,  click "get info", change default application to Neovide. Then double click on the file, it opens empty buffer instead of said file.
2) "open -a Neovide filename" should open filename, but it opens empty buffer. however "open -a Neovide --args filename" opens filename correctly.

**Comment by kabouzeid** [comment] 2023-01-07 14:17
fyi this problem has been reported multiple times. +1 i would also like to have this. hopefully someday someone will make a PR for this

**Comment by NikosEfthias** [comment] 2023-01-09 02:39
tried messing around a little creating a dummy project which is just 
```
fn main() {
    let args: Vec<String> = std::env::args().collect();
    std::fs::write("/tmp/out.txt", args.join(" ")).unwrap();
}
```
then I bundled this using cargo bundle when I set it as default for any file and double click MacOS does not pass any extra arguments.\
I have been researching about this whole night but every bit of info i could find on internet says macos does pass arguments.

If anybody can direct me to some piece of documentation i would be glad to open a pr about this

**Comment by girishji** [comment] 2023-01-09 09:43
Maybe the way neovide is bundled, it is ignoring the filename argument passed by macos when you set neovide as default application for opening a file. Instead it is looking for explicit arguments passed through 'open --args'.

**Comment by kabouzeid** [comment] 2023-01-11 22:07
I have no idea. I wanted to fix this myself, then finally found out about Apple Events, and then lost interest :D

**Comment by NikosEfthias** [comment] 2023-01-11 22:40
okay i will try to test thanks for the headers anyway :D

**Comment by NikosEfthias** [comment] 2023-02-04 17:08
I figured getting filepath out before i open a pr wanted to ask which would be a better way to handle openFile events on mac
1. wait until `applicationDidFinishLaunching` event and pass all files from `openFile` events as `files_to_open` flag into cmd_args and then actually do `start_bridge, start_editor, create_window` thus no extra stuff is needed since everything else works as before
1. start everything and on every `openFile` event start a new buffer (somehow!. I dont know the neovide api to do this yet)

which would be a better way to handle macos doubleclick openfile requests and potentially future file clicks by user as the app runs?

**Comment by NikosEfthias** [comment] 2023-02-04 20:26
I just dont understand how parts communicate on the entire codebase couldn't find anything that could potentially help me open a new buffer or send a raw command to neovim what am i missing here ?

**Comment by sharpenedblade** [comment] 2023-02-05 22:09
> 1. wait until `applicationDidFinishLaunching` event and pass all files from `openFile` events as `files_to_open` flag into cmd_args and then actually do `start_bridge, start_editor, create_window` thus no extra stuff is needed since everything else works as before

This is probably the best approach, it would behave the same on all platforms.

> 2. start everything and on every `openFile` event start a new buffer (somehow!. I dont know the neovide api to do this yet)

This would be the *correct* approach, but it would be better to implement this for all platforms, instead of having macos specific behavior.

> which would be a better way to handle macos doubleclick openfile requests and potentially future file clicks by user as the app runs?

I think using the first approach is better right now. We could revisit this later to implement the *correct* method, preferably for all platforms, at a later date.

**Comment by sharpenedblade** [comment] 2023-02-05 22:15
> I just dont understand how parts communicate on the entire codebase couldn't find anything that could potentially help me open a new buffer or send a raw command to neovim what am i missing here ?

I think the arguments are just passed to the `nvim` command.

**Comment by NikosEfthias** [comment] 2023-02-06 12:42
@sharpenedblade the issue is that openfile event could come any moment after the app is opened so i think would be better to be able to listen throughout the life of neovide process however still i could not figure out how i exactly open new buffers from neovide in rust

**Comment by sharpenedblade** [comment] 2023-02-06 15:39
> @sharpenedblade the issue is that openfile event could come any moment after the app is opened so i think would be better to be able to listen throughout the life of neovide process however still i could not figure out how i exactly open new buffers from neovide in rust

If the user is opening a file using `open` or the finder button, and Neovide is closed, then the openfile event will occur during startup.

**Comment by NikosEfthias** [comment] 2023-02-06 20:31
and if user clicks a file when a neovide process is already running  then that process will receive the notification not a new one

**Comment by sharpenedblade** [comment] 2023-02-06 23:07
> and if user clicks a file when a neovide process is already running then that process will receive the notification not a new one

I think it would be better to just handle it with the "naive" approach, then design a solution for *all* platforms. After this is working, then we could implement a system to handle new file opens on all platforms, and just handle `openFile` there. Building this entirely for macOS would mean rewriting code for other platforms(when we implement it).

**Comment by himhaidar** [comment] 2023-07-17 19:09
Same issue.

macOS: `13.4`
Neovide: `0.10.4`

By default, Neovide isn't enabled for supported files in the Application selection picker. Then, if we force the file to open with a Neovide, it results in an error:

`The document “Output.txt” could not be opened. Neovide cannot open files in the “text” format.`

It's pretty annoying. So ,I switched to `MacVim`, which is rock solid.

**Comment by ta3pks** [comment] 2023-07-18 04:35
> Same issue.
> 
> macOS: `13.4` Neovide: `0.10.4`
> 
> By default, Neovide isn't enabled for supported files in the Application selection picker. Then, if we force the file to open with a Neovide, it results in an error:
> 
> `The document “Output.txt” could not be opened. Neovide cannot open files in the “text” format.`
> 
> It's pretty annoying. So, I switched to `MacVim`, which is rock solid.

MacVim is just vim not neovim isnt it? also neovide comes with some pretty cool animations besides its a community project so I dont think your approach of treating it as a product is correct

**Comment by fredizzimo** [comment] 2023-07-18 06:41
If you are still wondering about the implementation, you should be able to to use the `ParallelCommand::FileDrop` that we already have and use here https://github.com/neovide/neovide/blob/eeac6e76fc19eefe07162148510f723706d49481/src/window/mod.rs#L199-L205

You just need to wait until Neovim has launched and accepts commands before calling it.

**Comment by himhaidar** [comment] 2023-07-18 11:22
> MacVim is just vim not neovim isnt it? also neovide comes with some pretty cool animations besides its a community project so I dont think your approach of treating it as a product is correct

You're right. It uses Vim but it integrates very well with the macOS ecosystem. Neovide does offer some cool features, but the presence of a few minor bugs makes it unusable for me.

I wish I knew some Rust, I would have helped. :/

**Comment by 9mm** [comment] 2023-12-21 14:46
I think i see the problem. It looks like the dropped file event only applies to dragging into the window, NOT the dock icon. Looking now at winit to see if theres some new event or something

**Comment by abhillman** [comment] 2024-01-26 22:19
I wonder if this is related https://github.com/neovide/neovide/issues/2147

**Comment by abhillman** [comment] 2024-01-26 22:32
> Same issue here.
> 
> 1. You can right click on a file in Finder,  click "get info", change default application to Neovide. Then double click on the file, it opens empty buffer instead of said file.
> 2. "open -a Neovide filename" should open filename, but it opens empty buffer. however "open -a Neovide --args filename" opens filename correctly.

Indeed, the issue appears to be that whereas `--args` passes the path to `main(...)` `open -a Neovide <path>` does not.

From the `man` page for `OPEN(1)` (i.e. `man open`):
```
     --args
         All remaining arguments are passed to the opened application in the argv parameter to main().
         These arguments are not opened or interpreted by the open tool.
```

**Comment by abhillman** [comment] 2024-01-26 23:26
Related PR https://github.com/neovide/neovide/pull/2191

**Comment by bogado** [comment] 2024-02-22 16:10
Here I get a "Neovide" cannot open files in the "text" format. That is ironic to say the least.

I do believe that this most be some missing key on a configuration of the application. Basically directing the OS that `Neovide` can open "text" and other types of files.

![image](https://github.com/neovide/neovide/assets/3781/511275d5-84eb-4826-950e-2109ff1d7dca)

**Comment by bogado** [comment] 2024-02-22 16:10
I can drag and drop files once the window is open though.

**Comment by brnt** [comment] 2024-03-13 17:21
Same issue. I can open files directly from the console with:

```sh
$ neovide foo.md
```

I can also drag files onto an existing neovide window and they open correctly, but neither "Open with..." nor double-clicking (with handler set to neovide) works. I get an empty neovide buffer.

Side note @bogado, I added this snippet to `Info.plist` and now neovide is recognized as a handler for all text-ish files.

```xml
  <key>CFBundleDocumentTypes</key>
  <array>
    <dict>
      <key>CFBundleTypeName</key>
      <string>All Text Files</string>
      <key>LSItemContentTypes</key>
      <array>
          <string>public.text</string>
      </array>
      <key>LSHandlerRank</key>
      <string>Owner</string>
    </dict>
  </array>
```

**Comment by brnt** [comment] 2024-03-13 17:28
Looks like @polachok 's PR may address the open-from-finder problem. Fingers crossed...

**Comment by fredizzimo** [comment] 2024-05-17 10:21
This was fixed by:
* https://github.com/neovide/neovide/pull/2395

**Comment by fredizzimo** [comment] 2024-05-18 14:22
Ok, re-opening this.

@polachok

**Comment by falcucci** [comment] 2024-07-12 18:37
This has been fixed.

I usually use two ways to open a file using finder.

open with and drag-and-drop on finder itself.

https://share.cleanshot.com/GY01xzZp

**Closed by falcucci** 2024-07-12 18:37 UTC
Labels: bug, macos
