### ISSUE TITLE
macOS icon should match new style guidelines for size

### ISSUE THREAD

**Issue by 9mm** [neovide/neovide#1978] opened 2023-08-15 13:47 UTC
**Describe the bug**
The neovim icon on MacOS doesn't follow the OSX icon guidelines, so it stands out like a sore thumb:

<img width="1158" alt="image" src="https://github.com/neovide/neovide/assets/1386207/d448947e-cc29-414c-895a-a0aa875cc39e">

Skype is stupid and decided to do it a different way. At least they kept it the same size, but they're a massive company and it's inexcusable. For a tiny project like this, at the very least it would be nice to have the same icon but the proper size, it wouldn't even need to be redesigned to save on effort

Sketch template for app icon:
https://developer.apple.com/design/resources/#macos-apps

Configuring app icon:
https://developer.apple.com/documentation/Xcode/configuring-your-app-icon

App icon in general:
https://developer.apple.com/design/human-interface-guidelines/app-icons

**Desktop (please complete the following information):**

The latest OSX right now is Ventura, however Sonoma is coming out, and it looks like it uses the same size, but in the link above for the sketch template, I would use the Sonoma size to be safe

Edit: I believe they switched to this size about 2 years ago, so this new size is here to stay

**Comment by fredizzimo** [comment] 2023-08-15 14:22
I'm closing this as a duplicate of https://github.com/neovide/neovide/issues/1629.

**Comment by 9mm** [comment] 2023-08-15 14:23
Ah, ok. I searched and didnt see anything. thanks

**Closed** 2023-08-15 14:24 UTC
Labels: bug
