### ISSUE TITLE
how to set italics as bold italic?

### ISSUE THREAD

**Issue by rafaeljacov** [neovide/neovide#2731] opened 2024-07-26 08:48 UTC
![image](https://github.com/user-attachments/assets/00ca8087-08ec-4785-9483-d3aa510dec37)

**Comment by fredizzimo** [comment] 2024-07-26 09:21
You can do that with the font config https://neovide.dev/config-file.html#font

For example
```toml
[[font.italic]]
family = "FiraCode Nerd Font"
style = "Bold Italic"
```

**Comment by rafaeljacov** [comment] 2024-07-26 09:29
> You can do that with the font config https://neovide.dev/config-file.html#font
> 
> For example
> 
> ```toml
> [[font.italic]]
> family = "FiraCode Nerd Font"
> style = "Bold Italic"
> ```

doesn't work

**Comment by fredizzimo** [comment] 2024-07-26 10:02
Are you using Neovide 0.13.3, this was a regression that was fixed in that?

**Comment by rafaeljacov** [comment] 2024-07-26 10:33
> Are you using Neovide 0.13.3, this was a regression that was fixed in that?

yes

**Comment by fredizzimo** [comment] 2024-07-26 10:41
That's strange, it works for me. What's your full `config.toml` file? 

Also make sure that you don't set guifont in your `init.lua`, since that will override the `config.toml` file.

**Comment by rafaeljacov** [comment] 2024-07-26 13:16
> That's strange, it works for me. What's your full `config.toml` file?
> 
> Also make sure that you don't set guifont in your `init.lua`, since that will override the `config.toml` file.

-- Neovide
if vim.g.neovide then
    vim.o.guifont = "SauceCodePro NF:b:h17"
    vim.g.neovide_scale_factor = 1.0
    local change_scale_factor = function(delta)
        vim.g.neovide_scale_factor = vim.g.neovide_scale_factor * delta
    end
    vim.keymap.set("n", "<C-=>", function()
        change_scale_factor(1.25)
    end)
    vim.keymap.set("n", "<C-->", function()
        change_scale_factor(1 / 1.25)
    end)
end

i tried commenting the guifont line but the font  just went back to regular weight

**Comment by rafaeljacov** [comment] 2024-07-26 13:33
how do i make the font bold anyway only through the config.toml?

**Closed** 2024-07-26 13:41 UTC
