### ISSUE TITLE
Popup window near the right edge of screen are out of view.

### ISSUE THREAD

**Issue by lkhphuc** [neovide/neovide#2118] opened 2023-11-09 15:08 UTC
**Describe the bug**
Popup window are out of view.

**To Reproduce**
1. Put cursor on a symbol near the right edge of screen.
3. Open LSP hover window.
5. Popup window are expanded to the right, off-screen. Content cannot be view.

![Screenshot 2023-11-09 at 15 53 01](https://github.com/neovide/neovide/assets/12573521/ae8ed50b-cb4a-47dc-91f6-c446b5a9fc33)

**Expected behavior**
Popup window should stop at the right edge of window or float to the left of screen.
![Screenshot 2023-11-09 at 15 55 47](https://github.com/neovide/neovide/assets/12573521/f5fd6fac-b6b6-47fc-a72b-f10870907231)
![Screenshot 2023-11-09 at 15 57 48](https://github.com/neovide/neovide/assets/12573521/c280633c-1244-4f27-b136-a651b26d4110)

**Desktop (please complete the following information):**
 - OS: macOS 13.5.2
 - Neovide Version 0.11.2
 - Neovim Version NVIM v0.10.0-dev-1496+g4c8fdc018-Homebrew

**Comment by fredizzimo** [comment] 2023-11-09 15:11
This is a duplicate of https://github.com/neovide/neovide/issues/1641 and should be fixed in main

**Closed by fredizzimo** 2023-11-09 15:11 UTC
Labels: bug
