### ISSUE TITLE
Colors more vivid in neovide than elsewhere

### ISSUE THREAD

**Issue by JeWe37** [neovide/neovide#1102] opened 2021-12-20 13:22 UTC
**Describe the bug**
Colors with the same color scheme appear differently as in terminal problems running raw neovim.

**To Reproduce**

The problem is most visible with themes that are not too vibrant by default(but as far as I can tell it is still present everywhere). In the screenshots I am using the shusia option of the sonokai colorscheme.

**Expected behavior**
The colors should match those of terminal applications

**Screenshots**
![image](https://user-images.githubusercontent.com/26010054/146772953-687fa0cf-453f-4190-acc5-da413bf1b7da.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Neovide Version 0.8.0
 - Neovim Version 0.6.0

**Additional context**
I previously used the older Vulkan version of neovide where this issue did not appear. As is, it makes it hard to properly match color schemes and at least in my eyes, the more vivid colors stand out far too much.

**Comment by LoipesMas** [comment] 2021-12-20 21:08
I'm not sure, but I think it might be caused by antialiasing.
![image](https://user-images.githubusercontent.com/46327403/146832454-6c3eadd3-32c7-4648-9465-85d044fcb33e.png)
Neovide on the left, ST on the right.
From what I've seen, the color in the middle of the character is the same, but edges look differently. In Neovide it looks like rgb split, while in ST (and Konsole too, I think) the edges are just less opaque (whidh is how it should be done).

**Comment by LoipesMas** [comment] 2021-12-20 21:28
Indeed, changing font edging from `Edging::SubpixelAntiAlias` to `Edging::AntiAlias` fixes that.
Not sure if neovide is doing something wrong, thus making subpixel antialiasing look bad, or if it's just bad.
![image](https://user-images.githubusercontent.com/46327403/146834988-a3a3db84-96b6-46ce-837d-fdf18a24a34e.png)
Subpixel on the right (current main), normal antialias on the left (after I changed it)

**Comment by JeWe37** [comment] 2021-12-20 21:30
Right, yes, I just tried it out here too by just trying a solid block where it is more clearly visible, and that got me the same result. The question is

**Comment by LoipesMas** [comment] 2021-12-20 21:34
I think some people reported that the fonts look "weird" and this might be the cause. I'm pretty sure non-subpixel is better (or at least more people would prefer it), but I might be wrong. If there isn't a big majority, maybe we could do an option to set which one to use.

**Comment by JeWe37** [comment] 2021-12-20 22:17
Well I tried around a bit but I'll give up on making a setting for tonight. The issue is that the whole font renderer is initialized very early on it seems, even before the settings are read from neovims config, meaning that tweaking anything there won't really help unless you make it update properly. Given that I honestly barely use Rust at all and am not that familiar with the code I'll leave it at that. I just statically changed it for myself for now.

**Comment by Kethku** [comment] 2022-01-24 08:04
Ok so it seems that the issues is fixed for now and nobody has really asked for subpixel font stuff from us since so I'm going to close this.

**Closed by Kethku** 2022-01-24 08:04 UTC
Labels: bug, font rendering

**Comment by orlandosh** [comment] 2023-09-19 18:12
Sorry for commenting on a closed issue, but I have this issue as well. Would you please tell us in more depth how you solved it locally @JeWe37 ?

**Comment by JeWe37** [comment] 2023-09-19 18:20
I don't use Neovide anymore, but it seems that this has become configurable since then, see [here](https://github.com/neovide/neovide/blob/33df9e578c52e285ed40f037908c4fa7330af582/src/renderer/fonts/font_options.rs#L117)

**Comment by fredizzimo** [comment] 2023-09-19 18:42
Can you check if it's the font or the colors in general, by setting the background color for example
`:highlight Normal guibg=#FA8072`? Then check with a color picker what values you get in Neovide and the other terminals.

You can do the same for the fonts by setting a big font to rule out any edging issues and then use `guifg`

**Comment by orlandosh** [comment] 2023-09-19 20:03
sure. tested with monaco and menlo (i found them in my font book app), and same thing
kitty(right colors): ![image](https://github.com/neovide/neovide/assets/84464728/92e5bee3-329b-4724-a097-aadaf74d28e0)
neovide:
![image](https://github.com/neovide/neovide/assets/84464728/33d33f46-e95c-47c1-9046-faed6cfd1200)

colorpicker results
neovide:
![image](https://github.com/neovide/neovide/assets/84464728/69c891fe-dfd6-4f6f-b580-81ed2896dade)

kitty:
![image](https://github.com/neovide/neovide/assets/84464728/5b30859c-000a-4921-9b29-6f0b9940c696)

**Comment by fredizzimo** [comment] 2023-09-19 21:56
It depends on how you define "correct"

The output from Neovide is 250,128,114=#FA8072, exactly as specified in linear RGB values. On the other terminals the output is converted to sRGB 232,137,118=#E88976

Apparently the built in macOS terminal chose to use sRGB for some unexplainable reason, and the other terminal emulators were forced to follow.
* https://github.com/alacritty/alacritty/pull/6602
* https://github.com/kovidgoyal/kitty/issues/2249

That also means that a color scheme designed on Linux or Windows will look wrong on macOS and vice-versa. But apparently that's what macOS users want, so I'm not opposing creating an option to enable sRGB output, but I'm not sure about making that the default.

I acknowledge that the sRGB format is superior, especially since most new monitors are wide gamut, but terminals have traditionally used linear RGB. Most web browsers use sRGB though, and therefore the sRGB colors will match the ones you see in a color picker in the web browser, while the linear colors match the colors you see in most other applications including simple painting programs like Microsoft Paint.

I will however, not re-open this issue, since it was originally clearly about the fonts. If you want sRGB support, you should create a new issue for it.
