### ISSUE TITLE
Freezes on startup until being resized

### ISSUE THREAD

**Issue by aj3423** [neovide/neovide#922] opened 2021-08-29 10:05 UTC
**Describe the bug**
When it launches, the window is not responding to any keyboard clicking, the command bar is black (abnormal color).  Everything becomes normal after resizing the window. And there is also a 20% chance that it works all fine on startup.

**To Reproduce**
1. Launch Neovide
2. Click "i", or any key, nothing happens
3. Resize the window
4. Click "i", it goes to insert mode correctly

**Expected behavior**
Works when it launches.

**Screenshots**
![neovide](https://user-images.githubusercontent.com/4710875/131252122-121a81ff-860a-4bc6-8f52-9d94e0ba62b3.gif)

**Desktop (please complete the following information):**
 - Kali Linux 2021.2 with everything up-to-date
 - Neovide v0.8.0
 - Neovim v0.6.0-dev

**Please run `neovide --log` and paste the contents of the `.log` file here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/7072244/neovide_rCURRENT.log)

**Additional context**

**Comment by Kethku** [comment] 2022-01-20 02:53
I think this may be fixed in main. Please reopen if not.

**Comment by aj3423** [comment] 2022-01-20 13:18
Just tried the main branch, which shows version v0.8.0, problem still exists.

**Comment by fredizzimo** [comment] 2022-01-20 18:44
This looks very similar to this https://github.com/neovide/neovide/issues/960, but that one is reported fixed, and the inputs starts to work when clicking the window, so no actual resize is needed.

**Comment by aj3423** [comment] 2022-05-02 12:28
This problem still exists in verion 0.9.0.

**Comment by MultisampledNight** [comment] 2022-06-30 08:24
The freeze referred to a case where configuration locks were mishandled, not this issue, sorry. I'm not sure how to debug this, too.

**Comment by aj3423** [comment] 2022-11-07 16:01
This seems fixed, thank you guys.

**Comment by aj3423** [comment] 2022-11-15 08:21
It still happens,  but much less likely to happen.

**Comment by kirillrdy** [comment] 2022-11-15 08:25
It stopped happening to me on start up, but still consistently  happens if i resize using  Win+{Left,Right} ( Gnome )

**Comment by fredizzimo** [comment] 2023-08-07 16:05
This should be fixed in Neovide 0.11.0

**Closed by fredizzimo** 2023-08-07 16:05 UTC
Labels: bug

**Comment by meisme-dev** [comment] 2024-03-22 15:46
This still happens for me on Gnome if I resize or move the window, cannot reproduce on any other desktop

> It stopped happening to me on start up, but still consistently happens if i resize using Win+{Left,Right} ( Gnome )
