### ISSUE TITLE
How neovide calculates width and height of its window?

### ISSUE THREAD

**Issue by VladimirMarkelov** [neovide/neovide#333] opened 2020-08-12 03:40 UTC
Two laptops with Windows 10 (one is 2004 another one is 19xx) use the same neovide binary downloaded from releases.
First laptop has 100% scaling(no scaling due to rather low resolution). The second laptop uses 175% scaling. On the first laptop when I pass  `--geometry=120x50`, neovide opens with the same size - that is great. On the second laptop I had to go trial-and-error way. Eventually I realized that the real size of neovide window in characters almost half of what I passed in `--geometry`. It is kind of inconvenient and it looks close to scaling percentage. The same trouble with font size: to make the font the same size as in `neovim-qt`, I had to increase font size in `ginit.vim`. So, it gets incompatible with neovim-qt and if I ever need to switch between them I will have to edit its config(to tune up the font).

Is it possible to fix?

**Comment by Kethku** [comment] 2020-08-18 21:50
Couple points:

1. You can specialize your config by looking for the existence of the g:neovide variable which gets declared on startup.
2. The resolution jump is likely a bug which has to do with the dpi handling. What happens is that the window is initialized with the font settings on startup ignoring the dpi. Then the window adjusts to the dpi settings when it first renders and attempts to keep the same window size. This is the recommended solution when you have multiple monitors with different dpi scaling. However this results in the grid shrinking to match the new font size. As you mentioned this will likely be close to the scaling percentage. I see this as a bug.
3. I'm not sure which is correct between neovide and neovim-qt. The font rendering size interpretation is inherited from skia which is the font renderer for a number of different applications. I'm not sure how we should pick the correct font size as neovim-qt isn't exactly an authority. Maybe we could pick some standard app (chrome?) and try to match it?

**Comment by Kethku** [comment] 2020-08-18 21:52
As with most of the dpi related issues on this project, they got demonstrably worse when we switched to sdl2. I think we may switch back in the not too distant future (or at least provide builds for both), so its possible that this problem will just go away when we swap back. Hard to tell.

**Comment by VladimirMarkelov** [comment] 2020-08-18 22:09
Thanks for the explanation. At this moment it is not a big issue as most of the time I use neovide on my laptop with 100% scale. So, it is not urgent at all. Though, it is good to know that the issue can be fixed(even if it won't happen soon).

**Comment by VladimirMarkelov** [comment] 2020-08-18 22:31
> 3. I'm not sure which is correct between neovide and neovim-qt

As neovide creates a windows with about `150x50` charaters when I pass `--geometry=300x100`, I think, neovide's calculation is incorrect.  

Though, I am not sure about neovim-qt. When I started using it I failed to find how to make it open a windows with a given size(it ignored col&row settings from vim config) , so I just added `call GuiWindowMaximized(1)` to `ginit.vim`. It was not ideal but it was better than default tiny window.

**Comment by j4qfrost** [comment] 2020-08-19 20:48
Sorry, been mia due to a borked machine (again). I think I might have a scaling solution in my snake branch, I'll see if this resolves the problem.

**Comment by Kethku** [comment] 2021-06-27 22:43
@smolck You mentioned configuring the window dimensions in gitter. I responded explaining that currently the window size gets set twice because the initial size is computed using the default font, and then the window tries to resize to match the configured font afterward. This causes the problem where the width and height is not expected using the geometry flag, and also the default screen doesn't show because the window is resized causing it to dismiss (I think). More details on the second issue here: https://github.com/Kethku/neovide/issues/620 I believe both of these problems can be fixed with a couple steps:

As explained in the (outdated) comment in the main file, https://github.com/Kethku/neovide/blob/main/src/main.rs#L50 neovide communicates between the components using commands that are sent via logging channels. One of the channels is a pipe between the editor component and the window component currently used for sending window title updates and mouse enabled status to the front end. I propose we add another command which should be raised when the bridge is done loading the user config.

I believe this would be done here https://github.com/Kethku/neovide/blob/bc1009babc04eb3dbe30c452756173fb9fed0ee5/src/bridge/mod.rs#L286. Note: to send the command likely the bridge would need to take a clone of the WindowCommand sender defined here: https://github.com/Kethku/neovide/blob/main/src/main.rs#L185.

Then I would add some logic which listens to the window commands here: https://github.com/Kethku/neovide/blob/main/src/window/mod.rs#L94 and waits for the init command before continuing. Given that its on its own thread, a reasonable way to do this would be to just spin until we get the right result.

At least this is my current theory for how it might work. I could be completely wrong about why the window dimensions are so screwy. But this is what I would try first.

**Comment by smolck** [comment] 2021-06-29 03:53
Hmm so I tried following along here, but it doesn't seem to make a difference even though it's waiting until after the UI attach to get the initial window dimensions. I can push my changes to a branch so you can see if maybe I'm missing something though.

In any case, perhaps the problem is something else? To reiterate, the problem I see is that for some reason, even despite having smaller dimensions, say 200x50, the winit window resizes to full width (at least when I tested this; in my case full width is 1920) after startup. That doesn't seem like an issue with the size being set before nvim is (fully) loaded to me, but something else? Although I could be wrong.

**Comment by Kethku** [comment] 2021-06-29 19:30
Ok that gives me at least a start to take it from there. Could you push your branch somewhere?

**Comment by smolck** [comment] 2021-06-29 19:33
@Kethku Yup, done: https://github.com/smolck/neovide/tree/win-dimensions

**Comment by Kethku** [comment] 2021-06-29 19:42
k I'll take a look at that in the next couple days. My life is chaos atm so it may be a bit

**Comment by last-partizan** [comment] 2021-07-07 06:17
I'll take a look too.

@Kethku is there a way to get guifont from neovim before neovide is created window? i think with this we can create `CachingShaper` with `FontOptions` at init.

And it should solve issue.

**Comment by Kethku** [comment] 2021-07-07 15:23
I think @smolck's branch here: https://github.com/Kethku/neovide/issues/333#issuecomment-870859843 does just that. But I haven't dug in yet

**Closed** 2021-08-08 18:33 UTC
Labels: bug, DPI Handling, Windowing
