### ISSUE TITLE
macOS cannot close window without frame

### ISSUE THREAD

**Issue by hahuang65** [neovide/neovide#2087] opened 2023-10-21 05:15 UTC
**Describe the bug**
Does not respond to cmd+w on macOS (with `--frame none`)

**To Reproduce**
1. Open `neovide --frame none`
2. Press cmd+w

**Expected behavior**
Window should close (and application if it's the final window)
This is a particular problem for me because I use a tiling window manager ([yabai](https://github.com/koekeishiya/yabai)) and I have muscle memory that presses alt-q (which maps to cmd+w) to close all my windows/applications.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 13.3.1 (22E261)
 - Neovide Version 0.11.2
 - Neovim Version 0.10.0-dev-1363+g2eecb1b85-Homebrew

**Comment by MultisampledNight** [comment] 2023-10-21 16:01
Hi, thanks for reporting!

At least as a quick fix, you can remap <kbd>Cmd</kbd> + <kbd>W</kbd> to `:q` in Neovim, for example in VimScript:

```vim
noremap <D-w> <Cmd>quit<CR>
```

**Comment by crupest** [comment] 2023-11-25 15:54
I can stably reproduce this bug but in another way. I don't have any special map. In no-frame mode, `:q` makes the window freeze. Command + Q quits Neovide as expected like other apps. I think I can give it a try on fixing this bug.

**Comment by hahuang65** [comment] 2024-01-10 17:42
For what it's worth, `neovide --frame buttonless` does exactly what I want... it actually does NOT have a frame in macOS (and has rounded window corners, where as `--frame none` has squared window corners), and allows for closing the window.

**Comment by fredizzimo** [comment] 2024-01-11 01:41
@crupest, regarding that hang, it was encountered again on discord, and we decided to see if refactoring the Window creation to inside the event loop helps. Otherwise, we will report it to Winit.

**Comment by crupest** [comment] 2024-01-11 01:46
That's what I think. I guess the cause is either that we are doing something wrong with event loop and window system or an internal bug in winit.

**Comment by fredizzimo** [comment] 2024-01-11 02:26
For a more detailed description of moving the window creation, see this https://github.com/neovide/neovide/issues/2182#issuecomment-1886098109

**Comment by fredizzimo** [comment] 2024-05-18 17:50
I have a potential fix for this here:
* https://github.com/neovide/neovide/pull/2562

It would be good if someone could test it.

**Closed** 2024-05-19 15:48 UTC
Labels: bug, macos
