### ISSUE TITLE
macos, laggy if move mouse on startup (window being created).

### ISSUE THREAD

**Issue by crupest** [neovide/neovide#2073] opened 2023-10-10 11:43 UTC
**Describe the bug**
Neovide becomes laggy when I move mouse during the startup.
As Neovide will create a maximized window during startup (after click the app icon in dock), during the window being created and zooming out in the screen, if I move mouse, Neovide becomes laggy (maybe losing frames?) and does not recover even after performing some actions.
But when I deliberately keep the mouse not moved and wait for the window created, zoomed out and completely stable, the problem disappears.
It can be reproduced stably in my environment.

**To Reproduce**
1. Click the App icon in Dock
2. Immediately move mouse in the window being created and zooming out.
3. After the window created completely, Neovide becomes laggy (maybe losing frames) and never recovers.

**Expected behavior**
Running fluently of course.

**Screenshots**
Not really useful I think. But if you need one, I'll provide.

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.6 (22G120), Intel CPU, macbook pro 13inch.
 - Neovide Version 0.11.2 (cask from homebrew)
 - Neovim Version (from homebrew)
```
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.0-beta3
```
Logs:
There are two files after run with --log. Both are two long, so I make a zip of them.
Dir `good` for the good one
Dir `bad` for the bug one
[log.zip](https://github.com/neovide/neovide/files/12856695/log.zip)

Feel free to ask me for more info if you need! I love Neovide! Thanks so much!

**Comment by fredizzimo** [comment] 2023-10-10 12:50
@crupest, can you try this branch? 
* https://github.com/neovide/neovide/pull/1977

And to make it even smoother on macOS, launch `nevoide --no-vsync` and set the refresh rate to your monitor refresh rate https://neovide.dev/configuration.html#refresh-rate in your config.

**Comment by crupest** [comment] 2023-10-10 14:16
@fredizzimo Of course sure, I'll try that pr. And if problem disappears, it's ok to just close this issue, as I think cause of this kind bug is very obscured and worth no deep research. Just wait for my test. Thanks!

**Comment by fredizzimo** [comment] 2023-10-10 14:19
@crupest, if it happens with that, we need to check it a bit further, since it's supposed to fix all kinds of problems like these. 

But otherwise, we can link this issue to the PR and close it when it gets merged. It's better to leave it open until that, so that people can find it.

**Comment by crupest** [comment] 2023-10-10 14:48
There is some bad news.
The pr does not fixes it. Disabling vsync and setting refresh-rate does not fix it either. Nor does removing `init.lua` work.
And I also cross testing the pr, vsync and refresh-rate, and it does not work in any case of combination.

By the way, there is some additional symptom that might be helpful for diagnostic.
The cursor is an empty rectangle rather than the normal full rectangle.

I wonder if it is a problem specific to me. Let this issue stay here and see if others run into this bug. But I don't think this bug is of high-priority.

I just keep the mouse a good boy during starting Neovide 😂. Anyway, thanks for building such an amazing app.

**Comment by fredizzimo** [comment] 2023-10-10 15:07
@crupest, the first thing you could check is to run `: let g:neovide_profiler=1` and see what kind of frame rates you get in both cases. 

If that does not help, to get a clue it gets harder to debug, but we do support https://github.com/wolfpld/tracy profiler, so it should be possible to determine what's taking time. Even if you can't read the traces from it yourself, they can be saved and analyzed by someone else.

**Comment by crupest** [comment] 2023-10-10 15:28
@fredizzimo  OK, I'll follow your instructions to get more info for debugging. It's a little later for me now but I'll get back right after testing. Please wait!

**Comment by fredizzimo** [comment] 2023-10-10 15:55
Ok, here's some more instructions for the tracy profiling. if you are able to that.

You should be able to get tracy from homebrew https://formulae.brew.sh/formula/tracy
1. Start tracy
2. Then run `cargo run --profile profiling -- --no-fork`
3. Connect to neovide inside tracy. For me the autoconnect does not always work, and you have to click on the "discovered clients"
4. Click the radio wave icon to stop and save the trace after running for a while

I'm not sure how big the traces will be, but I hope not too big.

**Comment by crupest** [comment] 2023-10-11 13:16
@fredizzimo I was unable to connect Neovide to tracy. I succeeded to build Neovide with command provided by you. And I installed tracy. However, when I started Neovide and check tracy, there was no options to connect. And I checked neovide. It does not listen to any port. Did I miss anything?

**Comment by fredizzimo** [comment] 2023-10-11 13:18
@crupest, Ah, I mistyped the command, it should be `cargo run --profile profiling --features profiling -- --no-fork`? 

So it need to use both the profiling profile, and the profiling feature.

**Comment by crupest** [comment] 2023-10-11 13:52
@fredizzimo The trace is on pr #1977

**Comment by crupest** [comment] 2023-10-11 14:46
Hey, I'm back again. But before the trace, here are some other clues I want to tell. All my test in on pr #1977 , with refresh rate set to 60 and `:let g:neovide_profiler=1`
1. The problem seems always to occur and no more relates to mouse. However, 0.11.2 is related.
2. I try to have a screen record but when I do it, everything becomes slow.
3. When I turn on vsync and have refresh rate set to 60, the frame rate displayed in lefttop float is still up and down, sometimes above 100 and sometimes below 60 a lot. I'm not familiar with vsync things, but is this right? But with `-no-idle`, it is stable around 60.
4. It becomes smooth on turning on `--no-idle`. But not under screen record.

And here is the new trace:
1. `trace1`: nothing
2. `trace2`: `--no-vsync`
3. `trace3`: `--no-idle --no-vsync`

[trace123.zip](https://github.com/neovide/neovide/files/12871317/trace123.zip)

**Comment by fredizzimo** [comment] 2023-10-11 14:53
The graph is not that reliable without `--noidle`, since nothing is rendered unless there are changes or things are animating. 

But if we ignore the graph and concentrate on just how it feels. Does it still feel laggy with `--no-idle` or does that lag disappear too?

**Comment by fredizzimo** [comment] 2023-10-11 14:58
Trace 2 looks strange, it should have `--no-vsync` but it's still waiting for `swap_buffers`,

**Comment by fredizzimo** [comment] 2023-10-11 15:41
@crupest, can you try do do trace2 again. it looks wrong, but I just want to double check

`cargo run --profile profiling --features profiling -- --no-fork  --no-vsync`

**Comment by crupest** [comment] 2023-10-11 15:44
Of course.
[trace4.zip](https://github.com/neovide/neovide/files/12871955/trace4.zip)

**Comment by fredizzimo** [comment] 2023-10-11 15:56
It definitely looks like `--no-vsync` is not working, it's blocking on `swap_buffers`, but strangely it's not blocking when `no-idle` is also specified.

Can you also generate a log with `cargo run --profile profiling --features profiling -- --no-fork  --no-vsync --log`?

**Comment by fredizzimo** [comment] 2023-10-11 16:23
Also how does the traces look like, if you set the refresh rate to something really high, like 9999? For the two `—no-vsync` variations, one with `—no-idle` and one without.

**Comment by crupest** [comment] 2023-10-11 16:32
> Can you also generate a log with cargo run --profile profiling --features profiling -- --no-fork  --no-vsync --log?

Here is the log.
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/12872418/neovide_rCURRENT.log)


> Also how do the traces look like, if you set the refresh rate to something really high, like 9999? For the two `—no-vsync` variations, one with `—no-idle` and one without.

I'm sorry it's late for me again in my timezone. I can't provide you these right now. But I'm pleasant to continue here tomorrow. So please have a wait again. I really appreciate your time and efforts on this.

**Comment by fredizzimo** [comment] 2023-10-11 16:45
Yes, let's continue another day. 

The log did not contain anything useful. So if those traces don't provide any new information, we need to add more logging to determine if this branch is entered https://github.com/neovide/neovide/blob/7aa8d451577d863c171afcdb8765d26264339f45/src/renderer/opengl.rs#L131

If the swap interval is indeed set to `SwapInterval::DontWait`, then it's the vsync is even more broke than I though and our best hope is that someone implements this https://github.com/rust-windowing/winit/issues/2412 and that it fixes it.

**Comment by crupest** [comment] 2023-10-12 14:53
@fredizzimo I'm back. With refresh rate 9999. Here are the trace and log
- `5` is `--no-vsync`
- `6` is `--no-vsync --no-idle`, by the way, it looks slower than refresh rate at 60
[trace56.zip](https://github.com/neovide/neovide/files/12883918/trace56.zip)

**Comment by fredizzimo** [comment] 2023-10-12 15:17
From trace 6 , it looks like it's allowing a few fast frames, and when there's enough buffering it starts to block :disappointed: 

![image](https://github.com/neovide/neovide/assets/9946255/021524b9-10ac-4f09-b468-16e3f1f47b19)


The compositor is probably running at 120 FPS, it allows new frames as fast as possible for roughly 8.3 ms, and after that one frame roughly every 8.3 ms, but that is not constant, and the swaps are most likely not properly synchronised so it will not look good. This interacts badly with the way we detect how long a frame takes since the frames are most likely not presented at that interval. And then when it stabilises again, it takes a long time until the frame time is updated (it's calculated using a moving average). This will make things look choppy, since in most cases t

I think you might be able to make it better by setting the `neovide_refresh_rate` to 120, rather than 60, which you had before. But in order to properly fix this we really need to sync with the compositor and get https://github.com/rust-windowing/winit/issues/2412 implemented.

**Comment by crupest** [comment] 2023-10-12 15:49
If you have found the cause of this problem, I think we can settle here and wait for the root problem to be solved.
I'm interested in UI very much. But this let me feel I really know nothing about it. Next I'll take a look at those issues you referred and have a deep research on it by myself.
Really thank you for your devotion on this. Nobody has the duty to make an open-source always work well for others. It's the mission of us all. I really want to help, not only to report bug, but to contribute my codes. However, I can't.
Thank you again for all your work and the knowledge you have taught me.❤️

**Comment by fredizzimo** [comment] 2023-10-12 15:55
Thank you, I cant fully guarantee that it will work after that, but there's a really good chance that it will.

It should be a pretty easy thing to implement, but I don't own a mac computer myself, so I can't do it. And it looks like no macOS developers are available either here or in the winit repository.

I'm marking this with the [hacktoberfest](https://hacktoberfest.com/) tag, in hope that someone picks it up easier that way. Even winit does not participate in that. You can get it here for the PR that updates to the winit version that uses it.

**Comment by crupest** [comment] 2023-10-14 12:53
@fredizzimo Hi, I have succeeded to port display link api to rust. Here is the diff.
https://github.com/neovide/neovide/compare/improve-render-loop...crupest:neovide:macos-display-link
I hope it can help solve the pain. But I have some problems for the following steps.
I don't know how to use the display link api to solve this issue. Now the api can just run well in rust.
And the display link is specific to __one__ screen, how do we deal with the window movement between screens.
I'm quite new to rust. Do you have any ideas about my coding style?

**Comment by fredizzimo** [comment] 2023-10-14 18:38
@crupest. Thank you that looks like a good start. 

I think ideally we want it integrated into Winit like https://github.com/rust-windowing/winit/pull/2896. But if it's monitor specific, I don't know how that would fit their design. In any case, it's probably better to implement and test it here first, at least it's easier that way.

You should be able to get the current monitor from the window with this https://docs.rs/winit/0.29.1-beta/winit/window/struct.Window.html#method.current_monitor

To solve the problem you will need to some kind of event. that you wait for in the main loop, and that is signalled when the frame callback happens https://developer.apple.com/documentation/corevideo/cvdisplaylinkoutputcallback. The windows implementation uses a condition variable to to signal from a different thread, and you can do it in a similar way from the output callback. I'm not sure if the `inOutputTime`, is needed or not, the documentation seems very unclear to me.

Regarding the coding style, I think everything looks good. But I'm not that experienced with rust either.

**Comment by crupest** [comment] 2023-10-15 16:29
I know it's a relatively complex problem. Actually I had read code of winit and some related discussion before. But it seems the team of winit is struggling on too many things, like cross-platform problems. The code of macos implementation of winit is a little messy for me. I thought the display link api could help directly in Neovide. But I also know it's not very easy, because the problem is not a simple one on just display link api, but lies deeply on the whole ui rendering process. I'll try to talk to winit team and hope I can do something for winit, and then Neovide can solve this kind of problems thoroughly. But it might not be that easy and very soon indeed. Anyway, thank you for your patience on this. Let's just have a break and wait!

**Comment by 9mm** [comment] 2023-10-25 15:50
@crupest what settings did you use for tracy to connect? i tried 127.0.0.1, localhost, etc

It just says "waiting for connection..."

**Comment by fredizzimo** [comment] 2023-10-25 15:58
I also see that tracy 0.10.0 is out, but I'm not sure if Neovide is compatible with that.

**Comment by fredizzimo** [comment] 2023-10-25 16:04
@crupest, I checked this a bit more, but forgot to write a comment. The Winit redraw request is actually per window, so which is always bound to a single montitor, so at least that part does not need any re-design of how things work. 

https://docs.rs/winit/latest/winit/event/enum.WindowEvent.html#variant.RedrawRequested

**Comment by crupest** [comment] 2023-10-25 16:05
@9mm First, you have to confirm the compile command is right.
```
cargo run --profile profiling --features profiling -- --no-fork
```
You need both profile and features.

Second, I didn't use the gui for capturing. Actually I use the cli named `tracy-capture`. Run it with specified output file and it will keep listening until you start neovide. Then after you close neovide the capture stops too. Now you can open the output tracy file  in the gui.

I didn't build with feature at first and tracy didn't begin capture. After turning on it the capture succeeded.

Hope this can help you.

**Comment by crupest** [comment] 2023-10-25 16:11
@9mm Additionally, I didn't pay attention to the address and port. Everything just works fine.

@fredizzimo Ok, I'll take a look on that. It's a little busy for me these days. But I'll try my best to work on it.

**Comment by 9mm** [comment] 2023-10-25 16:11
```
Connecting to 127.0.0.1:8086...
The client you are trying to connect to uses incompatible protocol version.
Make sure you are using the same Tracy version on both client and server.
```

Hmm.. weird

**Comment by fredizzimo** [comment] 2023-10-25 16:12
@9mm, yes try to downgrade to 0.9.1

**Comment by 9mm** [comment] 2023-10-25 16:27
OK, 

```
cargo run --profile profiling --features profiling -- --no-fork -- --clean
```

Produces:

[output.tracy.zip](https://github.com/neovide/neovide/files/13168369/output.tracy.zip)

FWIW i cant reproduce the initial issue, is there a specific thing I can try? I read the thread but if anyone knows off hand any specific commands that have been found or actions?

I have tried moving mouse, copying pasting, doing everything. It runs extremely smooth

**Comment by 9mm** [comment] 2023-10-25 16:28
I also have 100GB of memory and M2 so not sure if that matters 😂

**Comment by fredizzimo** [comment] 2023-10-25 16:34
The vsync issues are very random, and this is only one way it can happen, and I don’t think all systems see any symptoms. I suspect having multiple monitors configured also affects the behavior.

**Comment by crupest** [comment] 2023-10-26 12:49
Yes. This issue might be related to screen, OpenGL and compositor.
I'm using a MacBook Pro with Intel cpu and builtin 60Hz screen. But in previous discussion, we found the compositor runs at 120Hz and OpenGL vsync does not work correctly. So it is quite normal if you can't reproduce it.

**Comment by crupest** [comment] 2023-10-26 12:57
> @crupest, I checked this a bit more, but forgot to write a comment. The Winit redraw request is actually per window, so which is always bound to a single montitor, so at least that part does not need any re-design of how things work.
> 
> https://docs.rs/winit/latest/winit/event/enum.WindowEvent.html#variant.RedrawRequested

The problem is that the window can move between different screen. If you just have one screen, it is simple. But since the display link is bound to a screen, we have to create a new display link when window moves. The most ideal way is there had an event of window movement between screens. But I guess it could be implemented by just `Moved` and check if the screen changes.

**Comment by fredizzimo** [comment] 2023-10-26 13:11
Yes, I guess that's what needs to be done if it's implemented here. But if it's implemented in Winit, I think you can hook into this event https://github.com/rust-windowing/winit/blob/53ca5af48ff5cf17ca0fa0012f1860e582fa9402/src/platform_impl/macos/window_delegate.rs#L417-L428

**Closed** 2023-11-26 11:03 UTC
Labels: bug
