### ISSUE TITLE
Cmd+Shift mappings on macOS don't work anymore

### ISSUE THREAD

**Issue by skanev** [neovide/neovide#1992] opened 2023-08-25 06:58 UTC
**Describe the bug**
Command+Shift mappings have stopped working in neovide. They used to not work, then a `use_logo` option got introduced, then it got removed and they are not working again. Pressing <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>f</kbd> gets reported as `<D-f>` instead of any of `<S-D-f>`, `<D-F>`, and so on.

**To Reproduce**
I'm building the latest `main` branch at the time of writing. An easy way to see it is.
1. Enter insert mode
2. Press `<C-v>` to insert a key literaly
3. Press <kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>f</kbd>
4. You see `<D-f>`

**Expected behavior**
You should see `<S-D-f>`

**Desktop (please complete the following information):**
 - OS: macOS 13.5
 - Neovide Version [e.g. 0.6.0]
 - Neovim Version 0.11.1 on a7c5981

**Comment by fredizzimo** [comment] 2023-08-25 08:13
This is a known issue and was documented as a breaking change for 0.11. 

Closing this as a duplicate of https://github.com/neovide/neovide/issues/1237. Note that I'm still waiting to get for logs with ctrl+shift before reporting the bug upstream to Winit. So, if someone can produce that, we can start moving the bug forward.

**Closed by fredizzimo** 2023-08-25 08:13 UTC
Labels: bug
