### ISSUE TITLE
winbar moves with the text in multigrid mode

### ISSUE THREAD

**Issue by mrshmllow** [neovide/neovide#1550] opened 2022-09-22 06:27 UTC
Using the winbar in neovim moves around when scrolling, despite all other UI elements staying in place
![out](https://user-images.githubusercontent.com/40532058/191671025-d495508c-1815-42ad-9187-59e477fc614b.gif)

Im guessing is likely because the winbar is kinda tacked onto the window contents and not _really_ a UI element?

**Comment by ronisbr** [comment] 2023-10-19 16:07
Is there any work around for this issue? Like disable smooth scrolling with `multigrid`?

**Comment by fredizzimo** [comment] 2023-10-19 16:23
We have this issue open on the Neovim side https://github.com/neovim/neovim/issues/23610.

Unfortunately, it has since then turned out that the built-in borders of floating windows also suffers from the same problem, so we might have to think about some better option to for solving both. I'm not sure if we can do it in Neovide alone or not.

**Comment by fredizzimo** [comment] 2023-12-04 08:36
There's a fix for this in https://github.com/neovide/neovide/pull/2165

**Closed** 2023-12-23 21:57 UTC
Labels: enhancement

**Comment by mikaraunio** [comment] 2024-03-02 01:06
Hmm, I'm still seeing this with lualine winbars in 0.12.2. Scrolling in windows with borders is fine, though.

**Comment by thetic** [comment] 2024-04-17 05:45
i am also seeing this issue in 0.12.2

**Comment by fredizzimo** [comment] 2024-04-17 07:56
The remaining with the winbar should be fixed on main together with Neovim nightly with:
* https://github.com/neovide/neovide/pull/2455
But there was a regression for the floating window borders, which will be fixed here
* https://github.com/neovide/neovide/pull/2487
