### ISSUE TITLE
Numpad period/decimal/dot is not working in insert mode

### ISSUE THREAD

**Issue by brady444** [neovide/neovide#2347] opened 2024-02-08 02:50 UTC
**Describe the bug**
In insert mode, when I press the numpad decimal key while numlock is on, it deletes a character instead of typing ".".

I think this is probably related to [these changes](https://github.com/neovide/neovide/pull/2032) that were merged recently.

**To Reproduce**
1. Open a buffer
2. Go into insert mode
3. Turn numlock on
4. Press the numpad decimal key

**Expected behavior**
A "." character should be typed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 11.4] Windows 11
 - Neovide Version [e.g. 0.6.0] 0.12.2
 - Neovim Version [e.g. 0.5.0] 0.9.5

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/14203745/neovide_rCURRENT.log)

**Additional context**
N/A

**Comment by unknownK19** [comment] 2024-02-10 13:42
I know, I Tried numpad-dot But it do numpad-delete
May be it's new bug.
You can Try xmodmap (On Linux) to resolve this problem your numpad-delete behave as dot(.) (period) keycode

Look what we have to do. First test it what keycode is ? Try xev to know map of numpad-delete,
I got keycode 91 then It means I Need to do 
configuration `keycode 91 = period`
> I don't know what windows tool do as xmodmap.

**Comment by unknownK19** [comment] 2024-02-10 13:47
I know; I tried numpad-dot. But it does numpad-delete.
Maybe it's a new bug.
You can try xmodmap (on Linux) to resolve this problem. Your Numpad-delete behaves as a dot(.) (period) keycode.

Look what we have to do. First, test it. What keycode is it? Try xev to know the map of Numpad-delete.
I got keycode 91, which means I need to do
configuration `keycode 91 = period` Which behave as keycode 60,And then `xmodmap ~/keymap.txt` on startup.
_** Wait until a new update comes. **_
> I don't know what the Windows tool does as an xmodmap.

**Comment by fredizzimo** [comment] 2024-02-11 13:17
This should be fixed on main by https://github.com/neovide/neovide/pull/2334

**Comment by unknownK19** [comment] 2024-03-07 07:21
Well, seems like that's not a bug, Every pro programming don't use Numpad(dot)

Therefor, this is a feature not a bug

**Closed** 2024-05-17 10:02 UTC
Labels: bug
