### ISSUE TITLE
Spaces in path not handled properly when starting over "open with"-dialogue

### ISSUE THREAD

**Issue by FabioMCi** [neovide/neovide#1674] opened 2022-12-12 22:29 UTC
**Describe the bug**
When opening a file from the file-explorer over the "Open With" dialogue (or just "Open", if Neovide is the default for chosen file), if there is a space in the path somewhere, Neovide will fail to read it's contents (and also later to save it), but still open an empty file.

**To Reproduce**
1. Go into a folder with a space in it's path (e.g. by opening "~/Desktop/has space/" (if the folder "has space" exists on the Desktop)) 
2. Right click any file in any folder that is child to this space-containing folder 
3. Select "Open With"
4. Select Neovide

**Expected behavior**
An empty document should open in Neovide (independent of the read file's contents) which can't be written to (E212: Can't open file for writing: no such file or directory) with the path given ""~/Desktop/has space/test"" (two " to each side, file edited assumed to be test, one can see the space in "has space" not to be escaped with "\", also as seen in screenshot the name shown contains a closing " (but the showing tab is configuration-specific))

**Screenshots**
(edited homepath out and replaced with appropriate ~)
![error](https://user-images.githubusercontent.com/111157344/207166851-4d35bf39-be7a-45e6-bc36-e7293a71fcf0.png)

**Desktop (please complete the following information):**
 - OS: Linux 5.15.81-1-MANJARO
 - Neovide Version 0.10.3-1
 - Neovim Version 0.8.1-2 (but error doesn't exist here)
 - (Same behavior in "bare" setup, with unconfigured neovide and manjaro of same version)

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
Not possible as problem doesn't exist when started over the terminal, as path is correctly parsed.

**Additional context**
The problem seems to stem from the way the input is received from the "Open With"-dialogue, as when the path is given from the calling console or using "pure" nvim, no such problem exists.

**Comment by k0ral** [comment] 2022-12-18 10:14
> **Please run neovide --log and paste the contents of the .log file created in the current directory here:**
> Not possible as problem doesn't exist when started over the terminal, as path is correctly parsed.

I actually have the issue when starting neovide from the terminal (`neovide some\ file.txt` or `neovide "some file.txt"`). Logs are pretty unhelpful though, just this:
```
TRACE [neovide] Neovide version: 0.10.3
```

**Comment by anonymous-user** [comment] 2022-12-24 04:31
I am having the same issue with Neovide however if I try the example of `neovide "some file.txt" ` then neovide will create the file with the quote marks as part of the name. Here is a log of opening a file named `new file`, typing hello world, and then saving. Instead of giving an error though, it just created a new file name `"new file"`.

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/10297990/neovide_rCURRENT.log)

I am on Arch Linux running sway.

**Comment by vialrogo** [comment] 2022-12-27 15:02
I have the same issue but, in my case, the problem is with no spaced filenames too: Right click, open with neovide, open a empty neovide with a file <filename>" . In my case, the quote mark is added only and the end. Of course, the file doesn't exist, and is ok to be empty. 

The .desktop file has the line: Exec=neovide %F

Other software and neovim in terminal works normal.

**Comment by fredizzimo** [comment] 2024-01-13 05:27
Does `neovide -- %F` work?

**Comment by fredizzimo** [comment] 2024-01-16 01:17
It was actually probably fixed by
* https://github.com/neovide/neovide/pull/2056

**Closed by fredizzimo** 2024-01-16 01:17 UTC
Labels: bug
