### ISSUE TITLE
Buffer not refreshing when modified outside of Neovide

### ISSUE THREAD

**Issue by alexventuraio** [neovide/neovide#1494] opened 2022-08-19 23:42 UTC
**Describe the bug**
When I open a file in Neovide and do some changes from another editor like the Github app to undo any change in the same file. The buffer inside Neovide does not get updated so I can still see the old code that I removed using Github app.

Then when I try to edit the save it it shows a warning but if I select Y it saves the old changes undone, so that is not expected and there is no way to refresh the buffer other than closing the file and reopen it but what about if you have changes in both sides.

**To Reproduce**
1. Open a file
2. Edit the same file but with another editor like with Sublime Text
3. Go back to Neovide you won't see the latest changes
4. Try to save it and you'll see the warning
5. Select Yes and it will save the old changes done outside of the file

**Expected behavior**
I should be able to edit the file from any place and the changes should be reflected in the Neovide buffer.

**Screenshots**
<img width="530" alt="Screen Shot 2022-08-19 at 18 37 00" src="https://user-images.githubusercontent.com/13169164/185719571-105a1004-dcdb-4bae-a8e6-a86e77902579.png">

**Desktop (please complete the following information):**
 - OS X Monterrey 12.04
 - Neovide Version 0.10.1
 - Neovim Version 0.7.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

**Additional context**

**Comment by MultisampledNight** [comment] 2022-08-20 07:52
Thank you for reporting! Closing as a duplicate of #1477 though, even though I haven't looked into that one yet.

**Closed by MultisampledNight** 2022-08-20 07:52 UTC
Labels: bug

**Comment by alexventuraio** [comment] 2022-11-04 01:27
I added this line to my config and it works fine according to this comment https://github.com/neovim/neovim/issues/20082#issuecomment-1288228566:
```vim
autocmd FocusGained * checktime
```
