### ISSUE TITLE
`...` unpositioned with Monaspace

### ISSUE THREAD

**Issue by codefensory** [neovide/neovide#2671] opened 2024-06-26 14:55 UTC
**Describe the bug**
When I use the `Monaspace` font the `...` and `//` are unpositioned.

**To Reproduce**
1. Set `guifont` to `Monaspace`
2. Add `...` or `//` to script

**Screenshots**
Vim in terminal with `Monaspace`
![image](https://github.com/neovide/neovide/assets/26307524/466f400a-c2b3-4cba-88ab-162dcac2970b)

Neovide with `Monaspace`
![image](https://github.com/neovide/neovide/assets/26307524/134c183e-5ec8-4f54-ba20-1163c11665aa)

Neovide, but if I select the `...` with the visual mode, they appear where they should
![image](https://github.com/neovide/neovide/assets/26307524/cd236ec3-cffc-468a-bddf-199201579948)

**Desktop (please complete the following information):**
 - OS: Arch linux
 - Neovide Version 0.13.1
 - Neovim Version 0.10.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/user-attachments/files/15991035/neovide_rCURRENT.log)

**Comment by fredizzimo** [comment] 2024-06-26 15:19
I'm closing this as a duplicate of 
* https://github.com/neovide/neovide/issues/2539

And I will probably try to fix it in a couple of weeks.

**Closed by fredizzimo** 2024-06-26 15:19 UTC
Labels: bug

**Comment by fredizzimo** [comment] 2024-07-09 09:22
Check this comment for a workaround:
* https://github.com/neovide/neovide/issues/2539#issuecomment-2214823903
