### ISSUE TITLE
Neovide >= 0.12 freezes

### ISSUE THREAD

**Issue by ngseba** [neovide/neovide#2462] opened 2024-04-03 21:25 UTC
While coding I experienced with Neovide getting stuck, there is no crash going on, it just becomes unresponsive and it does not matter how long I wait, it won't become responsive again. **I could not reproduce this with Neovide < 0.12, and couldn't reproduce it on iTerm or the macOS terminal either**.

I believe the bug is somewhere [in here v0.11.2...v0.12.0](https://github.com/neovide/neovide/compare/0.11.2...0.12.0).

The easiest way to reproduce it is by doing multiple fast searches on telescope one after another, this is not the only way to do it, as I experienced it multiples times without having telescope opened, but I found that this way I can reproduce it in about 30 seconds, consistently.

It doesn't seem to be a telescope issue since I reproduced it in other ways as well, but not easily, also the size of the project does not matter, I used telescope in a folder with 3 files and still managed to break it.

I also removed all of my plugins, only left telescope 0.1.6 with no custom configuration at all. It's still reproducing.

**To Reproduce**
1. Open telescope and rapidly search around files

https://github.com/neovide/neovide/assets/48485344/9c4228ad-faa2-46e2-a88b-494d99a9ba6b

Ironically, I wanted to type in telescope, only managed to type in `"te"` and it got stuck.

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 13.3.1]
 - Neovide Version [0.12.2]
 - Neovim Version [e.g. 0.9.5]

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_r2024-04-03_21-30-05.log](https://github.com/neovide/neovide/files/14858716/neovide_r2024-04-03_21-30-05.log)
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/14858717/neovide_rCURRENT.log)

**Additional context**

Seems related to this:
https://github.com/neovide/neovide/issues/2384

I also tried debugging neovide's master using VSCode as mentioned here [#2384 (comment)](https://github.com/neovide/neovide/issues/2384#issuecomment-2025617803) but eventually I got lost.

<img width="913" alt="Screenshot 2024-04-04 at 01 22 47" src="https://github.com/neovide/neovide/assets/48485344/28c5880b-0bbe-4c9e-90f5-5104d53ded7c">

**Comment by fredizzimo** [comment] 2024-04-03 22:24
Yes, I would say it's a duplicate of, which also seems to be render related and macOS specific and render related.
* #2384

Since no one provided logs in the previous issue, I didn't spot this
> TRACE [neovide::renderer::vsync::vsync_macos] Window moved to a new screen, try to re-create the display link.
> TRACE [neovide::renderer::vsync::vsync_macos] Succeeded to create display link.
> TRACE [neovide::renderer::vsync::vsync_macos] Display link started.

Which should give a pretty good hint for starting to look at the issue. 

I will close this one and write more information in the other issue.

**Closed by fredizzimo** 2024-04-03 22:24 UTC
Labels: bug

**Comment by ngseba** [comment] 2024-04-03 23:00
> While coding I experienced with Neovide getting stuck, there is no crash going on, it just becomes unresponsive and it does not matter how long I wait, it won't become responsive again. **I could not reproduce this with Neovide < 0.12, and couldn't reproduce it on iTerm or the macOS terminal either**.
> 
> I believe the bug is somewhere [in here v0.11.2...v0.12.0](https://github.com/neovide/neovide/compare/0.11.2...0.12.0).
> 
> The easiest way to reproduce it is by doing multiple fast searches on telescope one after another, this is not the only way to do it, as I experienced it multiples times without having telescope opened, but I found that this way I can reproduce it in about 30 seconds, consistently.
> 
> It doesn't seem to be a telescope issue since I reproduced it in other ways as well, but not easily, also the size of the project does not matter, I used telescope in a folder with 3 files and still managed to break it.
> 
> I also removed all of my plugins, only left telescope 0.1.6 with no custom configuration at all. It's still reproducing.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Open telescope and rapidly search around files
> 
>  Screen.Recording.2024-04-04.at.00.11.mp4 
> Ironically, I wanted to type in telescope, only managed to type in `"te"` and it got stuck.
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. macOS 13.3.1]
> * Neovide Version [0.12.2]
> * Neovim Version [e.g. 0.9.5]
> 
> **Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:** [neovide_r2024-04-03_21-30-05.log](https://github.com/neovide/neovide/files/14858716/neovide_r2024-04-03_21-30-05.log) [neovide_rCURRENT.log](https://github.com/neovide/neovide/files/14858717/neovide_rCURRENT.log)
> 
> **Additional context** Add any other context about the problem here.
> 
> Seems related to this: #2384

I do remember exiting full screen and resizing the Neovide window, wanted to show that it's still unresponsive. But I had to cut that out of the screen recording as it was too big already.

I believe that the message `TRACE [neovide::renderer::vsync::vsync_macos] Window moved to a new screen, try to re-create the display link.` is due to the fact that I exited full screen and so Neovide returned to the desktop with all the other non full-screen apps, as on macOS all apps create their own desktop when entering full screen.

@fredizzimo Just wanted to mention that we don't go on a false path, I could provide another one this time without exiting full screen or resizing the Neovide window at all.

**Comment by fredizzimo** [comment] 2024-04-03 23:06
It still most likely has something to do with the DisplayLink/Vsync  support, which was introduced in your commit range here:
* https://github.com/neovide/neovide/pull/2102

You can try disabling it by running `neovide --no-vsync`, and see if the freezing stops.

**Comment by ngseba** [comment] 2024-04-03 23:13
I did pass in the `--no-vsync` arg but it's still reproducible.

Not sure if it will provide anything useful, but generated some logs again (ran with both no-vsync and --log). This time I didn't resize or play around with the windows
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/14859452/neovide_rCURRENT.log)
[neovide_r2024-04-03_23-10-38.log](https://github.com/neovide/neovide/files/14859451/neovide_r2024-04-03_23-10-38.log)
