### ISSUE TITLE
Ctrl+6 not working (Tested on Windows)

### ISSUE THREAD

**Issue by borisbrodski** [neovide/neovide#1898] opened 2023-06-16 08:02 UTC
**Describe the bug**
On Windows, on German keyboard, the only keystroke to switch between last two buffers is Ctrl-6, since Ctrl-^ is not available:

```
							*CTRL-^* *CTRL-6*
CTRL-^			Edit the alternate file.  Mostly the alternate file is
			the previously edited file.  This is a quick way to
			toggle between two files.  It is equivalent to ":e #",
			except that it also works when there is no file name.

```
In Neovide, Ctrl-6 is unfortunatly not working!

**To Reproduce**
1. On Windows, install German keyboard layout and switch to it
2. Open Neovide
3. Open another buffer with `:enew` and add some text to it
4. Try Ctrl-6 (it will not switch to the first buffer)
5. Try `:b#` (it will switch to the first buffer and back)

**Expected behavior**
Vim and Neovim default behavior - switching between alternave and current buffers.

**Desktop:**
 - OS: Windows 10 Enterprise
 - Neovide Version 0.10.4
 - Neovim Version 0.8.3, 0.9.1

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

The file is 900k :(

**Additional context**
Workaround I'm using now:

* `nmap <C-&> <C-^>`

This remaps Ctrl-^ to Ctrl-Shift-6 on German keyboard

**Comment by fredizzimo** [comment] 2023-06-16 08:07
This is a duplicate of https://github.com/neovide/neovide/issues/1646

**Closed** 2023-06-16 08:14 UTC
Labels: bug
