### ISSUE TITLE
Could Neovide be expanded to be a full terminal?

### ISSUE THREAD

**Issue by jeanlucthumm** [neovide/neovide#1701] opened 2022-12-26 21:04 UTC
My biggest pain with Neovide is that I need a separate terminal open for my workflow. But also, I would like my terminal to have the same cursor animations and features as Neovide. One solution is to use the nvim built in terminal for everything, but launching nvim just to use a terminal seems the opposite of how it should be.

At a high level, would it be difficult to expand the scope of Neovide into a full terminal?

**Comment by mightyiam** [comment] 2022-12-29 06:49
This is a GUI for neovim... Why?

**Comment by AlexvZyl** [comment] 2022-12-29 10:07
AFAIK, Neovide does not currently have a large team maintaining it.  Keeping it running smoothly is a lot of work already - and adding a feature (that seems quite out of scope and does not really make sense for Neovide specifically) would make the base Neovide worse.  You would have better luck trying to convince Alacritty to add animations.

**Comment by shaunsingh** [comment] 2022-12-30 17:23
The renderer itself still has quite a few issues but it *can* be used in other projects if you'd like. The issue is just finding someone to maintain and support another project like that.

**Closed** 2023-01-06 15:43 UTC
Labels: enhancement

**Comment by MichalNemecek** [comment] 2024-04-04 18:11
> This is a GUI for neovim... Why?

I, for one, think it would be cool to have a terminal with the same visual effects as neovide. It would be somewhat like the smooth scrolling effect on [a VT320 terminal](https://www.youtube.com/watch?v=RuZUPpmXfT0).
