### ISSUE TITLE
Text rendering will grey out when diagnostics error appear as virtual text.

### ISSUE THREAD

**Issue by AllenDang** [neovide/neovide#851] opened 2021-08-01 07:19 UTC
**Describe the bug**
Text rendering will grey out when diagnostics error appear as virtual text.
I thought this might related to refresh, so I set `neovide_no_idle = true`, issue remains.

BTW, neovim-qt works well in the mean time.

**To Reproduce**
1. Open any *.go file.
2. Type a wrong statement which could trigger diagnostic error.

**Expected behavior**
1. Diagnostics error message will be shown and other text looks normal.

**Screenshots**
This is normal text rendering looks like.
![截屏2021-08-01 下午3 06 05](https://user-images.githubusercontent.com/18550/127762688-78212025-c299-4b23-b0a8-37b55f9a7bf2.png)

This is grey out text rendering looks like.
![截屏2021-08-01 下午3 06 16](https://user-images.githubusercontent.com/18550/127762693-894e26c4-da36-4988-840d-5e747c39ab60.png)

**Desktop (please complete the following information):**
 - OS: macOS 11.5.1
 - Neovide Version: newest from master branch
 - Neovim Version: 0.6.0-dev

**Please run `neovide --log` and paste the contents of the `.log` file here:**

**Additional context**

**Comment by PyGamer0** [comment] 2021-08-01 13:17
Can you try with a different colorscheme?

**Comment by Kethku** [comment] 2021-08-02 01:55
I wonder if whatever completion plugin you're using pops a fullscreen window to show diagnostics. That may result in grayed out text due to https://github.com/neovide/neovide/issues/720

**Comment by AllenDang** [comment] 2021-08-06 03:06
Same config with same colorscheme works fine with other neovim GUI like neovim-qt and goneovim. So I don't think it's related to colorscheme. This is the only issue which prevents me to use neovide.

**Comment by Kethku** [comment] 2021-08-06 14:32
Can you upload the log for a session demonstrating the issue by running with - - log

**Comment by Kethku** [comment] 2021-08-06 14:33
Also can you send a link to your config?

**Comment by guolimin1995** [comment] 2021-08-11 04:01
same issue with me.  colorscheme: space-vim-dark

**Comment by Kethku** [comment] 2021-08-11 04:18
Can you link a screen cap?

**Comment by AllenDang** [comment] 2021-08-11 05:00
@Kethku 
![commatolines](https://user-images.githubusercontent.com/18550/128972068-dcbd0771-26ec-473b-ad60-aa993b3b4233.gif)

**Comment by Kethku** [comment] 2021-08-11 06:30
I do appreciate that you already linked that example. I was looking for another example. Its not clear to me whether what you are seeing is a graying out of existing text vs the text being too bold before the diagnostic.

I've encountered that particular variant of the issue on my own machine and think its related to https://github.com/neovide/neovide/issues/589

**Comment by AllenDang** [comment] 2021-08-11 06:55
@Kethku It's a graying out of existing text from my understanding. Text rendering in normal state is same with terminal and other GUI.

**Comment by guolimin1995** [comment] 2021-08-11 07:15
thanks for reply.

![iShot2021-08-11 14](https://user-images.githubusercontent.com/29330637/128984933-d9cc884c-1932-4d82-ae2c-41d5e0d5f8eb.gif)
I don't know if this is normal, fonts is grey when open files.

**Comment by AllenDang** [comment] 2021-08-12 03:08
@Kethku I just built newest code, things are changed a little bit.

![commatolines](https://user-images.githubusercontent.com/18550/129132464-7fe4d063-e14a-4457-aa55-db10f1a9cd55.gif)

**Comment by bmulholland** [comment] 2021-10-04 05:57
This is affecting me too, and it changes the contrast of the text enough that it strains my eyes, so I have to switch to another GUI. Is there any information or debugging I can provide to help fix this?

**Comment by Kethku** [comment] 2021-10-05 04:51
to be honest I have absolutely no idea why this is happening.

My best guess is that the renderer is drawing the same text twice but honestly that doesn't make much sense... What would help a ton is a minimal config repro instructions as I don't see anything like this on my machine

If somebody could reduce their config down and or build up a repro config from a scratch vim and then give a minimal set of steps to repro I could maybe do something about this

**Comment by bmulholland** [comment] 2021-10-05 06:17
Here's a minimal repro: https://github.com/bmulholland/dotfiles/tree/neovide-faded-text/neovim

A repro requires two things: an ?advanced? ?neovim? font (see below) and an LSP for virtual text. My repro has only LSPs for Js/TS/Vue and Ruby; I'm sure you can add other LSPs to make it easier to repro.

About the theme: I tried two different ayu themes and can only reproduce this issue on one of them; seems like a solid clue. Specifically [this neovim-specific one](https://github.com/Shatur/neovim-ayu), while [the normal vim one does not reproduce the issue](https://github.com/Luxed/ayu-vim). It's not quite as visible in this example, but the issue is present and reproducible (there's much less contrast with my full config). To switch between, just [swap the plugin installation](https://github.com/bmulholland/dotfiles/blob/neovide-faded-text/neovim/lua/settings/plugins.lua#L26) and run a PackerSync.

If it helps, here's a screenshot I too of an example. On the left is ayu-vim, which shows full contrast with the virtual text. On the right is neovim-ayu, with the top showing before the LSP loads and displays virtual text, and the bottom showing after that happens:
<img width="1676" alt="Screen Shot 2021-10-04 at 23 12 45" src="https://user-images.githubusercontent.com/247713/135970237-b31945b4-90e3-4859-8903-30c49d64c4be.png">

**Comment by bmulholland** [comment] 2021-11-12 18:04
I could take a stab at figuring this out if you give me a starting point (even just a file...)

**Comment by Kethku** [comment] 2021-12-13 05:26
I don't have a repro of the blurry font issue on my machine. Can somebody repro this again? I recently (as of like a month ago or so) reworked how the font rendering gets sent from the editor to the renderer.

I have a hunch that whats going on is lines of text getting rendered multiple times on top of the same background without clearing. This would cause the subpixel anti-aliasing to act very strangely and cause some characters to be either too bold, or something similar.

I'm not positive, but I thiink that the recent changes prevent this sort of rendering bug.

**Comment by Kethku** [comment] 2021-12-13 09:31
@bmulholland just realized the offer for help. The relevant files are
https://github.com/neovide/neovide/blob/main/src/renderer/grid_renderer.rs#L116 this renders text onto a surface.
https://github.com/neovide/neovide/blob/main/src/editor/window.rs#L246 this draws a series of cells and sends them to the above renderer

My guess is that the issue above happened when a line got draw over and over without clearing. These days we redraw the entire line which I *thiiink* should fix the problem, but its not clear to me because I've never had a consistent repro.

**Comment by bmulholland** [comment] 2021-12-13 16:36
Thanks for the pointers - I'll try some experiments to see if I can figure it out. Happy to do a Zoom/pair with someone more knowledgeable, too.

FWIW, my observations of the issue is the opposite of what you describe: when the issue happens, the darker text is not double dark, but rather the "proper" darkness (i.e. matches the appearance before the issue, and matches how text shows in other UIs).

**Comment by Kethku** [comment] 2021-12-13 19:14
You're probably right. At this point I'm just making guesses. If you end up looking into this, don't hesitate to ask NY question no matter how small. I'm very motivated to make progress on this but have run out of ideas, so enabling another set of eyes is a high priority

**Comment by bmulholland** [comment] 2022-01-12 10:47
Throwing it out there that I'd be happy to jump on a pairing session to work through this with someone

**Comment by fredizzimo** [comment] 2022-01-12 13:07
I tried to reproduce it with your config above, but it does seem to happen on my machine. So I have a few questions.
Does it matter if you use --multigrid or not?
Does `g:neovide_transparency` change things.
Does `g:neovide_window_floating_opacity` change things?
Does it it go back to normal when you are in insert mode, and editing the code, until you press ESC again?
Can you also provide a log file?
And finally if you want to experiment, could you try to edit the highlight group in the plugin itself, to see which highlight group actually causes the issue?

To me, it looks like a transparency/alpha issue, since the darkest part of the color does not seem to change, the font just gets thinner and contain a lot more lighter shades.

**Comment by bmulholland** [comment] 2022-01-13 12:56
**The issue happens only when text with style = 'underline' is present.** See the last bullet point.

Thanks, really appreciate having some guidance on what to test. As I say, happy to pair on this too, if it helps. Tested the following on latest master (98e1a72).

* Happens with and without multigrid
* `g:neovide_transparency` changes how it looks, into a weird shadow thing. Screenshots below.
* `g:neovide_window_floating_opacity` - no change
* "Does it it go back to normal when you are in insert mode" -> No
* "Can you also provide a log file?" -> which log and how do I get it?
* I cut out highlight groups until it stopped happening. This was fast, as the LSP diagnostic section is where it stopped happening. In the end, I removed only [all the `style = 'undercurl'` calls from the theme's LSP section](https://github.com/Shatur/neovim-ayu/blob/afac814359bb03fc5a1cb9d86a45d619a59ba7d9/lua/ayu/init.lua#L103-L106). With those styles in, the issue happens; without, no problems.

Transparency, before diagnostic text:
<img width="430" alt="Screen Shot 2022-01-12 at 15 28 04" src="https://user-images.githubusercontent.com/247713/149158969-5a046a9d-e912-4f75-8d14-dfc7c28e0d34.png">

Transparency, after diagnostic text (note "Missing" on the right, which is the diagnostic):
<img width="435" alt="Screen Shot 2022-01-12 at 15 28 46" src="https://user-images.githubusercontent.com/247713/149159083-432877ef-1267-40f8-afe5-3463902e4908.png">

**Comment by fredizzimo** [comment] 2022-01-13 13:19
Thanks, this was very helpful, I think @Kethku or someone else has enough information now to track the bug down.

But I guess you mean `undercurl` not `underline`, since undercurl is mentioned later in the text?

From the image it looks like there's an outline rendered around the text, which is in the wrong place when the diagnostics is enabled, making the text seem lighter. But I'm not sure that it should be there at all, @Kethku might be right about the text being rendered twice.

**Comment by Kethku** [comment] 2022-01-13 16:22
Yes this is very helpful. I'll do some thinking and experimentation soon

**Comment by Kethku** [comment] 2022-01-13 19:25
https://github.com/neovide/neovide/tree/isolate-undercurl-settings

@bmulholland even with (an approximation of) your minimal repro config, I can't get the issue to reproduce on my machine. However the hint around undercurl was a good one so I've made a change to try and isolate any rendering settings applied while rendering underlines or undercurls. Can you try this branch and see if the issue goes away?

**Comment by IrenejMarc** [comment] 2022-01-19 10:59
The new branch seems to have fixed the issue for me.

![image](https://user-images.githubusercontent.com/15063546/150117207-cd311aa9-08a7-4e46-9b6f-af7d3a7ce36b.png)

**Comment by bmulholland** [comment] 2022-01-19 13:20
I confirm the new branch also fixes the issue for me! Thank you so much, excited to be able to use neovide full time.

**Comment by Kethku** [comment] 2022-01-20 01:03
Ok merged. Thanks for testing

**Closed by Kethku** 2022-01-20 01:03 UTC
Labels: bug
