### ISSUE TITLE
Non-standard window decorations in Gnome/Wayland

### ISSUE THREAD

**Issue by last-partizan** [neovide/neovide#728] opened 2021-06-14 20:49 UTC
![image](https://user-images.githubusercontent.com/301015/121957132-aa296880-cd6a-11eb-9603-b09d0b74164a.png)

Here is wezterm on the right, using correct window decorations.
Neovide on the left, using something like default wayland decorations and no shadows.

It happens only on wayland, i checked xorg session, and it has correct decorations under xorg.

**Comment by Kethku** [comment] 2021-06-14 22:30
@last-partizan does alacritty provide the same weird client?

**Comment by last-partizan** [comment] 2021-06-15 06:57
@Kethku yes, exactly the same.

**Comment by Kethku** [comment] 2021-06-15 07:14
That means this is an upstream issue. Could you raise it in the winit repository? I recommend linking to this one.

**Comment by last-partizan** [comment] 2021-06-15 19:04
https://github.com/rust-windowing/winit/issues/306

They already have similar issue, and that's just "how wayland works".

Is there a way to tell neovide not to use wayland?

**Comment by Kethku** [comment] 2021-06-15 19:12
I have no idea. I'm very much not a linux expert. Would you be willing to look into it? I can answer any questions you might have.

**Comment by Kethku** [comment] 2021-06-15 19:14
we use glutin to create a gl context (which delegates most of the window creation work to winit).

My understanding is that there are multiple ways to get a gl context using x11 or wayland. A keyword that keeps coming up is egl, but I don't really know what the details are. One problem is that whatever solution we use must interact correctly with skia-safe which has limited support. I just fiddled with the settings until a combination seemed to work. Its possible that a different set of settings would work better.

**Comment by last-partizan** [comment] 2021-06-15 19:18
I'll look into it.

Right now i'm searching gnome bug-tracker for related issues, and then i'll try to find workaroung for running neovide using x11.

**Comment by last-partizan** [comment] 2021-06-16 17:00
I created issue for winit.

And looking for some ways to disable wayland. Oh, i found it: https://github.com/rust-windowing/winit/blob/c916eb613734b389d7add7efec7f698ca739bae2/src/platform_impl/linux/mod.rs#L50

```
src/neovide > WINIT_UNIX_BACKEND=x11 cargo run
```

Now neovim uses x11 and normal decorations.

**Comment by last-partizan** [comment] 2022-05-20 06:55
https://github.com/rust-windowing/winit/issues/1967#event-6646624377

Winit issue just got resolved and we can try it with latest winit! (but we're still have our custom branches set up for keyboard fixes).

When everything is resolved we could have nice window decorations on wayland.

**Comment by MultisampledNight** [comment] 2022-05-20 14:28
Indeed. But it may be enough to "avoid" other issues with Xwayland, such as #1278.

**Comment by 4e554c4c** [comment] 2022-09-05 05:36
felt like i should chime in since i can add some context here

Some (in fact, _most_) compositors support server side decorations, and many don't allow you to disable them. See the [wayland.app comparison table](https://wayland.app/protocols/kde-server-decoration#compositor-support) for more info.

Gnome is a bit of an outlier here.
I think it wouldn't be a bad idea to add client side decoration support in neovide, but it should definitely be an option that should be toggleable, so that neovide can be used without client side decorations. The best way to be a good wayland citizen is to be able to perform both client side and server side decorations.

**Comment by kchibisov** [comment] 2022-09-05 05:42
Given that winit v0.27.2 got release you might use its decorations with `sctk-adwaita` feature. They look GNOME-ish.

**Comment by rlees85** [comment] 2022-09-30 08:33
I wouldn't even mind it as it is - looking a bit different - if the titlebar text wasn't white the same as the background.

![Screenshot from 2022-09-30 09-32-47](https://user-images.githubusercontent.com/21251286/193228238-ae868729-9541-456d-b9f7-4ce6674cb9b7.png)

I can see the OP screenshot doesn't have this problem. I have absolutely no clue what about my system is making that happen. All other wayland apps (even those without Gnome decorations) at least have black on white title bars.

**Comment by WhyNotHugo** [comment] 2023-01-07 16:32
This is a Gnome/Mutter issue (or technically, a design choice).

On Wayland there's two types of decorations: client side decorations and server side decorations. Client side decorations are drawn by each application, and each application can render whatever sort of decoration it wants. This is what neovide is doing. Server side decorations are rendered by the compositor, and allow having a system where all window decorations look the same.

Mutter does not support server side decorations. There's been a lot of complaints about it and the devs have asserted again and again that they this won't happen. See: https://gitlab.gnome.org/GNOME/mutter/-/issues/217

So there's no such thing as "standard window decorations" on GNOME/Wayland. Each application renders their own. If all your applications have a consistent style, then it's likely because all your applications use GTK to render their decorations, but if you use anything that doesn't you'll get different decorations.

If you ask me, the GNOME/GTK devs don't want server side decorations to push everyone to use GTK on their application for decorations, but that's just my paranoid speculation.

The reality is that this issue is technically not an issue: it's the result of a design choice by GNOME devs that each application must render its own decoration. There's no such thing as "standard" decorations on GNOME. Neovide is behaving as intended. The only way to "fix" this it to port neovide to use GTK, but that would likely result in problems with decorations in every other compositor out there (plus, I'm not sure that the devs are really interested in porting to GTK).

**Comment by MostHated** [comment] 2023-02-02 23:57
> The only way to "fix" this it to port neovide to use GTK, but that would likely result in problems with decorations in every other compositor out there (plus, I'm not sure that the devs are really interested in porting to GTK).

I would argue that "fixing it" (as a temp workaround, permanent addition, etc) is only a matter of making it so I can make the title bar anything but "white AF". If the apps are rendering their own decorations and whatnot, why does it have to be white? Where/how can I change this (while retaining the intended controls and what not)? I don't really care if it is using server rendering, client rendering, GTK, whatever, I just want the color not to be the whitest white I have ever seen.

**Comment by rlees85** [comment] 2023-02-03 21:33
I'm using neovim-qt now. Running with Wayland support - with a funky white title bar but at least the title bar text is black so I can see what file I have open. A temp fix like that would be more than sufficient if it is at all possible with rust.

**Comment by MostHated** [comment] 2023-02-03 21:54
> I'm using neovim-qt now. Running with Wayland support - with a funky white title bar but at least the title bar text is black so I can see what file I have open. A temp fix like that would be more than sufficient if it is at all possible with rust.

You can probably fix that by doing the following:

```sh
# Run this to install QT5 Config Tool
sudo apt-get install qt5ct
```

Then run it and select the options you want:

<details>
<summary>Select Settings</summary>

![](https://img.instance.id/UIB4Cdc4cGwK/direct)

</details>




Then either add the export below to make all QT apps use it, or do it as a one time thing as seen in the second example below:

```sh
# Either add this to your exports
export QT_QPA_PLATFORMTHEME=qt5ct

# or start the app like this
QT_QPA_PLATFORMTHEME=qt5ct neovim-qt
```

<details>
<summary>End Result</summary>

![](https://img.instance.id/YII6t6SxAjHQ/direct)

</details>

**Comment by fredizzimo** [comment] 2023-07-23 14:08
Hm. Is this still not fixed? [This](https://github.com/neovide/neovide/pull/1870#issuecomment-1646770921] message by @last-partizan seem to indicate that it isn't.

The version of Winit we are using now, should support client side decorations through https://github.com/PolyMeilex/sctk-adwaita. Starting from this pull request https://github.com/rust-windowing/winit/pull/2263.

And as far as I can see we enable that feature.

**Comment by kchibisov** [comment] 2023-07-23 14:12
They are still non-standard and never will standard, because there's no standard on Wayland for client side decorations.

**Comment by fredizzimo** [comment] 2023-07-23 17:20
I'm closing this then, as this is all we can do on the Neovide side.

If you need improvements to decorations, please open issues in the  https://github.com/PolyMeilex/sctk-adwaita repository.

**Closed by fredizzimo** 2023-07-23 17:20 UTC
Labels: bug, Windowing

**Comment by MultisampledNight** [comment] 2023-07-23 17:46
...it might be worth considering to draw our fully own CSD, actually (though of course, there's no pressuring reason to do so since the ones by sctk are just fine, too).

**Comment by kchibisov** [comment] 2023-07-23 17:52
Well, you can do so, but you still don't address the issue, they won't look native.

**Comment by last-partizan** [comment] 2023-07-24 06:29
One thing i'm missing in our sctk-adwaita decorations - is the shadows, and there was some attempts to fix this:

https://github.com/PolyMeilex/sctk-adwaita/issues/4

But i really hope somewhere along the way sctk will integrate libdecor: https://github.com/Smithay/client-toolkit/issues/196, and that's the proper way to do it.

**Comment by kchibisov** [comment] 2023-07-24 06:34
libdecor is doing the exact same thing as sctk, it's not native in any mean. You can write gtk4 plugin the way libdecor does, but it's just technically bad if you look into what they are doing (they force gtk to render to offscreen texture and export it, to update it you forward all input to it. Their cairo rendering is no different than what we have in sctk-adwaita and provides some decorations.

Also, libdecor is gtk3, not gtk4, so it's not native either.

**Comment by rlees85** [comment] 2023-07-24 22:01
Is there a way to actually enable this? Neovide just looks like the same for me completely unusable (white text on a white titlebar)

**Comment by fredizzimo** [comment] 2023-07-24 22:02
@rlees85, it should be enabled on Neovide main. I forgot that we haven't done a  proper release with the new winit version and proper wayland support yet.

**Comment by rlees85** [comment] 2023-07-24 22:07
yep that wasn't a proud moment for me, didn't check the pull request time vs the actual release date... my bad!

**Comment by Jack77793** [comment] 2023-08-21 17:33
I have tried the 0.11.0 version of this programme, and expectedly, neovide uses more acceptable window decoration now and the window could be resized correctly. However, the neovide window are still in lack of shadows in wayland while which is in existence in xwayland. And I found that the ime (ibus) cannot follow the wayland window (which works properly in xwayland one). I wonder that whether this is caused by this programme?

P.S. Whether the window decorations could seemed to be more native in gnome? I think this should be better.

Something may useful:
- OS: NixOS Unstable
- DE: Gnome 44.3
- WM: Mutter 44.3
- Neovide version: 0.11.0
- iBus version: 1.5.28

Here are some screencasts:

**Comment by fredizzimo** [comment] 2023-08-21 17:38
As mentioned previously, we use https://github.com/PolyMeilex/sctk-adwaita for Wayland decorations, so any improvement requests should be added there. 

For the window shadows, there's an open issue already https://github.com/PolyMeilex/sctk-adwaita/issues/4

**Comment by fredizzimo** [comment] 2023-08-21 17:44
For the IME following you should open a new issue. For me it worked correctly on Wayland with KDE Plasma and fcitx5.

**Comment by Jack77793** [comment] 2023-08-22 18:19
Thanks for your reply, and I will follow the information you give.

**Comment by last-partizan** [comment] 2023-11-30 16:24
For anyone interested,

Shadows support got merged into sctk-adwaita: https://github.com/PolyMeilex/sctk-adwaita/pull/43
And we can build it with patched winit.

Try `window-shadows` branch.

I'm not doing PR yet, we're waiting for sctk-adwaita release and winit update to support it.

![image](https://github.com/neovide/neovide/assets/301015/0713ff1a-0a17-46d8-9b74-f5fbeba6b599)

**Comment by kchibisov** [comment] 2023-11-30 16:30
>I'm not doing PR yet, we're waiting for sctk-adwaita release and winit update to support it.

only SCTK adwaita release is required, nothing on winit side. still non-native though.
