### ISSUE TITLE
Scaling wrong on fresh install, font size change has no effect

### ISSUE THREAD

**Issue by YvesCB** [neovide/neovide#1644] opened 2022-11-19 17:08 UTC
**Describe the bug**
Neovide appears scaled up by a factor of about 2 when launching.
This is with a completely blank nvim config and even a fresh OS install. I'm using bspwm right but I've had the same issue with other Linux installs and other WMs.

**To Reproduce**
1. Install Neovide via AUR
2. Launch Neovide

**Expected behavior**
Neovide launches at the correct scaling.

**Screenshots**
I
![image](https://user-images.githubusercontent.com/33640353/202862589-f6aca1fb-d2e7-4bf9-a32c-96883310ea2c.png)

**Desktop (please complete the following information):**
 - OS: Archcraft x86_64 6.0.9-arch1-1
 - Neovide Version 0.10.3
 - Neovim Version 0.8.1

**Comment by kelbyfaessler** [comment] 2023-01-07 00:04
I've also noticed a scaling issue. 

I have my display scaling turned up because its a small laptop screen with a high resolution, so its easier to read stuff if I turn the scaling up. In the terminal its fine (and every other app e.g. browsers and such). 

In neovide text is far too large. If I turn the OS scaling down then neovide looks good but everything else is too small.

**Comment by fredizzimo** [comment] 2024-01-13 05:21
If you are on X11, winit can't detect the scale factor automatically, and you should set the `WINIT_X11_SCALE_FACTOR` environment variable.

But currently there's another bug, that will be fixed by

* https://github.com/neovide/neovide/pull/2218

**Comment by kelbyfaessler** [comment] 2024-01-13 20:51
@fredizzimo I'm on wayland via Fedora (where wayland is now the default). What should I do in this case?

**Comment by fredizzimo** [comment] 2024-01-14 00:02
@kelbyfaessler, I think you need to wai until the #2218 PR is fixed properly. You can already try it, but I don't think it works correctly yet.

But if that does not fix it then we have to debug further to see what the issue is. I assume that you have configured the scale factor for your two monitors to have the same effective dpi, since other programs scale correctly.

I will only have a computer to test and fix this on in around a week, so I might not be able to figure it out until then

**Comment by fredizzimo** [comment] 2024-01-14 00:10
Now, when I look at the screenshot I can that it's possible that I misinterpreted scaling as meaning scale factor, while it's infact the windows size that's wrong.

In that case, I think the issue is the same as this, with the same workaround
* https://github.com/neovide/neovide/issues/2248

**Comment by falcucci** [comment] 2024-11-19 15:08
hey @YvesCB 

could you check if this issue still persist in the latest neovide version or validate follow fredzzimo suggestion if it works for you?

**Comment by fredizzimo** [comment] 2024-12-24 18:53
Closing this due to no response, and unclear bug report

**Closed by fredizzimo** 2024-12-24 18:53 UTC
Labels: bug
