### ISSUE TITLE
Failed to build on MacOS.

### ISSUE THREAD

**Issue by AllenDang** [neovide/neovide#799] opened 2021-07-06 07:58 UTC
**Describe the bug**
Failed to build on MacOS.

**To Reproduce**
1. Run `git clone https://github.com/Kethku/neovide`
2. Run `cd neovide` and `cargo build --release`.

**Expected behavior**
Build success.

**Screenshots**
```sh
❯ cargo build --release
    Updating git submodule `https://github.com/neovim/neovim/`
error: failed to get `nvim-rs` as a dependency of package `neovide v0.7.0 (/Users/allendang/Downloads/neovide)`

Caused by:
  failed to load source for dependency `nvim-rs`

Caused by:
  Unable to update https://github.com/kethku/nvim-rs#109feea9

Caused by:
  failed to update submodule `neovim`

Caused by:
  failed to fetch submodule `neovim` from https://github.com/neovim/neovim/

Caused by:
  failed to authenticate when downloading repository: git@github.com:neovim/neovim/

  * attempted ssh-agent authentication, but no usernames succeeded: `git`

  if the git CLI succeeds then `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  ERROR: Repository not found.
  ; class=Ssh (23); code=Eof (-20)
```

**Desktop (please complete the following information):**
 - OS: macOS 11.4
 - Neovide Version: master branch
 - Neovim Version: 0.5

**Comment by clason** [comment] 2021-07-06 08:08
Works here -- the error looks like network issue on your side?

**Comment by AllenDang** [comment] 2021-07-06 08:24
@clason I could git clone, so I think the key error here is `attempted ssh-agent authentication, but no usernames succeeded: `git``

**Comment by clason** [comment] 2021-07-06 08:27
yes; I don't get that error.

**Comment by shaunsingh** [comment] 2021-07-06 13:21
How did you clone the repo? Can you try using https instead.

**Comment by AllenDang** [comment] 2021-07-07 04:38
@shaunsingh I did use https, check my description for this issue.

**Comment by zrfrank** [comment] 2021-07-08 09:42
Could this be the cause, that the trailing slash of `https://github.com/neovim/neovim/`

```
`git fetch --tags --force --update-head-ok 'https://github.com/neovim/neovim/' 'refs/heads/*:refs/remotes/origin/*' 'HEAD:refs/remotes/origin/HEAD'`
```

For example, `git clone https://github.com/neovim/neovim` works, but `git clone https://github.com/neovim/neovim/` won't.

**Comment by clason** [comment] 2021-07-08 09:46
Again, basic `cargo install --release` works without problems on macOS (both Intel and ARM, 11.4 and 12). So the issue must be more specific. What's your `git` (and `openssl`) version? Do you use the ones from `homebrew` or the stock ones?

**Comment by zrfrank** [comment] 2021-07-08 10:04
It's caused by the trailing slash in the git url as mentioned above. The dependency `kethku/nvim-rs` in its `.gitmodules` used 
```
 1 [submodule "neovim"]
  2     path = neovim
  3     url = https://github.com/neovim/neovim/
  4     branch = master
```
As a workaround, if you go to your cargo's cache, for example,
```
~/.cargo/git/checkouts/nvim-rs-c4c48010ee5540c9/109feea/
`
and correct its `.gitmodules`, i.e. by removing the trailing slash from the git url. Then you can resume your build process. And that submodule should be fetched as expected.

**Comment by AllenDang** [comment] 2021-07-08 14:04
> It's caused by the trailing slash in the git url as mentioned above. The dependency `kethku/nvim-rs` in its `.gitmodules` used
> 
> ```
>  1 [submodule "neovim"]
>   2     path = neovim
>   3     url = https://github.com/neovim/neovim/
>   4     branch = master
> ```
> 
> As a workaround, if you go to your cargo's cache, for example,
> 
> ```
> ~/.cargo/git/checkouts/nvim-rs-c4c48010ee5540c9/109feea/
> ```
> 
> and correct its `.gitmodules`, i.e. by removing the trailing slash from the git url. Then you can resume your build process. And that submodule should be fetched as expected.
> 
> ---Additional---
> This may caused by the difference in git, I use macports git built without any variants, version 2.32.0

Yes, this is the root cause. After manullay modification, build success.

**Comment by Kethku** [comment] 2021-07-08 18:42
Wow thanks for doing the investigation! That means this is an upstream issue in the nvim repository. Currently we use my fork (which has some async fixes that haven't yet merged) so I will create an issue in the appropriate repository and make a fix in my fork

**Comment by Kethku** [comment] 2021-07-08 18:49
Looks like the change has already been made upstream. Uploading my fix now.

**Closed** 2022-01-20 02:39 UTC
Labels: bug
