### ISSUE TITLE
Crash after suspend

### ISSUE THREAD

**Issue by Froloket64** [neovide/neovide#1056] opened 2021-11-23 06:07 UTC
When I suspend (put to sleep mode) my laptop and then wake it up, neovide suddenly crashes and throws a backtrace (full):
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 4, kind: Interrupted, message: "Interrupted system call" }', /home/froloket/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/linux/x11/mod.rs:396:54
stack backtrace:
   0:     0x5586f250899a - std::backtrace_rs::backtrace::libunwind::trace::h94b503c36dba7903
                               at /rustc/1.56.1/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x5586f250899a - std::backtrace_rs::backtrace::trace_unsynchronized::h655a42dea680a248
                               at /rustc/1.56.1/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5586f250899a - std::sys_common::backtrace::_print_fmt::h4110bbd76bdd1b8a
                               at /rustc/1.56.1/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5586f250899a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hb300d7b4bcb7abbc
                               at /rustc/1.56.1/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5586f244914c - core::fmt::write::h872e832230b6cc2d
                               at /rustc/1.56.1/library/core/src/fmt/mod.rs:1150:17
   5:     0x5586f2507334 - std::io::Write::write_fmt::h2def0cb416325237
                               at /rustc/1.56.1/library/std/src/io/mod.rs:1667:15
   6:     0x5586f2507a80 - std::sys_common::backtrace::_print::ha4a4bdfdc780db67
                               at /rustc/1.56.1/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5586f2507a80 - std::sys_common::backtrace::print::h400e21d23f1f70b4
                               at /rustc/1.56.1/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5586f2507a80 - std::panicking::default_hook::{{closure}}::h23ed76f29cbcf4c5
                               at /rustc/1.56.1/library/std/src/panicking.rs:210:50
   9:     0x5586f2506f71 - std::panicking::default_hook::h2cf73a02d82f5d12
                               at /rustc/1.56.1/library/std/src/panicking.rs:227:9
  10:     0x5586f2506f71 - std::panicking::rust_panic_with_hook::hcfb1400d4b55f82b
                               at /rustc/1.56.1/library/std/src/panicking.rs:624:17
  11:     0x5586f2527e38 - std::panicking::begin_panic_handler::{{closure}}::hebf77047a5d73716
                               at /rustc/1.56.1/library/std/src/panicking.rs:521:13
  12:     0x5586f2527db6 - std::sys_common::backtrace::__rust_end_short_backtrace::hd843165880920e54
                               at /rustc/1.56.1/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x5586f2527d72 - rust_begin_unwind
                               at /rustc/1.56.1/library/std/src/panicking.rs:517:5
  14:     0x5586f22f2300 - core::panicking::panic_fmt::h3c031ae033919cfd
                               at /rustc/1.56.1/library/core/src/panicking.rs:101:14
  15:     0x5586f22f2632 - core::result::unwrap_failed::h2008e92911cd236c
                               at /rustc/1.56.1/library/core/src/result.rs:1617:5
  16:     0x5586f23701bb - winit::platform_impl::platform::x11::EventLoop<T>::run::h1f8377e0892737fb
                               at /rustc/1.56.1/library/core/src/result.rs:1299:23
  17:     0x5586f2319730 - winit::platform_impl::platform::EventLoop<T>::run::h40aa6d49eea99947
                               at /home/froloket/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/platform_impl/linux/mod.rs:676:56
  18:     0x5586f23c6fbc - winit::event_loop::EventLoop<T>::run::h5cf512d33cc7d58b
                               at /home/froloket/.cargo/git/checkouts/winit-cdba476763ae8f28/3b5462e/src/event_loop.rs:154:9
  19:     0x5586f23c67ab - neovide::window::window_wrapper::create_window::hef0bd662b0b69ea2
                               at /home/froloket/Git/neovide/src/window/window_wrapper/mod.rs:318:5
  20:     0x5586f23b9c4c - neovide::main::he4a85d59f489604e
                               at /home/froloket/Git/neovide/src/main.rs:171:5
  21:     0x5586f2313ba3 - core::ops::function::FnOnce::call_once::hf9d3b6ec85e20f2b
                               at /rustc/1.56.1/library/core/src/ops/function.rs:227:5
  22:     0x5586f2313ba3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1b2bc5afcc2a89f2
                               at /rustc/1.56.1/library/std/src/sys_common/backtrace.rs:125:18
  23:     0x5586f23b45a4 - main
  24:     0x7fb03a53cb25 - __libc_start_main
  25:     0x5586f230451e - _start
  26:                0x0 - <unknown>
```

I'm using Arch Linux and neovide 0.8.0 (built from 2689bcc)

**PS**
To suspend (on Linux) you can execute `systemctl suspend` if you're using **systemd**

**Comment by dineshKumar777** [comment] 2021-11-23 06:14
Duplicate of #972

**Comment by Froloket64** [comment] 2021-11-23 06:15
Oh, I see, should I close it and join the #972?

**Comment by dineshKumar777** [comment] 2021-11-23 06:16
yes that would be great.

**Closed** 2021-11-23 06:17 UTC
Labels: bug
