### ISSUE TITLE
Smooth scrolling is laggy when “relativenumber” is on

### ISSUE THREAD

**Issue by unclechu** [neovide/neovide#1902] opened 2023-06-19 19:33 UTC
I use https://github.com/psliwka/vim-smoothie for smooth scrolling.

With `set relativenumber` it’s pretty laggy. When I `set norelativenumber` it’s scrolling pretty smoothly.

**Desktop (please complete the following information):**

 - OS: NixOS 23.05.997.ddf4688dc7a (Stoat)
 - Neovide Version: 402382c0a2dd51aa8e14801f80956294eee7fe8f (a pin from #1899 but I think it’s the same in `main` or `0.10.4` release)
 - Neovim Version: `0.9.1`

**Comment by unclechu** [comment] 2023-06-19 19:40
A screencast demonstrating the issue:

https://github.com/neovide/neovide/assets/799353/ba768be1-93b2-4254-98fc-bdeaacba74a3

It shows it’s scrolling smoothly when `rnu` is off and then it’s getting very laggy when `rnu` is on.

**Comment by unclechu** [comment] 2023-06-19 19:45
A screencast showing that in TUI with `rnu` the scroll is smooth too. Just to confirm it’s not the neovim itself or the plugin that gets laggy in case of `rnu`.

https://github.com/neovide/neovide/assets/799353/9f7a588a-267e-4f7f-be3c-b5255affa7aa

**Comment by fredizzimo** [comment] 2023-06-19 19:56
This is a duplicate of https://github.com/neovide/neovide/issues/1519, but leaving this open for now as it provides more information.

This should fix it https://github.com/neovide/neovide/pull/1870, but does not contain the input fixes.

**Comment by unclechu** [comment] 2023-06-19 23:42
@fredizzimo indeed the native `--multigrid`/`NEOVIDE_MULTIGRID=1` smoothing with the plugin turned off performs much better. Though still, when relative numbers turned on holding `j` or `k` to repeat moving up or down lags a bit.

**Comment by everdimension** [comment] 2023-06-20 08:41
Just noticed a very similar issue, but about the cursor, not scrolling (smooth scrolling seems to be turned off by default and I have not enabled it)

I have a very quick keyboard repeat rate setup, so the cursor flies pretty fast
<details>
<summary>(if you wonder)</summary>

```sh
defaults write NSGlobalDomain KeyRepeat -int 1
defaults write NSGlobalDomain InitialKeyRepeat -int 10
```
</details>

As soon as I turn on `:set relativenumber`, cursor starts lagging, FPS seemingly drops to like 15-20 frames.

I can record a screencast if needed

Specs:
**MacOS 13.4, Apple M1
neovide 0.10.4**

**Comment by isakbm** [comment] 2023-10-08 13:10
## Description

I am experiencing the same or similar issue.

When scrolling with relative line numbering the rendering of frames seems so slow that scrolling becomes very janky, even without any smooth scrolling enabled. Also seems to be worsened by having a file with different highlights (syntax highlighting).

> NOTE: I do not have this issue in iTerm2

## Specs
- MacOS 13.3.1 (a) Apple M1
- nevoide 0.11.2
- nvim v0.9.2  + LuaJIT 2.1.0-beta3

**Comment by fredizzimo** [comment] 2023-10-08 14:11
@isakbm, can you try the following, as far as I know it should fix the problem
* https://github.com/neovide/neovide/pull/1977

On macOS you furthermore need to start with `neovide —no-vsync` and in your configuration set `g:neovide_refreshrate` to your monitor’s refresh rate, to make it a bit smoother until proper vsync is implemented for it.

**Comment by isakbm** [comment] 2023-10-08 14:12
For now while waiting for #1977  ... I decided to just add this kind of workaround to my `init.lua` maybe someone else finds it useful

```lua
  do
    -- register autocommand callacks to cleverly toggle
    -- relative numbers when scrolling, .. this works
    -- around the issue with frames dropped in neovide
    -- when scrolling quickly with relative numbering on

    -- this autocommand turns relative numbering off when we begin to scroll
    vim.api.nvim_create_autocmd({ "WinScrolled" }, {
      callback = function(ev)
        if vim.o.relativenumber then
          vim.cmd('set relativenumber norelativenumber')
        end
      end
    })

    -- this autocommand turns relative numberin on when we have idled (stopped scrolling)
    vim.api.nvim_create_autocmd({ "CursorHold", "CursorHoldI"}, {
      callback = function(ev)
        if not vim.o.relativenumber then
          vim.cmd('set relativenumber relativenumber')
        end
      end
    })
  end
```

**Comment by isakbm** [comment] 2023-10-08 14:17
> @isakbm, can you try the following, as far as I know it should fix the problem
> 
> * [Improve render loop #1977](https://github.com/neovide/neovide/pull/1977)
> 
> On macOS you furthermore need to start with `neovide —no-vsync` and in your configuration set `g:neovide_refreshrate` to your monitor’s refresh rate, to make it a bit smoother until proper vsync is implemented for it.

@fredizzimo , you would like me to check out that branch and build it locally?

I already tried the `--no-vsync` and setting the framerate to `60` on the current version that I am on `v0.9.2` .

**Comment by fredizzimo** [comment] 2023-10-08 14:22
@isakbm, yes it would be good to confirm that it fixes it.

You can either build locally, or use the CI artifacts https://github.com/neovide/neovide/actions/runs/6377740408

**Comment by isakbm** [comment] 2023-10-08 15:15
> @isakbm, yes it would be good to confirm that it fixes it.
> 
> You can either build locally, or use the CI artifacts https://github.com/neovide/neovide/actions/runs/6377740408

I'll get back to you as soon as I have found the time to look into this 🤞

**Closed** 2023-11-01 18:54 UTC
Labels: bug
