### ISSUE TITLE
Neovide crashes instantly

### ISSUE THREAD

**Issue by Tomkoid** [neovide/neovide#1384] opened 2022-07-03 18:06 UTC
Recently I updated Neovide from version 0.8.0 to 0.9.0, but when I launched it, it instantly crashed. I tried to use --nofork argument to see what is the issue and I got this panic error:

```
thread 'main' panicked at 'attempt to divide by zero', src/window/mod.rs:207:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I managed to fix it by building it from source and replacing scale_factor as 1 at line 207 in src/window/mod.rs

**Comment by MultisampledNight** [comment] 2022-07-03 18:08
I'll just copy over what I wrote at #1383, which you closed (I guess accidentally):

Could you provide us with some environment information? Which scale factor is the actually yielded one? What's your `xrandr` setup, or whatever the equivalent on your system (which, actually?) is?

**Comment by Tomkoid** [comment] 2022-07-03 18:12
> I'll just copy over what I wrote at #1383, which you closed (I guess accidentally):
> 
> Could you provide us with some environment information? Which scale factor is the actually yielded one? What's your `xrandr` setup, or whatever the equivalent on your system (which, actually?) is?

I actually use Wayland, but it also didn't work in Xorg. There is xrandr output:

```
Screen 0: minimum 16 x 16, current 1366 x 768, maximum 32767 x 32767
XWAYLAND0 connected 1360x768+0+0 (normal left inverted right x axis y axis) 340mm x 190mm
   1360x768      59.80*+
   1024x768      59.92
   800x600       59.86
   640x480       59.38
   320x240       59.52
   720x480       59.71
   640x400       59.95
   320x200       58.96
   1280x720      59.86
   1024x576      59.90
   864x486       59.92
   720x400       59.55
   640x350       59.77
```

**Comment by TheMagzuz** [comment] 2022-07-29 22:01
This seems to be a duplicate of #1307, where any scaling factor less than 1 is rounded to 0. A temporary fix, at least on X11, would be to force the scaling factor to be 1 by prefixing the neovide command with `WINIT_X11_SCALE_FACTOR=1`

**Closed** 2022-08-06 12:33 UTC
Labels: bug
