### ISSUE TITLE
Inconsistent titlebar on Gnome Wayland

### ISSUE THREAD

**Issue by vinicius507** [neovide/neovide#1445] opened 2022-08-03 00:26 UTC
**Describe the bug**
Neovide's titlebar on Wayland is inconsistent with GTK settings on Gnome Wayland.

**To Reproduce**
1. Install Neovide
2. Open Neovide in a wayland session

**Expected behavior**
A titlebar consistent with the GTK theming

**Screenshots**
![image](https://user-images.githubusercontent.com/6608056/182498909-5efb65ba-a58b-4b1d-8f6f-36f4f06ccfb7.png)
_GTK titlebar_
![image](https://user-images.githubusercontent.com/6608056/182497815-3b1adfa3-1a2f-4582-a884-f051ca9a25be.png)
_Neovide titlebar_

**Desktop (please complete the following information):**
 - OS: EndeavourOSz
 - Neovide Version: 0.9.0
 - Neovim Version: v0.7.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
https://pastebin.com/k7QcBynW

**Additional context**
None

**Comment by akhilman** [comment] 2022-09-20 04:02
Winit 0.27.0 has the environment variable to toggle dark decoration: WINIT_WAYLAND_CSD_THEME=dark
https://github.com/rust-windowing/winit/releases/tag/v0.27.0

**Comment by fredizzimo** [comment] 2023-06-14 22:25
We have now updated to Winit 0.28.6 win master. Could you try if the above environment variable works?

**Comment by akhilman** [comment] 2023-06-14 22:45
> We have now updated to Winit 0.28.6 win master. Could you try if the above environment variable works?

Strangely, the environment variable has no effect on neovid's decoration color. At the same time, egui with the same winit 0.28 changes the decoration according to the environment variable.

**Comment by fredizzimo** [comment] 2023-06-14 22:48
Ok, we still need to do something on our side then, but I don't have time to investigate now.

**Comment by MultisampledNight** [comment] 2023-07-08 21:52
Hi! I believe this is a duplicate of #728, I'll close this issue in favor of the older one. Thanks for reporting though!

**Closed by MultisampledNight** 2023-07-08 21:52 UTC
Labels: bug, Windowing
