### ISSUE TITLE
can't map <c-s-v>

### ISSUE THREAD

**Issue by Mr-LLLLL** [neovide/neovide#2017] opened 2023-09-09 09:36 UTC
**Describe the bug**
can't map <ctrl+shift+v> in any mode, the behavior is normar only nvim.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Neovide Version 0.11.2
 - Neovim Version v0.9.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

**Additional context**

**Comment by MultisampledNight** [comment] 2023-09-09 10:56
Hi, thanks for reporting! Could you try `<C-V>` (note the capitalization of the `V`)?

**Comment by Mr-LLLLL** [comment] 2023-09-09 11:09
> Hi, thanks for reporting! Could you try `<C-V>` (note the capitalization of the `V`)?

i try it;
if i mapped `<c-V>`, and i found `<c-v>` is worked like `<c-V>` in neovide. but it's goods in nvim.

by a way:
i test in 0.10.4, `<c-s-v>` is work goods like nvim.
0.11.x (all version) will have the bug above.

**Comment by fredizzimo** [comment] 2023-09-09 11:12
`<C-V>` and `<C-v>` are actually the same in Neovim due to legacy reason, and that's not something we can do about. The actual mapping actual overwrites the previous one if you try to do that.

From https://neovim.io/doc/user/intro.html (the notation section)

> CTRL-{char} {char} typed as a control character; that is, typing {char}
while holding the CTRL key down. The case of {char} is
ignored; thus CTRL-A and CTRL-a are equivalent. But in
some terminals and environments, using the SHIFT key will
produce a distinct code (e.g. CTRL-SHIFT-a); in these
environments using the SHIFT key will not trigger commands
such as CTRL-A

But Neovide produces `<C-S-V>` as a different mapping, so you should be able to use that. `<C-S-v>` might also work, but I'm not sure. 

I'm just testing this myself now, on Windows, and yes it's broken for some reason. I'm pretty sure it used to work.

**Comment by Mr-LLLLL** [comment] 2023-09-09 11:17
> -a are equivalent. But in



> `<C-V>` and `<C-v>` are actually the same in Neovim due to legacy reason, and that's not something we can do about. The actual mapping actual overwrites the previous one if you try to do that.
> 
> From https://neovim.io/doc/user/intro.html (the notation section)
> 
> > CTRL-{char} {char} typed as a control character; that is, typing {char}
> > while holding the CTRL key down. The case of {char} is
> > ignored; thus CTRL-A and CTRL-a are equivalent. But in
> > some terminals and environments, using the SHIFT key will
> > produce a distinct code (e.g. CTRL-SHIFT-a); in these
> > environments using the SHIFT key will not trigger commands
> > such as CTRL-A
> 
> But Neovide produces `<C-S-V>` as a different mapping, so you should be able to use that. `<C-S-v>` might also work, but I'm not sure.
> 
> I'm just testing this myself now, on Windows, and yes it's broken for some reason. I'm pretty sure it used to work.

i'm just testing your talked, it's not work `<c-S-V>`(no matther capitalization of any), my system is ubuntu 22.04

**Comment by Mr-LLLLL** [comment] 2023-09-09 11:17
> > -a are equivalent. But in
> 
> > `<C-V>` and `<C-v>` are actually the same in Neovim due to legacy reason, and that's not something we can do about. The actual mapping actual overwrites the previous one if you try to do that.
> > From https://neovim.io/doc/user/intro.html (the notation section)
> > > CTRL-{char} {char} typed as a control character; that is, typing {char}
> > > while holding the CTRL key down. The case of {char} is
> > > ignored; thus CTRL-A and CTRL-a are equivalent. But in
> > > some terminals and environments, using the SHIFT key will
> > > produce a distinct code (e.g. CTRL-SHIFT-a); in these
> > > environments using the SHIFT key will not trigger commands
> > > such as CTRL-A
> > 
> > 
> > But Neovide produces `<C-S-V>` as a different mapping, so you should be able to use that. `<C-S-v>` might also work, but I'm not sure.
> > I'm just testing this myself now, on Windows, and yes it's broken for some reason. I'm pretty sure it used to work.
> 
> i'm just testing your talked, it's not work `<c-S-V>`(no matther capitalization of any), my system is ubuntu 22.04

**Comment by fredizzimo** [comment] 2023-09-09 11:18
Yes, as I mentioned, it's broken on my system as well. I know the reason, we are always stripping of the `shift`, so no I need to think about a way to fix this without breaking anything else.

**Comment by Mr-LLLLL** [comment] 2023-09-09 11:20
> Yes, as I mentioned, it's broken on my system as well. I know the reason, we are always stripping of the `shift`, so no I need to think about a way to fix this without breaking anything else.

i am sorry, i misunderstand; but why version 0.10.4, it's work well?

**Comment by fredizzimo** [comment] 2023-09-09 11:21
There were a lot of changes to the keyboard input in 0.11

**Comment by Mr-LLLLL** [comment] 2023-09-09 11:24
thanks; i will be read neovide source, try to solve it.

**Comment by fredizzimo** [comment] 2023-09-09 11:34
I know what the problem is. We never send the shift state to neovim unless the pressed key is a special key like `space`, `enter` or `F1`. 

But the CTRL key combinations are special cased in Neovim to require shift, but I think only for standard `a-Z` and nothing else.  But I'm not fully sure about that. So we need to figure out the exact situations we need to send shift. Depending on how Neovim deals with it, it might even be OK to always do so. But probably not, because then some mappings like `$`, might suddenly break, requiring `<S-$>`. 

We also have to remember that according to the Neovim documentation, the alt based mappings are documented to not need shift, but here's shift is allowed. But again I'm not sure how it deals with special characters.
> For a readable mapping command the `<A-k>` form can be used.  Note that `<A-k>`
and `<A-K>` are different, the latter will use an upper case letter.  Actually,
`<A-K>` and `<A-S-K>` are the same.  Instead of "A" you can use "M".  If you have
an actual Meta modifier key, please see [:map-meta-keys](https://neovim.io/doc/user/map.html#%3Amap-meta-keys).

**Comment by fredizzimo** [comment] 2023-09-09 11:38
To always send shift, it's just a matter of moving `is_special` from here https://github.com/neovide/neovide/blob/a6018383d45f4c8ec3e86e899d60a12dc67c7b9f/src/window/keyboard_manager.rs#L125

That fixes the `<C-S-V>` mapping, but as explained might break a lot of other things.

**Comment by fredizzimo** [comment] 2023-09-09 11:52
Based on my initial testing, that seems to actually work for everything I have tried. I check the Neovim source code now to verify what it's actaully doing, and then put up a PR for more extensive testing

**Comment by Mr-LLLLL** [comment] 2023-09-09 11:59
thank you @fredizzimo, i read neovide source code by now, and found it's dfficult for me. rust is hard, i am rookie for rust. i thnk i can't help anything.

**Comment by fredizzimo** [comment] 2023-09-09 12:00
Searching for issues here, apparently that can break some stuff, https://github.com/neovide/neovide/pull/1547. So, we might need to re-introduce, the exact thing that was done in that PR.

**Comment by fredizzimo** [comment] 2023-09-09 12:10
We have to ensure that we follow the exact same logic (same character ranges) as https://github.com/neovim/neovim/blob/c422722b2e94b94d7f9374dbae12f17580cd1d41/src/nvim/keycodes.c#L764-L799 and elsewhere in that file.

**Comment by fredizzimo** [comment] 2023-09-09 13:46
If I'm correct, the relevant piece looks like this:
```c
  // Command-key and ctrl are special
  if (!(modifiers & MOD_MASK_CMD) && !(modifiers & MOD_MASK_CTRL)) {
    if ((modifiers & MOD_MASK_SHIFT) && ASCII_ISALPHA(key)) {
      key = TOUPPER_ASC(key);
      modifiers &= ~MOD_MASK_SHIFT;
    }
  }
```
So, Neovim internally, always removes shift and converts to an uppercase character if neither CMD or CTRL is pressed. And the character is a regular alpha character.

This means that Neovide can do the reverse of that. Only include shift if CMD or CTRL is pressed, and the character is an alpha character. 

That also, at least partially fixes https://github.com/neovide/neovide/issues/1237, but perhaps not in the way it was supposed to be fixed.

**Comment by fredizzimo** [comment] 2023-09-09 18:22
There's now a PR open that should fix the issue https://github.com/neovide/neovide/pull/2018

**Comment by JamesWidman** [comment] 2023-09-10 12:39
> NOTE: That the `CMD` condition should perhaps not be there at all [neovim/neovim#25068](https://github.com/neovim/neovim/issues/25068).

I'm not sure I follow the reasoning here (and fwiw i'd really like it if we could keep shift if cmd/super/logo is present, because that fixes things for me that broke in 0.11.0).

in case it helps, i made a table that shows, for each of the 16 possible combinations of the states of the four modifier keys (plus the 'y' key), the output produced by neovide at 3 different versions, the last of which is an experimental patch of my own. I'm using neovide with neovim 0.9.2. 

In each case, in insert mode, i entered `<ctrl-v>` followed by the key combo for the row:

| M | C | S | D | 0.10.4        | main/a601838  | experimental  |
|---|---|---|---|---------------|---------------|---------------|
| 0 | 0 | 0 | 0 | y             | y             | y             |
| 0 | 0 | 0 | 1 | `<D-y>`       | `<D-y>`       | `<D-y>`       |
| 0 | 0 | 1 | 0 | Y             | Y             | Y             |
| 0 | 0 | 1 | 1 | `<S-D-y>`     | `<D-y>`       | `<S-D-y>`     |
| 0 | 1 | 0 | 0 | ^Y            | ^Y            | ^Y            |
| 0 | 1 | 0 | 1 | `<C-D-Y>`     | `<C-D-Y>`     | `<C-D-Y>`     |
| 0 | 1 | 1 | 0 | `<C-S-Y>`     | ^Y            | `<C-S-Y>`     |
| 0 | 1 | 1 | 1 | `<C-S-D-Y>`   | `<C-D-Y>`     | `<C-S-D-Y>`   |
| 1 | 0 | 0 | 0 | `<M-y>`       | `<M-y>`       | `<M-y>`       |
| 1 | 0 | 0 | 1 | `<M-D-y>`     | `<M-D-y>`     | `<M-D-y>`     |
| 1 | 0 | 1 | 0 | `<M-Y>`       | `<M-Y>`       | `<M-Y>`       |
| 1 | 0 | 1 | 1 | `<M-S-D-Y>`   | `<M-S-D-y>`   | `<M-S-D-y>`   |
| 1 | 1 | 0 | 0 | `<M-C-Y>`     | `<M-C-Y>`     | `<M-C-Y>`     |
| 1 | 1 | 0 | 1 | `<M-C-D-Y>`   | `<M-C-D-Y>`   | `<M-C-D-Y>`   |
| 1 | 1 | 1 | 0 | `<M-C-S-Y>`   | `<M-C-S-Y>`   | `<M-C-S-Y>`   |
| 1 | 1 | 1 | 1 | `<M-C-S-D-Y>` | `<M-C-S-D-Y>` | `<M-C-S-D-Y>` |


(in the case of `^Y` the actual character inserted was U+0019, and this UTF-8, so it's one byte with value `0x19`.)

The diff for my experimental patch is:

```diff
diff --git a/src/window/keyboard_manager.rs b/src/window/keyboard_manager.rs
index f86c5e1..878fa03 100644
--- a/src/window/keyboard_manager.rs
+++ b/src/window/keyboard_manager.rs
@@ -120,9 +120,15 @@ impl KeyboardManager {
     pub fn format_modifier_string(&self, is_special: bool) -> String {
         // Is special is used for special keys so that all modifiers are always included
         // It's also true with alt_is_meta is set to true.
-        // When the key is not special, shift is removed, since the base character is already
-        // shifted. Furthermore on macOS, meta is additionally removed when alt_is_meta is set to false
-        let shift = or_empty(self.modifiers.state().shift_key() && is_special, "S-");
+        // When the key is not special and there are no other modifiers, shift is removed, since the base character is already
+        // shifted. (If other modifiers are set in addition to shift, then the base character might be the lower-case variant.)
+        // Furthermore on macOS, meta is additionally removed when alt_is_meta is set to false
+        let include_shift: bool = is_special
+            || self.modifiers.state().control_key()
+            || self.modifiers.state().super_key()
+            || (use_alt() && self.modifiers.state().alt_key());
+
+        let shift = or_empty(include_shift && self.modifiers.state().shift_key(), "S-");
         let ctrl = or_empty(self.modifiers.state().control_key(), "C-");
         let alt = or_empty(
             self.modifiers.state().alt_key() && (use_alt() || is_special),
```

So far it's been working well for me (on macOS 13.5.2).

Should I submit a pull request?

**Comment by JamesWidman** [comment] 2023-09-10 12:57
> > NOTE: That the `CMD` condition should perhaps not be there at all [neovim/neovim#25068](https://github.com/neovim/neovim/issues/25068).
> 
> I'm not sure I follow the reasoning here

to clarify: I see that neovim doesn't normalize different spellings of "cmd + shift + $letter", and this could mean that different clients may send different strings for the same key combo, which makes mappings non-portable across different GUIs, but...  does that mean we have to maintain the regression that was introduced in neovide 0.11.0?

 I mean, maybe i'll have to fixup my cmd+shift mappings when a future version of neovim comes out, but making neovide drop shift from `cmd + shift` combos isn't going to solve neovim's issue.

**Comment by fredizzimo** [comment] 2023-09-10 13:38
@JamesWidman, can you try my PR first?

Including shift like you suggest would only work for standard ascii alphas and break for all mappings involving special characters. You should not need to include  shift in your mappings, since that's keyboard layout dependent. For example the following does not trigger the mappings:
```
:map <C-%> <cmd>echo "hello"<cr>
:call feedkeys("\<C-S-%>")
```
And there are a few standard mappings with the potential to break like
`<C-^>` and `<C-\><C-N>`, depending on the keyboard layout.

Always including shift has also caused problems previously https://github.com/neovide/neovide/pull/1547 (I found out when doing more research while making my fix)

Finally, another reason I don't like to use shift in the mappings is that from the perspective of Neovide the following mappings are all different `5`, `<S-5>`, `%`, `<S-%>`, if you use just `5` and `%`, there's no ambiguity, and that's also the approach Vim itself took and including other modifiers should be no different.

> I mean, maybe i'll have to fixup my cmd+shift mappings when a future version of neovim comes out, but i'm ok with that, and making neovide drop shift from cmd + shift combos isn't going to solve neovim's issue.

No, not with my PR, you won't have to change your mappings in the future, as long as you map your CMD mappings like this,
`<D-A>. When the Neovim bug is fixed you will additionally be able to use the alternative forms `<D-S-A>` and even `<D-S-a>`, which means that everything stays compatible no matter which GUI you are using. Note that the equivalence is only true for ascii alpha characters, special characters should always be mapped without shift using the resulting character.

And that makes it totally consistent with how ALT/META mappings work inside Neovim already.

CTRL mappings are different due to legacy reasons. For ascii alphas `<C-a>` and `<C-A>'> both means unshifted characters, while `<C-S-A>` and `<C-S-a>`, means shifted characters. That's the only confusing part here, and without that we could say: "never use shift in your mappings". That's still true for the non-ascii characters or non-alphas.

So, the final rule is the following:
**Never use shift in your mappings, unless the mapping contains CTRL and an ascii alphabetic character together.**

**Comment by JamesWidman** [comment] 2023-09-10 14:07
> @JamesWidman, can you try my PR first?

done. I fixed up my keymaps (`<S-D-a>` --> `<D-A>`) and all is well. 

Thank you!

**Comment by JamesWidman** [comment] 2023-09-10 14:18
> So, the final rule is the following:
> **Never use shift in your mappings, unless the mapping contains CTRL and an ascii alphabetic character together.**

So... in insert mode, when I type `ctrl-v` followed by the combo `meta + shift + cmd + y`, neovide/nvim produces: `<M-S-D-Y>`.

We don't have `ctrl`, so is that 'S-' supposed to be there?

**Comment by fredizzimo** [comment] 2023-09-10 14:27
@JamesWidman, hm.. that looks like a bug, but I don't really see how it can happen by looking at the code, since the condition is the following.
```rust
        let include_shift =
            is_special || (self.modifiers.state().control_key() && is_ascii_alphabetic_char(text));
```

Unless `is_special` is set wrong somehow. 

I don't have a Mac to test it on myself, but are you able to add some logging to see what's going on?

**Comment by JamesWidman** [comment] 2023-09-10 14:31
> > @JamesWidman, can you try my PR first?
> 
> done. I fixed up my keymaps (`<S-D-a>` --> `<D-A>`) and all is well.

Well, `shift + cmd + 8` yields `<D-8>` instead of `<D-*>`, but then, it did that in 0.10.4 too—meaning, it's not a regression.  

All is apparently back to normal!

**Comment by JamesWidman** [comment] 2023-09-10 14:32
> I don't have a Mac to test it on myself, but are you able to add some logging to see what's going on?

sure; but i'll have to pick this up later today.

how should I enable logging?

**Comment by fredizzimo** [comment] 2023-09-10 14:36
> Well, shift + cmd + 8 yields <D-8> instead of <D-*>, but then, it did that in 0.10.4 too—meaning, it's not a regression.

Yes, I believe that should be fixed once https://github.com/rust-windowing/winit/issues/3078 is fixed.

> https://github.com/rust-windowing/winit/issues/3078

Starting `neovide --log` should do it, it writes a `neovide_rCURRENT.og` file in the current directory. Then you can use `log::info!`,  `log::debug!` and `log::trace!` to do the actual logging.

**Comment by JamesWidman** [comment] 2023-09-10 22:04
> Unless `is_special` is set wrong somehow.

so, it turns out that `is_special` is true in this case, because we reach this invocation of format_modifier_string() by way of the macOS-specific part of format_normal_key():

```
        #[cfg(target_os = "macos")]
        if self.modifiers.state().alt_key() && use_alt() {
            return key_event
                .key_without_modifiers()
                .to_text()
                .map(|text| self.format_key_text(text, true));
```

i'll attach the trace momentarily...

(When I first started debugging this, I did feel a little confused about `is_special = true`  in `format_key_text(text, true)`, because we have an alphabetic key and get_special_key() must have returned None.)

**Comment by JamesWidman** [comment] 2023-09-10 22:18
so the logging annotation is like so:
```
diff --git a/src/window/keyboard_manager.rs b/src/window/keyboard_manager.rs
index a40a962..172eff2 100644
--- a/src/window/keyboard_manager.rs
+++ b/src/window/keyboard_manager.rs
@@ -15,6 +15,7 @@ fn is_ascii_alphabetic_char(text: &str) -> bool {
     text.len() == 1 && text.chars().next().unwrap().is_ascii_alphabetic()
 }
 
+#[derive(Debug)]
 pub struct KeyboardManager {
     modifiers: Modifiers,
     ime_preedit: (String, Option<(usize, usize)>),
@@ -141,8 +142,10 @@ impl KeyboardManager {
         // uppercase without shift, or <M-A> .
         // But in combination with ohter characters, such as <M-S-$> they are not,
         // so we don't want to send shift when that's the case.
+        log::trace!("format_modifier_string self.modifiers: {:#?}, text: {:#?}, is_special: {:#?}", self.modifiers, text, is_special);
         let include_shift =
             is_special || (self.modifiers.state().control_key() && is_ascii_alphabetic_char(text));
+        log::trace!("include_shift {:#?}", include_shift);
 
         // Always send meta (alt) togehter with special keys, or when alt is meta on macOS
         let include_alt = use_alt() || is_special;
```

... and neovide is launched from the shell like so:
```
RUST_LOG=neovide::window::keyboard_manager ../b/debug/neovide --log -- --clean -c startinsert -u ../c.vim
```
...and c.vim is:
```
lua vim.g.neovide_input_macos_alt_is_meta = true
```
...and then i type:
```
ctrl + v
meta + shift + cmd + y
```
...and quit. Log file attached.
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/12570859/neovide_rCURRENT.log)

**Comment by fredizzimo** [comment] 2023-09-10 22:19
That was some hack for dealing with our custom alt_is_meta option. I think we need to remove that hack and implement it properly using the winit `OptionAsAlt`, which will as a bonus allow us to map the left and right key separately. I can't find the actual documentation other than in the source code https://github.com/rust-windowing/winit/pull/2887. 

There was an attempt to implement right and left mapping separately here, but it was still not using the Winit native method.

And I don't want to implement it myself, since I can't test on macOS.

**Comment by JamesWidman** [comment] 2023-09-10 22:22
> And I don't want to implement it myself, since I can't test on macOS.

i could give it a try (though we might want a neovide lcontributor who is also a mac user to review the PR)

**Comment by fredizzimo** [comment] 2023-09-10 22:24
> i could give it a try (though we might want a neovide contributor who is also a mac user to review the PR)

Thanks, that would be nice. We do have several people that are able to at least test on mac. But everyone being able to write code has been busy.

BTW, I think this is the message, which led me to the implementation there is right now https://github.com/neovide/neovide/pull/1899#issuecomment-1595656852

**Comment by JamesWidman** [comment] 2023-09-19 00:54
hey, sorry for the lag; picking this up again...

So, i've gotten as far as:

-  calling `winit_window_builder.with_option_as_alt(OptionAsAlt::OnlyLeft)` in `create_window()` (this is only a temporary change so that i could test the next part. I will replace it with something that reads a  `vim.g.neovide_` option later; see below.)
- modifying src/window/keyboard_manager.rs to respond to modifier events

... and this seems to be working well. The next step is to respond to a user's config setting like:
```lua
vim.g.neovide_input_macos_option_is_meta = "OnlyLeft"
```
...by calling the corresponding winit api (either `WindowExtMacOS::set_option_as_alt()` or `WindowBuilderExtMacOS::with_option_as_alt`, presumably the former if we want to respond to this option being set after startup.) And this is the part where I feel a little lost: I expected that the place to handle the setting of `neovide_input_macos_option_is_meta` would be in a function that's inserted into  `Settings::listeners`, but i set a breakpoint in `Settings::handle_changed_notification`, and apparently we never hit it...?

Apparently this is because neovim never sends a `setting_changed` notification (see `handle_notify()`)...

How should I proceed?

**Comment by fredizzimo** [comment] 2023-09-19 07:49
@JamesWidman, the original PR did this https://github.com/neovide/neovide/pull/1979/files. So that's another option for doing it, 

But I think I prefer a single option like you are suggesting. If you could add boolean true/false support for backwards compatibility that sets "Both/None" respectively, then it would be even better.

Yes, I think doing it the same way as `ime_enabled` is fine.

**Closed** 2023-09-23 18:10 UTC
Labels: bug
