### ISSUE TITLE
Code highlights are dependant on Neovide's window size?

### ISSUE THREAD

**Issue by sgoudham** [neovide/neovide#1406] opened 2022-07-19 23:38 UTC
Hi, I just wanted to say thanks for creating a cool neovim GUI editor!

**Describe the bug**
From my testing, it looks like a particular highlight is applied to the same area where it shouldn't be in different buffers. Please look at the gif shown below as it shows the issue in much greater detail.

**To Reproduce**
Unfortunately, I have no idea how to reproduce the issue but it _looks_ to be tied to the window size? I have no idea why the highlights are seemingly out of sync in the first place.

Steps to reproduce the behaviour:
1. Open Neovide with the colourscheme `Catppuccin` (the one that I'm using in the gif below)
2. Find a file with messed up highlights (usually always in pink) 
3. Observe highlights being odd even with edits
4. Change window size of Neovide and reopen the same file
5. Observe that different code is highlighted incorrectly

**Expected behavior**
The window size _should not_ affect the highlighting of the code.

**Screenshots**
Please see the gif below:
![neovide-bug](https://user-images.githubusercontent.com/58985301/179865061-15ce58c1-b12c-47e1-9bce-1b73c7315b2c.gif)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Neovide Version: 0.9.0
 - Neovim Version 0.7.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
I have attached a file [neovide_rCURRENT.log](https://github.com/neovide/neovide/files/9145301/neovide_rCURRENT.log) containing the logs as they are too long.

**Additional context**
I think that this problem _only_ occurs when using the colour scheme `Catppuccin` but I haven't tested this enough as it looks to be somewhat undefined behaviour. I have spoken to the plugin authors and they don't seem to think it's an issue on their end as they are simply setting the highlights.

**Comment by MultisampledNight** [comment] 2022-07-20 11:31
First, thanks for reporting!

Then, could you try reducing your config down to the key parts which cause these incorrect highlights? I'm not able to reproduce the weird highlight by itself with this config:

```
call plug#begin("~/.local/share/nvim/vim-plug")
Plug 'https://github.com/catppuccin/nvim'
Plug 'https://github.com/nvim-treesitter/nvim-treesitter'
call plug#end()

colorscheme catppuccin

lua <<EOF
require("nvim-treesitter").setup {
	highlight = {
		enable = true,
	}
}
EOF

```

**Comment by sgoudham** [comment] 2022-07-20 17:41
Hi, I was able to perform some more testing and think I've found the root cause. 
Essentially, I think the plugin [glepnir/dashboard](https://github.com/glepnir/dashboard-nvim) is _burning_ its highlights into the screen when launched in neovide? 

Here are some screenshots of what I mean:

**Dashboard Screenshot:**
![image](https://user-images.githubusercontent.com/58985301/180045328-68974a4a-f244-4501-a953-5424ba9eb3a8.png)

**Code with Weird Highlights:**
![image](https://user-images.githubusercontent.com/58985301/180045301-2c660da7-398c-4bec-acab-83ea00d8f244.png)

I've tried to line up the screenshots from the edge of my window, and as you can see, the pink highlights are still existing within the code after I've gone away from the dashboard. This also explains the earlier behaviour in the gif and how it's related to the window size. Even if it's not precisely the "burning", it's definitely some highlighting issue when using glepnir's dashboard.nvim and launching in neovide. 

Here's the config I used to reproduce this. I hope that you're still able to reproduce this even though I'm using an `init.lua`

```lua
local fn = vim.fn

-- Automatically install Packer
local install_path = fn.stdpath "data" .. "/site/pack/packer/start/packer.nvim"
if fn.empty(fn.glob(install_path)) > 0 then
    PACKER_BOOTSTRAP = fn.system {
        "git",
        "clone",
        "--depth",
        "1",
        "https://github.com/wbthomason/packer.nvim",
        install_path,
    }
    print "Installing Packer. Close and reopen Neovim..."
    vim.cmd([[packadd packer.nvim]])
end

-- Use a protected call so we don't error out on first use
local status_ok, packer = pcall(require, "packer")
if not status_ok then
    return
end

return packer.startup(function(use)
    -- Packer can manage itself
    use 'wbthomason/packer.nvim'

    use {
        "glepnir/dashboard-nvim",
        config = function()
            local dashboard = require("dashboard")
            dashboard.custom_header = {
                '                                                       ',
                '                                                       ',
                ' ███╗   ██╗ ███████╗ ██████╗  ██╗   ██╗ ██╗ ███╗   ███╗',
                ' ████╗  ██║ ██╔════╝██╔═══██╗ ██║   ██║ ██║ ████╗ ████║',
                ' ██╔██╗ ██║ █████╗  ██║   ██║ ██║   ██║ ██║ ██╔████╔██║',
                ' ██║╚██╗██║ ██╔══╝  ██║   ██║ ╚██╗ ██╔╝ ██║ ██║╚██╔╝██║',
                ' ██║ ╚████║ ███████╗╚██████╔╝  ╚████╔╝  ██║ ██║ ╚═╝ ██║',
                ' ╚═╝  ╚═══╝ ╚══════╝ ╚═════╝    ╚═══╝   ╚═╝ ╚═╝     ╚═╝',
                '                                                       ',
                '                                                       ',
            }

            dashboard.custom_center = {
                {
                    icon = '',
                    desc = 'Load session                         ',
                    shortcut = '<leader> l s             ',
                    action = ':SessionManager load_session'
                },
                {
                    icon = '',
                    desc = 'Load Last Session                    ',
                    shortcut = '<leader> s l             ',
                    action = ':SessionManager load_last_session'
                },
                {
                    icon = '',
                    desc = 'Open Project                         ',
                    shortcut = '<leader> c d             ',
                    action = ":lua require'telescope'.extensions.project.project{}"
                },
                {
                    icon = '',
                    desc = 'Open Terminal                        ',
                    shortcut = '<leader> n               ',
                    action = ':FloatermNew'
                },
                {
                    icon = '',
                    desc = 'Update Plugins                       ',
                    shortcut = ':PackerSync              ',
                    action = ':PackerSync'
                },
                {
                    icon = '',
                    desc = 'View Installed LSP Servers           ',
                    shortcut = ':LspInstallInfo          ',
                    action = ':LspInstallInfo'
                }
            }
        end
    }
    use {
        "catppuccin/nvim",
        as = "catppuccin",
        run = ":CatppuccinCompile",
        config = function()
            require("catppuccin").setup()
            vim.g.catppuccin_flavour = "mocha"
            vim.cmd [[colorscheme catppuccin]]
        end
    }
    use {
        "nvim-treesitter/nvim-treesitter",
        run = function() require('nvim-treesitter.install').update({ with_sync = true }) end,
        after = "catppuccin",
        config = function()
            require("nvim-treesitter.configs").setup {
                highlight = {
                    enable = true
                }
            }
        end
    }

    -- Automatically set up your configuration after cloning packer.nvim
    -- Put this at the end after all plugins
    if PACKER_BOOTSTRAP then
        require("packer").sync()
    end
end)
```

**Comment by MultisampledNight** [comment] 2022-07-20 18:50
Yep, now I can reproduce this issue perfectly (though now everything's cluttered with packer's files and clones). Thank you for reducing it down so far!

**Comment by sgoudham** [comment] 2022-07-20 19:13
Apologies! I switched to Lua only a few weeks ago 😅

I was unsure whether to raise this issue in the dashboard plugin after figuring it out. Hope you're able to find the cause and if not, I can raise it within dashboard.nvim 👍

Thanks for the quick responses!

**Comment by MultisampledNight** [comment] 2022-07-20 19:13
From investigating a bit, I found out the following:

- [dashboard-nvim uses `matchaddpos` to add a highlighting at a certain position](https://github.com/glepnir/dashboard-nvim/blob/bb0d5019dcac944896582787684ab03b5225ff2d/lua/dashboard/init.lua#L285), which causes the nice pink highlight by itself.
- But it ignores the returnal value, which would it need to use later to "free" it once it enters a file. You can actually observe the matches persisting by using `:echo getmatches()` after opening any real file after the dashboard, it still shows the old matches for the shortcuts.
- This lets us open with two (well, three) options, which can even be matched to some extent:
  * We open a bug report in dashboard-nvim. As concise as the author seems to handle issues, I'm confident they'd build in logic to free those highlights after the dashboard's done its job.
  * We open a bug report at Neovim itself, listing that the TUI renderer somehow ignores matches once the text changes, but should it? Even `nvim-qt` has this issue.
  * We implement logic ourselves to ignore matches once text has changed. Least useful change to the ecosystem, but would allow us to just walk away slowly. Not advised.

**Comment by MultisampledNight** [comment] 2022-07-20 19:14
I think I'll go for the Neovim route once I grabbed some more debugging information, would you like to go for the dashboard-nvim one? If not, I can do it myself later.

**Comment by sgoudham** [comment] 2022-07-20 19:18
I can open one in dashboard-nvim later with references to your findings here. Surely it can't be worse if we go for 2/3 options listed above ahaha. 

Thanks so much for investigating! It was driving me nuts for weeks and finally gathered the energy to try and reproduce / raise an issue. Really appreciate it!

**Comment by MultisampledNight** [comment] 2022-07-20 19:55
...ok, the Neovim thing is much more interesting than I thought it would be. Seemingly the match _is_ being persisted in TUI mode across files, but somehow dashboard-nvim works around that and I haven't been able to find out why. It's not the options, for sure. I'm not sure now if I should open an issue on the Neovim repo, I'll decide that tomorrow _when I also have a bit more concentration than I have right now_.

**Comment by sgoudham** [comment] 2022-07-20 20:00
Very interesting, no worries! I'm actually really wanting to try and contribute to this repo as Neovide is my daily driver. I was actually thinking of raising an issue to try and find what the state of this repository is and how I could best help / what areas of the codebase are critical. Thanks for all your work once again!

**Comment by MultisampledNight** [comment] 2022-07-20 20:25
(btw. random thought, you can temporarily add an autocmd on BufEnter or the like which `call clearmatches()` to work around that for now)

**Comment by MultisampledNight** [comment] 2022-07-21 13:43
Back with a clear mind, this config was able to reproduce the issue (until it just got fixed):

```vim
call plug#begin()
Plug 'glepnir/dashboard-nvim'
Plug 'catppuccin/nvim', {'as': 'catppuccin'}
call plug#end()

colo catppuccin

lua <<EOF
require("dashboard").custom_center = {
	{
			desc = 'meow!  ',
			shortcut = 'this is a very long text with highlights',
			action = 'echo "meow"',
	}
}
EOF
```

But if I use that one with an example text like [this one](https://gist.github.com/MultisampledNight/7ff8919164e16e62afa3294de9b296d8), I can reproduce the issue even in terminal neovim, which renders me completely confused. As a random guess, I think usual code just wasn't long enough to actually reach so far for the positional highlighting to kick in, but that wouldn't explain why it didn't show it in your case.

I mean, as the issue is now reproducable consistently on terminal Neovim, nvim-qt and Neovide, this might have just been the dashboard plugin. Maybe the TUI renderer of Neovim is doing something wrong in terms of handling positional matches, but I'm on a too sandy basis to actually prove that. Would you mind if I close this issue?

**Comment by sgoudham** [comment] 2022-07-21 16:45
Oh very interesting, yeah feel free to close this issue! I'm just about to try out the fix for dashboard that the author kindly committed. Thanks for your help in debugging in this issue!

**Closed** 2022-07-21 18:12 UTC
Labels: bug
