### ISSUE TITLE
the cursor is not visible 

### ISSUE THREAD

**Issue by linwan623910** [neovide/neovide#2803] opened 2024-09-22 06:23 UTC
**Describe the bug**

bug:
After executing `<leader>r` in normal mode, the cursor is not visible in the command line. It only becomes visible after pressing the home key. The mapping is as follows:
`vim.keymap.set('n', '<Leader>r', 'yiw:%s/<C-R>"//g<left>')`

**To Reproduce**
1. executing `<leader>r` in normal mode
2. error : the cursor is not visible in the command line

**Expected behavior**
the cursor is visible in the command line

**Screenshots**
![2024-09-22_14-18-28](https://github.com/user-attachments/assets/04ab1fa9-c5de-465b-be61-36fc585d1978)

**Desktop :**
 - OS: WIN10 20H2
 - Neovide Version :0.13.3
 - Neovim Version :v0.10.1
[neovide_rCURRENT.log](https://github.com/user-attachments/files/17088556/neovide_rCURRENT.log)

**Comment by fredizzimo** [comment] 2024-09-22 14:50
This is a duplicate of
* https://github.com/neovide/neovide/issues/2376

I'm looking at fixing this, but it will most likely require Neovide nightly, or 0.11 when it's out.

**Closed by fredizzimo** 2024-09-22 14:50 UTC
Labels: bug
