### ISSUE TITLE
Building under win11/arm fails on skia-bindings

### ISSUE THREAD

**Issue by bogorad** [neovide/neovide#2655] opened 2024-06-14 22:54 UTC
**Describe the bug**
Builds 329 out of 333 items, fails on skia-bindings which does not exist for the platform. Maybe the x64 version (under transparent emulation) will do?

**To Reproduce**
```
> cargo build --release
   Compiling skia-bindings v0.73.0
error: failed to run custom build command for `skia-bindings v0.73.0`

Caused by:
  process didn't exit successfully: `C:\Users\chuck\git\neovide\target\release\build\skia-bindings-3cd2da05431fbb92\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=DOCS_RS
  cargo:rerun-if-env-changed=SKIA_DEBUG
  HOST: aarch64-pc-windows-msvc
  cargo:rerun-if-env-changed=SKIA_SOURCE_DIR
  cargo:rerun-if-env-changed=FORCE_SKIA_BUILD
  cargo:rerun-if-env-changed=FORCE_SKIA_BINARIES_DOWNLOAD
  TRYING TO DOWNLOAD AND INSTALL SKIA BINARIES: 0.73.0/532a0a24135b37b65b91-aarch64-pc-windows-msvc-d3d-gl-textlayout
  cargo:rerun-if-env-changed=SKIA_BINARIES_URL
    FROM: https://github.com/rust-skia/skia-binaries/releases/download/0.73.0/skia-binaries-532a0a24135b37b65b91-aarch64-pc-windows-msvc-d3d-gl-textlayout.tar.gz
  DOWNLOAD AND INSTALL FAILED: curl error code: Some(22)
  curl stderr: Ok("")
  STARTING A FULL BUILD
  cargo:rerun-if-env-changed=CLANGCC
  cargo:rerun-if-env-changed=CC
  cargo:rerun-if-env-changed=CLANGCXX
  cargo:rerun-if-env-changed=CXX
  HOST: aarch64-pc-windows-msvc
  cargo:rerun-if-env-changed=OPT_LEVEL
  cargo:rerun-if-env-changed=SKIA_USE_SYSTEM_LIBRARIES
  HOST: aarch64-pc-windows-msvc
  cargo:rerun-if-env-changed=SDKTARGETSYSROOT
  cargo:rerun-if-env-changed=SDKROOT
  HOST: aarch64-pc-windows-msvc
  HOST: aarch64-pc-windows-msvc
  cargo:rerun-if-env-changed=VCINSTALLDIR
  cargo:rerun-if-env-changed=LLVM_HOME
  cargo:rerun-if-env-changed=USERPROFILE

  --- stderr
  Checking for "C:\\Program Files\\LLVM\\bin\\clang-cl.exe"
  Checking for "C:\\LLVM\\bin\\clang-cl.exe"
  Checking for "C:\\Users\\chuck\\scoop\\apps\\llvm\\current\\bin\\clang-cl.exe"
  thread 'main' panicked at C:\Users\chuck\.cargo\registry\src\index.crates.io-6f17d22bba15001f\skia-bindings-0.73.0\build_support\platform\windows.rs:32:13:
  Unable to locate LLVM installation
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by fredizzimo** [comment] 2024-06-15 02:53
Skia does indeed not provide arm binaries on Windows. But I think it should build from source if you have LLVM installed according to the instructions here https://github.com/rust-skia/rust-skia?tab=readme-ov-file#on-windows

If not, an issue should be opened in the `rust-skia` repository.

**Comment by fredizzimo** [comment] 2024-06-17 04:29
I'm closing this, but it can be re-opened if there are issues compiling Neovide itself once Skia compiles.

**Closed by fredizzimo** 2024-06-17 04:29 UTC
Labels: bug

**Comment by yashamon** [comment] 2024-06-21 02:32
In my case skia compilation finds llvm etc, but fails with a strange error:
`error: failed to update submodule `skia`

Caused by:
  path too long: 'C:/Users/yasha/scoop/persist/rustup/.cargo/git/checkouts/rust-skia-35c6c5f9d522ea9f/0a9683d/skia-bindings/skia/infra/bots/recipe_modules/flavor/examples/full.expected/Test-Ubuntu18-Clang-Golo-GPU-QuadroP400-x86_64-Release-All-Valgrind_AbandonGpuContext_SK_CPU_LIMIT_SSE41.json'; class=Filesystem (30)`

**Comment by fredizzimo** [comment] 2024-06-21 03:13
The long path issue is tricky to resolve on Windows, see https://github.com/rust-skia/rust-skia/issues/770

There are at least three other ways to resolve the issue, which IMO are better than the proposed solutions
1. Change the environment variable `CARGO_HOME` to a shorter path
1. Clone skia to a location with a shorter path, check out tag 0.73, and patch the location in `Cargo.toml` , or `neovide/.cargo/config.toml` 
  
    ```toml
    [patch.crates-io]
    skia-safe = { path = "../path/to/skia-rs" }
     ```
1. Use `cargo vendor` to download and use all dependencies from another location https://doc.rust-lang.org/cargo/commands/cargo-vendor.html

**Comment by yashamon** [comment] 2024-06-21 12:24
With regard to 1. Where do I set this variable?

**Comment by yashamon** [comment] 2024-06-21 13:18
I have a new error: ` File "C:\Cargo\registry\src\index.crates.io-6f17d22bba15001f\skia-bindings-0.73.0\skia\bin\fetch-gn", line 28, in <module>
      f.write(urlopen(url).read())
              ^^^^^^^^^^^^
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 215, in urlopen
      return opener.open(url, data, timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 521, in open
      response = meth(req, response)
                 ^^^^^^^^^^^^^^^^^^^
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 630, in http_response
      response = self.parent.error(
                 ^^^^^^^^^^^^^^^^^^
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 559, in error
      return self._call_chain(*args)
             ^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 492, in _call_chain
      result = func(*args)
               ^^^^^^^^^^^
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 639, in http_error_default
      raise HTTPError(req.full_url, code, msg, hdrs, fp)
  urllib.error.HTTPError: HTTP Error 404: Not Found
  Traceback (most recent call last):
    File "C:\Cargo\registry\src\index.crates.io-6f17d22bba15001f\skia-bindings-0.73.0\skia\tools\git-sync-deps", line 281, in <module>
      exit(main(sys.argv[1:]))
           ^^^^^^^^^^^^^^^^^^
    File "C:\Cargo\registry\src\index.crates.io-6f17d22bba15001f\skia-bindings-0.73.0\skia\tools\git-sync-deps", line 270, in main
      subprocess.check_call(
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 413, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['C:\\Users\\yasha\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\python.exe', 'skia\\bin\\fetch-gn']' returned non-zero exit status 1.
  thread 'main' panicked at C:/Cargo\registry\src\index.crates.io-6f17d22bba15001f\skia-bindings-0.73.0\build_support\skia\config.rs:282:9:
  `skia/tools/git-sync-deps` failed
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to compile `neovide v0.13.1 (https://github.com/neovide/neovide#1db63d93)`, intermediate artifacts can be found at `C:\Users\yasha\AppData\Local\Temp\cargo-installMPvBrX`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.`

**Comment by yashamon** [comment] 2024-06-26 16:41
It looks like it can't find some remote file.

**Comment by fredizzimo** [comment] 2024-06-27 03:23
Can you report it to https://github.com/rust-skia/rust-skia first?

But it's likely that skia-rs can't do anything and the problem needs to be reported to Google. The problem is in their code, they don't have the required binary available https://github.com/google/skia/blob/main/bin/fetch-gn. The skia issue tracker is here https://issues.skia.org/issues

**Comment by yashamon** [comment] 2024-06-27 14:31
I am not sure how to formulate it. Also if I want to compile rust-skia directly how do I do that? I need to specify a component, is it skia-org? so cargo install --git https://github.com/rust-skia/rust-skia skia-org?

**Comment by fredizzimo** [comment] 2024-06-27 14:52
Since you got this far, you probably already have all the dependencies https://github.com/rust-skia/rust-skia?tab=readme-ov-file#on-windows

After that you can clone the rust-skia repository and run `cargo build` in that directory. You will most likely get a similar error as you got previously. Then you can create an issue that it fails to buil on Windows arm64, you can also include a link to this issue. I think it's better that you create the issue, since I can't answer any follow up questions.

If you manage to compile, you can try the example application https://github.com/rust-skia/rust-skia?tab=readme-ov-file#example-applications. Once that's done we can see what needs to be done on the neovide side.

**Comment by yashamon** [comment] 2024-06-29 03:38
I downloaded gn binary.
There is a new error:
error: failed to run custom build command for `skia-bindings v0.73.0`

Caused by:
  process didn't exit successfully: `C:\Users\yasha\AppData\Local\Temp\cargo-installpmeieC\release\build\skia-bindings-422e8ca75165190a\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=DOCS_RS
  cargo:rerun-if-env-changed=SKIA_DEBUG
  HOST: aarch64-pc-windows-msvc
  cargo:rerun-if-env-changed=SKIA_SOURCE_DIR
  cargo:rerun-if-env-changed=FORCE_SKIA_BUILD
  cargo:rerun-if-env-changed=FORCE_SKIA_BINARIES_DOWNLOAD
  TRYING TO DOWNLOAD AND INSTALL SKIA BINARIES: 0.73.0/532a0a24135b37b65b91-aarch64-pc-windows-msvc-d3d-gl-textlayout
  cargo:rerun-if-env-changed=SKIA_BINARIES_URL
    FROM: https://github.com/rust-skia/skia-binaries/releases/download/0.73.0/skia-binaries-532a0a24135b37b65b91-aarch64-pc-windows-msvc-d3d-gl-textlayout.tar.gz
  DOWNLOAD AND INSTALL FAILED: curl error code: Some(22)
  curl stderr: Ok("")
  STARTING A FULL BUILD
  cargo:rerun-if-env-changed=CLANGCC
  cargo:rerun-if-env-changed=CC
  cargo:rerun-if-env-changed=CLANGCXX
  cargo:rerun-if-env-changed=CXX
  HOST: aarch64-pc-windows-msvc
  cargo:rerun-if-env-changed=OPT_LEVEL
  cargo:rerun-if-env-changed=SKIA_USE_SYSTEM_LIBRARIES
  HOST: aarch64-pc-windows-msvc
  cargo:rerun-if-env-changed=SDKTARGETSYSROOT
  cargo:rerun-if-env-changed=SDKROOT
  HOST: aarch64-pc-windows-msvc
  HOST: aarch64-pc-windows-msvc
  cargo:rerun-if-env-changed=VCINSTALLDIR
  cargo:rerun-if-env-changed=LLVM_HOME
  cargo:rerun-if-env-changed=USERPROFILE
  cargo:rerun-if-env-changed=SKIA_NINJA_COMMAND
  cargo:rerun-if-env-changed=SKIA_GN_COMMAND
  Probing 'python'
  Python 3 found: "python"
  Synchronizing Skia dependencies
  Skipping "bin".
  ...rd_party/externals/d3d12allocator @ 169895d529dfce00390a20e69c2f516066fe7a3b
  skia\third_party/externals/freetype  @ f42ce25563b73fed0123d18a2556b9ba01d2c76b
  skia\third_party/externals/brotli    @ 6d03dfbedda1615c4cba1211f8d81735575209c8
  ...y/externals/vulkanmemoryallocator @ a6bfc237255a6bac1513f7c1ebde6d8aed6b5191
  skia\third_party/externals/libwebp   @ 2af26267cdfcb63a88e5c74a85927a12d6ca1d76
  ...ird_party/externals/libjpeg-turbo @ ed683925e4897a84b3bffc5c1414c85b97a129a3
  skia\third_party/externals/libpng    @ 144b348e072a78e8130ed0acc452c9f039a67bf2
  skia\third_party/externals/expat     @ 441f98d02deafd9b090aea568282b28f66a50e36
  skia\third_party/externals/wuffs     @ e3f919ccfe3ef542cfc983a82146070258fb57f8
  skia\third_party/externals/zlib      @ 646b7f569718921d7d4b5b8e22572ff6c76f2596
  skia\third_party/externals/harfbuzz  @ 4cfc6d8e173e800df086d7be078da2e8c5cfca19
  skia\third_party/externals/icu       @ a0718d4f121727e30b8d52c7a189ebf5ab52421f
  ...third_party/externals/spirv-cross @ b8fcf307f1f347089e3c46eb4451d27f32ebc8d3
  Skia args: is_official_build=true is_debug=false skia_enable_svg=false skia_enable_gpu=true skia_enable_skottie=false skia_enable_pdf=true skia_use_gl=true skia_use_egl=false skia_use_x11=false skia_use_system_libpng=false skia_use_libwebp_encode=false skia_use_libwebp_decode=false skia_use_system_zlib=false skia_use_xps=false skia_use_dng_sdk=false cc="clang" cxx="clang++" skia_use_direct3d=true skia_enable_skshaper=true skia_use_icu=true skia_use_system_icu=false skia_use_harfbuzz=true skia_pdf_subset_harfbuzz=true skia_use_system_harfbuzz=false skia_use_sfntly=false skia_enable_skparagraph=true skia_use_freetype=false skia_use_system_libjpeg_turbo=false skia_use_expat=true skia_use_system_expat=false win_vc="C:\Program Files\Microsoft Visual Studio\2022\Community\VC" clang_win="C:\Users\yasha\scoop\apps\llvm\current" clang_win_version="C:\Users\yasha\scoop\apps\llvm\current\lib\clang\18" target_cpu="arm64" extra_cflags=["/MD","--target=aarch64-pc-windows-msvc"] extra_asmflags=["--target=aarch64-pc-windows-msvc"]
  WARNING at the command-line "--args":1:560: Build argument has no effect.
  is_official_build=true is_debug=false skia_enable_svg=false skia_enable_gpu=true skia_enable_skottie=false skia_enable_pdf=true skia_use_gl=true skia_use_egl=false skia_use_x11=false skia_use_system_libpng=false skia_use_libwebp_encode=false skia_use_libwebp_decode=false skia_use_system_zlib=false skia_use_xps=false skia_use_dng_sdk=false cc="clang" cxx="clang++" skia_use_direct3d=true skia_enable_skshaper=true skia_use_icu=true skia_use_system_icu=false skia_use_harfbuzz=true skia_pdf_subset_harfbuzz=true skia_use_system_harfbuzz=false skia_use_sfntly=false skia_enable_skparagraph=true skia_use_freetype=false skia_use_system_libjpeg_turbo=false skia_use_expat=true skia_use_system_expat=false win_vc="C:\Program Files\Microsoft Visual Studio\2022\Community\VC" clang_win="C:\Users\yasha\scoop\apps\llvm\current" clang_win_version="C:\Users\yasha\scoop\apps\llvm\current\lib\clang\18" target_cpu="arm64" extra_cflags=["/MD","--target=aarch64-pc-windows-msvc"] extra_asmflags=["--target=aarch64-pc-windows-msvc"]



                                                                                                                     ^----
  Did you mean "skia_use_sfml"?

  The variable "skia_use_sfntly" was set as a build argument
  but never appeared in a declare_args() block in any buildfile.

  To view all possible args, run "gn args --list <out_dir>"

  The build continued as if that argument was unspecified.

**Comment by fredizzimo** [comment] 2024-06-29 03:57
@yashamon I think you posted in the wrong issue, can you reply inhttps://github.com/rust-skia/rust-skia/issues/998

**Comment by yashamon** [comment] 2024-07-01 19:29
I noticed that nvy compiles almost instantly, is it just a much simpler code base?
