### ISSUE TITLE
Banding on Dashboard

### ISSUE THREAD

**Issue by Black-Sirius69** [neovide/neovide#1408] opened 2022-07-20 17:58 UTC
**Describe the bug**
I am getting bands on my neovim dashboard when I open it using neovide. I am using transparency settings 0.8

**To Reproduce**
IDK. You can clone my neovim repo and try

**Expected behavior**
I expected a clean transparent dashboard

**Screenshots**
![2022-07-20_23-27](https://user-images.githubusercontent.com/71623796/180050406-97152d5b-0443-427a-aca1-d483b9e691b3.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux 
 - Neovide Version 0.9.0
 - Neovim Version 0.8.0 dev (built from scratch

**Comment by MultisampledNight** [comment] 2022-07-20 18:15
Thanks for reporting! Closing to remove this seemingly duplicate of #1387 though.

**Closed by MultisampledNight** 2022-07-20 18:15 UTC
Labels: bug

**Comment by Black-Sirius69** [comment] 2022-07-20 18:23
I would however like to add that the issue you mentioned does not give any solutions on how to fix it

**Comment by MultisampledNight** [comment] 2022-07-20 18:29
That's right, though I'd prefer to have one bug at one place, to avoid split discussion and findings.
