### ISSUE TITLE
Anyway to avoid the startup zoom out animation?

### ISSUE THREAD

**Issue by AllenDang** [neovide/neovide#1783] opened 2023-03-01 03:27 UTC
**Is your feature request related to a problem? Please describe.**
In macOS, each time when I launch neovide, the window will appear with a small size and zoom out to fullscreen, I did add the --maximized, still can see the zoom out process.

**Describe the solution you'd like**
Launch neovide directly with fullscreen without a explicit zoom out.

**Additional context**
I'm using newest master branch.

**Comment by yavorski** [comment] 2024-02-29 00:17
This is happening on `windows-11` too. 

Also it is causing issues with `lualine tabline` for reason, because in the moment of starting `vim.o.columns` is equal to  `100` and `lualine tabline` is using this for its configuration, which leads to tabline not being expanded to full width.

Workaround is to start neovide with explicit size flag e.g. `neovide --size 1900x968` for example, this is working fine and then to maximize - which is a bit tedious of course.

[Config `max_length` for tabline width doc](https://github.com/nvim-lualine/lualine.nvim/blob/7d131a8d3ba5016229e8a1d08bf8782acea98852/doc/lualine.txt#L532)

In my config i just set it to `max_length = vim.o.colums` to take the full width, but it is not working in `neovide` when maximized and started with `maximized` flag.

**Comment by falcucci** [comment] 2024-02-29 18:15
@AllenDang @yavorski unable to reproduce it, could any of you send a video/gif for better comprehension?

**Comment by yavorski** [comment] 2024-02-29 20:25
@falcucci 

https://github.com/neovide/neovide/assets/3436517/981159fa-5a9f-4b10-ac28-3e4f74d39ccf

**Comment by yavorski** [comment] 2024-02-29 22:49
That is indeed strange, yes it does not play in Firefox for some reason, don't know why. 
Maybe try different browser, if that is the case.

**Comment by falcucci** [comment] 2024-03-01 00:12
Ive handle to see it using chrome tho, thank you!

I just can't reproduce it, or it opens so fast that maybe isn't even eye perceptive here.

but I guess it's taking the default inner size position grid and then maximizing it. For some it perceptible for others not that much.

**Comment by falcucci** [comment] 2024-03-01 01:09
could some of you test this candidate fix? https://github.com/neovide/neovide/pull/2389

**Comment by yavorski** [comment] 2024-03-01 07:30
@falcucci hi, I have built it with `cargo build --release` unfortunately both issues still persists, there is no difference. at least on `Windows` os.

**Comment by falcucci** [comment] 2024-03-01 09:40
did you try using --maximized?

this change only affects if you use it for now.

**Comment by yavorski** [comment] 2024-03-01 09:48
Hi, yes I did, and just re/tried it again `.\target\release\neovide.exe --maximized`. I confirm it is the same as before with no difference.

**Comment by fredizzimo** [comment] 2024-03-01 09:53
I know what the problem is, and how we should solve it, but I don't have time to properly explain it right now, I will try to do it later today in the evening my time. There are several different issues interacting.

**Comment by fredizzimo** [comment] 2024-03-01 09:59
A quick workaround is probably to run `neovide --grid <columns>x<lines>` Adn specify the number of lines and columns you want to start with. But make sure that you don't specify more columns or lines than what will fit onto your screen.

**Comment by fredizzimo** [comment] 2024-03-01 10:06
You might also want to set `g:neovide_position_animation_length=0` to disable the Neovide animation when new windows are shown.

**Comment by falcucci** [comment] 2024-03-01 10:25
@fredizzimo okay, so my theory didn't work as expected, but I still think the PR is valid tho, we shouldn't requested the inner in case of maximized.

we should also treat it in case of full-screen persisted windows

**Comment by falcucci** [comment] 2024-03-01 10:54
@fredizzimomakes much more sense now, I'll close the PR.

thank you!

**Comment by fredizzimo** [comment] 2024-05-18 17:51
I have a potential fix for this here:
* https://github.com/neovide/neovide/pull/2562

It would be good if someone could test it.

**Closed** 2024-05-19 15:48 UTC
Labels: enhancement, macos
