### ISSUE TITLE
[Wayland] Neovide crashes on startup when not launched as root

### ISSUE THREAD

**Issue by x1rom** [neovide/neovide#1617] opened 2022-10-30 10:30 UTC
When launching `neovide --nofork`, this message appears:
`[wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting.`

Neovide launches normally when launching as root: `sudo neovide`

Log when starting as regular user:
```
TRACE [neovide] Neovide version: 0.10.1
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "/usr/bin/nvim" "--embed", kill_on_drop: false }
INFO [neovide::bridge::setup] Neovide registered to nvim with channel id 1
INFO [neovide::bridge] Neovim process attached
```

I'm running arch linux with linux-surface, KDE-plasma and Xwayland.

**Comment by Wycers** [comment] 2022-10-31 04:25
same issue in fedora 36 with gnome 42.5

**Comment by tan-wei** [comment] 2022-11-03 15:31
Met the same issue. Does the issue just appear in the latest version?

**Comment by CertainLach** [comment] 2022-11-06 19:05
Duplicate of https://github.com/neovide/neovide/issues/1356
It works as root, because it uses xorg backend in this case

**Comment by MultisampledNight** [comment] 2022-11-07 17:59
Closing in favor of #1617, thanks for the report though!

**Closed by MultisampledNight** 2022-11-07 17:59 UTC
Labels: bug
