### ISSUE TITLE
Support shortcuts for "open new window" on macOS

### ISSUE THREAD

**Issue by nanozuki** [neovide/neovide#2020] opened 2023-09-11 02:55 UTC
**Is your feature request related to a problem? Please describe.**

In macOS, we use "cmd+N" to open a new window for the current application. But when I press "cmd+N", no new window appears but displays "E486" in the cmd line.

**Comment by kipelovets** [comment] 2023-09-11 14:48
This is my workaround:

```lua
if vim.g.neovide then
    vim.keymap.set("n", "<D-n>", ":silent exec '!neovide'<cr>")
end
```

There's also another issue open for this problem: https://github.com/neovide/neovide/issues/1332

**Comment by nanozuki** [comment] 2023-09-12 05:49
> This is my workaround:
> 
> ```lua
> if vim.g.neovide then
>     vim.keymap.set("n", "<D-n>", ":silent exec '!neovide'<cr>")
> end
> ```
> 
> There's also another issue open for this problem: #1332

Thanks. I tried this workaround, but there is something strange:
1. Will open new neovide in the current path. But we can do `!cd ~ &&neovide` to fix it.
2. Mac will treat these windows as separate apps, so we can't use "cmd+`" to walk in neovide windows.

**Comment by fredizzimo** [comment] 2023-09-12 11:03
I'm closing this as a duplicate of #1332 to keep the issue list sane.

If you want, you can add this workaround there to help other users out. But the shortcoming of not being able to walk the windows is already mentioned there.

**Closed by fredizzimo** 2023-09-12 11:03 UTC
Labels: enhancement
