### ISSUE TITLE
Stuttering and thrashing on macOS when window is maximised.

### ISSUE THREAD

**Issue by ananthb** [neovide/neovide#1561] opened 2022-09-28 14:54 UTC
**Describe the bug**
Neovide stutters and performs very poorly when the window is maximised.

**To Reproduce**
1. Set the contents of ~/.local/share/nvim/neovide-settings.json to `{"window": "Maximized"}`
2. Open Neovide
3. See very slow rendering and stuttering.

**Expected behavior**
Neovide should run smoothly.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 12.6
 - Neovide Version 0.10.1
 - Neovim Version 0.7.2

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

I attached the logs because they are large.

[neovide_r2022-09-28_20-17-11.restart-0000.log](https://github.com/neovide/neovide/files/9666234/neovide_r2022-09-28_20-17-11.restart-0000.log)
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/9666248/neovide_rCURRENT.log)

**Additional context**

**Comment by fredizzimo** [comment] 2022-09-30 06:57
Closing this as a duplicate of https://github.com/neovide/neovide/issues/1312

**Closed by fredizzimo** 2022-09-30 06:57 UTC
Labels: bug
