### ISSUE TITLE
Why do the lines look like this?Only nvim will be normal

### ISSUE THREAD

**Issue by peiwithhao** [neovide/neovide#2720] opened 2024-07-21 02:44 UTC
The version:
```
os - Arch linux
kernel - linux-6.9.10
neovide 0.13.3
WM: Hyprland
```

In Neovide
![image](https://github.com/user-attachments/assets/d06a2f17-174f-45a9-a643-e12352b473f8)
![image](https://github.com/user-attachments/assets/285f750a-bcc2-48cd-9f93-ac833a6270fb)

But just in nvim
![image](https://github.com/user-attachments/assets/6da294f8-61e4-416c-b984-afe0cf14239a)
![image](https://github.com/user-attachments/assets/d9e90d7b-f913-4f74-8546-7ba54a085427)

**Comment by fredizzimo** [comment] 2024-07-21 03:54
I'm closing this as a duplicate of:
* https://github.com/neovide/neovide/issues/2491

It has mostly to do with how the font hinting is rendered when lines don't align with exact pixels. You can work around the issue by one of the following:
1. Change the hinting option https://neovide.dev/config-file.html#font, https://neovide.dev/configuration.html#font. Setting it to `none` should get rid of the issue, but at the cost of text clarity
2. Change the font size
3. Change to another font

**Closed by fredizzimo** 2024-07-21 03:54 UTC
Labels: bug
