### ISSUE TITLE
command line options not working

### ISSUE THREAD

**Issue by LollipopFt** [neovide/neovide#1004] opened 2021-10-10 05:22 UTC
**Describe the bug**
when typing ```neovide --help``` or any other command into cmd.exe or alacritty, nothing appears.

**To Reproduce**
1. Open alacritty
2. Type in command line ```neovide -h``` or any other command
3. Nothing appears

**Expected behavior**
Help for what I need appears

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10 Pro]
 - Neovide Version [0.8.0]
 - Neovim Version [v0.6.0-dev+394-g8a9f29299]

**Please run `neovide --log` and paste the contents of the `.log` file here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/7316893/neovide_rCURRENT.log)

**Comment by jsosulski** [comment] 2021-12-03 06:36
For what its worth, on current main I have no cmd flag issues on Ubuntu 20.04
I also dont have the issue in #1055

**Comment by dineshKumar777** [comment] 2021-12-03 07:07
@jsosulski  For me issue is reproducible in windows os. so this issue is platform specific??

![image](https://user-images.githubusercontent.com/21097695/144560154-bf2473bd-825f-4b73-9e6c-7dae4c827130.png)

**Comment by jsosulski** [comment] 2021-12-03 07:20
I only have a Ubuntu machine here, but it seems like it.

![grafik](https://user-images.githubusercontent.com/2545339/144561330-cf0165e8-7aba-42c4-b473-bf29074231ed.png)

**Comment by jsosulski** [comment] 2021-12-03 07:22
Maybe a dumb question, but apparently `--log` does work on windows?

**Comment by dineshKumar777** [comment] 2021-12-03 07:29
> Maybe a dumb question, but apparently `--log` does work on windows?

yeah that one works. Very few commands are not working.

**Comment by jeremycostanzo** [comment] 2021-12-03 19:59
I could reproduce it on windows, but only when neovide is compiled in release version:
![only_release](https://user-images.githubusercontent.com/56163564/144664796-870cd5d3-015a-4c6a-ae24-247bf551d620.png)

**Comment by jeremycostanzo** [comment] 2021-12-03 21:00
The first line of main.rs seems to be the cause: https://github.com/neovide/neovide/blob/8b1a81ded3a42dc935a5f04a35873d94184d52a3/src/main.rs#L1
removing it fixes the issue for me.

However, it creates a console window if I run the executable outside of a command line, which is not desired I believe.

We could also hide the console with this snippet:
```
fn hide_console_window() {
    use std::ptr;
    use winapi::um::wincon::GetConsoleWindow;
    use winapi::um::winuser::{ShowWindow, SW_HIDE};

    let window = unsafe {GetConsoleWindow()};
    // https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-showwindow
    if window != ptr::null_mut() {
        unsafe {
            ShowWindow(window, SW_HIDE);
        }
    }
}
```
found at https://stackoverflow.com/questions/29763647/how-to-make-a-program-that-does-not-display-the-console-window.

There is likely a better option but I don't know any :(

**Comment by jeremycostanzo** [comment] 2021-12-04 07:15
I don't think that any recent PR caused this behaviour, the command line options seem to work, but it is not possible to see any output in the terminal from the release build of neovide on windows.

From what I can see, we have to compromise:
- no output available on the release build
- output available on the release build, but a terminal window is created when launching the executable

@Kethku I believe that you had already thought about it?

**Comment by jsosulski** [comment] 2021-12-06 07:28
Hm so for windows this seems to be working "as intended". I guess then the issue is that windows STDOUT is not working, while the flags do work?

But then #1055 is unrelated to this?

**Comment by jeremycostanzo** [comment] 2021-12-06 13:35
Windows stdout is disabled for the release build, because it would create a terminal window if we just launched the executable outside of the command line.
But the behavior on MacOS should not be affected by this issue.
I believe that #1055 is unrelated.

**Comment by Kethku** [comment] 2021-12-13 07:28
This has been fixed in main by attaching the console on startup. Note: this causes minor issues because running programs will not wait for the app to finish, but this is just a minor issue which other apps seem to accept.

Other solutions require flickering a console window on startup which I'm really not a fan of, so I think this is the best compromise.

**Closed by Kethku** 2021-12-13 07:28 UTC
Labels: bug, daily blocker
