### ISSUE TITLE
Opengl (building) and main (running) branches failed

### ISSUE THREAD

**Issue by mikkovedru** [neovide/neovide#734] opened 2021-06-18 23:34 UTC
**Describe the bug**

### OpenGL branch
I wasn't able to test the fix for bug #692, because the `cargo build` process on branch `opengl` failed on me with the following error message:

> error[E0062]: field `distance_length_adjust` specified more than once
  --> src/renderer/cursor_renderer/mod.rs:51:13
   |
47 |             distance_length_adjust: true,
   |             ---------------------------- first use of `distance_length_adjust`
...
51 |             distance_length_adjust: false,
   |             ^^^^^^^^^^^^^^^^^^^^^^ used more than once
>
> error: aborting due to previous error
>
> For more information about this error, try `rustc --explain E0062`.
> error: could not compile `neovide`

The error is in these lines:
https://github.com/Kethku/neovide/blob/opengl/src/renderer/cursor_renderer/mod.rs#L47-L51

`distance_length_adjust` is mentioned two times and has conflicting values. Only one should be declared.

### Main branch
Building the main branch was successful, but running the program failed with the following error message:
>Ignored client type property: "methods"
>Ignored client type property: "attributes"
>thread 'main' panicked at 'Could not load font', src/renderer/fonts/caching_shaper.rs:50:14

The error leads to this line:
https://github.com/Kethku/neovide/blob/opengl/src/renderer/fonts/caching_shaper.rs#L50

Tell me what information I can provide to help fix the issue.

**Desktop (please complete the following information):**
 - OS: Linux Mint Cinnamon 20.1

**Comment by shaunsingh** [comment] 2021-06-19 01:39
I can't reproduce the building issue on my machine (macOS, latest neovide) but the duplicate instances of `distance_length_adjust` is an easy fix. However I'm not sure which is supposed to be the default behavior so I'll wait until Kethku can take a look

**Comment by PyGamer0** [comment] 2021-06-19 08:33
For the main branch try: setting a font in your init.vim

**Comment by Kethku** [comment] 2021-06-19 20:01
The opengl branch no longer contains current development. All work is happening in main now.

I believe the issue with the caching shaper in main is due to an invalid font name in your vim config. Could you try unsetting the guifnot option?

**Comment by mikkovedru** [comment] 2021-06-20 17:28
@PyGamer0 @Kethku 
I couldn't find any mention of `guifont` in my configs (so there was nothing to remove).

I tried to set it in all kinds of different ways, but nothing changed (I get the same error message every time).

Please advise.

**Comment by PyGamer0** [comment] 2021-06-21 10:16
which monospace font is installed on your system

**Comment by Kethku** [comment] 2021-06-26 19:42
These days neovide embeds a font by default. So at least in theory it shouldn't require a particular font to be installed

**Comment by Kethku** [comment] 2021-08-28 03:31
Closing as I think this is fixed. Please reopen if issues continue.

**Closed by Kethku** 2021-08-28 03:31 UTC
Labels: bug
