### ISSUE TITLE
Neovide Crash Issue: Crash Occurs When Adding Parameters

### ISSUE THREAD

**Issue by N1nEmAn** [neovide/neovide#2546] opened 2024-05-15 02:28 UTC
**Error Description**

When entering `neovide -- -a`, Neovide crashes.
（neovide -- -{this can input anything to crash}）

**Steps to Reproduce**

1. Open a terminal.
2. Enter the command `neovide -- -a` and press Enter.

**Expected Behavior**

Neovide should start normally and run with the specified parameter `-a`.

**Log**

```plaintext
TRACE [neovide] Neovide version: 0.12.2
ERROR [neovide::settings::config] Could not watch config file, chances are it just doesn't exist: No such file or directory (os error 2) about ["/home/N1nE/.config/neovide"]
DEBUG [neovide::settings::window_size] Loaded window settings: Windowed { position: PhysicalPosition { x: 1308, y: 8 }, pixel_size: Some(PhysicalSize { width: 1244, height: 1544 }), grid_size: Some(Dimensions { width: 65, height: 39 }) }
DEBUG [neovide::bridge::command] Starting neovim with: Command { std: "/usr/bin/nvim" "--embed" "-p" "-a", kill_on_drop: false }
ERROR [neovide::error_handling] Neovide just crashed :(
This is the error that caused the crash. In case you don't know what to do with this, please feel free to report this on https://github.com/neovide/neovide/issues!

Neovide requires nvim version 0.9.2 or higher. Download the latest version here https://github.com/neovim/neovim/wiki/Installing-Neovim
```

**Desktop Information**

- Operating System: Arch Linux x86_64
- Neovide Version: 0.12.2
- Neovim Version: 0.9.5

**Additional Context**

- Screenshot: ![Neovide Screenshot](https://github.com/neovide/neovide/assets/118088443/9dbde9c0-2478-4897-bb86-957df2c51b78)

**Comment by fredizzimo** [comment] 2024-05-17 11:00
I'm closing this as a duplicate of (although it's not exactly a complete duplicate)
* https://github.com/neovide/neovide/issues/2446

**Closed by fredizzimo** 2024-05-17 11:00 UTC
Labels: bug
