### ISSUE TITLE
Add link highlighting and click on links to open support

### ISSUE THREAD

**Issue by NeutronOrg** [neovide/neovide#2649] opened 2024-06-12 01:54 UTC
Neovide isnt able to recognize or highlight any links
![image](https://github.com/neovide/neovide/assets/96955087/79e870dd-a0b8-4cfa-8254-781041f1a8bc)
Here is the same thing in Windows Terminal:
![image)](https://github.com/neovide/neovide/assets/96955087/c09f45e5-6207-4857-a8aa-98fd4b693d89)

You can also `Ctrl+Click` the link to open it on the browser
But on Neovide tries the find the tag/word you have clicked on or go to where the object defined (or my lsp does that)
This is the error i get when `Ctrl+Click`ing a link on Neovide:
![image](https://github.com/neovide/neovide/assets/96955087/e095d21f-dac5-479e-9ec0-28639f9615dd)

It would be great if you could add link support to Neovide so when hovered on a link it would highlight/[underline](#) the link and when control clicked on, it would open it in the browser
That way it would be easier to open up a link that a program asked you to do in the terminal or in the code

**Comment by fredizzimo** [comment] 2024-06-12 08:17
This is supported by Neovim https://neovim.io/doc/user/various.html#gx, and the `@string.special.url` and can be mappee to the right click menu if that's desired.

For a more complex implementation, like changing the cursor we need something like one of these
* https://github.com/neovim/neovim/pull/28016
* https://github.com/neovim/neovim/issues/21458

Also a duplicate of, so if you have more comments, add them there and we will re-open if necessary
* https://github.com/neovide/neovide/issues/1492

**Closed by fredizzimo** 2024-06-12 08:17 UTC
Labels: enhancement
