### ISSUE TITLE
neovide_fullscreen errors with "E475: Channel does not exists"

### ISSUE THREAD

**Issue by jmlucjav** [neovide/neovide#1504] opened 2022-08-24 17:59 UTC
**Describe the bug**
Setting g:neovide_fullscreen fails with an error: 
![image](https://user-images.githubusercontent.com/1813237/186489121-53443148-f929-43d0-93f0-c7a5278e9c92.png)

**To Reproduce**
1. open command line
2. run 
```
let g:neovide_fullscreen=v:true
```
using 1 instead of v:true is the same

**Expected behavior**
Full screen

**Desktop (please complete the following information):**
 - OS: Win10 21H2
 - Neovide 0.10.1
 - Neovim 0.8 from a few days ago, running on WSL ubuntu

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/9418379/neovide_rCURRENT.log)
[neovide_r2022-08-24_19-57-59.log](https://github.com/neovide/neovide/files/9418380/neovide_r2022-08-24_19-57-59.log)

thanks

**Comment by MultisampledNight** [comment] 2022-08-24 19:46
Thanks for reporting! I can't reproduce the issue on Arch Linux/Sway though, so I guess this is a Windows or more to say WSL specific issue.

**Comment by groner** [comment] 2022-11-28 21:48
I've run into an issue like this when connecting to a remote neovim. I'm not using Windows, but I think the fix may be the same.

The `NeovideNotifycursor_animation_lengthChanged()` glue function contains the channel id 1, but `g:neovide_channel_id` is now 3. I'm not sure why they seem to be out of sync from the get go.

In either case, updating the glue functions to use `g:neovide_channel_id` would probably fix this (assuming there isn't some other Windows issue at play).

**Comment by camAtGitHub** [comment] 2023-01-10 08:20
Kind of inline with this... running neovim in WSL2 environment via command: 
```nvim --headless --listen  127.0.0.1:41234``` and using Neovide via
```C:\Users\cam\scoop\apps\neovide\0.10.1\neovide.exe --remote-tcp=127.0.0.1:41234``` - It is impossible to detect Neovide `exists('g:neovide')` (as it may not have attached yet...).  
Even creating a timer function and attaching before the timer triggers then I hit these 'Channel doesn't exist' errors.

I can confirm `exists('g:neovide')` = 1. Running `echo g:neovide_channel_id` outputs `6` as an example.

**Comment by fredizzimo** [comment] 2024-01-13 06:08
This was fixed in the 0.12.0 release by
* https://github.com/neovide/neovide/pull/2070

**Closed by fredizzimo** 2024-01-13 06:08 UTC
Labels: bug, wsl, windows
