### ISSUE TITLE
Font Fallback Fails for Certain Glyphs

### ISSUE THREAD

**Issue by shaunsingh** [neovide/neovide#748] opened 2021-06-24 15:47 UTC
**Describe the bug**
(continued form https://github.com/Kethku/neovide/issues/741#issuecomment-867731459)

**To Reproduce**
1. Download/install neovide
2. Set gui font to a nerd font (user is using CaskaydiaCove Nerd Font, (I believe this is Cascadia Code)
3. Open a Nerdtree buffer

**Expected behavior**
Glyphs should render correctly. 

**Screenshots**

(top terminal, bottom neovide)

![](https://user-images.githubusercontent.com/65481813/123112355-433b3c00-d45b-11eb-9b6c-0b7b5bc897fb.png)

![](https://user-images.githubusercontent.com/65481813/123112402-4b937700-d45b-11eb-8355-d983308ebecb.png)

**Desktop (please complete the following information):**
 - OS: MacOS 11
 - Neovide Version: Latest intel build pulled from github actions (running on an m1 machine)
 - Neovim Version: 0.5.0 nightly

**Please run `neovide --log` and paste the results here:**
--not run, don't think its required for this issue

**Additional context**
User is using Cascadia code nerd font, but has tried it with "FiraCode, FuraCode and JetBrainsMono nerd fonts. None of them worked." I will test this on my personal machine shortly

**Comment by shaunsingh** [comment] 2021-06-24 15:51
<img width="420" alt="image" src="https://user-images.githubusercontent.com/71196912/123293574-1bdb8200-d4e2-11eb-95f9-e95d2fa9edc7.png">

I can't repro this on my machine. I am using the FiraCode nerd font and the latest release of neovide built from source. I checked, and the arrow/star glyphs are included with the nerd font

**Comment by IBS27** [comment] 2021-06-24 15:53
Which icon set do you use and which filetree is that?

**Comment by shaunsingh** [comment] 2021-06-24 15:55
I am using the nvim-devicons, which is using the glyphs provided in the nerd font 
The tree itself is nvim-tree, and the icons are defined in my personal config here: https://github.com/shaunsingh/vimrc-dotfiles/blob/a5546ba505341531234a43afe44046e9cb8636aa/.config/nvim/init.lua#L1169 (it appears blank because GitHub doesn't have the glyphs, if you paste it into a terminal it should work)

**Comment by IBS27** [comment] 2021-06-24 15:56
I can see that you are using lua. But, my config isn't based on it.

**Comment by shaunsingh** [comment] 2021-06-24 15:57
Lua shouldn't be an issue. If you would like to test my config, you can use 
```lua 
lua <<EOF 
--code goes here 
EOF 
```
Note that you need to install nvim-tree and nvim-devicons for this to work

**Comment by IBS27** [comment] 2021-06-24 16:26
I tried your config. And I liked it. It worked fine except that a couple of glyphs were not working.

**Comment by shaunsingh** [comment] 2021-06-24 16:38
could you kindly send a screenshot showing the glyphs not working

**Comment by IBS27** [comment] 2021-06-24 18:24
It's fine. I replaced those with some very similar looking emojis from the mac emoji viewer. It works now.

**Comment by Kethku** [comment] 2021-06-25 02:09
Ok so this is a font fallback issue. Unfortunately its niche enough that I'm not gonna make it super high priority in the short run.

**Comment by IBS27** [comment] 2021-06-25 03:45
What about the dead keys issue? When will that be fixed?

**Comment by Kethku** [comment] 2021-06-25 04:45
dead keys are tracked here: https://github.com/Kethku/neovide/issues/445

Wanna help out?

**Comment by IBS27** [comment] 2021-06-25 04:49
Yeah! I can help in testing it on mac.

**Comment by IBS27** [comment] 2021-06-25 05:19
@Kethku how do you use the .snap files? I am kinda new to all this.

**Comment by Kethku** [comment] 2021-06-25 05:51
pinging @j4qfrost as I know nothing about various linux packing systems. I'm as in the dark as you

**Comment by IBS27** [comment] 2021-06-25 05:53
Oh. So is that snap file only for linux?

**Comment by IBS27** [comment] 2021-06-25 05:56
And I tried the latest mac build of neovide. That is the one with the new icons. The icon doesn't show.
![Screenshot 2021-06-25 at 11 25 37 AM](https://user-images.githubusercontent.com/65481813/123376413-121c5200-d5a8-11eb-9c26-d835567e77e4.png)

**Comment by Kethku** [comment] 2021-06-25 05:57
@shaunsingh I think you've been working on a better mac build. Does your new PR set the icon?

**Comment by j4qfrost** [comment] 2021-06-25 06:14
The cargo bundle command should already set an icon for the dmg, everything's ng installs just fine for me. I have it running just fine on the Mac mini.

**Comment by j4qfrost** [comment] 2021-06-25 06:14
@IBS27 @Kethku snap is just for Linux.

**Comment by IBS27** [comment] 2021-06-25 06:42
@Kethku how do you insert emojis in neovide? In terminal vim I just press the fn key on mac and I get the emoji picker. But if I do the same thing in neovide it doesn't take it. The emoji feature in neovide is useless if I can't insert emojis.

**Comment by Kethku** [comment] 2021-06-25 06:46
It's not useless as the primary use case for it was to enable linting overlays which depends on some emoji.

Is what you describe standard behavior on Mac?

**Comment by IBS27** [comment] 2021-06-25 06:49
By what I described, what exactly do you mean?

**Comment by IBS27** [comment] 2021-06-25 12:18
@Kethku I tried out the latest build and the dead keys issue seems to be fixed.

**Comment by IBS27** [comment] 2021-06-25 12:18
@Kethku the icons are still not working. Can I just get the .icns file of the icon for mac as it looks weird now.

**Comment by shaunsingh** [comment] 2021-06-25 14:08
@IBS27 Can you try cloning this: https://github.com/Kethku/neovide/pull/746, and running `make dmg`? That should create a .dmg build that you can open and run, with the icon.

**Comment by IBS27** [comment] 2021-06-25 14:23
I tried it. It throws an error while building. This always happens when it starts building skia-bindings.

**Comment by fredizzimo** [comment] 2021-07-08 19:25
I have the same problem on Windows, but I believe the description of the bug is wrong.

It doesn't seem to have anything to do with font fallbacks, it happens when using patched fonts with all the required glyphs.

Instead I'm fairly sure it's related to how colored double width glyphs are rendered. For me it happens with telescope.nvim, but only if I set the option `color_devicons`  to true. It does not happen in `nvim-tree.lua`, but that's because it has a workaround in the plugin itself

This is not a unique problem to Neovide, some terminals also have the same problem, but others like Alacritty, which I'm using render the glyphs correctly. 

The issue is discussed here https://github.com/nvim-telescope/telescope.nvim/issues/674, and here https://github.com/nvim-telescope/telescope.nvim/issues/358
The fix for nvim-tree (adds highlight to the space following the glyph) is here https://github.com/kyazdani42/nvim-tree.lua/pull/162

**Comment by st-rafer** [comment] 2021-08-28 09:26
I have the same bug (at left) on linux too, with same config in neovim over alacritty (at right) it looks good:
<img src="https://user-images.githubusercontent.com/25098837/131213001-df4b3966-eb29-4765-b6f3-18fd9d7df29c.png" width="100" height="300">     <img src="https://user-images.githubusercontent.com/25098837/131213074-094b669e-5065-49fc-8c14-06e176915349.png" width="100" height="300">

**Comment by alexzanderr** [comment] 2021-09-27 23:14
yes
im experiencing the same thing ( a little chop from icons )

nvim-tree si fine
![image](https://user-images.githubusercontent.com/54772464/134997564-0466da1b-a269-4bda-925f-145be0b00f30.png)


but the rest ...

symbols outline
![image](https://user-images.githubusercontent.com/54772464/134997575-e7dc7cbc-eef6-4d64-a7be-1eb38185197e.png)

telescope
![image](https://user-images.githubusercontent.com/54772464/134997599-3ec543f2-bcb4-4034-af69-f97744161459.png)

**Comment by Kethku** [comment] 2021-09-28 00:55
I just merged a change which I believe fixes this issue. Can you try building from main?

**Comment by st-rafer** [comment] 2021-09-28 05:37
Excellent work @Kethku !
<img src="https://user-images.githubusercontent.com/25098837/135029327-8f1bc1ae-00b8-45f5-b710-7a80a310b333.png" width="100" height="300">

**Closed** 2021-09-28 07:18 UTC
Labels: bug

**Comment by alexzanderr** [comment] 2021-09-28 08:20
> Excellent work @Kethku !
> <img alt="" width="100" height="300" src="https://user-images.githubusercontent.com/25098837/135029327-8f1bc1ae-00b8-45f5-b710-7a80a310b333.png">

did you tested with telescope or symbols outline or aerial?

**Comment by st-rafer** [comment] 2021-09-29 03:50
> did you tested with telescope or symbols outline or aerial?

Yes, that's ok

<img src="https://user-images.githubusercontent.com/25098837/135199612-96289e89-65be-4a39-b0d2-46428cc7741f.png" width="100" height="300">     <img src="https://user-images.githubusercontent.com/25098837/135200186-d4a92660-9699-421f-93aa-10516642d3ff.png" width="100" height="300">
