### ISSUE TITLE
Add a Small Icon for Windows - alt tab menu

### ISSUE THREAD

**Issue by madcdevelop** [neovide/neovide#2391] opened 2024-03-01 15:20 UTC
**Is your feature request related to a problem? Please describe.**
On Windows 10 or 11 when you use the old Alt Tab menu from Windows NT it uses small icons. Neovide doesn't show the same icon as when you use the newer alt tab display.

**Describe the solution you'd like**
I would like the current Neovide icon to be set as a small icon for Windows builds so that it's easy to distinguish when switching between apps.

**Describe alternatives you've considered**
I've looked at the code but it doesn't seem to be anywhere you can set the small icon for windows. 
I found these alternatives though I'm unfamiliar with rust.
- https://github.com/mxre/winres
- https://anthropicstudios.com/2021/01/05/setting-a-rust-windows-exe-icon/

![image](https://github.com/neovide/neovide/assets/40719351/b32ddd69-f12f-43fb-9b20-2052ce2d6555)

**Comment by falcucci** [comment] 2024-03-01 15:35
PR welcome @madcdevelop 🙂

**Comment by fredizzimo** [comment] 2024-03-01 16:12
I think we need to update the `winres` package, our version is 0.1.12 which does not have this fix
* https://github.com/mxre/winres/issues/28

If someone wants to attempt to fix it, it should be trivial by just changing `Cargo.toml`. I'm not on Windows now, so I can't do it myself at the moment.

**Comment by fredizzimo** [comment] 2024-03-01 16:26
Sorry it looks like it was never merged... So, I think we should switch to this fork instead https://github.com/BenjaminRi/winresource. It should be a drop-in replacement, at least for our use cases.

**Comment by madcdevelop** [comment] 2024-03-07 16:05
I tried to update to winresource but the icon is not showing up. It shows up for the Command Prompt window but not Neovide itself. I don't see a **.res** file which I thought was needed for the icon shown here: https://anthropicstudios.com/2021/01/05/setting-a-rust-windows-exe-icon/

**Cargo.toml**
```
[target.'cfg(target_os = "windows")'.build-dependencies]
winresource = "0.1"
```

**build.rs**
`let mut res = winresource::WindowsResource::new();`

![image](https://github.com/neovide/neovide/assets/40719351/19eaeade-8a7f-4fa9-84f2-db60915cbd82)

**Comment by fredizzimo** [comment] 2024-03-07 16:07
The latest version is 0.1.17 https://docs.rs/winresource/latest/winresource/, can you try to update to that?

**Comment by madcdevelop** [comment] 2024-03-08 14:56
I tried updating to 0.1.17 explicitly, but it doesn't seem to work.
`winresource = "0.1.17"`

![image](https://github.com/neovide/neovide/assets/40719351/9bbe5772-86bc-4e42-9d20-273fad1c1b85)

**Comment by fredizzimo** [comment] 2024-03-08 16:22
I'm not sure what the problem is, but it's possible that we need 8-bit icons as well:
https://learn.microsoft.com/en-gb/windows/win32/uxguide/vis-icons?redirectedfrom=MSDN
It's at least strongly recommended there, and the default Visual Studio icons include 8-bit.

Do you think you can try adding 8-bit, following the instructions there to `assets/neovide.ico`? I don't really want to edit the registry to test the old alt-tab menu myself.

**Comment by madcdevelop** [comment] 2024-03-09 15:35
Tried the 8-bit icon but it doesn't work.
I was reading at the bottom of this page: https://anthropicstudios.com/2021/01/05/setting-a-rust-windows-exe-icon/
It says you need to call this function and assign the icon to the window class.
```
HICON icon = LoadIconA(hInstance, "arbitrary_name_here");
global_window_class.hIcon = icon;
```

I saw the project uses Winit. I downloaded the latest source code from that project. Winit doesn't end up setting the `hIcon` when they register the window class. Maybe that needs to be updated?
![image](https://github.com/neovide/neovide/assets/40719351/6dbe1acf-3046-4483-b411-3a18c41ff7fe)

**Comment by fredizzimo** [comment] 2024-03-09 19:43
I think we are also setting the window icon correctly,

It's done here https://github.com/neovide/neovide/blob/13077db88e7f464d6841f6bb121d60c013ada55b/src/window/mod.rs#L157

Which ends up calling 
https://github.com/rust-windowing/winit/blob/563b0bf5e38e8d2785bd7da3db8b0a83c4b1821d/src/platform_impl/windows/icon.rs#L138

But, I noticed there's also `with_taskbar_icon` https://docs.rs/winit/latest/x86_64-pc-windows-msvc/winit/platform/windows/trait.WindowBuilderExtWindows.html#tymethod.with_taskbar_icon

Which sets the large icon of the window and from this documentation  https://learn.microsoft.com/en-us/windows/win32/winmsg/wm-seticon
> The system displays the large icon in the ALT+TAB dialog box, and the small icon in the window caption.

So, that seems like the one we need to set.


We should probably also load the correct sizes, for better quality, I don't actually know which size it loads right now.


I think it needs to be called like this
`WindowBuilderExtWindows::with_taskbar_icon(winit_window_builder, Some(icon))

**Comment by madcdevelop** [comment] 2024-09-29 01:22
Hello, I got this working now with the following code. It displays the window icon in the old alt+tab dialog. I will create a pull request now.

neovide/src/window/mod.rs
```
    #[cfg(target_os = "windows")]
    let window_attributes = window_attributes
        .with_taskbar_icon(Some(load_icon()));
```

**Comment by madcdevelop** [comment] 2024-09-29 01:34
hmm. I'm not able to push my branch. Any help is appreciated. Thanks!
```
λ git push -u origin windows-app-icon
remote: Permission to neovide/neovide.git denied to madcdevelop.
fatal: unable to access 'https://github.com/neovide/neovide/': The requested URL returned error: 403
```

**Comment by Kethku** [comment] 2024-09-29 01:39
I think you are trying to push to the main repo which we don't allow directly. If thats the case, you need to fork the repo on github and push your branch there. Once thats done you can open a pull request

**Comment by madcdevelop** [comment] 2024-09-29 01:57
ok thanks! Created a pull request: https://github.com/neovide/neovide/pull/2816

**Closed** 2024-10-05 18:12 UTC
Labels: enhancement
