### ISSUE TITLE
Neovide doesn't open file specified if called with 'open' macos command

### ISSUE THREAD

**Issue by Yohannfra** [neovide/neovide#1613] opened 2022-10-22 21:38 UTC
**Describe the bug**

Last month I made this [PR](https://github.com/desktop/desktop/pull/14929) in Github desktop software to add Neovide support. It got merged but It doesn't work and open a blank Neovide.

I tried to reproduce the issue in the terminal: If I open Neovide with the **open** command like this
```
$ open -a Neovide -- main.c
```

It opens a blank Neovide.

But if I open it with the full path to Neovide like this
```
$ /Applications/Neovide.app/Contents/MacOS/neovide main.c
```

Then it opens the file.

**Expected behavior**

The file should open in both way

**Desktop (please complete the following information):**
 - OS: MacOS 12.4
 - Neovide Version 0.9.0

**Comment by sharpenedblade** [comment] 2023-02-05 22:03
This is a duplicate of https://github.com/neovide/neovide/issues/1682. Using `open` will call the applications `openFile` handler, which Neovide *does not* support. Calling the binary will pass the file as an argument, which Neovide *does* support.

**Comment by fredizzimo** [comment] 2024-01-13 05:41
Closing as duplicate of
* #1682

**Closed by fredizzimo** 2024-01-13 05:41 UTC
Labels: bug, macos
