### ISSUE TITLE
Settings through pure lua (vim.g)

### ISSUE THREAD

**Issue by AckslD** [neovide/neovide#1487] opened 2022-08-16 08:16 UTC
**Describe the bug**
Setting config values using pure lua (`vim.g`) instead of vimscript (`let g:`) does not seem to trigger an update of eg transparency.

**To Reproduce**
```
:lua vim.g.neovide_transparency = 0.2
```
**Expected behavior**
Transparent window

**Desktop (please complete the following information):**
 - OS: arch linux 5.19.1-arch2-1
 - Neovide Version 10.1
 - Neovim Version v0.8.0-dev-854-gd334249833

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

**Additional context**
```
:let g:neovide_transparency=0.2
```
does work.

**Comment by MultisampledNight** [comment] 2022-08-16 08:57
Thank you for reporting! After a discussion on Element yesterday, I can confidently link https://github.com/neovim/neovim/pull/15373 and say "this is to be fixed upstream". Closing as duplicate of #745.

**Closed by MultisampledNight** 2022-08-16 08:57 UTC
Labels: bug

**Comment by AckslD** [comment] 2022-08-16 09:12
Thanks @MultisampledNight! Sorry for the duplicate, I searched for "vim.g" in the issues but didn't get a match for some reason.

**Comment by clason** [comment] 2022-09-27 16:19
Finally fixed upstream.
