### ISSUE TITLE
Moving cursor forces user out of terminal mode (i3)

### ISSUE THREAD

**Issue by Algorhythm-sxv** [neovide/neovide#1838] opened 2023-04-15 18:46 UTC
**Describe the bug**
When a terminal buffer is open and in terminal node, moving the cursor inside the neovide window forces the user into normal mode. This does not occur when in e.g. insert mode in a text buffer, and is only present in neovide, not terminal neovim.

**To Reproduce**
1. run `:terminal` and enter terminal mode
2. move the mouse cursor inside the neovide window

**Expected behavior**
The buffer remains in terminal mode until keyboard input forces it out

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Neovide Version 0.10.4
 - Neovim Version 0.9.0

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
Log is very long (2670 lines). I can provide it elsewhere if necessary.

**Comment by sa-mendez** [comment] 2023-05-10 20:08
I am experiencing this as well.  It appears to have started happening in Neovide version 0.10.4 in confjunction with Neovim Version 0.9, as it was not happening to me before that.

**Comment by amv-dev** [comment] 2023-05-13 19:09
I have the same problem.
Linux 6.1 / X11 21.1.8 / Gnome 43.5

**Comment by amv-dev** [comment] 2023-05-13 21:53
Found temporal solution.
`tnoremap <MouseMove> <NOP>`
or
`vim.keymap.set("t", "<MouseMove>", "<NOP>)`

**Comment by TheDreadedAndy** [comment] 2023-06-27 01:19
> Found temporal solution.
> `tnoremap <MouseMove> <NOP>`
> or
> `vim.keymap.set("t", "<MouseMove>", "<NOP>")`

That resolved the issue for me, but it also hints at what the actual problem is: Neovide is ignoring the value of `mousemoveevent` and always sending `<MouseMove>`. If you set `mousemoveevent` while running Neovim in a terminal, the issue is present there as well.

The documentation for the Neovim terminal is worded in such a way that I can't tell if this is a bug or not. I _think_ it's not, since the help file says focus is lost from the terminal if the program running in it doesn't catch a mouse event.

**Comment by fredizzimo** [comment] 2023-09-13 10:08
Yes, we should fix the `mousemoveevent` option. The issue was known by the author of the feature that added the mouse movement support, but it was merged a bit prematurely https://github.com/neovide/neovide/pull/1766

**Comment by 9mm** [comment] 2023-09-13 13:06
@amv-dev awesome thanks for this

**Comment by fredizzimo** [comment] 2023-09-13 15:09
@9mm, I'm answering this here:

> With that said... what actually makes the `mousemoveevent` ignore the floating window? Wouldnt it make sense if it floated back onto the window when the mouse is back over it? or is that not how it works. No need to really answer just curious if you feel like it.

@TheDreadedAndy, explained why that happens, More specifically these lines in the documentation https://github.com/neovim/neovim/blob/27a566f3f8e07a4cebb426674800bdf9a7f4f222/runtime/doc/nvim_terminal_emulator.txt#L92-L93
> - If mouse events are disabled (the default), terminal focus will be lost and
  the event will be processed as in a normal buffer.

What this really means, is that it will exit the terminal mode unless the terminal app you are running handles the mouse:
For example, if you run this in your terminal:
`dialog --yesno "Are you OK?" 5 20`

Then it will stay in the terminal mode as long as the dialog is open, and you can click the buttons with the mouse. 

The reason why properly respecting `mousemovementevent` fixes the issue, is that it defaults to off. And then it only sends mouse events when you actually click something. But now we are sending it all the time, so it exits the terminal mode as soon as you move the mouse.

**Comment by fredizzimo** [comment] 2023-09-13 15:21
And thinking more about it, I think this is something that should be reconsidered on the Neovim side as well. 

It makes totally sense that mouse clicks exit the terminal mode, so that you are able to easily select and copy some text. But I can't really see any use cases of exiting the terminal mode when the mouse is moved.

**Closed** 2023-11-08 19:31 UTC
Labels: bug

**Comment by Crispy13** [comment] 2024-05-27 00:10
Is this issue resolved?
I'm experiencing the exact same thing

When I move the mouse, it automatically enters normal mode from terminal mode.
