### ISSUE TITLE
some weird 0.12.0 release build regression test failure

### ISSUE THREAD

**Issue by chenrui333** [neovide/neovide#2199] opened 2023-12-24 17:51 UTC
👋 trying to build the latest release, but run into some build issue. The error screenshots are as below:

![image](https://github.com/neovide/neovide/assets/1580956/2e9bcd06-951b-4f7d-a293-12dc6df7dd34)
![image](https://github.com/neovide/neovide/assets/1580956/19cd79f3-2354-426c-a6c0-1f595aa29c83)

relates to Homebrew/homebrew-core#158189

**Comment by chenrui333** [comment] 2023-12-24 17:52
I just regression test the 0.11.2 bottle, works fine in my local.

![image](https://github.com/neovide/neovide/assets/1580956/5520f1df-ee48-4d5a-b2ff-1bf1d9dec7a3)

**Comment by fredizzimo** [comment] 2023-12-25 16:55
I'm closing this as a duplicate of https://github.com/neovide/neovide/issues/2204, even if this one is older, since the other issue is more descriptive about the actual problem.

**Closed by fredizzimo** 2023-12-25 16:55 UTC
