### ISSUE TITLE
Mouse scrolling with Multigrid is broken

### ISSUE THREAD

**Issue by TudbuT** [neovide/neovide#1746] opened 2023-01-25 20:59 UTC
**Describe the bug**
When scrolling **up** while multigrid is enabled, the cursor can get stuck, and part of the screen doesn't reload.

**To Reproduce**
1. Enable multigrid
2. Open a large file, with mouse=a and smooth scrolling enabled
3. Scroll down for a while, then scroll up some amount again. Do not scroll so much as to make the cursor hit the top of the screen.
4. This might require multiple attempts. Repeat 3 until something happens.
5. The bottom of the screen will appear funky, and the cursor will hover over a nonexistent character, possibly even inbetween lines.

**Expected behavior**
Scrolling shouldn't break the alignment of the grid so much, and shouldn't leave parts of the grid empty.

**Screenshots**
![image](https://user-images.githubusercontent.com/48156391/214440670-2d102f8d-3d89-4510-88ad-016ea6ee0ea5.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux, i3wm
 - Neovide Version 0.10.3
 - Neovim Version v0.8.2
   Build type: Release
   LuaJIT 2.1.0-beta3
   Features: +acl +iconv +tui

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/10503647/neovide_rCURRENT.log)

**Additional context**
This only happens when scrolling up.

**Comment by fdev31** [comment] 2023-01-27 13:49
Could be a duplicate of #1630 
And looks eventually related to #1584

**Comment by TudbuT** [comment] 2023-01-27 20:22
Looks similar to 1630, but is not a duplicate. 1630 fixes itself after the animation is done, and isnt a regression. This one is a regression and stays until i click somewhere.

**Comment by b4skyx** [comment] 2023-04-04 17:07
Bump. I can reproduce this bug on windows.

**Comment by fredizzimo** [comment] 2023-07-31 09:44
This will be fixed by https://github.com/neovide/neovide/pull/1870.

**Closed** 2023-11-01 18:54 UTC
Labels: bug, multigrid
