### ISSUE TITLE
Cursor focuses to command line

### ISSUE THREAD

**Issue by comiluv** [neovide/neovide#902] opened 2021-08-17 01:17 UTC
**Describe the bug**
If a user presses i to enter insert mode from normal mode, the cursor gets misplaced at the bottom of the command line where -- INSERT -- appears

**To Reproduce**
1. press i in Normal mode

**Expected behavior**
The cursor is placed on the text where user pressed keyboard key "i" on

**Screenshots**
![GIF 2021-08-17 오전 10-08-45](https://user-images.githubusercontent.com/19642705/129648176-91e65318-4d2b-4fcc-a44c-58ad6c820f8a.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10/21H1 19043.1165
 - Neovide Version Neovide version: 0.8.0
 - Neovim Version NVIM v0.6.0-dev+116-g35041432b

**Please run `neovide --log` and paste the contents of the `.log` file here:**

**Additional context**
Happens with almost empty init.vim file

**Comment by Kethku** [comment] 2021-08-17 02:40
do you have lazyredraw set in your config?

**Comment by comiluv** [comment] 2021-08-17 03:15
I don't use that setting when running Neovide.

My init.vim is exactly as follows:
```vimscript
set runtimepath^=~/vimfiles runtimepath+=~/vimfiles/after
set packpath+=~/vimfiles
set guifont=JetBrainsMono\ Nerd\ Font:h12
source ~/OneDrive/dotfiles/.vim/vimrc
```
and ~/OneDrive/dotfiles/.vim/vimrc was purposely modified to be like below to skip my vimrc settings when I tested this
```vimscript
finish
" My previous vimrc settings below
```
I also have set lazyredraw to only run when in I'm not running neovide anyway:
```vimscript
if exists('g:neovide')
    set notitle
else
    set lazyredraw
    set title
endif
```

**Comment by JorisDeRidder** [comment] 2021-08-24 12:51
I can confirm this bug in Neovide 0.7.0 on Max OSX 10.15.7.

**Comment by Kethku** [comment] 2021-08-24 20:54
Interesting. Seems like nvim 0.6.0 may have changed something. Does the problem occur with nvim 0.5?

**Comment by JorisDeRidder** [comment] 2021-08-25 06:54
Yes, it does. I'm using nvim v0.5.0-dev+1274-gbb3372792.

**Comment by Kethku** [comment] 2021-08-25 08:18
Ok cool, that rules that out. Can you link your vim config?

**Comment by Gremious** [comment] 2021-12-15 21:13
Wanted to chime in and say that this happens to me too, and bothers me a lot because it means that every time I enter insert mode - the cursor is gone until moved, which is really disorienting when you're about to start typing.

I am running neovide 0.7.0, and having deleted my entire init.vim to check - it still happens. All I gotta do is spam i -> esc over and over and the cursor basically stays at that --INSERT-- in the command line.

It behaves a bit weird, if you just spam i -> esc it goes there *most* of the time. Sometimes it'll stay there through like 8 insert mode cancels before going back to it's rightful place for 1, or vice-versa.

**Comment by Gremious** [comment] 2021-12-16 16:26
Update: I believe this only happens when `--multigrid` is not enabled.
(I am now just running with multigrid on and am v happy about having smooth animations and no disappearing cursor, so that's deffo good enough for me).

**Comment by fredizzimo** [comment] 2022-01-07 14:41
I think this is either fixed by https://github.com/neovide/neovide/pull/1131 or something before it, since it used to happen for me all the time, but not anymore when I just tested. And yes, `--multigrid` fixed it before, but now I tested without multigrid too.

**Comment by Kethku** [comment] 2023-04-09 07:15
Closing as I think this is fixed

**Closed by Kethku** 2023-04-09 07:15 UTC
Labels: bug
