### ISSUE TITLE
Neovide crash / not responding, window don't show up

### ISSUE THREAD

**Issue by xarthurx** [neovide/neovide#1995] opened 2023-08-27 11:23 UTC
[

**Describe the bug**
Similar to the bug here: https://github.com/neovide/neovide/issues/972

**To Reproduce**
1. Open `neovide`
2. Hibernate the PC
3. Wake up the PC again
4. neovide is not responding and don't show the window. Need to kill the process.

**Expected behavior**
Don't crash 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Neovide Version 0.11.1
 - Neovim Version `0.9.1`

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**

**Additional context**
](https://github.com/neovide/neovide/issues/972)

**Comment by xarthurx** [comment] 2023-08-29 07:35
Additonally, sometimes the window showed up, but looks like this (the content is at upper left corner, but window freeze)

![image](https://github.com/neovide/neovide/assets/1921878/90ec465a-611d-4eb3-8005-89f84742ede0)

**Comment by xarthurx** [comment] 2023-08-31 07:16
I think I don't have this issue very often during `v.0.10.4`, but after updating to `v0.11.x`, this almost happens every time my computer wakes up from sleep.

**Comment by fredizzimo** [comment] 2023-09-02 20:21
I'm unable to reproduce this myself, after several tries. Neither on the 0.11.1 version or on the render loop fix branch https://github.com/neovide/neovide/pull/1977

I would start by checking that you have up to date GPU drivers. That could cause issues similar to what you are seeing.

There's also a possibility that there's some kind of Windows event flooding, in that case https://github.com/neovide/neovide/pull/1977 should fix it. So, it's worth trying if that fixes the issue.

Otherwise, I'm afraid that there's no easy way to debug this, other than building from the source and launch through a debugger and check where it freezes.

**Comment by fredizzimo** [comment] 2024-01-24 08:20
I can reproduce something similar myself now, but I think that's a new regression in 0.12.0 and later. When I leave Neovide  running on a disconnected remote desktop over the night, it takes a long time to respond.

I have not fully debugged it, but it seems to be caused by this:
* https://github.com/neovide/neovide/pull/2188

More specifically in this code
https://github.com/neovide/neovide/blob/3e575fcd21863fdaa1fd14d23db649738694af97/src/window/update_loop.rs#L148-L156

The delta should not be allowed to be too large.

**Comment by fredizzimo** [comment] 2024-05-17 11:33
This should be fixed in Neovide 0.13.0

**Closed by fredizzimo** 2024-05-17 11:33 UTC
Labels: bug
