### ISSUE TITLE
Super+nr captured by neovide when switching panes in xmonad

### ISSUE THREAD

**Issue by kilpkonn** [neovide/neovide#763] opened 2021-06-27 08:34 UTC
**Describe the bug**
`Super+nr` is caputred by neovide whilst not by terminal / opter apps when switching between panes in xmonad.

**To Reproduce**
1. Open neovide
2. Go to insert mode
3. Type `abc`
4. Switch panes with `Super+2`
5. Switch back with `Super+1`
**6. See that `<D-2>` is entered**
7. Exit neovide

**Expected behavior**
No `<D-nr>` when switching between tabs should be entered.

**Desktop (please complete the following information):**
 - OS: Arch x86
 - Neovide Version `0.7.0.r56.g82b745c-1` <- latest on main branch
 - Neovim Version `0.4.4`

**Please run `neovide --log` and paste the contents of the `.log` file here:**
_Sadly the contents of the log file are too big (even tho I did like 10 keypresses), and GitHub does not allow pasting it here XD_

**Additional context**
Followup for https://github.com/Kethku/neovide/issues/759  
^ Can't really reopen (due to permissions?), so created new issue with narrowed down scope  
Also since I upgraded neovide to never build, issue 3 got fixed, 2 can be disregarded (oops :p), but issue 1 remains.  
I noticed that previously it captured both switching away and switching back to tab keypresses, but now it captures only one (switching away).

**Comment by kilpkonn** [comment] 2021-06-27 08:38
[neovide_rCURRENT.log](https://github.com/Kethku/neovide/files/6721261/neovide_rCURRENT.log)

**Comment by jceb** [comment] 2021-06-30 08:04
Same OS and same issue here.

**Comment by voider1** [comment] 2021-06-30 17:15
I'm on Pop!_OS 20.04 LTS x86_64, I'm using Gnome with the tiling extension from Pop. Whenever I switch window focus using super+h/j/k/l the window will act as if I'm holding the super key all the time and input every character as `<D-f>` if I would type `f`.

**Comment by lucas-miranda** [comment] 2021-07-30 12:01
I forget to mention this issue on my recently merged pull request #845, as #826 seems to be a duplicate of this issue originally

Can you try main to see if the issue persists?

**Comment by jceb** [comment] 2021-07-30 16:30
I can still reproduce the issue.

**Comment by lucas-miranda** [comment] 2021-07-31 01:43
@jceb could you please provide a log generated through `neovide --log` while reproduce the issue?

I tried to reproduce myself again several times using main branch and I can't do it

**Comment by jceb** [comment] 2021-07-31 09:46
Here are the logs and also the visual output in neovide:

[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/6910974/neovide_rCURRENT.log)

![210731_114347_neovide_press_super-k](https://user-images.githubusercontent.com/101593/127735968-85e2ad57-cdff-4a7f-8484-0263ea13d3b5.png)

**Comment by lucas-miranda** [comment] 2021-08-02 15:57
I've tried to figure out how to solve this past days, but this issue seems more a design problem than something else, as I'm just recently trying to collaborate to the project I'm mentioning @Kethku to guide me of what should be done, so I'll do a little overview about the issure

As I already said previously, issue #826 is a duplicate of this issue originally, and as my pull request #845 seems to fix the problem, it isn't entirely true, as @jceb reported and I'm able to reproduce it with some tricky key combinations

I think terminals just completely ignore command key inputs and it doesn't interfere with neovim usage, I've been using kitty  with neovim before switching to neovide and I've never run at something like this and to even be sure of that, as an example, kitty is ignoring command key and not forwarding to neovim, I've tested a simple map at neovim using command key plus something else and only at neovide it triggers (proving what I said)

After all that, I can only see two solutions:

1. Completely ignore command-key at linux also (and probably mac)

As it's already ignored at windows:
https://github.com/neovide/neovide/blob/257ec70a802094d8f9faed6b5cfbae77a8face24/src/window/window_wrapper/keyboard_manager.rs#L138-L143

To avoid this problem and to keep everything normalized between SOs and how terminals handle this subject, as it's very normal to someone which uses tiled window managers at linux to bind command/super key to move around and do things at windows

2. Just let it as it is and move on, as there is no way to know when a specific key combination should affect wm or when it should be a nvim thing, we can only know when we gain or lost focus, but some key combinations can come before these events, and it's resolution at `Event::MainEventsCleared` step, even occurs, as I checked myself a couple of times at my setup

Maybe there is another solution which I'm simply not seeing, so I ask @Kethku to decide what could be done about that

I can provide some logs showing every single winit event also while reproducing the issue

**Comment by Kethku** [comment] 2021-08-02 16:22
Maybe the correct solution would be to disable D modifiers by default and expose an option which re-enables them. This would also allow windows users to enable them if they so desire

**Comment by jceb** [comment] 2021-08-02 17:59
I like the strayed solution a lot. Terminals are a limiting factor when it comes to keybindings and since neovide isn't a terminal it doesn't have to abide to its rules.

**Comment by Kethku** [comment] 2021-08-02 20:54
What do you mean by strayed?

**Comment by lucas-miranda** [comment] 2021-08-03 14:56
> Maybe the correct solution would be to disable D modifiers by default and expose an option which re-enables them. This would also allow windows users to enable them if they so desire

I completely agree
I'm already working on this and when I was testing it, I had the following doubt: 

Shouldn't the entirely keyboard input be ignored when using D modifier (when at disabled state)? 
Otherwise we'll fall to the same issue, but without `<D->` part, just looking to how it's ignored the super key at windows SO, it's just suppressed from sending to nvim

**Comment by jceb** [comment] 2021-08-03 18:11
@Kethku sorry, typo,I meant suggested solution.

**Closed** 2021-08-04 19:38 UTC
Labels: bug
