### ISSUE TITLE
Alt send Esc in MacOs

### ISSUE THREAD

**Issue by augustocdias** [neovide/neovide#1046] opened 2021-11-15 16:20 UTC
Keymaps with the Alt key in MacOs doesn't work. What other apps that handle terminal does is configure it to send esc. [Alacritty](https://github.com/alacritty/alacritty/blob/1df7dc5171abfe1eab3e95be964f61c5876198f1/alacritty/src/input.rs#L809) and iTerm does that and it works fine with neovim.

**Comment by michalspano** [comment] 2021-11-17 08:40
The same issue here. 😿 
Ver. `macOS Big Sur 11.6.1 (20G224)`

**Comment by jasoneveleth** [comment] 2021-12-15 23:07
Here is a workaround:

```
map ˙ <a-h>
map ∆ <a-j>
map ˚ <a-k
map ¬ <a-l>
```
The way to map more of them is to type in insert mode <c-v><a-*> with * as a character, and map the output of that.

**Comment by ioreshnikov** [comment] 2022-06-30 08:14
@augustocdias @michalspano @jasoneveleth Hey, guys! I have a potential fix in PR #1366. At the moment it's not merged since we are waiting for more people to test. Could you please, if possible, re-build `neovide` from this repo

https://github.com/ioreshnikov/neovide

and test it with an additional flag in your `init.vim`

```
let g:neovide_input_macos_alt_is_meta=v:true
```

**Comment by augustocdias** [comment] 2022-06-30 09:12
Just installed. So far it is working as expected. Great job

**Comment by michalspano** [comment] 2022-06-30 09:26
Tried it; works as expected. I had a look at the __PR__ - there should be no problems either. Well done, @ioreshnikov!

```
ProductName:   macOS
ProductVersion: 12.1
BuieldVersion: 21C52
```

**Closed** 2022-06-30 15:47 UTC
Labels: enhancement

**Comment by jasoneveleth** [comment] 2022-07-01 17:18
I tried it and it worked perfectly. Well done

**Comment by jargv** [comment] 2023-01-05 22:40
This is working well for me, except for the mapping `<a-u>` 🤔. That mapping worked fine in Iterm2, so it seems like an issue with neovide. Any reason `<a-u>` would be different than other mappings like `<a-q>`, `<a-m>`, etc, which all work fine for me?

**Comment by ioreshnikov** [comment] 2023-01-06 11:39
No idea, but I have a feeling that after a `<a-u>` it's waiting for the next keypress. So if you press `<a-u> j j` it'll silently consume the first `j` and then only the second one gets processed.

**Comment by jargv** [comment] 2023-01-07 22:00
> No idea, but I have a feeling that after a `<a-u>` it's waiting for the next keypress. So if you press `<a-u> j j` it'll silently consume the first `j` and then only the second one gets processed.

Thanks for the response. Yes that's exactly what I'm seeing. The output is `¨j`. I tried this in normal, insert, and terminal mappings, all with the same result. I'm seeing the correct/expected behavior for the mapping in iterm2, and neovide on Linux. 

The output of `:map <a-u>?` is as expected, with just a single mapping, so I'm not sure why it would be waiting on additional keys. (same for imap and tmap). I also tried adding `nowait`, but no luck.

I tried creating the mapping through `vim.api.nvim_set_keymap` as well as with the traditional vimL `nnoremap <a-u> ...` which also didn't make any difference.
