### ISSUE TITLE
no node in path when running in --wsl mode

### ISSUE THREAD

**Issue by Lite5h4dow** [neovide/neovide#950] opened 2021-09-11 20:43 UTC
**Describe the bug**
when you run neovide from any terminal (WSL, Powershell, CMD) in WSL mode, there is no node in path despite if you launch nvim from the WSL terminal it is there because .zshrc initialised the path.

**To Reproduce**
1. run `neovide.exe --wsl` from any environment
2. enter `<ESC>:!which node<CR>`
3. See `node not found`
4. Coc will crap itself on launch if you have that installed 

**Expected behavior**
I would expect node to be in path

**Screenshots**
![image](https://user-images.githubusercontent.com/18059545/132961123-13564c9f-4d3b-4b64-82d0-2afedd02aa63.png)

**Sidenote**
if anyone knows a decent alternative to Coc that dosent require node, and has Typescript support (Deno and Node) i would be open to switching.

**Comment by PyGamer0** [comment] 2021-09-12 03:49
Does it work if you don't use neovide? (calling neovim from wsl)

**Comment by Lite5h4dow** [comment] 2021-09-12 22:11
@PyGamer0 yes it does.

**Comment by Lite5h4dow** [comment] 2021-09-13 10:59
nvim in terminal:
![image](https://user-images.githubusercontent.com/18059545/133072303-da8b6582-ca48-48d0-8e06-822d19157d79.png)

**Comment by Kethku** [comment] 2021-09-18 18:41
I don't know much about linux integration with windows.

Recently a change went in to try to harvest the path from the wsl bash before running to fix issues like this. The relevant line is here:
https://github.com/neovide/neovide/blob/main/src/bridge/mod.rs#L39

Sounds like you're using zsh? I don't know, but is it possible that that config isn't loaded with the wsl command linked above?

**Comment by fredizzimo** [comment] 2022-01-03 12:21
I created a pull request that should fix this issue https://github.com/neovide/neovide/pull/1118

**Comment by fredizzimo** [comment] 2022-01-12 13:42
I merged #1118. But see the comments there, there might be unexpected problems, so open a new issue if you find any.

**Comment by williamJmelton** [comment] 2022-02-04 05:17
I'm also having this issue having just built Neovide from source last week. When launching neovide.exe --wsl I don't get the executables added to my path from my .zshrc. When I launch with --wsl with the WSL distro's default login shell set to bash I don't have the PATH problems, but I do when using zshrc

**Comment by fredizzimo** [comment] 2022-02-04 09:03
Hm, are you sure if you were building the latest master version? If not I will check later today or tomorrow to see if something has broken, since there were some refactoring to the code after I wrote it, and I haven't updated to that version myself yet.

**Comment by Hackder** [comment] 2022-09-24 19:12
I had the same issue, I fixed it on the current stable version. When you launch this command from powershell:
`wsl zsh -lc 'node --version'`, it won't find the node executable. As it turns out, the wsl.exe only loads profile files. In my case `.zprofile`.

To fix this you need to add this line:
`source ~/.zshrc`
to the end of your `.zprofile` file.

**Comment by fredizzimo** [comment] 2022-09-25 23:49
@Hackder,

Yes, that's what's happening if you run a login shell in a non-interactive mode, `.zshrc` is not supposed to load in that case. https://zsh.sourceforge.io/Guide/zshguide02.html, `.zshrc` only runs for interactive shells.

So if you start `wsl zsh -lic 'node --version'` it should  run `.zshrc`. 

I fixed it here https://github.com/neovide/neovide/pull/1118, but it looks like there's a regression here  it https://github.com/neovide/neovide/pull/1217, depending on how you look at, which disables the interactive mode, but keeps the login mode. I haven't personally seen the issue, since I haven't updated my version of Neovide for quite a while.

You could argue that the new behaviour of disabling the interactive mode is correct, since we don't show any console, or let you type anything before Neovide is launched. However, that's also a little bit troublesome, since Neovim is a shell program, normally launched from an interactive shell, and people excpect that all of their normal shell environment is availabe. Note that, any embedded terminals launches an interactice shell, so everything is available there. 

I guess the ideal fix would be to actually display a terminal before Neovim is launched. But that's probably a lot of work. A command line option to enable the interactive shell, could be another alternative. Or then just leave it as it is, and the startup files acts as if you are launching a graphical environment through a display manager for example.

If we leave it as it is, it mostly only affects `zsh` users, maybe `fish`  and other shells, but I'm not familiar with their startup behaviour. `.bashrc` is typically sourced from `.bash_profile` so that's why bash users are mostly unaffected.

However, the same should not be done for zsh, since both `.zshrc` and `.zprofile` are automatically source for interactive login shells, so you would end up loading `.zshrc` twice. So you either need to do some checking, or better yet, move the environment variables to either `.zenv` or `.zprofile`.

**Comment by fredizzimo** [comment] 2023-08-09 10:52
I'm closing this, this is documented in the FAQ https://neovide.dev/faq.html#neovide-is-not-picking-up-some-shell-configured-information

I don't recommend sourcing `.zshrc` from `.zprofile` like @Hackder suggests though, since it gets harder to seperate what's run in interactive and non-interactive shells that way.

BTW, you can mostly ignore my previous message, I'm now convinced that the current way of doing it, running a non-interactive login shell is the correct way of doing it. And if the users configure the paths and environment variables in the correct configuration files it works as expected. Here's an image of the initialization flow for bash and zsh. For other shells, refer to the documentation of that.

![image](https://github.com/neovide/neovide/assets/9946255/7f9f0840-cd6d-471c-8b4c-02bffd782086)

**Closed by fredizzimo** 2023-08-09 10:52 UTC
Labels: bug, wsl
