### ISSUE TITLE
termsync support?

### ISSUE THREAD

**Issue by mawkler** [neovide/neovide#2553] opened 2024-05-17 09:37 UTC
Neovim 0.10 added support for [termsync](https://neovim.io/doc/user/options.html#'termsync'):

> If the host terminal supports it, buffer all screen updates made during a
> redraw cycle so that each screen is displayed in the terminal all at once. This
> can prevent tearing or flickering when the terminal updates faster than Nvim
> can redraw.

Is this something that Neovide supports, or are there plans to add support for it?

**Comment by fredizzimo** [comment] 2024-05-17 09:44
All Neovide draws are already atomic, so the option does not apply to us.

The inconsistencies and small flickering that can be seen from time to time, especially when using the built in terminal is caused by Neovim not sending all the updates in a single redraw cycle but splitting it over several cycles. That's something that can only be fixed in Neovim itself.

**Closed by fredizzimo** 2024-05-17 09:44 UTC
Labels: enhancement
