### ISSUE TITLE
neovide doesn't play nicely with amethyst

### ISSUE THREAD

**Issue by wasim42** [neovide/neovide#915] opened 2021-08-24 08:54 UTC
I'm not a Mac expert (only been using it since lockdown) so the terms I use will probably be wrong…

I use amethyst (a tiling window manager) on MacOS (primarily for its focus follows mouse, but the tiling is nice too).  In the main display I usually have only terminal, and I will launch my editor windows as required, and close them when done.

With gvim this works fine and terminal takes the left-hand side of the screen, and gvim the right-hand-side, and focus follows mouse.

With neovide this does not work so well.  The neovide screen appears in the middle, while the terminal takes the whole screen behind neovide.  If I move the mouse the terminal jumps to the foreground and neovide is inaccessible behind it.

**Comment by shaunsingh** [comment] 2021-08-28 05:26
I'll look into as why this happens, but is there any reason you can't use yabai? I believe its the superioir window manager for macos from what I've heard

**Comment by wasim42** [comment] 2021-08-31 09:18
I draw the attention of the right honourable gentleman to my very first sentence ;)

I'd never heard of yabai and got worried that it wouldn't work without disabling SIP (this is a work laptop and our policy states that I wouldn't be allowed to do that).  However it does everything I need from it, and works well with neovide without SIP so I'm a happy customer!

**Comment by Ajibaji** [comment] 2022-07-29 02:33
im an amethyst man myself so this was particularly frustrating. interestingly, for me the issue arises only when neovide is launched from the terminal... if i open neovide through finder, it behaves like any other window. in both situations it seems to run with the `--nofork` flag and ive got zero env vars interfering. even more curious is that from the terminal, if i hit the application directly, rather than the symlink (`/usr/local/bin/neovide -> /Applications/Neovide.app/Contents/MacOS/neovide
`) i dont face the problem. i still havent got a clue whats going on but as a simple workaround ive added an alias to my shell profile and all is well again: `alias vv='Applications/Neovide.app/Contents/MacOS/neovide'`

im running version v0.9.0, installed via `brew`. tried zsh and bash, kitty and terminal.app - all with the same results. someone put me out of my misery!

**Comment by gennaro-tedesco** [comment] 2023-08-09 21:55
I am having the same issue with both Amethyst and Yabai with 0.11.0 too.

**Comment by fredizzimo** [comment] 2023-08-09 22:06
Does [Alacritty](https://github.com/alacritty/alacritty), which uses the same winit library as we use for the windowing work?

**Comment by fredizzimo** [comment] 2023-08-09 22:35
This was closed before a proper solution was found https://github.com/ianyh/Amethyst/issues/1298. I suggest that you open a new issue there, I bet the Amethyst team has a much better chance of figuring out what's wrong.

**Comment by Ajibaji** [comment] 2023-08-13 08:10
> Can you try again with Neovide 0.11.0. A lot of things changed there.

all seems fine now! :thumbsup: :pray: . haven't used neovide since v0.9.0. seems to have moved quite far since then. nothing has managed to pry me off of neovim running in kitty yet but v0.11.0 is looking tempting so im giving it a go as my daily driver. startup time isnt quite as snappy but then it was always going to be longer than plain ol' neovim and the potential benefits heavily outweigh the marginal cost. probably ought to shift some plugins to lazy-loading

**Comment by fredizzimo** [comment] 2023-08-15 20:54
I'm not sure if the issue should be closed or not, on one hand @Ajibaji reports that it's working, while on the other hand @gennaro-tedesco reports that it doesn't.

**Comment by gennaro-tedesco** [comment] 2023-08-15 21:18
Just to be precise: @Ajibaji are you saying version 0.11.0 is working with yabai/amethyst or are you just saying you are trying it out?

**Comment by Ajibaji** [comment] 2023-08-16 11:31
Neovide 0.11.0 was working just fine with Amethyst 0.19.0 (i haven't tried Yabai) using the following config.toml
```
wsl = false
multigrid = true
vsync = true
maximized = false
srgb = false
idle = true
frame = "None"
```
However, after updating Amethyst to 0.20.0, Neovide was opening in a small window somewhere off-screen (but within the same desktop) and wasn't moveable or expandable. This would always happen whether launched from the terminal or finder. After commenting out `frame = "None"` opening Neovide would work as expected again. Interestingly, once normal behaviour resumed, I could un-comment the line again without unwanted behavior returning

**Comment by fredizzimo** [comment] 2023-08-16 12:04
I suggest that you create a new issue in the Amethyst repository for this. As I said earlier, they have a much better chance of figuring out what's wrong if it's a Neovide or Amethyst bug, and what needs to be done to fix it.

**Comment by williamhCode** [comment] 2023-12-13 05:41
I am using Neovide 0.11.2, and opening neovide from the terminal doesn't work for Yabai. Clicking on the symlink does work however, so same issue that @Ajibaji had.

**Comment by shaunsingh** [comment] 2023-12-15 19:19
Could you guys kindly check if alacrity has the same issue? Think this might be our issue

**Comment by fredizzimo** [comment] 2023-12-15 20:35
Also, if it is a Neovide bug, one likely cause is the forking behaviour, so could you check with `neovide --no-fork`.

BTW, that's a default behaviour I and many others would like to change https://github.com/neovide/neovide/issues/2147

**Comment by sp3ctum** [comment] 2024-01-28 19:36
I can reproduce this issue using the following:
- neovide `0.12.1` (`--no-fork` has the same result)
- amethyst `0.20.0 (108)`
- osx sonoma `14.2.1 (23C71)` on an Apple M1 Pro

**Comment by fredizzimo** [comment] 2024-05-18 17:51
I have a potential fix for this here:
* https://github.com/neovide/neovide/pull/2562

It would be good if someone could test it.

**Closed** 2024-05-19 15:48 UTC
Labels: bug, macos
